### ISSUE TITLE
resource-detector-gcp does not declare core dependency

### ISSUE THREAD

**Issue by dougvalenta** [open-telemetry/opentelemetry-js-contrib#1000]
### What version of OpenTelemetry are you using?
@opentelemetry/resource-detector-gcp:0.26.2

### What version of Node are you using?
16

### What did you do?

GcpDetector.ts imports and calls getEnv from @opentelemetry/core, but package does not declare it as a dependency or a peer dependency

### What did you expect to see?
@opentelemetry/core should be listed as a dependency or a peer dependency

### What did you see instead?
@opentelemetry/core is only listed as a dev dependency

### Additional context

I'm happy to try contributing a PR, but I do not know whether it should be a dependency or a peer dependency

**Comment by Flarna** [comment]
fixed via #1003
