### ISSUE TITLE
MetricReader is not bound to a MetricProducer

### ISSUE THREAD

**Issue by Eomm** [open-telemetry/opentelemetry-js-contrib#1014]
### What version of OpenTelemetry are you using?

```
    "@opentelemetry/api": "^1.1.0",
    "@opentelemetry/exporter-prometheus": "^0.28.0",
    "@opentelemetry/host-metrics": "^0.27.1",
```

### What version of Node are you using?

v16.13.0

### What did you do?

```js
const { MeterProvider } = require('@opentelemetry/sdk-metrics-base');
const { HostMetrics } = require('@opentelemetry/host-metrics');
const { PrometheusExporter } = require('@opentelemetry/exporter-prometheus');

const exporter = new PrometheusExporter(
  {
    startServer: true
  }, () => {
    console.log('prometheus scrape endpoint: http://localhost:9464/metrics')
  }
)

const meterProvider = new MeterProvider({
  exporter,
  interval: 2000
})

const hostMetrics = new HostMetrics({ meterProvider, name: 'example-host-metrics' })
hostMetrics.start()

const fastify = require('fastify')()
fastify.listen(8080)
```

### What did you expect to see?

Host metrics

### What did you see instead?

By reaching the URL: http://localhost:9464/metrics
I get:

```
# failed to export metrics: Error: MetricReader is not bound to a MetricProducer
```

### Additional context

I was trying to add the HostMetrics to the opentelemetry.NodeSDK component, but unsuccessfully. So I tried the basic example, and I get the same error.

**Comment by Eomm** [comment]
Digging a bit, I think it relates to https://github.com/open-telemetry/opentelemetry-js-contrib/issues/983

**Comment by legendecas** [comment]
Metrics API is still experimental and we are working to adopt the latest metrics spec changes towards GA. From @opentelemetry/sdk-metrics-base v0.28.0, you'll need to apply the following changes the get the example in the OP working:


```diff
const exporter = new PrometheusExporter(
  {
    startServer: true
  }, () => {
    console.log('prometheus scrape endpoint: http://localhost:9464/metrics')
  }
)

const meterProvider = new MeterProvider({
-   exporter,
-   interval: 2000
})

+ meterProvider.addMetricProvider(exporter);
```

And the @opentelemetry/host-metrics that are compatible with sdk-metrics-base v0.28.0 is pending release: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/947

**Comment by Eomm** [comment]
Applying your suggestion leads to:

> TypeError: meterProvider.addMetricProvider is not a function

My versions

```
├─┬ @opentelemetry/exporter-prometheus@0.28.0
│ └── @opentelemetry/sdk-metrics-base@0.28.0 deduped
├─┬ @opentelemetry/host-metrics@0.27.1
│ └── @opentelemetry/sdk-metrics-base@0.27.0
├── @opentelemetry/sdk-metrics-base@0.28.0
└─┬ @opentelemetry/sdk-node@0.28.0
  └── @opentelemetry/sdk-metrics-base@0.28.0 deduped
```

Should I wait for @opentelemetry/host-metrics v0.28?

**Comment by dyladan** [comment]
> Should I wait for @opentelemetry/host-metrics v0.28?

yes

**Comment by Eomm** [comment]
Is there any release plan?

**Comment by dyladan** [comment]
I'm cutting a release today sorry. The release automation failed while we were at kubecon and i'm looking into it

**Comment by BakrFlow** [comment]
Is there any updates?, I still get the same error even with @opentelemetry/host-metrics v0.28

**Comment by Eomm** [comment]
I will get the chance to test it by my side on the next days

**Comment by dyladan** [comment]
@Eomm any update on if this is still an issue?

**Comment by Eomm** [comment]
Just tried the doc example but same error for me by using node v16.x: https://www.npmjs.com/package/@opentelemetry/host-metrics

Switching to node.js v18.6.0 I get the same:

<img width="716" alt="image" src="https://user-images.githubusercontent.com/11404065/190876643-84adf2c2-d230-4b72-8a3d-ad5ad79dfa43.png">

I wonder if it is an OS issue (I'm using mac os)

**Comment by legendecas** [comment]
Would you mind updating the dependency `opentelemetry/sdk-metrics-base` with `opentelemetry/sdk-metrics` v0.33.0? It has been renamed in the recent release. Thank you!

**Comment by Eomm** [comment]
Sure, but.. the same result.
Am I the only one that is facing this issue?

I have `rm -rf node_modules` and reinstalled only these packages:

```
    "@opentelemetry/exporter-prometheus": "^0.33.0",
    "@opentelemetry/host-metrics": "^0.30.0",
    "@opentelemetry/sdk-metrics": "^0.33.0",
    "@opentelemetry/sdk-node": "^0.33.0",
```

Here the code I'm running:

<details>
  <summary>Click to expand!</summary>

```
const { MeterProvider } = require('@opentelemetry/sdk-metrics')
const { HostMetrics } = require('@opentelemetry/host-metrics')
const { PrometheusExporter } = require('@opentelemetry/exporter-prometheus')

const exporter = new PrometheusExporter(
  {
    startServer: true
  }, () => {
    console.log('prometheus scrape endpoint: http://localhost:9464/metrics')
  }
)

const meterProvider = new MeterProvider({
  exporter,
  interval: 2000
})

const hostMetrics = new HostMetrics({ meterProvider, name: 'example-host-metrics' })
hostMetrics.start()

// const fastify = require('fastify')()
// fastify.listen(8080)
setInterval(() => { console.log('tick') }, 10000)

```
</details>

**Comment by legendecas** [comment]
Sorry but you have to apply the patch mentioned at https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1014#issuecomment-1120442125 too.

**Comment by Eomm** [comment]
Yeah, I did it, but I keep getting the `is not a function` error and the module is up to date:

```
$ npm ls @opentelemetry/sdk-metrics       
chapter-13@1.0.0 /_experiments/prj
├─┬ @opentelemetry/exporter-prometheus@0.33.0
│ └── @opentelemetry/sdk-metrics@0.33.0 deduped
├─┬ @opentelemetry/host-metrics@0.30.0
│ └── @opentelemetry/sdk-metrics@0.32.0
├── @opentelemetry/sdk-metrics@0.33.0
└─┬ @opentelemetry/sdk-node@0.33.0
  └── @opentelemetry/sdk-metrics@0.33.0 deduped

$ node prova.js                    
/_experiments/prj/prova.js:17
meterProvider.addMetricProvider(exporter)
              ^

TypeError: meterProvider.addMetricProvider is not a function
    at Object.<anonymous> (/_experiments/prj/prova.js:17:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by legendecas** [comment]
Sorry, it's not `addMetricProvider` but rather `addMetricReader`. The code snippet I use is as follows:


```js
const { MeterProvider } = require('@opentelemetry/sdk-metrics');
const { HostMetrics } = require('@opentelemetry/host-metrics');
const { PrometheusExporter } = require('@opentelemetry/exporter-prometheus');

const exporter = new PrometheusExporter(
  {
    startServer: true
  }, () => {
    console.log('prometheus scrape endpoint: http://localhost:9464/metrics')
  }
)

const meterProvider = new MeterProvider()
meterProvider.addMetricReader(exporter)

const hostMetrics = new HostMetrics({ meterProvider, name: 'example-host-metrics' })
hostMetrics.start()
```

**Comment by Eomm** [comment]
Thanks, it works!
I should study a but the APIs
