### ISSUE TITLE
Should the plugin React Load be part of the meta packages for web ?

### ISSUE THREAD

**Issue by CyberHippo** [open-telemetry/opentelemetry-js-contrib#1019]
- [x] This only affects the JavaScript OpenTelemetry library
- [ ] This may affect other libraries, but I would like to get opinions here first
---
Should the [plugin React Load](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/web/opentelemetry-plugin-react-load) be added to the [meta packages for web](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/metapackages/auto-instrumentations-web) ? If it should be, I am willing to open a PR.

**Comment by martinkuba** [comment]
I don't think it should because 1) not all web applications use React, and 2) user of the plugin needs to take manual steps to use the plugin anyway (components need to extend the class from the plugin).

**Comment by CyberHippo** [comment]
Sounds good. Thank you for your input @martinkuba
