### ISSUE TITLE
Undici 

### ISSUE THREAD

**Issue by stefee** [open-telemetry/opentelemetry-js-contrib#1021]
### Is your instrumentation request related to a problem? Please describe

When making server-side requests using undici.request the trace is not propagated across service boundaries. This is because undici does not use core http module for making requests (unlike other popular fetch libraries).

### Is it applicable for Node or Browser or both?

Node

### Do you expect this instrumentation to be commonly used?
Weekly Downloads: 

### What version of instrumentation are you interested in using?
Versions:

### Additional context

https://github.com/nodejs/undici

**Comment by stefee** [comment]
See unofficial instrumentation https://github.com/gadget-inc/opentelemetry-instrumentations/tree/main/packages/opentelemetry-instrumentation-undici

**Comment by stefee** [comment]
See discussion over on undici project: https://github.com/nodejs/undici/discussions/1439

**Comment by stefee** [comment]
Following from the thread linked, I’m looking into implementing instrumentation using the Undici diagnostics channel. https://github.com/nodejs/undici/blob/main/docs/api/DiagnosticsChannel.md

The tricky thing I can see with the JS API for OTEL is that the only way to update the current active context is using the “with” method which takes a callback. https://open-telemetry.github.io/opentelemetry-js-api/classes/contextapi.html#with

See also: https://opentelemetry.io/docs/instrumentation/js/api/context/#active-context

In order to use the diagnostics channel we need a way of accessing the active context asynchronously, to set the active context during “request create” diagnostics function and restore the previous context during the “trailers” diagnostics - it feels like this what an async context is supposed to solve for in theory but the current context API doesn’t allow this.

The way this API works seems different to what the spec states, but I’m probably not understanding it. https://opentelemetry.io/docs/reference/specification/trace/api/#context-interaction

**Comment by vmarchaud** [comment]
I don't think this is feasible with the current context API, we'll need to move forward with https://github.com/open-telemetry/opentelemetry-js-api/pull/123 that allows manually control the context like you said (insert at request create and remove afterwards)

**Comment by m1heng** [comment]
So once https://github.com/open-telemetry/opentelemetry-js-api/pull/123 is merged, we can looking forward to have https://github.com/gadget-inc/opentelemetry-instrumentations/tree/main/packages/opentelemetry-instrumentation-undici merged into current repo and have it as part of auto-instrumentations?

**Comment by vmarchaud** [comment]
It can be upstreamed by @gadget-inc folks into this repo and added into auto instrumentations without requiring https://github.com/open-telemetry/opentelemetry-js-api/pull/123 to be merged, it's just that it spans created by a undici request will not have the correct parent (which isn't a big issue i think since undici is just a http client).

**Comment by m1heng** [comment]
I see, thank you @stefee and @vmarchaud for your contributions on this which would really solve my problem, I will try the "unofficial" one on my project first and see how it goes with splunk signalFX.
I still looking forward to see the context API PR get merged and we can have a comprehensive undici instrumentation and see it on auto meta.

**Comment by SimenB** [comment]
Was https://github.com/open-telemetry/opentelemetry-js-api/pull/123 ever ported to https://github.com/open-telemetry/opentelemetry-js?

**Comment by mateus4k** [comment]
Is there any solution other than using the unofficial package?

**Comment by MadLittleMods** [comment]
To better cross-link, I was able to get [`opentelemetry-instrumentation-fetch-node`](https://www.npmjs.com/package/opentelemetry-instrumentation-fetch-node) (instruments `undici`) working with Node.js 18 ✅

Whereas with the other unofficial suggestion, [`opentelemetry-instrumentation-undici`](https://www.npmjs.com/package/opentelemetry-instrumentation-undici), didn't seem to instrument anything (no new spans).

**Comment by joostmeijles** [comment]
> opentelemetry-instrumentation-fetch-node

Same here on NodeJS v18. Only https://www.npmjs.com/package/opentelemetry-instrumentation-fetch-node works (tested icw. NextJS v13). 

It was quite a search to find a working NodeJS v18 fetch instrumentation solution.
Adding it as plugin to this repository would be helpful.

**Comment by dyladan** [comment]
If discoverability is the issue I would encourage any package authors to add their instrumentations to the registry which is intended for that purpose https://opentelemetry.io/ecosystem/registry/

**Comment by david-luna** [comment]
PR for undici support https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1951

**Comment by JamieDanielson** [comment]
#1951 has been merged 🎉  I will close this as completed, please comment if that is incorrect.
