### ISSUE TITLE
The URL for homepage should link to package inside monorepo

### ISSUE THREAD

**Issue by trivikr** [open-telemetry/opentelemetry-js-contrib#1025]
### Is your feature request related to a problem? Please describe
The [homepage][homepage] field for the individual packages (if present) links to root of the monorepo.
The folks using the link and landing on GitHub have to go through monorepo structure, and find out the correct package.

For example, open [@opentelemetry/instrumentation-aws-sdk][npm-aws-sdk-instrumentation-pkg] on npm, and click on Homepage in the right sidebar.

<details>
<summary>Screenshot</summary>

![opentelemetry-instrumentation-aws-sdk](https://user-images.githubusercontent.com/16024985/168678623-c1f9c7c3-bdd6-4b28-92f9-366a3e8b1088.png)

</details>

The page opened will be https://github.com/open-telemetry/opentelemetry-js-contrib#readme

### Describe the solution you'd like to see
The homepage config should link to folder where source code for the package is present.

For `@opentelemetry/instrumentation-aws-sdk` package, the URL stored in homepage should be `https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-aws-sdk`

### Describe alternatives you've considered
N/A

[homepage]: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#homepage
[npm-aws-sdk-instrumentation-pkg]: https://www.npmjs.com/package/@opentelemetry/instrumentation-aws-sdk

**Comment by blumamir** [comment]
Fixed in #1032
