### ISSUE TITLE
@opentelemetry/instrumentation-express : ignoreLayers does not work as described

### ISSUE THREAD

**Issue by smnbbrv** [open-telemetry/opentelemetry-js-contrib#1034]
First of all thanks for the great work you are doing!

### What version of OpenTelemetry are you using?
```
    "@opentelemetry/api": "1.1.0",
    "@opentelemetry/exporter-jaeger": "1.1.0",
    "@opentelemetry/instrumentation": "0.28.0",
    "@opentelemetry/instrumentation-express": "0.28.0",
    "@opentelemetry/instrumentation-grpc": "0.28.0",
    "@opentelemetry/instrumentation-http": "0.28.0",
    "@opentelemetry/sdk-trace-base": "1.1.0",
    "@opentelemetry/sdk-trace-node": "1.1.0",
```

### What version of Node are you using?

16

### What did you do?

```
    new ExpressInstrumentation({
      ignoreLayers: [
        '/health',
        '/metrics',
        /^\/health$/,
        /^\/metrics$/,
      ],
      // ignoreLayersType: [
      //   ExpressLayerType.MIDDLEWARE,
      // ],
      spanNameHook: ({ request }) => `${request.method} ${request.path || ''}`,
    }) as any,
```

### What did you expect to see?

The spans from `/health` and `/metrics` should be ignored

### What did you see instead?

The spans from `/health` and `/metrics` are still reported

### Additional context

I have two express servers in one application (the error although happens regardless of servers amount), one for serving the data and one for metrics. The second server should be fully ignored but there is no option to do so.

In fact there are two solutions / improvements one can have here:

1. It would be great if instead of `name` (or in addition to) in `ignoreLayers` one could have access to native `req` and `res`. 
2. Also, it would be great to have a possibility to use this plugin as an ordinary middleware, where one can easily decide where and how to add it.

Actually it would be perfect to have both options in place

**Comment by vmarchaud** [comment]
Are you sure that the spans you are seeing come from the express app and not the http one ?

**Comment by MadLittleMods** [comment]
I was also confused about this. You can differentiate whether the spans came from one library or the other by looking at `otel.library.name` in the tags of each span.

I assumed the spans which looked like the express route, `GET /:roomIdOrAlias/date/:yyyy(\d{4})/:mm(\d{2})/:dd(\d{2})/:hourRange(\d\d?-\d\d?)?` were coming from `@opentelemetry/instrumentation-express`. But those spans are actually from `@opentelemetry/instrumentation-http` and are renamed by the following code in `@opentelemetry/instrumentation-express`

https://github.com/open-telemetry/opentelemetry-js-contrib/blob/375dfe07bcd88b8cfb0e6dc291dcc9fd3fba2f9e/plugins/node/opentelemetry-instrumentation-express/src/instrumentation.ts#L207-L223

From the docs, it's confusing to know that in order to not log certain express routes, you need to use `ignoreIncomingPaths` from `@opentelemetry/instrumentation-http` instead.

**Comment by vmarchaud** [comment]
> I was also confused about this. You can differentiate whether the spans came from one library or the other by looking at otel.library.name in the tags of each span

Yes sadly its a dirty hack around how web framework interact with http module in Node, the spec ask for span to have low cardinality but the http instrumentation cannot provide this out the of box, so we settled on http framework renaming the root span when it have a good (and low cardinality) name

**Comment by smnbbrv** [comment]
Thank you on the tips guys! 

The `ignoreIncomingPaths ` is deprecated, but `ignoreIncomingRequestHook` is working really well.

As I understand, there is still no option to enable the tracing for specific HTTP server instead of being globally assigned?

@vmarchaud what should I do with this issue? For me it is resolved, but it could be nice to add this to express instrumentation docs somewhere...

**Comment by MadLittleMods** [comment]
> The `ignoreIncomingPaths` is deprecated, but `ignoreIncomingRequestHook` is working really well.

Ahh, good catch! Need to update my usage 👍

---

It sounds like the action to take out of this issue to update the `@opentelemetry/instrumentation-express` docs (readme) to explain the intricacy of ignoring things. Or simply explain the common problem of ignoring express routes and the solution.

**Comment by Rauno56** [comment]
The docs could definitely be better explaining this.
Would you like to suggest an change in a PR, @MadLittleMods, @smnbbrv?
