### ISSUE TITLE
Recently release not published to npm

### ISSUE THREAD

**Issue by mplachter** [open-telemetry/opentelemetry-js-contrib#1035]
Looks like the recent opentelemetry-js-contrib releases from last week have not been published to npm.
https://www.npmjs.com/package/@opentelemetry/auto-instrumentations-node <-- for example 0.29.0 should have been published and it has not.

- [x] This only affects the JavaScript OpenTelemetry library

**Comment by dyladan** [comment]
I'm working on this right now

**Comment by dyladan** [comment]
This is blocked currently because the docker resource detector is listed as 1.0 and i'm trying to verify with @Rauno56 if that is correct or if it needs to be fixed

**Comment by dyladan** [comment]
For now I will release all packages except that one

**Comment by dyladan** [comment]
Done. Closing this issue as docker is a separate deal
