### ISSUE TITLE
Memcached instrumentation does not work

### ISSUE THREAD

**Issue by rohanagarwal36** [open-telemetry/opentelemetry-js-contrib#1037]
### What version of OpenTelemetry are you using?
```
    "@opentelemetry/api": "^1.1.0",
    "@opentelemetry/exporter-trace-otlp-http": "^0.28.0",
    "@opentelemetry/instrumentation-express": "^0.24.0",
    "@opentelemetry/instrumentation-grpc": "^0.24.0",
    "@opentelemetry/instrumentation-http": "^0.24.0",
    "@opentelemetry/instrumentation-ioredis": "^0.24.0",
    "@opentelemetry/instrumentation-memcached": "^0.28.0",
    "@opentelemetry/instrumentation-mongodb": "^0.24.0",
    "@opentelemetry/instrumentation-redis": "^0.24.0",
    "@opentelemetry/instrumentation-winston": "^0.24.0",
    "@opentelemetry/resources": "^0.24.0",
    "@opentelemetry/sdk-node": "^0.28.0",
    "@opentelemetry/sdk-trace-base": "^1.2.0",
    "opentelemetry-instrumentation-elasticsearch": "^0.24.0"
```

### What version of Node are you using?
v14.17.6

### What did you do?
```
var memjs = require('memjs');

var mc = memjs.Client.create('localhost:11211');
mc.set('foo1', 'bar1');

app.get('/test', (req, res) => {
	res.status(200);
	mc.set('foo', 'bar');
	mc.get('foo', function (err, value, key) {
		if (value != null) {
			console.log(value.toString());
		}
	});
	tracer.addTags({name: "Aakash"});
	return res.send('OK test');
});
```

### What did you expect to see?
There are spans for the http call to /test, but there should be spans for the calls to memcached as well.

### What did you see instead?
Spans for the calls to memcached are not present.

### Additional context
`"memjs": "^1.3.0"`
No examples on using memcached instrumentation are available. I am using:
`new MemcachedInstrumentation({enhancedDatabaseReporting: true,})`

**Comment by Flarna** [comment]
This is not a bug because the instrumentation you use is for [memcached](https://www.npmjs.com/package/memcached), not for [memjs](https://www.npmjs.com/package/memjs).

**Comment by rohanagarwal36** [comment]
I am confused a bit. When we say opentelemetry is supporting memcached instrumentation, does that mean it supports only very particular clients used to connect to memcache? for eg, I am able to get the spans when I use the "memcached" package to connect to memcache and query memcache, but when I use memjs, it does not work.

**Comment by Flarna** [comment]
Exactly.

An instrumentation is built for a specific npm module and it uses monkey patching to hook into the APIs and extract the needed data.
