### ISSUE TITLE
@opentelemetry/instrumentation-fs Failed to record an exception true

### ISSUE THREAD

**Issue by Radik24** [open-telemetry/opentelemetry-js-contrib#1047]
### What version of OpenTelemetry are you using?
`0.3.0`

### What version of Node are you using?
docker `node:16.14-slim`

### What did you do?

When running my Hapi locally, everything works fine. But when I build it for production to docker, it always fails. I tested each instrumentation locally in docker but only `@opentelemetry/instrumentation-fs ` is causing this issue

### What did you expect to see?
Running container and working opentelemetry tracing.

### What did you see instead?
Opentelemetry debug logs.
![image](https://user-images.githubusercontent.com/23722745/171663600-96e905a2-8784-4195-ae77-b76d60e373d1.png)

### Additional context

It does not like docker obviously. Is there any reason for this behaviour?

Thanks

**Comment by Rauno56** [comment]
Could you please share some code to repro this?
