### ISSUE TITLE
AWS SDK instrumentation logs entire DynamoDB statement, including potentially sensitive values

### ISSUE THREAD

**Issue by monken** [open-telemetry/opentelemetry-js-contrib#1053]
### What version of OpenTelemetry are you using?

OpenTelemetry Lambda extension, version: v0.1.0

### What version of Node are you using?

NodeJS 16

### What did you do?

Use the Lambda Layer for instrumentation

### What did you expect to see?

I expected **not** to see the whole DynamoDB statement to be part of the trace. This should not be the default. The statement will most likely include very sensitive information that you don't want to leak to your observability toolchain.

Example:

```json
{
  "metadata": {
      "default": {
          "aws.service.api": "DynamoDB",
          "aws.signature.version": "v4",
          "aws.service.name": "DynamoDB",
          "db.statement": "{\"TableName\":\"table-name\",\"FilterExpression\":\"begins_with(GSI1PK,:a)\",\"ExpressionAttributeValues\":{\":a\":\"U:abcabcabc:\"}}",
          "rpc.service": "DynamoDB",
          "aws.service.identifier": "dynamodb",
          "db.system": "dynamodb",
          "aws.request.id": "B115QKDKVVJF66Q9ASUAAJG",
          "db.operation": "Scan",
          "rpc.system": "aws-api",
          "db.name": "table-name"
      }
  }
}
```

### What did you see instead?

I saw the entire DynamoDB statement, unscrubbed.

### Additional context

Culprit is https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-aws-sdk/src/services/dynamodb.ts#L39 where the entire DynamoDB statement is serialized and added to the trace.

**Comment by blumamir** [comment]
We should probably add a `dynamoDbStatementSerializer`and supply a safe default that records only non-sensitive values, similar to #1052 .

Would you be willing to contribute a PR to do that?

**Comment by monken** [comment]
@blumamir I can take a crack at it. I thought this was an officially supported library by AWS (they definitely promote it) but it seems like this is mostly supported by Dynatrace and other companies.

**Comment by blumamir** [comment]
@NathanielRN @willarmiros [trivikr](https://github.com/trivikr/trivikr) are from AWS and were involved in the past with this instrumentation

**Comment by NathanielRN** [comment]
I've seen our X-Ray AWS SDK sanitize trace at times like in this PR https://github.com/aws/aws-xray-sdk-go/pull/228 where we sanitized the HTTP URL query and we seem to have done efforts [to sanitize the query in the X-Ray Go SDK](https://github.com/aws/aws-xray-sdk-go/blob/d66401caaea67ff87f43486c8b5ddd6c2fcd3bbd/xray/sql_context.go#L534) in the past?

Other than that, we don't have precedence for it, so we wouldn't have too much bias when proposed ideas come around 🙂

**Comment by monken** [comment]
Trying to come up with a good sanitization strategy per API call. I suggest an allow-list approach where we maintain a list of attributes that are safe to capture.

Only capture the command input for the following actions:

* ExecuteStatement
* BatchExecuteStatement
* PutItem
* BatchWriteItem
* GetItem
* BatchGetItem
* Query
* Scan
* UpdateItem
* DeleteItem
* BatchWriteItem
* ExecuteTransaction
* TransactWriteItems
* TransactGetItems

Always include the following attributes if present:

* ConsistentRead
* ExpressionAttributeNames
* FilterExpression
* IndexName
* KeyConditionExpression
* Limit
* ProjectionExpression
* ReturnConsumedCapacity
* ReturnItemCollectionMetrics
* ReturnValues
* ReturnValuesOnConditionCheckFailure
* ScanIndexForward
* Segment
* Select
* TableName
* TotalSegments
* UpdateExpression

This means the following attributes will be excluded (and future attributes):

* AttributesToGet (legacy)
* AttributeUpdates (legacy)
* ConditionalOperator (legacy)
* ExclusiveStartKey
* Expected (legacy)
* ExpressionAttributeValues
* Item
* Key
* KeyConditions (legacy)
* NextToken
* QueryFilter (legacy)
* ScanFilter (legacy)
* Statement

**Comment by monken** [comment]
The [aws-xray-sdk](https://www.npmjs.com/package/aws-xray-sdk) doesn't capture anything except the `TableName` from the request.

**Comment by ithompson-gp** [comment]
Has there been any update on this with regard the AWS instrumentation exposing DynamoDB queries as an attribute?
