### ISSUE TITLE
Remove deprecated package `@types/mongodb` from mongodb instrumentation

### ISSUE THREAD

**Issue by mic-max** [open-telemetry/opentelemetry-js-contrib#1070]
The dependency is marked as deprecated [here](https://www.npmjs.com/package/@types/mongodb)

It says

> mongodb provides its own types. @types/mongodb is no longer needed.

This is the [package.json file](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-mongodb/package.json#L71) listing the dependency

I noticed this error when performing an `npm install` on a project that includes this package

Note: I tried simply deleting the line from the `package.json` but got this error when trying to run `npm run compile` from `\plugins\node\opentelemetry-instrumentation-mongodb`

![image](https://user-images.githubusercontent.com/15165028/175439456-b499fd93-510f-4047-8b4e-cc4833099259.png)

The top error is the only one from an src file, all other are from a test, which I believe is based on the npm version (which would need to be updated and create a new release as part of this fix)

**Comment by Flarna** [comment]
The problem is that current version of the instrumentation requires the types. Removing the dependency to `@types/mongodb` would require to add one to `mongodb` which would be quite bad.

Work is ongoing to remove the need to include types dependencies in instrumentations (e.g. #1036, #1066) but it will take a while until this is fixed. As usual help is welcome!

**Comment by osherv** [comment]
@mic-max @Flarna Hey :) According to this PR: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1141
The dependencies of @types/mongo are now devDependencies only.
I think it met your requirements, right?

**Comment by Flarna** [comment]
@osherv yes, looks good.

**Comment by mic-max** [comment]
@osherv Yes, I believe that does it! Now projects that use this module will no longer see this message when installing it as it will not fetch `devDependencies`
