### ISSUE TITLE
`@opentelemetry/instrumentation-graphql` Error when running synchronously

### ISSUE THREAD

**Issue by ronilan** [open-telemetry/opentelemetry-js-contrib#1082]
## Description
Instrumenting a `graphql` application which uses the synchronous method `graphqlSync` causes  `Error: GraphQL execution failed to complete synchronously.` App is working fine when not istrumented.

### What version of OpenTelemetry are you using?
```
 "@opentelemetry/instrumentation-graphql": "^0.29.0"
 "@opentelemetry/instrumentation": "^0.29.2"
 "@opentelemetry/sdk-trace-node": "^0.25.0"
```
With:
```
 "graphql": "^15.8.0"
```
### What version of Node are you using?
`v16.14.2`

### What did you do?

1. Create a `async.js` with "Hello World!" example as per: https://graphql.org/graphql-js/

```javascript
const { graphql, buildSchema } = require('graphql')

// Construct a schema, using GraphQL schema language
const schema = buildSchema(`
  type Query {
    hello: String,
  }
`)

// The rootValue provides a resolver function for each API endpoint
const rootValue = {
  hello: () => {
    return 'Hello world!'
  }
}

// Run the GraphQL query '{ hello }' and print out the response
graphql({
  schema,
  source: '{ hello }',
  rootValue
}).then((r) => {
  console.log(r)
})

```

2. Create a `sync.js` with a synchronous version of "Hello World!"

```javascript
const { graphqlSync, buildSchema } = require('graphql')

// Construct a schema, using GraphQL schema language
const schema = buildSchema(`
  type Query {
    hello: String,
  }
`)

// The rootValue provides a resolver function for each API endpoint
const rootValue = {
  hello: () => {
    return 'Hello world!'
  }
}

// Run the GraphQL query '{ hello }' and print out the response
const r = graphqlSync({
  schema,
  source: '{ hello }',
  rootValue
})
console.log(r)

```

3. Create a `tracing-gql.js` script as per: https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-graphql

```javascript
'use strict'

const { GraphQLInstrumentation } = require('@opentelemetry/instrumentation-graphql')
const { NodeTracerProvider } = require('@opentelemetry/sdk-trace-node')
const { registerInstrumentations } = require('@opentelemetry/instrumentation')

const provider = new NodeTracerProvider()
provider.register()

registerInstrumentations({
  instrumentations: [
    new GraphQLInstrumentation({
    // optional params
      // allowValues: true,
      // depth: 2,
      // mergeItems: true,
    })
  ]
})

```

4. Run `node -r ./tracing-gql.js async.js` ✅ 

5. Run `node -r ./tracing-gql.js sync.js` ❌ 

### What did you expect to see?

```
node -r ./tracing-gql.js async.js   ✅ 
```
```
opentelemetry
{ data: [Object: null prototype] { hello: 'Hello world!' } }
```

### What did you see instead?

```
node -r ./tracing-gql.js sync.js ❌ 
```
```
opentelemetry
/usr/src/instrumented/graphql/node_modules/graphql/graphql.js:63
    throw new Error('GraphQL execution failed to complete synchronously.');
    ^

Error: GraphQL execution failed to complete synchronously.
    at graphqlSync (/usr/src/instrumented/graphql/node_modules/graphql/graphql.js:63:11)
    at Object.<anonymous> (/usr/src/instrumented/graphql/sync.js:18:11)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
root@8f40b7e64865:/usr/src/instrumented/graphql# 
```

### Additional context

App works fine when NOT instrumented. Instrumenting and modifying `graphql` internals is causing the error.
```
node sync.js ✅ 
```
```
{ data: [Object: null prototype] { hello: 'Hello world!' } }
```

**Comment by patrickdronk** [comment]
It might not even be a bug. The home page mentions supported versions: >=14 <16
https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-graphql#readme

**Comment by dyladan** [comment]
> It might not even be a bug. The home page mentions supported versions: >=14 <16 [https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-graphql#readme](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-graphql?rgh-link-date=2022-08-08T17%3A00%3A47Z#readme)

He is using `"graphql": "^15.8.0"` which falls in the range

**Comment by dyladan** [comment]
@obecny originally contributed this component but is no longer a maintainer. I'm looking into this

**Comment by Rauno56** [comment]
Tests for `graphql@15.8.0` failing: https://github.com/open-telemetry/opentelemetry-js-contrib/actions/runs/3077464972/jobs/4972348257

**Comment by blumamir** [comment]
debugged it and found the issue [here](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/23589d65a1e167da375def9a532f58b1f0969d24/plugins/node/opentelemetry-instrumentation-graphql/src/utils.ts#L383)

instrumentation code wraps each resolver with `safeExecuteInTheMiddleAsync` which turns sync functions into async. This is why `graphqlSync` throws. It also changes the behavior of the package, degrading performance, and making things parallel where they are not supposed to be:

![image](https://user-images.githubusercontent.com/22870745/197814664-47abbbb4-657c-4d7b-87fa-5f5364c3a2be.png)

This is a timeline screenshot for the resolvers which should run synchronous, but the instrumentation causes them to appear to run in parallel
