### ISSUE TITLE
Broken configuration support

### ISSUE THREAD

**Issue by sta-szek** [open-telemetry/opentelemetry-js-contrib#1087]
First of all, thanks for implementing this library! 🙇 
It saved my day! (or weeks 😅 ) It's just awesome!
Here I have question / bug report.

### What version of OpenTelemetry are you using?
```
"@opentelemetry/auto-instrumentations-node": "^0.31.0",
"@opentelemetry/core": "^1.4.0",
"@opentelemetry/exporter-jaeger": "^1.4.0",
"@opentelemetry/propagator-b3": "^1.4.0",
"@opentelemetry/resources": "^1.4.0",
"@opentelemetry/sdk-node": "^0.30.0",
"@opentelemetry/sdk-trace-base": "^1.4.0",
"@opentelemetry/semantic-conventions": "^1.4.0",
```

### What version of Node are you using?
```
node -v
v17.8.0
```

### What did you do?
Try to configure 16 lowercase hex characters `traceId` (instead of default 32)

### What did you expect to see?
16 characters traceId with working propagation
Example of working tracing (with 32 characters):
![Screenshot 2022-07-11 at 12 10 56](https://user-images.githubusercontent.com/6240704/178241802-ae3adc51-9768-49f8-843b-535da9c27a17.png)

### What did you see instead?
16 characters (3f9166c1476751b1) traceId WITHOUT propagation, despite the fact it is configured.
![Screenshot 2022-07-11 at 12 13 51](https://user-images.githubusercontent.com/6240704/178242343-f15549aa-2203-4be0-9964-458ff6b0984e.png)

### Additional context
I have configured tracing, according to examples taken from [Usage section](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/metapackages/auto-instrumentations-node#usage).

The code that is working, but generates 32 chars traceid is following:

```
const opentelemetry = require('@opentelemetry/sdk-node');
const {AsyncLocalStorageContextManager} = require('@opentelemetry/context-async-hooks');
const {getNodeAutoInstrumentations} = require('@opentelemetry/auto-instrumentations-node');
const {Resource} = require('@opentelemetry/resources');
const {SemanticResourceAttributes} = require('@opentelemetry/semantic-conventions');
const {JaegerExporter} = require('@opentelemetry/exporter-jaeger');
const {BatchSpanProcessor} = require("@opentelemetry/sdk-trace-base");
const {AlwaysOnSampler} = require("@opentelemetry/core");
const {B3Propagator, B3InjectEncoding} = require("@opentelemetry/propagator-b3");

// configure the SDK to export telemetry data to the Jaeger instance
// enable all auto-instrumentations from the meta package
const traceExporter = new JaegerExporter({endpoint: 'http://localhost:14268/api/traces'});
const spanProcessor = new BatchSpanProcessor(traceExporter);
const sampler = new AlwaysOnSampler();
const resource = Resource.default().merge(new Resource({
  [SemanticResourceAttributes.SERVICE_NAME]: 'optimization-reporting-jopi-localhost',
  [SemanticResourceAttributes.SERVICE_VERSION]: '1.0.0'
}));
const textMapPropagator = new B3Propagator({ injectEncoding: B3InjectEncoding.MULTI_HEADER });
const contextManager = new AsyncLocalStorageContextManager(); // this contextManager is not required if we do not want to invoke sdk#configureTracerProvider - can be removed
contextManager.enable() 

const sdk = new opentelemetry.NodeSDK({
  traceExporter: traceExporter,
  spanProcessor: spanProcessor,
  sampler: sampler,
  contextManager: contextManager,
  resource: resource,
  textMapPropagator: textMapPropagator,
  instrumentations: [getNodeAutoInstrumentations()]
})

// initialize the SDK and register with the OpenTelemetry API
// this enables the API to record telemetry
sdk.start();

// gracefully shut down the SDK on process exit
process.on('SIGTERM', () => {
  sdk.shutdown().finally(() => process.exit(0));
});
```

However, one of our requiremetns is to use 16chars for traceid (which is the default length in some libraries), but its not possible to configure it via `NodeSDKConfiguration`.
The only way to configure 16chars for traceId is to develop custom IdGenerator and pass it via `sdk#configureTracerProvider` method.
So I implemented it, then added `sdk#configureTracerProvider` before line where SDK is started (`sdk.start()`):

```
const customIdGenerator = new class implements IdGenerator {
  private delegate: IdGenerator = new RandomIdGenerator();
  generateSpanId(): string { return this.delegate.generateSpanId(); }
  generateTraceId(): string { return this.delegate.generateSpanId(); }
}

const tracerConfig = {sampler: sampler, resource: resource, idGenerator: customIdGenerator };
console.log(tracerConfig);
//TODO below line sets 16-chars TraceID, however it breaks tracing propagation
sdk.configureTracerProvider(tracerConfig , spanProcessor, contextManager, textMapPropagator);
```

But then, as already shown above, tracing propagation IS NOT working anymore, BUT traceId has 16 chars.

I re-used exactly thee same objects for `spanProcessor`, `contextManager` and `textMapPropagator`.

Additional question, as per docs:
> Custom configuration for each of the instrumentations can be passed to the function, by providing an object with the name of the instrumentation as a key, and its configuration as the value.

But where can i find examples of possible configurations?

PS 
I am not a NodeJS developer, just starting...

**Comment by Flarna** [comment]
The 128 bit size of the traceId is even mention in [API](https://github.com/open-telemetry/opentelemetry-js-api/blob/bafcf0d0756e6ecc79fcc75f221b9dd17641eba5/src/trace/span_context.ts#L25-L30).

Therefore I assume it wont work to limit the size to 16 bytes via an id generator. There are various places where the 128 bits are checked (e.g. [here](https://github.com/open-telemetry/opentelemetry-js-api/blob/bafcf0d0756e6ecc79fcc75f221b9dd17641eba5/src/trace/spancontext-utils.ts#L21), again in API).

You could create an id generator here the top 16 bytes are fixed (e.g. 0) and then you don't loose info in the 16 byte tools and you can reconstruct the full traceId for other tools.
I think something like this is already done in opentracing propagator [here](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/e2657232c9007a77ddc873a93e8247f99087b9c1/propagators/opentelemetry-propagator-ot-trace/src/OTTracePropagator.ts#L70)
