### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by Djiit** [open-telemetry/opentelemetry-js-contrib#1098]
### Is your feature request related to a problem? Please describe
Using `@opentelemetry/plugin-react-load` with React 18 throw an error.

### Describe the solution you'd like to see

Looks like by "just" extending the range of React versions supported, we could use "as is" the plugin with newer versions of React.

### Describe alternatives you've considered

Forcing `--legacy-peer-deps` with npm.

### Additional context

Reproduction:
- Create a new project using React 18
- Add opentelemetry-js and `@opentelemetry/plugin-react-load`

**Comment by vmarchaud** [comment]
@Djiit Feel free to open a PR, we should also bump version a used in tests so we make sure evertying works as it shoud be

**Comment by Djiit** [comment]
Thanks, I just opened a first draft. Not sure where to update the versions in test. Any guidance appreciated.
