### ISSUE TITLE
resource-detector-github failed to compile

### ISSUE THREAD

**Issue by legendecas** [open-telemetry/opentelemetry-js-contrib#1101]
Constant CI failure with the following outputs:

```
> @opentelemetry/resource-detector-github@0.27.0 compile
> tsc -p .

error TS2688: Cannot find type definition file for 'parse5'.
  The file is in the program because:
    Entry point for implicit type library 'parse5'

../../../node_modules/@types/jsdom/base.d.ts:4:33 - error TS7016: Could not find a declaration file for module 'parse5'. '/home/runner/work/opentelemetry-js-contrib/opentelemetry-js-contrib/node_modules/parse5/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/parse5` if it exists or add a new declaration (.d.ts) file containing `declare module 'parse5';`

4 import { ElementLocation } from "parse5";
                                  ~~~~~~~~
```

Example link: https://github.com/open-telemetry/opentelemetry-js-contrib/runs/7547491100?check_suite_focus=true
Find out more: https://github.com/open-telemetry/opentelemetry-js-contrib/actions/workflows/unit-test.yml

**Comment by aadharsh-rengarajan** [comment]
can we please fix this? this is causing a lot of test failures across the repository.

**Comment by dyladan** [comment]
There is no listed component owner for the github resource detector. We have a lot of unmaintained components like this and the burden on the SIG maintainers is unsustainable. I think we should consider our options on what we can do with these unmaintained components.

**Comment by legendecas** [comment]
The problem is caused by the dependencies of the package https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/packages/opentelemetry-browser-extension-autoinjection. It is not the problem with the resource-detector-github, but I'm not sure why it is failed to compile -- might be related to dependencies hoisting.

**Comment by Flarna** [comment]
> There is no listed component owner for the github resource detector. We have a lot of unmaintained components like this and the burden on the SIG maintainers is unsustainable. I think we should consider our options on what we can do with these unmaintained components.

I think we should remove unmaintained components from the learn project and from autoinstrumentation and created an issue with label help wanted to get it back into useable state.

**Comment by dyladan** [comment]
It isn't related to hoisting. It doesn't compile even standalone without lerna. It has something to do with the parse5 module types. I think they updated to a later typescript that is outputting syntax that our (fairly old) typescript doesn't support.
