### ISSUE TITLE
`@opentelemetry-instrumentation-ioredis` failed to record traces for ioredis version 5.x

### ISSUE THREAD

**Issue by ronenl3** [open-telemetry/opentelemetry-js-contrib#1116]
### What version of OpenTelemetry are you using?
@opentelemetry/sdk-trace-base@1.5.0
@opentelemetry/sdk-trace-node@1.5.0
@opentelemetry/instrumentation@0.31.0
@opentelemetry/instrumentation-ioredis@0.31.0

### What version of Node are you using?
16.16.0

### What did you do?
```javascript
registerInstrumentations({
      instrumentations: [
        new IORedisInstrumentation(),
      ],
});
```

### What did you expect to see?
Traces for Redis commands

### What did you see instead?
No traces are sent to the console and jaeger exporters

### Additional context
When using ioredis version `4.28.5` traces are sent. When using version `5.0.6` I don't see any traces for Redis commands.
I don't see any info when enabling debug level logs from OTEL

**Comment by vmarchaud** [comment]
There is an issue open tracking this: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/978

**Comment by ronenl3** [comment]
@vmarchaud Thank you for the reference, can it be added the the README under `Supported Version`?

**Comment by vmarchaud** [comment]
@ronenl3 I've opened a PR https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1117
