### ISSUE TITLE
otel-collector + AWS X-Ray: large gaps in tracing blocks

### ISSUE THREAD

**Issue by toddtarsi** [open-telemetry/opentelemetry-js-contrib#1130]
- [X] This may affect other libraries, but I would like to get opinions here first

Hey all, I use Opentelemetry on Hapi, and I'm currently doing AWS X Ray via the otel-collector sidecar on ECS. This might be something I need AWS support for, but I wanted to check here first, as I am not sure how to see what I'm missing. Basically, I get these inconsistent untraced segments of my request. This doesn't happen on most requests, but the sampling picks up a few of them about every hour.

What I'm confused about here is that the top level trace from the otel-collector sidecar clocks the request at 2.7 seconds, and then the application level traces only account for maybe 700 ms. So, my confusion is, where are the other 2 seconds going?

If someone has an answer, I'd appreciate the heck if you shared, but I'm also trying to figure out what I can do to get more context here. Also, if I should instead be having this conversation with AWS I will, but publicly having this conversation might benefit the next person in my spot.

Thanks for the awesome libraries! You guys are amazing 

<img width="1410" alt="Screen Shot 2022-08-26 at 12 55 15 PM" src="https://user-images.githubusercontent.com/4707505/186964333-5430d0f4-1793-4779-9848-e59839025947.png">

**Comment by noliva** [comment]
> Basically, I get these inconsistent untraced segments of my request

That made me think of a similar issue we faced.

In our case, we were using a remote sampler and we were sampling spans, that's why some spans would appear and others would not.

We then moved to sample all spans if a trace is sampled, the way we achieved that in go was like this:

```go
sdktrace.WithSampler(sdktrace.ParentBased(sampler)),
```

Not sure if this is of help, but worth a try.

**Comment by dyladan** [comment]
@toddtarsi does the 👍 mean this helped you solve your problem? If so can you close this or comment?

**Comment by toddtarsi** [comment]
@dyladan - Not sure yet, but I am extremely appreciative of a helpful suggestion like this, and I'm definitely going to implement my sampling rules more deliberately. Sorry to leave this open here.

**Comment by dyladan** [comment]
No worries I just wanted to make sure the status was clear
