### ISSUE TITLE
[Bug] Web based karma tests are no longer running

### ISSUE THREAD

**Issue by MSNev** [open-telemetry/opentelemetry-js-contrib#1135]
### What version of OpenTelemetry are you using?

Current rebase of the contribu repo

### What version of Node are you using?
16.14.0

### What did you do?
- clean fetch of repo
- npm install
- npm run install
- Go into the plugins/web/opentelemetry-instrumentation-document-load
- npm run test

### What did you expect to see?
- passing tests

### What did you see instead?
- failing tests

**Comment by dyladan** [comment]
@MSNev if you have it handy can you post the failure? If not i'll just run it myself

**Comment by MSNev** [comment]
```
D:\MSNev1\opentelemetry-js-contrib\plugins\web\opentelemetry-instrumentation-document-load>npm run test:browser

> @opentelemetry/instrumentation-document-load@0.29.0 test:browser
> nyc karma start --single-run

Webpack bundling...
Error: EINVAL: invalid argument, mkdir 'C:\Users\newylie\AppData\Local\Temp\_karma_webpack_341915\D:\MSNev1\opentelemetry-js-contrib\plugins\web\opentelemetry-instrumentation-document-load\build\src'
```

The normal documented way to avoid this issue is to set the webpack 
```
optimization: {
    runtimeChunk: false,
    splitChunks: false
}
```

However, these options did not work for the contrib repo

**Comment by dyladan** [comment]
Is that a windows-specific issue? I ask because it didn't get caught during the initial PR to update to webpack 5. It's a bummer that we have to roll back to a previous testing version just for a single plugin.

**Comment by MSNev** [comment]
No it's not, it's just a little more obvious because of the drive letter embedded in the resulting path that it uses to understand what is going on.

https://github.com/ryanclark/karma-webpack/issues/489

And in the contrib repo #1129 also hit it on a non-windows box https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1129#discussion_r957504262

**Comment by dyladan** [comment]
Interesting. That looks really similar to an error I was having on macos with temp directories in the main repo with webpack 5. any idea why this has taken so long to be a problem?

**Comment by MSNev** [comment]
I think it's environmental, the main tests on GitHub seem to be passing. So it's really just as people start contributing their setup's (including mine) have issues with the defaults.
