### ISSUE TITLE
Use swc instead of tsc

### ISSUE THREAD

**Issue by jscherer92** [open-telemetry/opentelemetry-js-contrib#1139]
At my current work we have switched away from tsc in favor of swc. From looking in the repository, I do not think there is anything that would stop us from being able to convert over to it. I know we converted due to the speed that it runs compared to tsc. I was wondering if there has been any thought around this or if it would be okay to do this?

**Comment by blumamir** [comment]
> At my current work we have switched away from tsc in favor of swc. From looking in the repository, I do not think there is anything that would stop us from being able to convert over to it. I know we converted due to the speed that it runs compared to tsc. I was wondering if there has been any thought around this or if it would be okay to do this?

Interesting, I see it's very popular and active
Can you share if you are aware of any potential risks with switching compilers?

**Comment by jscherer92** [comment]
There have been two potential risks:

1) if you rely on certain features of Typescript it could potentially break. I know decorators were busted for about a week which cause some of our code to not build.

2) the plugin system is not as diverse. It hasn't hurt us yet but if you are using a bunch of babel plugins it could be a problem.

Overall, I think the productivity increase in getting builds to go faster outweigh the above cons, but those would be the risks I know of.

Note: NextJS uses swc and works directly with maintainers so it is actively worked on from the Node community.
