### ISSUE TITLE
ioredis instrumentation should obey `requireParentSpan` for `connect`

### ISSUE THREAD

**Issue by evantorrie** [open-telemetry/opentelemetry-js-contrib#1150]
### Is your feature request related to a problem? Please describe

Yes. The `@opentelemetry/instrumentation-ioredis` documentation for parameter `requireParentSpan` says

"Require parent to create ioredis span, default when unset is true".

However, on code inspection, this currently applies only to ioredis spans which are created as part of an `ioredis` "command" such as `.set(), .get(), .zadd()` etc. There is another `ioredis` command which is the initial `connect()` call. This code does not honor the `requireParentSpan` parameter, and will always create a span.

### Describe the solution you'd like to see

Have `requireParentSpan` apply to `connect` as well.

### Describe alternatives you've considered

Considered trying to change code which calls the Redis connect to wrap the span in a non-recording span.

### Additional context

This ends up being somewhat painful in a Redis Cluster situation, where there is a recurring "connect" call due to ioredis 4's "refreshSlotsInterval" parameter.

**Comment by Rauno56** [comment]
@blumamir, @evantorrie, what's the usecase for requiring a parent span in a instrumentation?
