### ISSUE TITLE
@opentelemetry/instrumentation-aws-sdk has random version number that throws off Snyk

### ISSUE THREAD

**Issue by xavianaxw** [open-telemetry/opentelemetry-js-contrib#1153]
### What version of OpenTelemetry are you using?
`@opentelemetry/instrumentation-aws-sdk`@`v0.8.1`

### What version of Node are you using?
`v16.17.0`

### What did you do?
On Snyk dashboard, it is reported that it needs an upgrade from `v0.8.1` to `v0.25.0`. However, the `v0.25.0` is released a year ago and the latest version is actually `0.9.0`

### What did you expect to see?
Snyk not throwing a warning to upgrade to `v0.25.0`

### What did you see instead?
Snyk throwing a warning to upgrade to `v0.25.0`

**Comment by Flarna** [comment]
@NathanielRN @willarmiros @blumamir  I guess the old 0.25.0 release created before the 0.1.0 will result in a conflict sooner or later...
Maybe we should move towards 0.26.0 to correct this?

**Comment by xavianaxw** [comment]
Thanks for looking into this guys
