### ISSUE TITLE
Migrate examples for redis instrumentation

### ISSUE THREAD

**Issue by haddasbronfman** [open-telemetry/opentelemetry-js-contrib#1155]
We're moving instrumentation examples from the top-level examples folder to the individual instrumentation packages to help keep them up to date. https://github.com/open-telemetry/opentelemetry-js-contrib/pull/939.

This issue is specifically for the [@opentelemetry/instrumentation-redis](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/examples/redis) examples.

Step-by-step instructions for migrating these examples can be found in [examples/README.md](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/examples/README.md#instructions-for-migrating-an-example).

**Comment by haddasbronfman** [comment]
Can you assign this to me please?

**Comment by blumamir** [comment]
implemented in #1156
