### ISSUE TITLE
[pg + pg-pool] Update DB semantic conventions

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-js-contrib#116]
https://github.com/open-telemetry/opentelemetry-specification/pull/575

**Comment by naseemkullah** [comment]
This may fall out of scope but would it make sense to have a shared `opentelemetry-semantic-conventions` package that exports the enum of all attribute names and such? If so should this be package be hosted in the core repo?

**Comment by dyladan** [comment]
There is already such a package. https://github.com/open-telemetry/opentelemetry-js/tree/master/packages/opentelemetry-semantic-conventions

**Comment by naseemkullah** [comment]
perfect!

**Comment by naseemkullah** [comment]
@dyladan re: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/database.md#mysql

Please take note of span name and db statement.

Shall we proceed like as such? Currently span name is  e.g.: `mysql:query:SELECT`, the value of db statement is that of span name and we have a custom attribute MYSQL_VALUES with the  values. To adhere to spec, `MYSQL_VALUES` would be gone, they would be templated into the sql for db statement, and the non templated sql statement would be the span name.

If we proceed as per spec, should we worry about sanitization?

**Comment by dyladan** [comment]
We should follow the spec

**Comment by naseemkullah** [comment]
FYI I don't plan on tackling `pg` or `pg-pool` so those are up for grabs.
