### ISSUE TITLE
ResponseHook for cassandra driver

### ISSUE THREAD

**Issue by tomerfriedman** [open-telemetry/opentelemetry-js-contrib#1162]
### Is your feature request related to a problem? Please describe
Would love to have a responseHook to a query that being sent to cassandra driver. This will allow me to insert some custom attributes after response is back.

### Describe the solution you'd like to see
A responseHook function so I can insert custom attributes to the span after query was made.

**Comment by samimusallam** [comment]
Can this issue be assigned to me?
