### ISSUE TITLE
Express autoinstrumentation not auto-instrumenting

### ISSUE THREAD

**Issue by ringerc** [open-telemetry/opentelemetry-js-contrib#1166]
### What version of OpenTelemetry are you using?

* opentelemetry-js-api 1.2.0
* opentelemetry-js 1.6.0
* opentelemetry-js-contrib 0.31.0 (express and http autoinstrumentations)

### What version of Node are you using?

* node 18.4.0
* npm 8.15.1

### What did you do?

I've been able to get Express autoinstrumentations from my app, though http and other autoinstrumentations work fine.

I cut it down to an absolute bare-bones example at https://github.com/ringerc/otel-express-node-instrumentation-issue to demonstrate the issue.

### What did you expect to see?

Trace spans for http, then for Express request and middleware.

### What did you see instead?

Only trace spans for http, despite the Express server handling the request and firing middleware.

### Additional context

Self-contained compileable example at https://github.com/ringerc/otel-express-node-instrumentation-issue . Uses the console span exporter for simplicity.

Gitter thread I raised @ https://gitter.im/open-telemetry/opentelemetry-node?at=631e7f1811a6a83d04ad8353

Compare to https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-express/examples/src/tracer.ts which doesn't use `--require`. But if I import my tracing setup directly into the main app in my demo like the linked example code I get no auto-instrumentation from the http or express exporters.

**Comment by Flarna** [comment]
Some hints how to fix this:
* exclude tracing.js from the esbuild bundle
* remove anything not related to OTel setup from tracing.js (e.g `import consola from 'consola'`)
* load and register instrumentations before anything else (e.g. before importing other files and doing resource detection...)
* ensure your bundler does not bundle dependencies you want to instrument (e.g. express must stay in folder node_modules/express)

**Comment by ringerc** [comment]
@Flarna I've updated the test case to reflect these changes.

* In the test case supplied, `tracing.js` was already excluded from the esbuild bundle because it's outside the `src/` tree. But I've moved it into the tree and explicitly excluded it as external instead and pushed a new revision. `grep opentelemetry server/dist/use_require_arg.js` in the updated repo confirms that it is not bundled.
* Removed `consola` use from `tracing.ts`
* Ensured opentelemetry is loaded before anything else

I added a second test case that demonstrates the same behaviour when I use `require('./tracing');` in the main app's entrypoint script instead of using a separate `--require` argument. Invoke as `npm run start:combined`.

**Comment by ringerc** [comment]
@Flarna That was it.

Adding `--external:express` on the `esbuild` CLI in `package.json` allowed the Express server to be instrumented.

Thank you. I have bashed my head against this for days.

**Comment by ringerc** [comment]
For other readers, another pitfall is using `import` for your tracing script if you're loading it directly into your app rather than using `--require`.

It appears you must use e.g. `require('./tracing');` or if your tracing setup is an a function something like `const { initOpenTelemetry } = require('./tracing');` . 

**If you use `import { initOpenTelemetry } from './tracing';` your auto-instrumentation will not work.**

**Comment by ringerc** [comment]
I'll see about raising a docs PR for this. In the mean time the next person might find this issue or my updates to my demo PR and figure it out without quite so much pain. Thanks so much for the help.

**Comment by ringerc** [comment]
I pushed a fixed version to https://github.com/ringerc/otel-express-node-instrumentation-issue along with an explanation.

**Comment by polRk** [comment]
> @Flarna That was it.
> 
> **Adding `--external:request --external:express` on the `esbuild` CLI in `package.json` allowed the Express server to be instrumented.**
> 
> Thank you. I have bashed my head against this for days. And the reason that HTTP instrumentation worked is that I cargo-culted `--external:requests` from the real app I cut down to make this demo.
> 
> I would love to see this prominently highlighted in the docs for the instrumentation package, the node auto instrumentations bundle etc.

If it not possible to make express external? Why graphql works? why http works? But express - not working

**Comment by Flarna** [comment]
For graphql I can't tell. http is different because it's a node.js internal module which is never load from disc and as a result the module cache works different.
