### ISSUE TITLE
@opentelemetry/auto-instrumentations-web not ES5 compatible

### ISSUE THREAD

**Issue by mdbudnick** [open-telemetry/opentelemetry-js-contrib#1186]
### What version of OpenTelemetry are you using?
0.30.0

### What version of Node are you using?
14.20.0

### What did you do?

I've installed "@opentelemetry/auto-instrumentations-web": "^0.30.0",
and in my project use `import { getWebAutoInstrumentations } from '@opentelemetry/auto-instrumentations-web'` with an OTLPExporter.

It works fine except for IE 10 and 11 because the module code in my client js is not ES5-compatible:
```
function(e, t, r) {
            "use strict";
            Object.defineProperty(r, "__esModule", {
                value: !0
            }), r.getWebAutoInstrumentations = void 0;
            const n = e("@opentelemetry/api"),
                o = e("@opentelemetry/instrumentation-document-load"),
                s = e("@opentelemetry/instrumentation-fetch"),
                i = e("@opentelemetry/instrumentation-user-interaction"),
                a = e("@opentelemetry/instrumentation-xml-http-request"),
                l = {
                    "@opentelemetry/instrumentation-document-load": o.DocumentLoadInstrumentation,
                    "@opentelemetry/instrumentation-fetch": s.FetchInstrumentation,
                    "@opentelemetry/instrumentation-user-interaction": i.UserInteractionInstrumentation,
                    "@opentelemetry/instrumentation-xml-http-request": a.XMLHttpRequestInstrumentation
                };
            r.getWebAutoInstrumentations = function(e = {})
}
```
i.e. default values are not allowed for arguments: `function(e = {})`

### What did you expect to see?
ES5 compliant code that works in IE10 and 11. From what I have [found in this project](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/557), ES5 compliance can ([should?](https://github.com/open-telemetry/opentelemetry-js/pull/1368)) be expected.

### What did you see instead?
An error in my run.js: `Expected ')'` after the e in `function(e = {})` because default argument values were introduced in ES6

### Additional context

It is possible I am not doing something obvious, I am a backend engineer setting up OTel tracing in our company.

**Comment by mdbudnick** [comment]
Also this https://github.com/open-telemetry/opentelemetry-js/pull/1368

**Comment by mdbudnick** [comment]
Created https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1187

**Comment by dyladan** [comment]
This is not a bug since the packages in question aren't supporting es5

**Comment by mdbudnick** [comment]
Ok, closing this ticket. I have been working with the team on excluding it from IE clients. Thanks!
