### ISSUE TITLE
Express spans showing impossible duration_ms

### ISSUE THREAD

**Issue by DAlperin** [open-telemetry/opentelemetry-js-contrib#1193]
### What version of OpenTelemetry are you using?
0.33.0

### What version of Node are you using?
`16 lts`

### What did you do?
Instrumented node. I use the following to set up my tracing:
```ts
import { getNodeAutoInstrumentations } from "@opentelemetry/auto-instrumentations-node";
import { OTLPTraceExporter } from "@opentelemetry/exporter-trace-otlp-proto";
import { NodeSDK } from "@opentelemetry/sdk-node";
import { PrismaInstrumentation } from "@prisma/instrumentation";

const traceExporter = new OTLPTraceExporter();

const sdk = new NodeSDK({
    traceExporter,
    instrumentations: [
        getNodeAutoInstrumentations(),
        new PrismaInstrumentation(),
    ],
});

// eslint-disable-next-line @typescript-eslint/no-floating-promises
sdk.start().then(() => {
    // eslint-disable-next-line no-console
    console.log(`✅ OTLP ready`);
});
```
### What did you expect to see?
Reasonable tracing

### What did you see instead?
![Screenshot from 2022-09-21 12-45-04](https://user-images.githubusercontent.com/16063713/191564366-9bf2ba17-01e3-4123-bfd0-47a5df20f420.png)

**Comment by Rauno56** [comment]
`@prisma/instrumentation` is not hosted here. Have you tried to let them know at https://github.com/prisma/prisma_

**Comment by DAlperin** [comment]
The issue appears to be in express instrumentation. The issue persists even without the prisma instrumentation enabled.

**Comment by vmarchaud** [comment]
Could you share the code of the middleware in question ? There can be edge cases that make it hard to track exactly when each middleware is ended

**Comment by DAlperin** [comment]
Here is where I set up all my middlewares: https://github.com/DAlperin/dov.dev-remix/blob/main/server.ts

**Comment by beeme1mr** [comment]
I also ran into the same issue. Downgrading to `"@opentelemetry/auto-instrumentations-node": "^0.31.2"`  resolved the issue. It seems like the only noteworthy change for express was [requestHook support](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1091).

**Comment by DAlperin** [comment]
@beeme1mr out of curiosity what tool were you using to visualize your traces?

**Comment by beeme1mr** [comment]
I was using the latest version of Jaeger.

**Comment by Flarna** [comment]
see also #1193

**Comment by dyladan** [comment]
https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1210
