### ISSUE TITLE
Mongoose instrumentation imports types from the underlying package

### ISSUE THREAD

**Issue by Rauno56** [open-telemetry/opentelemetry-js-contrib#1217]
`utils.d.ts` and `mongoose.d.ts` of the build assets import types from `mongoose`:

```
import type [...] from 'mongoose';
```

Which means that the compilation fails, if the user has not installed the `mongoose` package - happens with metapackage users for example.

This needs to be fixed by removing all references of the mongoose types from the public APIs.

**Comment by Rauno56** [comment]
@blumamir, would you like to take it yourself or shall I?

**Comment by blumamir** [comment]
> @blumamir, would you like to take it yourself or shall I?

Sorry I was on vacation, thanks for taking this, will review your PR :)
