### ISSUE TITLE
Dataloader instrumentation imports types from the underlying package

### ISSUE THREAD

**Issue by Rauno56** [open-telemetry/opentelemetry-js-contrib#1218]
`instrumentation.d.ts` of the build assets import types from `dataloader`:

```
import type [...] from 'dataloader';
```

Which means that the compilation fails, if the user has not installed the `dataloader` package - happens with metapackage users for example.

This needs to be fixed by removing all references to any of the dataloader types from the public APIs.

**Comment by Rauno56** [comment]
@henrinormak, would you like to take it yourself or shall I?

**Comment by henrinormak** [comment]
Will be fixed by #1221, thanks for spotting and taking care of this! 🙇
