### ISSUE TITLE
pg instrumentation: enhancedDatabaseReporting value is not parsable

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-js-contrib#1235]
### What version of OpenTelemetry are you using?
 "@opentelemetry/instrumentation-pg": "0.31.1"

### What version of Node are you using?
16

### What did you do?
Executed the following pg query with instrumentation config `enhancedDatabaseReporting: true`
```js
    const res = await client.query('SELECT $1::text as message1, $2::text as message2', ['Hello,World', 'foo,bar']);
```

### What did you expect to see?
I expected to be able to tell what the query values are for this operation.

### What did you see instead?
I got this value in the `db.postgresql.values` attribute: `"[Hello,World,foo,bar]"`
This text is not reversible. all of these arrays will yield the same attribute value and there is no way to differentiate them in a deterministic way:
```js
['Hello,World', 'foo,bar']
['Hello', 'World,foo,bar']
['Hello,World,foo', 'bar']
```

### Additional context
The reason is that [this data is serialized](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/682d6107b7285829bb72e592936c585ccdfab16a/plugins/node/opentelemetry-instrumentation-pg/src/utils.ts#L48) in a non-standard, non-reversible way:
```js
function arrayStringifyHelper(arr: Array<unknown>): string {
  return '[' + arr.toString() + ']';
}
```

I suggest using `JSON.stringify`

**Comment by blumamir** [comment]
This serialization also fails to distinguish between types: 
```
['foo', 6]
['foo', '6']
```

are both serialized into the attribute with the same value: `"[foo,6]"`

**Comment by haddasbronfman** [comment]
Can you assign this to me?

**Comment by haddasbronfman** [comment]
after this pr https://github.com/open-telemetry/opentelemetry-specification/pull/3092 will be merged, the function `arrayStringifyHelper` is no more needed because `bd.bind.values` will be an array anyway. The fix will be to just use the `arr` as is, and delete the function `arrayStringifyHelper` from pg (and mysql) instrumentations.

**Comment by haddasbronfman** [comment]
Currently in work in this PR: #1453
