### ISSUE TITLE
mysql instrumentation: query parameters are recorded by default

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-js-contrib#1237]
### What version of OpenTelemetry are you using?
"@opentelemetry/instrumentation-mysql": "0.31.1",

### What version of Node are you using?
16

### What did you do?
```js
import { promisify } from 'util';
import mysql from 'mysql';
const connection = mysql.createConnection({});
const asyncQuery = promisify(connection.query).bind(connection);
asyncQuery('SELECT * FROM users WHERE id = ?', [1]);
```

### What did you expect to see?
I expected `db.statement` attribute to not record the parameter value by default, as it might contain sensitive values.

### What did you see instead?
`db.statement` contains the value `"SELECT * FROM users WHERE id = 1"`

**Comment by ranrib** [comment]
I guess there might be some cases where the data can be interesting, so I wouldn't omit everything by default, no?

**Comment by blumamir** [comment]
I think these values are considered "payload" and we try to have safe defaults which means not to record them unless the user explicitly requests to via instrumentation configuration.
I know postgres instrumentation does this and knex too if I remember correctly.

Maybe we should have some discussion and come up with guidance for this

**Comment by ranrib** [comment]
Adding my 2 cents here - at Epsagon, we used to have the ability to configure whether we should collect payloads, or not. As a general discussion, this can be applied globally, at a framework level, or even on a specific key.

Maybe a good start would be a specific mysql-instrumentation configuration on whether to collect query payloads or not.

**Comment by blumamir** [comment]
This issue is about possible sensitive data being collected by default.
Many instrumentations offer hooks via config, which makes it possible for users / vendor distributions to add payload attributes as they see fit.
I would be more than happy to see this being added for mysql too :)

**Comment by blumamir** [comment]
I found that `"@opentelemetry/instrumentation-mysql2": "0.32.0"` package also record the placeholder values into the `db.statement` attribute.

```js
import mysql from 'mysql2/promise';
    const connection = await mysql.createConnection({
        host: 'localhost',
        user: 'aspecto',
        password: 'secret',
        database: 'test_db',
        port: 33306,
    });

    const [queryValuesRes] = await connection.query('SELECT * FROM users WHERE id = ?', [1234]);
```

value in `db.statement`: "SELECT * FROM users WHERE id = 1234"

**Comment by arbiv** [comment]
The relevant configuration value in Postgres is [enhancedDatabaseReporting](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-pg/src/types.ts#L30)
