### ISSUE TITLE
mongodb: "db.mongodb.collection" attribute captures incorrect value "$cmd" for some commands

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-js-contrib#1244]
### What version of OpenTelemetry are you using?
"@opentelemetry/instrumentation-mongodb": "^0.32.1",
"mongodb": "^4.11.0",

### What version of Node are you using?
16

### What did you do?
```js
        const aggRes = await collection.aggregate([{ $match: { userName: 'amir' } }]).toArray();
```

### What did you expect to see?
I expected to see meaningful value in the "db.mongodb.collection" attribute.

### What did you see instead?
"db.mongodb.collection" contains the value "$cmd" which is not according to semantic conventions specification:

Attribute | Type | Description | Examples | Requirement Level
-- | -- | -- | -- | --
db.mongodb.collection | string | The collection being accessed within the database stated in db.name. | customers; products | Required

### Additional context
The example here is for `aggregate` but it also happens for other commands such as `listIndexes`, `findAndModify `, `createIndexes`, `isMaster` and probably others

**Comment by haddasbronfman** [comment]
Hi, can you assign this to me please?

**Comment by blumamir** [comment]
Thank you for looking into this
