### ISSUE TITLE
aws: 0.32.0 released but not documented in source code

### ISSUE THREAD

**Issue by icco** [open-telemetry/opentelemetry-js-contrib#1260]
### What version of OpenTelemetry are you using?

N/A

### What version of Node are you using?

N/A

### What did you do?

I see https://www.npmjs.com/package/@opentelemetry/instrumentation-aws-sdk/v/0.32.0 is released but is not a version documented in code.

### What did you expect to see?

Not see this version, or see a release on github

**Comment by blumamir** [comment]
There was a problem with `aws-sdk` instrumentation versioning.
When we first wrote it, it was published (probably by mistake) with version `0.25.0` and then the final version changed to `0.1.0` which [confused tools like snyk](#1153 ).

So I manually bumped the version in #1247 to be `0.32.0`.

Not sure how it got released. Our release automation workflow is currently not working and I think we run it manually until we resolve some issues with github rate limiting.
@dyladan - Did you run it manually? Should we expect github releases for it and entries in `CHANGELOG.md`?
If so, do you know why it failed this time (probably our tool got confused by the manual version bump)
