### ISSUE TITLE
Add ordering information for AWS resource detectors

### ISSUE THREAD

**Issue by sairam866** [open-telemetry/opentelemetry-js-contrib#1262]
### What version of OpenTelemetry are you using?
Latest from Github

### What version of Node are you using?
18.11.0

### What did you do?

AWS resource detectors documentation missing ordering information as in 
https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/detectors/node/opentelemetry-resource-detector-aws 

### What did you expect to see?
Ordering information for AWS resource detectors as in
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/resourcedetectionprocessor/README.md#ordering

### What did you see instead?
No ordering information for AWS resource detectors.

### Additional context

NA

**Comment by sairam866** [comment]
cc: @svrnm

**Comment by osherv** [comment]
You can assign this to me :)
