### ISSUE TITLE
rename types.ts to config.ts?

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-js-contrib#1271]
In #1251 I separated the instrumentation types into 2 files called: `types.ts` (for public types) and `internal-types.ts` (for private-types), and documented the convention in `GUIDELINES.md`.

However, after working on this lately, I now realize that the `types.ts` file only contains the instrumentation config and related types.

I want to suggest renaming the files to 
`config.ts`
for the public types which are instrumentation config and the related types like hooks and enums.

and
`types.ts`
for internal types of instrumentation (which should not be exported).

Since this is an internal change, it should not affect end users (which only import from `index.ts`)

I think this is a good time to do this change, because in the future we might have more complex dependencies and more users, and I was already touching a lot of the files around this area lately.

The name `internal-types.ts` doesn't feel like the best fit IMO.

What do you think?

**Comment by osherv** [comment]
I think it makes sense. I cannot think of types we're using that will not fall under these two categories.
