### ISSUE TITLE
Non-spec / AWS Lambda Detector / Add escape hatch for synchronous resource detection

### ISSUE THREAD

**Issue by NPellet** [open-telemetry/opentelemetry-js-contrib#1273]
### Is your feature request related to a problem? Please describe

- We want to get telemetry running for our AWS Lambdas.
- If resource detection is asynchronous, then:
  - So should the SDK initialization
  - Can't run the initialization with node -r (otherwise setup might not be done before the lambda has actually run)
  - Has to change application code (I have hundreds and hundreds of lambdas...)
  - Need to create one new handler file for each lambda (very impractical)

### Describe the solution you'd like to see
Luckily, the lambda detector is actually synchronous. As it turns out, in my case, it's the only asynchronous resource detection I'd like to run.
So until the opentelemetry-js core developers figure out how they want to handle asynchronous resources, I'd love to get a simple escape-hatch for the lambda resource detector, that would be out-of-spec, but would allow synchronous detection of the resource.

File: https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsLambdaDetector.ts

It could look something like:

```typescript

export class AwsLambdaDetector implements Detector {
  detectSync(_config?: ResourceDetectionConfig): Resource {
    
    // same implementation as now
  }

  async detect( _config?: ResourceDetectionConfig): Promise<Resource> {
    return this.detect(_config);
  }
}
```

### Describe alternatives you've considered
When node 19+ can be used as runtime in AWS Lambda, then we can use the `--import` cli option and a top-level await.

I'll happily open a PR if you'd consider it.

**Comment by Flarna** [comment]
As alternative you could use `@opentelemetry/sdk-trace-node` instead `@opentelemetry/sdk-node`.

It's a lower layer part of SDK for traces only used internally by NodeSDK and requires a bit more lines to write to set it up. For example you have to provide `Resource` as config. But this has exactly the advantage that you can do your sync resource detection and then create the NodeTracerProvider,...

**Comment by Flarna** [comment]
There was some discussion about sync resource detection: https://github.com/open-telemetry/opentelemetry-js/issues/3055
And also a PR which looked quite promising as far as I remember: https://github.com/open-telemetry/opentelemetry-js/pull/2933

but both were closed by the stale bot...

**Comment by NPellet** [comment]
Well it's what I do, e.g. for EKS

```typescript
    const resource = Resource.default()
      .merge(
        new Resource({
          [SemanticResourceAttributes.SERVICE_NAME]: options.serviceName,
        })
      )
      .merge(
        await detectResources({
          detectors: [awsEksDetector],
        })
      );

    /********* TRACING */
    const tracingProvider = new NodeTracerProvider({
      resource,
    });

```


That's the whole point isn't it ? I want to get rid of the ```detectResources``` and only use a synchronous call, like such:

```typescript
const _awsLambdaDetector = new AwsLambdaDetector()
const resource = Resource.default()
  .merge(
    new Resource({
      [SemanticResourceAttributes.SERVICE_NAME]: options.serviceName,
    }).merge( _awsLambdaDetector .detectSync() ) })
```

I've been through all those stales issues. I didn't necessarily want to get into that topic so I thought, at least for AWS Lambdas there's no need to solve the underlying issue before getting it to work...

**Comment by Flarna** [comment]
Ah well sorry. Forgot that's already the detectors API which is async in all cases. I thought that it's the NodeSDK which introduces the  async part in some case.

But actually running the `AwsLambdaDetector` via `-r` should work. I know it's async but there is no network request or similar which lets the event loop reach idle - it's just a microtask. I'm quite sure it will finish before your handler is called the first time.

**Comment by Flarna** [comment]
The async resource detection is one of the pain points left to be solved. OTel spec requires resource to be immutable so detection needs to be done before the first span is started as resource is a config of the TracerProvider.
Some detectors are really async as they do HTTP request. They "infected" all other detectors by using a common API.

See above linked issue/PR for more details, in depth discussions and started solutions. I'm sure there will be some movement in this at some time but for now be happy that your detector is not "too async" :o).

Actually I think you could implement a true async lambda init via [extension](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-extensions-api.html) as you have a async init phase. But I doubt this is worth the effort in your case.

**Comment by NPellet** [comment]
Yes well we are actually extensions to load the dependent packages and to provide ```-r``` cli flag via `NODE_OPTIONS`

But you may be right, I will check if a true async would be possible. So far we've only used external extensions, where this wouldn't apply. But perhaps internal ones... I'll investigate.

**Comment by NPellet** [comment]
It's me again !
Surprisingly, what we thought didn't work.

Given the following code:
```typescript

// Asynchronous
const setup = async () => {

 const resource = Resource.default().merge(
      new Resource({
        [SemanticResourceAttributes.SERVICE_NAME]: options.serviceName,
      })
    )
    .merge(
      await detectResources({
        detectors: [awsLambdaDetector],
      })
    );
    // Rest of init...
    opentelemetry.diag.info("Finished loading the OTLP tracer");

}

setup();
```

I get:

<html>
<body>


  | 2022-11-08T20:09:24.870+01:00 | 2022-11-08T19:09:24.870Z undefined WARN @opentelemetry/instrumentation-aws-lambda Module /var/task/getAssetsEndpoint.js has been loaded before @opentelemetry/instrumentation-aws-lambda so it might not work, please initialize it before requiring /var/task/getAssetsEndpoint.js
-- | -- | --
  | 2022-11-08T20:09:24.907+01:00 | 2022-11-08T19:09:24.907Z undefined INFO Finished loading the OTLP tracer


</body>
</html>


Given the synchronous version:

```typescript

// Asynchronous
const setup = () => {

 const resource = Resource.default().merge(
      new Resource({
        [SemanticResourceAttributes.SERVICE_NAME]: options.serviceName,
      })
    );
    // Rest of init...
    opentelemetry.diag.info("Finished loading the OTLP tracer");
}

setup();
```

I get proper initialization (and instrumentation)

**Comment by NPellet** [comment]
And on a sidenote, discussing lambda extensions, it sounded good but doesn't work as well.
Given an internal extension (runtime modification), I thought it would be possible to run:

```shell
#!/bin/bash
args=("$@")
OWN_FILENAME="$(basename $0)"
LAMBDA_EXTENSION_NAME="$OWN_FILENAME"
echo "${LAMBDA_EXTENSION_NAME}  launching extension"
node /opt/node_modules/path/to/my/otel/extension/code
echo "Finished setting up extension"
exec "${args[@]}" 
```

(Obviously) it doesn't work because the process (the first call to the node executable) finishes and all libraries unload. This was stupid of me to try.

Instead, what is needed is:

```shell
#!/bin/bash

args=("$@")
OWN_FILENAME="$(basename $0)"
LAMBDA_EXTENSION_NAME="$OWN_FILENAME" # (external) extension name has to match the filename
echo "${LAMBDA_EXTENSION_NAME}  launching extension"
NODE_PATH=NODE_PATH:/opt/node_modules
extra_args=("-r" "/opt/node_modules/path/to/otlp/extension/code")
args=("${args[@]:0:$#-1}" "${extra_args[@]}" "${args[@]: -1}")
echo "Executing ${args[@]}"
exec "${args[@]}" 
```

Which is just the same thing as setting the `-r` cli option, and therefore needs the synchronised init.

**Comment by NPellet** [comment]
Waw that's very interesting:

```
const doSmth = async() => {
  console.log("doSmth");
}

const main = async () => {
  await Promise.all( [ doSmth() ]);
  console.log( "done");
}

main();
console.log("afterMain");

/*
doSmth
afterMain
done
*/
```


```
const doSmth = async() => {
  console.log("doSmth");
}

const main = async () => {
  await Promise.all( [ doSmth() ]);
  console.log( "done");
}

main();
console.log("afterMain");

/*
doSmth
afterMain
done
*/
```


```

const doSmth = async() => {
  console.log("doSmth");
}

const main = async () => {
  Promise.all( [ doSmth() ]); // <== Notice here the lack of await
  console.log( "done");
}

main();
console.log("afterMain");

/* Notice here the inverted logs
doSmth
done
afterMain
*/
```

**Comment by Flarna** [comment]
Sees your ran into https://github.com/open-telemetry/opentelemetry-js/issues/3146. Unfortunately NodeSDK instantiates instrumentations late these days... Workaround is to move this part into the sync startup path instead delegating this task to NodeSDK.

Regarding extensions I was thinking about one implemented in JS. So your JS code registers as internal extension and says done once SDK startup is finished.

If you don't `await Promise.all()` it means you don't wait until it is finished. your second sample above creates a Promise which is never used. Usually you need the result of `doSmth()` and this is within the Promise returned by `Promise.all` which is settled once all promises in the list are settled.

**Comment by NPellet** [comment]
I absolutely agree. But basically all of this is to justify the associated PR.

In javascript, the internal extension could do something like

```typescript

setupOTLP().then( () => {
  require("/** process the AWS lambda env variable to determine the script path */");
});
```

I could certainly do that, but it requires processing the CLI flags in bash (which is doable of course) and reuse them to launch the opentelemetry wrapper.

But I'm not sure how brittle this approach would be.
