### ISSUE TITLE
instrumentation-fastify's docs don't match the latest release on npm

### ISSUE THREAD

**Issue by AskAlice** [open-telemetry/opentelemetry-js-contrib#1283]
A release wasn't cut for the requestHook functionality, so the docs are misleading, especially since there is no experimental package on npm that supports this either.
- [x] This only affects the JavaScript OpenTelemetry library
- [ ] This may affect other libraries, but I would like to get opinions here first

**Comment by SimenB** [comment]
It'll be included when #1269 lands
