### ISSUE TITLE
@opentelemetry/instrumentation-graphql@0.33.0 release failed

### ISSUE THREAD

**Issue by InsidersByte** [open-telemetry/opentelemetry-js-contrib#1293]
The pipeline to release @opentelemetry/instrumentation-graphql@0.33.0 failed https://github.com/open-telemetry/opentelemetry-js-contrib/actions/runs/3482104051/jobs/5824030580

**Comment by mhassan1** [comment]
> ❯ adding comment to https://github.com/open-telemetry/opentelemetry-js-contrib/issue/1269
Error: release-please failed: Server Error

@dyladan It seems like that URL is incorrect; shouldn't it be plural `/issues/1269` instead of singular `/issue/1269`?

**Comment by mhassan1** [comment]
It looks like the release has been done manually by @dyladan. I am seeing those packages have been published earlier today.

**Comment by dyladan** [comment]
Yep. Leaving the issue open while I work on a better fix than manually releasing

**Comment by dyladan** [comment]
Earlier today? Should have been Friday

**Comment by mhassan1** [comment]
Oops, yes, Friday ☝️.
