### ISSUE TITLE
feat(redis & redis-4): only serialize command name in db.statement attribute

### ISSUE THREAD

**Issue by haddasbronfman** [open-telemetry/opentelemetry-js-contrib#1294]
### What did you do?
I used the redis instrumentation

### What did you expect to see?
I expected to see the arguments of my command. e.g. `hset map1 key1 value1`

### What did you see instead?
I saw only the name of the command. e.g. `hset`

### Additional context
This issue was already solved for ioredis [here](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1052), I want to solve it also for redis and redis-4.

**Comment by haddasbronfman** [comment]
Can you please assign this to me? thanks.

**Comment by blumamir** [comment]
fixed in #1299
