### ISSUE TITLE
[express plugin] automatic metrics instrumentation

### ISSUE THREAD

**Issue by naseemkullah** [open-telemetry/opentelemetry-js-contrib#13]
**Describe the solution you'd like**

We can draw inspiration from @yuriatgoogle's https://dev.to/yuriatgoogle/custom-metrics-in-node-js-with-opentelemetry-and-prometheus-3dbd to expose the "golden signals"

**Comment by mbecca** [comment]
Hello, is there any progress?

**Comment by legendecas** [comment]
The metrics spec, JavaScript API, and SDK are under active development. I'd believe we need to wait for a (generally) stable metrics API to start the work on third-party instrumentation. (The work is being tracked at https://github.com/open-telemetry/opentelemetry-js/issues/2480 and https://github.com/open-telemetry/opentelemetry-js/issues/2574)

**Comment by anikdas** [comment]
@legendecas as both the issues linked are now closed. Can we expect any movement on the metrics inside the express plugin?

**Comment by legendecas** [comment]
@anikdas if you are using the http instrumentation, the instrumentation should start reporting HTTP metrics for you.

See more at https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/opentelemetry-instrumentation-http/src/http.ts#L78.

**Comment by pichlermarc** [comment]
> Hey @legendecas I've tried running metrics locally with:
> 
> ```
> OTEL_METRICS_EXPORTER=console
> ```
> 
> and I don't see anything showing in the console. I also don't see anything received by my collector in production.
> 
> On the other hand traces are working fine for me from the same `@opentelemetry/instrumentation-http` package. Is there a flag that I could have missed to ensure those histogram metrics are being captured?
> 
> Edit: just discovered this issue, is it actually not possible to configure the metrics entirely via the command line? [open-telemetry/opentelemetry-js#3193](https://github.com/open-telemetry/opentelemetry-js/issues/3193)

Yes, automatic setup of metrics exporters via env vars this is not implemented yet. #3193 tracks implementation of that.

**Comment by pichlermarc** [comment]
Closing this issue as it was the request to emit metrics for express, which the `@opentelemetry/instrumentation-http` package now does.
