### ISSUE TITLE
Set OTel trace id to request ID in Fastify

### ISSUE THREAD

**Issue by SimenB** [open-telemetry/opentelemetry-js-contrib#1304]
### Is your feature request related to a problem? Please describe

We currently try to set fastify's request ID from the active OTel span, like so

```js
genReqId: () => {
  const spanContext = trace.getActiveSpan()?.spanContext();
  const traceIdFromOtel = spanContext?.traceId;

  return traceIdFromOtel ?? randomUUID();
}
```

This works great if the incoming request had the tracing headers as there is an active span.

However, this means that if there is no active span (i.e. the incoming request didn't have the tracing header) we'll end up generating a request ID which OTel doesn't know about., and in the first request handler, it'll generate its own, and the 2 IDs are not connected (except if we explicitly log the request ID manually).

### Describe the solution you'd like to see

If there is no active span, for the fastify instrumentation to grab `request.id` instead of generating a new one.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by Flarna** [comment]
I wonder why the presence of a span depends on the incoming tracing headers. It's perfectly fine if a server gets a request from someone who is not monitored by OTel and therefore not trace headers are present.

in this case http instrumentation should still create a span but this span has no parent.

**Comment by SimenB** [comment]
I think this function is called before the instrumentation kicks in, perhaps?

**Comment by Flarna** [comment]
That's unlikely as the http instrumentation wraps the request handler.
And if it would kick in before the instrumentation then there would be never a span even if trace headers are present.

Could you share a reproducer?

**Comment by SimenB** [comment]
Oh, of course. My issue was that we passed `requestIdHeader: 'some-header'` to fastify, and it skipped `genReqId` if that header was there. Should have put out those breakpoints before opening an issue. My bad! 🤦
