### ISSUE TITLE
KafkaJS Plugin Request

### ISSUE THREAD

**Issue by sureshballa** [open-telemetry/opentelemetry-js-contrib#131]
**Is your plugin request related to a problem? Please describe.**
Traceability to Kafka for producing and consuming message via KafkaJS package 

**Is it applicable for Node or Browser or both**
Node

**Do you expect this plugin to be commonly used**
Weekly Downloads:
KafkaJS has about 64,000 weekly downloads as of today

**Comment by dyladan** [comment]
I think this is a great idea. @sureshballa are you thinking you want to work on this or are you just requesting the feature?

**Comment by sureshballa** [comment]
@dyladan requesting this plugin feature.

**Comment by mayurkale22** [comment]
Looks like we already have a kafkajs plugin for Node.js., see: https://opentelemetry.io/registry/instrumentation-js-kafkajs/

You may want to read the blog post on same: https://medium.com/aspecto/opentelemetry-plugin-for-kafkajs-8789960b1e66

/cc @blumamir author.

**Comment by dyladan** [comment]
We should add a section to the plugin request template that lets people know to look at the registry.

**Comment by sureshballa** [comment]
@mayurkale22 @blumamir Unfortunately this plugin doesn't wrap transaction based producers, it is implemented for simple producer send based actions. We are using transactions based kafka producers.

**Comment by blumamir** [comment]
Hi @sureshballa 
I am the maintainer of the plugin.
I don't plan to add transaction support anytime soon, but if you want to create a PR for that, I'll be happy to review and merge it.

**Comment by vmarchaud** [comment]
I'm going to close this since it has been implemented there: https://github.com/aspecto-io/opentelemetry-ext-js/tree/master/packages/instrumentation-kafkajs (as mentionned previously).

**Comment by hilleer** [comment]
Hello

Any concerns in including this "already build package" in the node auto instrumentation library? 👀 I'd be happy to make a pull request with such if considered.

**Comment by blumamir** [comment]
@hilleer

The instrumentation is planned to be upstreamed to this repo, I just didn't get to it yet. There are some refactors and changes that need to be done as part of this transition.

Is it possible for you to manually include the plugin in your code for now?

**Comment by hilleer** [comment]
> @hilleer
> 
> The instrumentation is planned to be upstreamed to this repo, I just didn't get to it yet. There are some refactors and changes that need to be done as part of this transition.
> 
> Is it possible for you to manually include the plugin in your code for now?

Awesome! Yeah we can find a temporary solution for that. Thanks for the quick reply.
