### ISSUE TITLE
AWS Lambda - http

### ISSUE THREAD

**Issue by obecny** [open-telemetry/opentelemetry-js-contrib#132]
### Is your plugin request related to a problem? Please describe
Currently on lambda function all the incoming requests are not "catched" / "handled" by http module. This causes that the http plugin is not creating any new span and when you try to get currentSpan in handler function it returns undefined. 
We should investigate this issue further and see if we can come out with some plugin solution that could mimic the behaviour of http plugin instrumentation only for incoming requests.
When lambda functions is doing any http request those requests are being instrumented correctly, but there is no information from the incoming / outside request that "hits" lambda 

### Is it applicable for Node or Browser or both
Node
### Do you expect this plugin to be commonly used
could be
### What version of plugin are you interested in using
latest
### Additional context
This can improve the tracing information. In a contrast on GCP the incoming request is using the http module so the context propagation is kept.

**Comment by dyladan** [comment]
Transferred this to contrib. If you think it should be in core let me know and we can maybe move it back.

**Comment by dyladan** [comment]
I have been working on this already and should have a PR incoming for the first part of this sometime early next week.

**Comment by obecny** [comment]
With regards to keeping this in contrib. Hard to say before seeing the PR, but if the plugin depends on our http plugin or its existence makes sense only if you use http plugin then I would keep it core. WDYT ? But I would like to hear feedback from @mayurkale22 as well

**Comment by dyladan** [comment]
It will not depend on the HTTP plugin and will handle more invocation types than just http.

**Comment by obecny** [comment]
> It will not depend on the HTTP plugin and will handle more invocation types than just http.

then I would leave it in contrib :)

**Comment by vmarchaud** [comment]
We have https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-aws-lambda now
