### ISSUE TITLE
tsc compiling both redis and redis-4 when importing getNodeAutoInstrumentations

### ISSUE THREAD

**Issue by chaychoong** [open-telemetry/opentelemetry-js-contrib#1323]
## Steps to Reproduce
- redis@4.0.2 or above installed in project
- `tsc --project tsconfig.json`

tsconfig file:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "rootDir": "./src",
    "outDir": "./build",
    "esModuleInterop": true,
    "inlineSourceMap": true,
    "inlineSources": true
  }
}
```

## Expected Result
No errors

## Actual Result
```
> xxx1.0.0 build
> tsc --project ./tsconfig.prod.json && tsc --project ./tsconfig-prisma.json

../node_modules/@opentelemetry/instrumentation-redis/build/src/types.d.ts:8:26 - error TS2694: Namespace '"/home/xxx/xxx/node_modules/redis/dist/index"' has no exported member 'Callback'.

8     callback: redisTypes.Callback<unknown>;
                           ~~~~~~~~
```

### OpenTelemetry Setup Code

```
import { NodeSDK } from "@opentelemetry/sdk-node";
import { HoneycombSDK } from "@honeycombio/opentelemetry-node";
import { getNodeAutoInstrumentations } from "@opentelemetry/auto-instrumentations-node";

export const honeycombSdk: NodeSDK = new HoneycombSDK({
  instrumentations: [getNodeAutoInstrumentations()]
});
```

**Comment by letruonglamit** [comment]
Same issue on my side

**Comment by dyladan** [comment]
@letruonglamit can you provide a little more info here? The OP doesn't really provide a lot so it's hard to tell what's happening.

**Comment by chaychoong** [comment]
Hi! Perhaps it's the tunnel vision but I'm not sure what additional information I could provide to make this report more complete.

- Install redis 4.0.2 (or any redis 4 version)
- Install and use auto instrumentation
- Run the tsc command
- It should fail with the provided error message.

Is this a problem with how I setup the project?

**Comment by pichlermarc** [comment]
Thanks for the info. I'll pick this up then. :slightly_smiling_face:
