### ISSUE TITLE
Support to disable specific library or middleware instrumentation via environment variable

### ISSUE THREAD

**Issue by santoshkashyap** [open-telemetry/opentelemetry-js-contrib#1331]
### Is your feature request related to a problem? Please describe

My application is based on NodeJs  express library and I tried to achieve auto instrumentation using different approaches as mentioned below

Consider the trace shown in the image below when the application is instrumented  (see Additional context section for dependencies used below)
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/16810482/208107626-c8f9504b-05d9-4366-892b-f81b8d897832.png">

I also have a different setup in Kubernetes cluster based on [OpenTelemetry Operator](https://github.com/open-telemetry/opentelemetry-operator)
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/16810482/208113158-8ca44a90-6359-464b-8d92-3edd0d834454.png">

On this occasion, the purple comes from the instrumented library `@opentelemetry/instrumentation-net`.

Even though the spans from auto-instrumentation is useful, they can clutter application specific spans and often digging through the span mesh to identify application specific spans can be frustrating.

### Describe the solution you'd like to see
From the screen shot above, I would like to have only the span highlighted in red displayed and the other spans(middleware or other libraries) disabled by some configuration or environment variables. Even though the spans provide useful information, but most of the times it adds unnecessary information cluttering the application specific spans. Often it becomes very hard to identify the application specific spans among the several library instrumented spans. I would like to see some support for environment variables to disable spans for specific instrumented libraries (Similar thing is possible with JavaAgent based instrumentation, see [suppressing-specific-auto-instrumentation](https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/#suppressing-specific-auto-instrumentation)). For example, there could be an environment variable to disable spans when not required for a specific library like `@opentelemetry/instrumentation-net` or support to disable middleware spans in any instrumented library.

In another approach in Kubernetes cluster, I used [OpenTelemetry Operator](https://github.com/open-telemetry/opentelemetry-operator) and the corresponding [annotations on the pod](https://github.com/open-telemetry/opentelemetry-operator#opentelemetry-auto-instrumentation-injection) to inject instrumentation libraries for NodeJS applications. Since, the OpenTelemetry Operator is a "client" of OpenTelemetry upstream instrumentation,  it would really be helpful to have environment variables to disable auto-instrumentation of specific libraries.

### Describe alternatives you've considered
Not aware of any. Only thing I tried is to use a individual dependencies instead of [auto-instrumentations-node](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/metapackages/auto-instrumentations-node). Even while using  `auto-instrumentation-node` package, it would be nice to have support for environment variables to disable auto-instrumentation for specific libraries.

### Additional context

The express application has following dependencies used for instrumentation:
```
"@opentelemetry/api": "1.3.0",
"@opentelemetry/exporter-trace-otlp-http": "0.34.0",
"@opentelemetry/instrumentation": "0.34.0",
"@opentelemetry/instrumentation-express": "0.32.0",
"@opentelemetry/instrumentation-http": "0.32.0",
"@opentelemetry/resources": "1.8.0",
"@opentelemetry/sdk-trace-base": "1.8.0",
"@opentelemetry/sdk-trace-node": "1.8.0",
"@opentelemetry/semantic-conventions": "1.8.0",
```

Thanks in advance!!!

**Best,**
Santosh

**Comment by Flarna** [comment]
I think this is a good idea.
As far as I remember the instrumentations usually install themself already during creation, not just during `registerInstrumentation()`.

I think the best place for this would be inside the instrumentation base class if it is possible. Would requite to define a pattern to translate instrumentation scope to env name.
If a central place doesn't work out it should be likely in the instrumentation itself.

I would not put it into `@opentelemetry/auto-instrumentations-node` because such disabling should work independent of using this metapackage.

**Comment by TylerHelmuth** [comment]
I would love to see this reopened.  Other language auto-instrumentation support this today; python uses `OTEL_PYTHON_DISABLED_INSTRUMENTATIONS`, java uses `OTEL_INSTRUMENTATION_[NAME]_ENABLED=false`, and dotnet uses `OTEL_DOTNET_AUTO_{SIGNAL}_{0}_INSTRUMENTATION_ENABLED`.
