### ISSUE TITLE
auto-instrumentations-node: Allow configuration of custom sampler

### ISSUE THREAD

**Issue by adecchi-2inno** [open-telemetry/opentelemetry-js-contrib#1333]
I am using [OpenTelemetry Operator](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-operator) and [NodeJS Auto Instrumentation](https://github.com/open-telemetry/opentelemetry-operator/tree/main/autoinstrumentation/nodejs), and I would like to create custom sampler, for example to ignoring certain url-patterns like:

- /info
- /health
-  /swagger-ui
- /openapi.json
- etc

I could not find a way to resolve it, is a way to create custom sampler ?

kind regards,

**Comment by blumamir** [comment]
This is not possible to be configured from environment variables.
The only supported values [from spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#general-sdk-configuration) are:

> Known values for OTEL_TRACES_SAMPLER are:
> 
> "always_on": AlwaysOnSampler
> "always_off": AlwaysOffSampler
> "traceidratio": TraceIdRatioBased
> "parentbased_always_on": ParentBased(root=AlwaysOnSampler)
> "parentbased_always_off": ParentBased(root=AlwaysOffSampler)
> "parentbased_traceidratio": ParentBased(root=TraceIdRatioBased)
> "parentbased_jaeger_remote": ParentBased(root=JaegerRemoteSampler)
> "jaeger_remote": JaegerRemoteSampler
> "xray": [AWS X-Ray Centralized Sampling](https://docs.aws.amazon.com/xray/latest/devguide/xray-console-sampling.html) (third party)

You will need to implement your own sampler in code and instrument the services yourself, or if the operator has a way of injecting custom SDKs you might do it there (I don't know, never used it myself).

**Comment by pichlermarc** [comment]
This looks like it needs to go though the spec first. Closing this for now.
