### ISSUE TITLE
MySQL: only serialize non-sensitive data in db.statement attribute

### ISSUE THREAD

**Issue by haddasbronfman** [open-telemetry/opentelemetry-js-contrib#1336]
### Is your feature request related to a problem? Please describe
When I use mysql instrumentation, I see the full query in the span: `db.statement: SELECT a FROM b WHERE password='ppp'`.
I think we shouldn't display sensitive data by default. 

### Describe the solution you'd like to see
In mongo/mongoose, and in redis/ioredis we have a config object that has a field called: `dbStatementSerializer` which is a **function** that determines how the statement will be parsed. I think we need to add this ability to mysql also. 

### Describe alternatives you've considered
I thought to add a boolean parameter that enables/disables the `db.statement`.
But I think this solution is too "narrow". With a function, the user can decide **how** the `db.statement` will look like and not just decide if to present it or not.

**Comment by haddasbronfman** [comment]
If accepted, can you assign this to me?

**Comment by blumamir** [comment]
Thanks for opening the issue. Is it the same as #1237 ?

**Comment by haddasbronfman** [comment]
duplicate of #1237

**Comment by haddasbronfman** [comment]
duplicate of #1237
