### ISSUE TITLE
instrumentation restify: support new versions

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-js-contrib#1339]
current restify instrumentation supports [the following range](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/28ad01e040f44a7b9ff1f76c4ba486074e8faf9c/plugins/node/opentelemetry-instrumentation-restify/src/constants.ts#L27)

```js
export const SUPPORTED_VERSIONS = ['>=4.0.0 <9'];
```

and [tav is configured with](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-restify/.tav.yml)
```yaml
restify:
  versions: "4.3.4 || 5.2.0 || 6.4.0 || 7.7.0 || ^8.4.0"
  commands: npm run test
```

There are [new versions of restify](https://www.npmjs.com/package/restify/v/9.0.0) that will not be instrumented (9.0.0, 10.0.0) which needs to be added to the supported and tested versions (and verified they also work).

Renovate tried to bump the version in #1317 but there are other code changes that needs to be done.

This issue is for adding support for newer restify versions

**Comment by blumamir** [comment]
`@types/restify` is also very old, and the renovate PR to bump it #1292 failed with message:
> lerna ERR! lifecycle "prepare" errored in "@opentelemetry/instrumentation-restify", exiting 1

The types should also be aligned as part of this issue

**Comment by kirrg001** [comment]
FYI restify v8 does not work with Node v18. Support was added in restify v10.
https://github.com/restify/node-restify/issues/1925

**Comment by kirrg001** [comment]
Can we please re-open this issue?

**Comment by pichlermarc** [comment]
> Can we please re-open this issue?
Yes, I think #1576 would take care of this. :slightly_smiling_face:
