### ISSUE TITLE
Add plugin for mysql2

### ISSUE THREAD

**Issue by kintel** [open-telemetry/opentelemetry-js-contrib#135]
This is supported by the current offerings of at least Google (https://github.com/googleapis/cloud-trace-nodejs#what-gets-traced) and Lightstep (https://docs.lightstep.com/docs/nodejs-auto-instrumentation#data-stores), so it would be good to add to OpenTelemetry.

**Comment by dyladan** [comment]
I agree. I have a local version of the mysql plugin which I started modifying to support mysql and mysql2. I may have time to finish that up in the near future.

**Comment by legendecas** [comment]
@dyladan So https://github.com/open-telemetry/opentelemetry-js/issues/1376#issuecomment-668796246 can be a blocker for this one right?

**Comment by dyladan** [comment]
@legendecas I actually fixed the flaky test by preventing that test from loading plugins. I don't see why it would be a blocker for this though.

**Comment by legendecas** [comment]
> @dyladan  I think the plugin system needs a drastic overhaul. Managing a list of plugins to autoload is cumbersome, the fact that a single plugin cannot instrument two modules can be a pain (as is the case with http/https and grpc/grpc-js, and would be similar with mysql/mysql2 if we supported mysql2), and plugin configuration is awkward.

I noticed that you mentioned that an overhaul might be needed to get mysql/mysql2 instruments merged in a single plugin. 
 So the feature you mentioned is better to have right? Before that, we can still have mysql2 instrument in a new plugin for them.

**Comment by dyladan** [comment]
Yes I think it would make sense to instrument them with the same plugin since the API surface is identical. Until then, I think it makes sense to have both.

**Comment by mike-marcacci** [comment]
Hey folks! We have a need for this (trying to move from the stackdriver sdk to opentelemetry), and wanted to check in on the status of any prerequisites. It sounds like the desired solution was to modify the existing `mysql` instrumentation package to also instrument `mysql2`, but that this was not yet possible.

Has this blocker been cleared? I imagine it would be fairly straightforward for us to simply duplicate the existing one and modify it as needed, but I'd rather direct our efforts in a way that contributes towards the ultimate goal.

**Comment by vmarchaud** [comment]
@mike-marcacci There is an open issue to migrate the already existing `mysql` plugin to our new instrumentation 
system (https://github.com/open-telemetry/opentelemetry-js-contrib/issues/249) that allows to handle multiple module with the same instrumentation, you have few examples already done ([pg](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/350) or [http](https://github.com/open-telemetry/opentelemetry-js/tree/main/packages/opentelemetry-instrumentation-http)).

The first step would be to do the migration and then add `mysql2` support

**Comment by mike-marcacci** [comment]
Ah excellent, thanks @vmarchaud - that sounds like a solid direction and we'll start a draft PR if we get to this before other folks.

**Comment by mpoitras** [comment]
Would be great to support mysql2 promises:
https://www.npmjs.com/package/mysql2#using-promise-wrapper
AFAIK, it does not look for promises require (https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-mysql2/src/instrumentation.ts#L51).

**Comment by dyladan** [comment]
@mpoitras can you please create a new issue for that. This issue is requesting a mysql2 plugin and there already is one.

Closing this issue as there is a mysql2 instrumentation now.
