### ISSUE TITLE
amqplib looses Baggage

### ISSUE THREAD

**Issue by nerumo** [open-telemetry/opentelemetry-js-contrib#1351]
### What version of OpenTelemetry are you using?
amqplib: 0.32.0

### What version of Node are you using?
19.4.0

### What did you do?
I'm using baggage propagators and I realized that I loose the baggage when I consume messages.

### What did you expect to see?
`propagator.getBaggage(context.active())` should return the baggage of the amqp header

### What did you see instead?
I get null/empty

### Additional context
I already found the problem: the wrong context is passed into the `setSpan` method.

![image](https://user-images.githubusercontent.com/8597645/211741390-81086955-48cf-480f-8f45-41ceb01ce03a.png)

Right now, the `context.active()` is passed in, but actually the `parentContext` must be passed in since only this one contains the baggage.

**Comment by Flarna** [comment]
This seems to be not limited to amqplib, e.g. grpc-js [looks similar](https://github.com/open-telemetry/opentelemetry-js/blob/2dcc898514a60e5b9ac7ddea9b6f1e6c219097af/experimental/packages/opentelemetry-instrumentation-grpc/src/grpc-js/index.ts#L214).

**Comment by nerumo** [comment]
agreed, but there the active context actually should have changed since they are doing a `context.with(...)` ([Code](https://github.com/open-telemetry/opentelemetry-js/blob/2dcc898514a60e5b9ac7ddea9b6f1e6c219097af/experimental/packages/opentelemetry-instrumentation-grpc/src/grpc-js/index.ts#L197)), but IMHO it should be solved with a single `context.with`

**Comment by Flarna** [comment]
right, I haven't seen this additional `context.with()`. I looked into http and grpc and http shows more or less what you propose ([code](https://github.com/open-telemetry/opentelemetry-js/blob/2dcc898514a60e5b9ac7ddea9b6f1e6c219097af/experimental/packages/opentelemetry-instrumentation-http/src/http.ts#L493-L498)).

**Comment by blumamir** [comment]
Thanks @nerumo 
Would you like to contribute a PR with a fix?
