### ISSUE TITLE
Allow over-riding patch and unpatch of ExpressInstrumentation

### ISSUE THREAD

**Issue by gmreads** [open-telemetry/opentelemetry-js-contrib#1369]
### Is your feature request related to a problem? Please describe
I want to patch the send method of response from Express class. 

### Describe the solution you'd like to see

```
init(){
new InstrumentationNodeModuleDefinition(
 'express',
 ['^4.0.0'],
  this._patch,
  this._unpatch
}

protected _patch(moduleExports, moduleVersion){
// same code as now
} 
protected _unpatch(moduleExports, moduleVersion){
//same code as now
}
```
This way I can have a child class and add my own functionality by over-riding _patch and _unpatch methods. 

### Describe alternatives you've considered

Currently I have copied the entire ExpressInstrumentation class and added _patchSendMethod calls in patch and unpatch

### Additional context

 Happy to raise a PR for the same, and make my first contribution to the awesome project.
Have only recently started with TS/JS, please correct me if I am missing something obvious.

**Comment by gmreads** [comment]
Sorry for mass tagging, I see you as contributors in the express plugin. 
Please let me know if this is something that can be merged upstream ?
@dyladan @Rauno56 @seemk @blumamir @vmarchaud @nwalters512

**Comment by gmreads** [comment]
test

**Comment by Flarna** [comment]
Is it an option to create an independent `ExpressSendInstrumentation`?
Or add a config option to the existing instrumentation to include this?

**Comment by gmreads** [comment]
1. I wanted to stay as close as possible to the standard otel-instrumentation-express, creating a completely independent instrumentation is what I have done(But it's just a copy paste from the original with a few lines added in patch and unpatch method)

2. For config based would something like this be acceptable upstream ?

```
init(){
// inside patch anonymous function
if(this.getConfig().getResponseSendPatch){
  if (instrumentation_1.isWrapped(moduleExports.response.send)) {
                    this._unwrap(moduleExports.response, 'send');
  }
  this._wrap(moduleExports.response, 'send', this.getConfig. getResponseSendPatch());
}

// similarly inside unpatch anonymous function
  this._unwrap(moduleExports.response, 'send');
}
```

**Comment by Flarna** [comment]
To my understanding you want to patch one more function and not to change the existing patches.
Therefore creating a new instrumentation for this new functionality doesn't replace the existing one. So some people use only express instrumentation and others like you would use express + express-send instrumentation.

**Comment by gmreads** [comment]
> Therefore creating a new instrumentation for this new functionality doesn't replace the existing one. 
Ah! okay, now I understand it. My new instrumentation can also patch the express module and do whatever it wants and the we register it on top of existing express instead of replacing.
```
registerInstrumentations([
new HttpInstrumentation(),
new ExpressInstrumentation(),
new ExpressSendInstrumentation()
])
```
I was trying to replace the express one with mine. TIL instrumentations can be stacked like a layer even for same modules.

Thank you @Flarna
