### ISSUE TITLE
Support for mysql2 version 3

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-js-contrib#1372]
Current `mysql2` instrumentation has [support for version range `['>= 1.4.2 < 3.0']`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/ff109b77928cc9a139a21c63d6b54399bb017fa4/plugins/node/opentelemetry-instrumentation-mysql2/src/instrumentation.ts#LL53C9-L53C27).

The package released a new major version [3.0.0](https://www.npmjs.com/package/mysql2/v/3.0.0) at 12/01/2023, and we should update the instrumentation accordingly:
- supported version for patch
- README
- unit tests
- test-all-versions config

**Comment by shaqued** [comment]
Hi, I would like to work on this issue. 
Can you assign it to me, please? :)

**Comment by zaq42** [comment]
This was released in 0.33.2.
I'm happily using it with mysql2 3.3.1.
