### ISSUE TITLE
Support for mongodb version 5

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-js-contrib#1373]
Current`mongodb` instrumentation has [support for version range ['>=3.3 <5']](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-mongodb#supported-versions).

The package released a new major version [5.0.0](https://www.npmjs.com/package/mongodb/v/5.0.0) at 31/01/2023, and we should update the instrumentation accordingly:

supported version for patch
README
unit tests
test-all-versions config

**Comment by haddasbronfman** [comment]
Can you assign this to me?

**Comment by viniciusfdev** [comment]
Any update on this? any orientation on how can i contribute is welcome.

**Comment by haddasbronfman** [comment]
I think we can close this one because someone else is working on this here: #1451

**Comment by blumamir** [comment]
implemented in https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1451
