### ISSUE TITLE
GraphQL Apollo Server

### ISSUE THREAD

**Issue by hekike** [open-telemetry/opentelemetry-js-contrib#14]
**Is your plugin request related to a problem? Please describe.**
GraphQL batches multiple queries and entities as a data access protocol into a single HTTP request.
In the background, the GraphQL server will run multiple so-called resolvers that return data for a specific chunk of the graph to fulfill these GraphQL queries. Resolvers can run parallel and depend on each other while they usually fetch data from downstream services or from databases using [data-loader](https://github.com/graphql/dataloader) concept which makes the data orchestration even more complex. Understanding this execution with timing and error is crucial to debug and optimize GraphQL servers.

![https://blog.apollographql.com/graphql-explained-5844742f195e](https://miro.medium.com/max/1572/1*tSO8TeQ9mYNWRzA2FqYlsQ.png)

[Apollo Server](https://www.apollographql.com/docs/apollo-server/) is probably the most popular library to run GraphQL in production.

Commercial alternative for GraphQL Apollo Tracing
https://blog.apollographql.com/the-new-trace-view-in-apollo-engine-566b25bdfdb0

**Is it applicable for Node or Browser or both**
Node.js only.

**Do you expect this plugin to be commonly used**
Yes
Weekly Downloads:  don't know the exact number

**Additional context**

- GraphQL Tracing format could may solve this in a more general way and provide compatibility for all GraphQL engines: https://github.com/apollographql/apollo-tracing

**Comment by jon-whit** [comment]
What's the status on this effort? I'm also looking at integrating OpenTelemetry into a GraphQL implementation using apollo-server.

**Comment by dyladan** [comment]
As far as I'm aware, nobody is working on this right now

**Comment by obecny** [comment]
@jon-whit are you working on that ?

**Comment by obecny** [comment]
ok it looks like no1 is working on that, I'm taking over it

**Comment by Hongbo-Miao** [comment]
Hi @obecny just a suggestion, it would be great to support from [GraphQL.js](https://github.com/graphql/graphql-js) level, so it does not matter which GraphQL framework people are using. 😀

**Comment by obecny** [comment]
@Hongbo-Miao yes that's exactly what will be doing

**Comment by jon-whit** [comment]
@obecny how's this work coming along? Anything that I can help with? My team and I are looking to expedite this process a bit. We really would love to have this.

**Comment by obecny** [comment]
@jon-whit in progress (graphql first), FYI to be able to patch graphql I had to refactor plugin instrumentation too which was done, without this such plugin could not be done.
