### ISSUE TITLE
Container.id set wrong in EKS v1.24

### ISSUE THREAD

**Issue by noMoreCLI** [open-telemetry/opentelemetry-js-contrib#1408]
## Steps to Reproduce
Run official otel demo
EKS cluster v.1.24

## Expected Result
container id should be set to the actual id of the container, and only the id.
35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9

## Actual Result
container id contains .scope suffix which is not part of the containeris
35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope

## Additional Details

$ cat /proc/self/cgroup 
11:perf_event:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope
10:pids:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope
9:blkio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope
8:cpu,cpuacct:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope
7:devices:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope
6:hugetlb:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope
5:net_cls,net_prio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope
4:memory:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope
3:cpuset:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope
2:freezer:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope
1:name=systemd:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope

$ cat /proc/self/mountinfo
1320 1357 0:377 / / rw,relatime master:247 - overlay overlay rw,lowerdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/154/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/146/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/88/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/87/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/85/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/84/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/82/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/79/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/75/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/70/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/68/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/65/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/61/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/40/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/29/fs,upperdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/155/fs,workdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/155/work
1321 1320 0:358 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
1682 1320 0:359 / /dev rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
1683 1682 0:360 / /dev/pts rw,nosuid,noexec,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=666
1684 1682 0:136 / /dev/mqueue rw,nosuid,nodev,noexec,relatime - mqueue mqueue rw
1685 1320 0:143 / /sys ro,nosuid,nodev,noexec,relatime - sysfs sysfs ro
1686 1685 0:361 / /sys/fs/cgroup rw,nosuid,nodev,noexec,relatime - tmpfs tmpfs rw,mode=755
1687 1686 0:25 /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope /sys/fs/cgroup/systemd ro,nosuid,nodev,noexec,relatime master:9 - cgroup cgroup rw,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd
1713 1686 0:27 /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope /sys/fs/cgroup/freezer ro,nosuid,nodev,noexec,relatime master:10 - cgroup cgroup rw,freezer
1714 1686 0:28 /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope /sys/fs/cgroup/cpuset ro,nosuid,nodev,noexec,relatime master:11 - cgroup cgroup rw,cpuset
1715 1686 0:29 /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope /sys/fs/cgroup/memory ro,nosuid,nodev,noexec,relatime master:12 - cgroup cgroup rw,memory
1716 1686 0:30 /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope /sys/fs/cgroup/net_cls,net_prio ro,nosuid,nodev,noexec,relatime master:13 - cgroup cgroup rw,net_cls,net_prio
1717 1686 0:31 /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope /sys/fs/cgroup/hugetlb ro,nosuid,nodev,noexec,relatime master:14 - cgroup cgroup rw,hugetlb
1718 1686 0:32 /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope /sys/fs/cgroup/devices ro,nosuid,nodev,noexec,relatime master:15 - cgroup cgroup rw,devices
1719 1686 0:33 /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope /sys/fs/cgroup/cpu,cpuacct ro,nosuid,nodev,noexec,relatime master:16 - cgroup cgroup rw,cpu,cpuacct
1720 1686 0:34 /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope /sys/fs/cgroup/blkio ro,nosuid,nodev,noexec,relatime master:17 - cgroup cgroup rw,blkio
1721 1686 0:35 /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope /sys/fs/cgroup/pids ro,nosuid,nodev,noexec,relatime master:18 - cgroup cgroup rw,pids
1722 1686 0:36 /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcfbe1789_8da4_4a1d_9fa1_f49a2be9eef5.slice/cri-containerd-35c6b5574bc50507e0b8535bb826e39c4cc0b8dd587930b0947d86239eb0f0a9.scope /sys/fs/cgroup/perf_event ro,nosuid,nodev,noexec,relatime master:19 - cgroup cgroup rw,perf_event
1723 1320 259:1 /var/lib/kubelet/pods/cfbe1789-8da4-4a1d-9fa1-f49a2be9eef5/etc-hosts /etc/hosts rw,noatime - xfs /dev/nvme0n1p1 rw,attr2,inode64,logbufs=8,logbsize=32k,noquota
1724 1682 259:1 /var/lib/kubelet/pods/cfbe1789-8da4-4a1d-9fa1-f49a2be9eef5/containers/frontend/7749c882 /dev/termination-log rw,noatime - xfs /dev/nvme0n1p1 rw,attr2,inode64,logbufs=8,logbsize=32k,noquota
1725 1320 259:1 /var/lib/containerd/io.containerd.grpc.v1.cri/sandboxes/5b4644fe5d2d17ebae8e1322ea4e10f036f990be103099b57f6bbce2e44ae2cf/hostname /etc/hostname rw,noatime - xfs /dev/nvme0n1p1 rw,attr2,inode64,logbufs=8,logbsize=32k,noquota
1726 1320 259:1 /var/lib/containerd/io.containerd.grpc.v1.cri/sandboxes/5b4644fe5d2d17ebae8e1322ea4e10f036f990be103099b57f6bbce2e44ae2cf/resolv.conf /etc/resolv.conf rw,noatime - xfs /dev/nvme0n1p1 rw,attr2,inode64,logbufs=8,logbsize=32k,noquota
1727 1682 0:120 / /dev/shm rw,nosuid,nodev,noexec,relatime - tmpfs shm rw,size=65536k
1728 1320 0:79 / /run/secrets/kubernetes.io/serviceaccount ro,relatime - tmpfs tmpfs rw,size=204800k
1358 1321 0:358 /bus /proc/bus ro,nosuid,nodev,noexec,relatime - proc proc rw
1359 1321 0:358 /fs /proc/fs ro,nosuid,nodev,noexec,relatime - proc proc rw
1360 1321 0:358 /irq /proc/irq ro,nosuid,nodev,noexec,relatime - proc proc rw
1361 1321 0:358 /sys /proc/sys ro,nosuid,nodev,noexec,relatime - proc proc rw
1362 1321 0:358 /sysrq-trigger /proc/sysrq-trigger ro,nosuid,nodev,noexec,relatime - proc proc rw
1363 1321 0:362 / /proc/acpi ro,relatime - tmpfs tmpfs ro
1364 1321 0:359 /null /proc/kcore rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
1365 1321 0:359 /null /proc/keys rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
1366 1321 0:359 /null /proc/latency_stats rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
1367 1321 0:359 /null /proc/timer_list rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
1392 1321 0:359 /null /proc/sched_debug rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
1393 1685 0:363 / /sys/firmware ro,relatime - tmpfs tmpfs ro

### OpenTelemetry Setup Code

```JavaScript
const opentelemetry = require('@opentelemetry/sdk-node');
const { getNodeAutoInstrumentations } = require('@opentelemetry/auto-instrumentations-node');
const { OTLPTraceExporter } = require('@opentelemetry/exporter-trace-otlp-grpc');
const { OTLPMetricExporter } = require('@opentelemetry/exporter-metrics-otlp-grpc');
const { PeriodicExportingMetricReader } = require('@opentelemetry/sdk-metrics');
const { alibabaCloudEcsDetector } = require('@opentelemetry/resource-detector-alibaba-cloud');
const { awsEc2Detector, awsEksDetector } = require('@opentelemetry/resource-detector-aws');
const { containerDetector } = require('@opentelemetry/resource-detector-container');
const { gcpDetector } = require('@opentelemetry/resource-detector-gcp');
const { envDetector, hostDetector, osDetector, processDetector } = require('@opentelemetry/resources');

const sdk = new opentelemetry.NodeSDK({
  traceExporter: new OTLPTraceExporter(),
  instrumentations: [
    getNodeAutoInstrumentations({
      '@opentelemetry/instrumentation-fs': {
        enabled: false,
      },
    }),
  ],
  metricReader: new PeriodicExportingMetricReader({
    exporter: new OTLPMetricExporter(),
  }),
  resourceDetectors: [
    containerDetector,
    envDetector,
    hostDetector,
    osDetector,
    processDetector,
    alibabaCloudEcsDetector,
    awsEksDetector,
    awsEc2Detector,
    gcpDetector,
  ],
});

sdk.start();
```

### Relevant log output

```shell
{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "npm run grpc:generate && NODE_OPTIONS='-r ./utils/telemetry/Instrumentation.js' next dev",
    "build": "next build",
    "start": "node --require ./Instrumentation.js server.js",
    "lint": "next lint",
    "cy:open": "cypress open",
    "grpc:generate": "mkdir -p ./protos && protoc -I ./pb  --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_opt=esModuleInterop=true --ts_proto_out=./protos --ts_proto_opt=outputServices=grpc-js demo.proto"
  },
  "dependencies": {
    "@grpc/grpc-js": "1.6.7",
    "@opentelemetry/api": "1.3.0",
    "@opentelemetry/auto-instrumentations-node": "0.35.0",
    "@opentelemetry/auto-instrumentations-web": "0.31.0",
    "@opentelemetry/context-zone": "1.8.0",
    "@opentelemetry/core": "1.8.0",
    "@opentelemetry/exporter-metrics-otlp-grpc": "0.34.0",
    "@opentelemetry/exporter-trace-otlp-grpc": "0.34.0",
    "@opentelemetry/exporter-trace-otlp-http": "0.34.0",
    "@opentelemetry/instrumentation": "0.34.0",
    "@opentelemetry/resources": "1.8.0",
    "@opentelemetry/sdk-metrics": "1.8.0",
    "@opentelemetry/sdk-node": "0.34.0",
    "@opentelemetry/sdk-trace-base": "1.8.0",
    "@opentelemetry/sdk-trace-node": "1.8.0",
    "@opentelemetry/sdk-trace-web": "1.8.0",
    "@opentelemetry/resource-detector-alibaba-cloud": "0.27.3",
    "@opentelemetry/resource-detector-aws": "1.2.1",
    "@opentelemetry/resource-detector-container": "0.2.1",
    "@opentelemetry/resource-detector-gcp": "0.27.4",
    "cookies-next": "^2.1.1",
    "currency-symbol-map": "5.1.0",
    "dotenv": "16.0.1",
    "dotenv-expand": "8.0.3",
    "next": "12.2.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-query": "3.39.1",
    "sharp": "0.30.7",
    "styled-components": "5.3.5",
    "ts-proto": "1.118.0",
    "uuid": "8.3.2"
  },
  "devDependencies": {
    "@types/node": "18.0.6",
    "@types/react": "18.0.15",
    "@types/react-dom": "18.0.6",
    "@types/uuid": "8.3.4",
    "@types/styled-components": "5.1.26",
    "@typescript-eslint/eslint-plugin": "5.30.7",
    "@typescript-eslint/parser": "5.30.7",
    "cypress": "10.4.0",
    "eslint": "8.20.0",
    "eslint-config-next": "12.2.2",
    "eslint-plugin-react": "7.30.1",
    "eslint-plugin-react-hooks": "4.6.0",
    "openapi-typescript": "5.4.1",
    "typescript": "4.7.4"
  }
}
```

**Comment by willarmiros** [comment]
Will have someone look into a fix for this

**Comment by willarmiros** [comment]
In the EKS resource detector we do actually truncate the string if it's longer than 64 chars: https://github.com/open-telemetry/opentelemetry-js-contrib/blob/d822f75e10d6d0421fe8fbd4b1dca261de736e69/detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsEksDetector.ts#L179-L181

I would echo @pichlermarc - can you remove the `containerDetector` from your setup and try again? It seems this may be a bug with the `containerDetector`.

**Comment by svrnm** [comment]
@noMoreCLI is using the operator which loads the containerDetector first and the eksDetector second:

https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/nodejs/src/autoinstrumentation.ts

I am wondering if it should be the other way round, i.e. loading cloud vendor specific ones first and then the generic? cc @sairam866

@abhee11 can you check if the way AwsEksDetector.ts is doing it also makes sense for the containerDetector?
