### ISSUE TITLE
Instrumentations that require HTTP instrumentation?

### ISSUE THREAD

**Issue by ab-resolver** [open-telemetry/opentelemetry-js-contrib#1409]
Certain instrumentation libraries under the JS branch such as:
https://www.npmjs.com/package/@opentelemetry/instrumentation-ioredis
https://www.npmjs.com/package/@opentelemetry/instrumentation-hapi

Do not appear to function unless you also enable:
https://www.npmjs.com/package/@opentelemetry/instrumentation-http

Is this by design? Should it be stated more explicitly in the documentation / README that to capture such traces you also need HTTP instrumentation, or is that just a given because of the protocols themselves?

Or is the fact that these instrumentations are not functioning without `http` also enabled a symptom of some other configuration issue?

Looking for answers.

- [ X ] This only affects the JavaScript OpenTelemetry library
- [ X ] This may affect other libraries, but I would like to get opinions here first

**Comment by Flarna** [comment]
They don't require the HTTP instrumentation.

IoRedis instrumentation requires a parent span on default. It's don't care which span this is, HTTP is as good as GRPC or a manual created span.
There is the [config option](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/instrumentation-ioredis-v0.33.2/plugins/node/opentelemetry-instrumentation-ioredis#ioredis-instrumentation-options) `requireParentSpan` which can be used to configure it to create a new trace.

I guess for HAPI it's similar but as HAPI is an HTTP server framework it's quite clear that the parent is likely HTTP.

**Comment by ab-resolver** [comment]
Ah I see. This explains it - HTTP is a natural choice for a parent, but not explicitly the one that is required.

I think this phenomena could be stated more explicitly in some of the documentation (particularly HAPI which last I checked does not even mention parent spans at all), but otherwise I would be down to close this.

Hopefully this discussion will help others running into the same confusion.
