### ISSUE TITLE
(node:41348) [fs-extra-WARN0003] Warning: fs.realpath.native is not a function. Is fs being monkey-patched?

### ISSUE THREAD

**Issue by kirrg001** [open-telemetry/opentelemetry-js-contrib#1418]
### What version of OpenTelemetry are you using?

```
    "@opentelemetry/api": "^1.4.0",
    "@opentelemetry/instrumentation-fs": "^0.7.0",
    "@opentelemetry/sdk-trace-base": "^1.9.1",
```

### What version of Node are you using?

18.14

### What did you do?

```
const { FsInstrumentation } = require('@opentelemetry/instrumentation-fs');
const instrumentation = new FsInstrumentation({
    requireParentSpan: true
  });

instrumentation.enable();
```

### What did you expect to see?

No warning

### What did you see instead?

> (node:41348) [fs-extra-WARN0003] Warning: fs.realpath.native is not a function. Is fs being monkey-patched?

See https://github.com/jprichardson/node-fs-extra/blob/f3a7f0beeb5858c628b10010ad819c813c7f3565/lib/fs/index.js#L133

**Comment by pichlermarc** [comment]
Hi, thanks for the detailed report. :slightly_smiling_face: 
I think the PR fixing this (#1332) may have already merged and should be included in the upcoming release. :slightly_smiling_face:

**Comment by kirrg001** [comment]
Unrelated, but didn't wanted to create a new ticket.

I have also noticed that using Otel tracing with the combination of the npm packages`request-promise` and `request-promise-native` does not work and throws an error. This is because Otel is using `require-in-the-middle` internally. `require-in-the-middle` serves cached objects from a map, which does not work if any NPM modules need a fresh copy to be able to function. See https://github.com/elastic/require-in-the-middle/issues/61

**Comment by pichlermarc** [comment]
The fix should now be out: https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-fs-v0.7.1
I'll close this issue for now, feel free to comment if the problem persists and I'll re-open it. :slightly_smiling_face:
