### ISSUE TITLE
Using gts instead of eslint

### ISSUE THREAD

**Issue by samimusallam** [open-telemetry/opentelemetry-js-contrib#1433]
I've been having some issues with eslint's configuration as it is configured as part of the gts module. Is there a specific reason for using gts instead of eslint, prettier, etc just like in the core repo?

**Comment by Flarna** [comment]
As far as I remember gts was the tool of choice in the early OTel days. it was removed in core repo because of some dependency issues. There were other build setup changes done in core repo that time like using a single typescript project.

The idea was to do the same in contrib as followup but noone found the time to do this.

**Comment by samimusallam** [comment]
> As far as I remember gts was the tool of choice in the early OTel days. it was removed in core repo because of some dependency issues. There were other build setup changes done in core repo that time like using a single typescript project.
> 
> The idea was to do the same in contrib as followup but noone found the time to do this.

I can create a PR for this. Is there anything else that should be done that was also changed in the core repo?

**Comment by Flarna** [comment]
Can't remember in detail. I guess the only way is to compare the repos. Maybe browser tooling like webpack differ also. Maybe also typescript, lerna,...

But there is no need to create a single PR to cover everything. Usually such repo wide changes tend to be complicated/cumbersome even if you touch just a part.

**Comment by samimusallam** [comment]
> Can't remember in detail. I guess the only way is to compare the repos. Maybe browser tooling like webpack differ also. Maybe also typescript, lerna,...
> 
> But there is no need to create a single PR to cover everything. Usually such repo wide changes tend to be complicated/cumbersome even if you touch just a part.

Agreed. Will start with a small PR for gts.
