### ISSUE TITLE
Renovate bot doesn't create PRs

### ISSUE THREAD

**Issue by Flarna** [open-telemetry/opentelemetry-js-contrib#1434]
It seems renovate bot doesn't work anymore. Otel core repo was released more then a week ago but still no PR.

**Comment by pichlermarc** [comment]
Update: We're having issues troubleshooting as we can't access logs, I'm talking to the renovate folks to see what we can do about it.

**Comment by pichlermarc** [comment]
Getting a hold of the logs took more work than expected. The fix I came up with looks unrelated, but it looks like a docker image that's been removed from Docker Hub is making the bot fail. Opened #1458 to update it to the latest collector.

**Comment by pichlermarc** [comment]
Closing this as the PRs were updated when #1458 merged.
Looks like it's intentional that the bot does not continue when the images go missing from docker hub: https://github.com/renovatebot/renovate/discussions/21248#discussioncomment-5522649
