### ISSUE TITLE
User-interaction switch span name failed

### ISSUE THREAD

**Issue by ronghuijun** [open-telemetry/opentelemetry-js-contrib#1467]
### What version of OpenTelemetry are you using?
@opentelemetry/instrumentation-user-interaction@0.32.1
@opentelemetry/sdk-trace-base@1.10.1
### What version of Node are you using?
16.18.1

### What did you do?

In opentelemetry-instrumentation-user-interaction, called in the code `_PatchHistoryApi` listens for events such as route switching and jumping. When the new and old urls are different, it will call `_updateInteractionName` to modify the instrumentation span name.
`_updateInteractionName` calls `span.updateName`, but when it detects a route change, span has already ended. This instrumentation listens for user action events, and once the user action is called, it ends.  its status  `_ended` is true, causing `span.updateName` to fail to modify the name.

### What did you expect to see?
The span name has been changed to ` ${EVENTNAVIGATIONNAME} ${URL}`

### What did you see instead?
The span name has not been modified

### Additional context

Listen for route changes
![image](https://user-images.githubusercontent.com/36073072/232362832-e233f590-bd0c-438f-b822-c4503a759b49.png)

After the user action is called, it ends span
![image](https://user-images.githubusercontent.com/36073072/232363882-b4beb815-e977-4fda-a49b-347a6d54f965.png)

Failed to modify name
![image](https://user-images.githubusercontent.com/36073072/232363627-e142460e-9dbc-46d1-b3b3-096bec252f7d.png)

![image](https://user-images.githubusercontent.com/36073072/232363954-386d13a3-de01-4c64-8acc-3ab69613e0d0.png)

**Comment by obecny** [comment]
If the span is exported this is correct behaviour you can't change the span name. Semantically I think this is correct, the span name is what it was when it was created. Imagine the situation the route changes 100 times, what name would it have then ?. You could either create a new span or add some events / attributes so it will show for example that span name was originally "foo.com/somelink" but then it could have some child spans with description route change or additional params. etc. I might not have all context, but changing the name of span every time the route changed does not seem right to me, no matter if span is exported or not yet.
