### ISSUE TITLE
Disable trace_id, span_id, and trace_flags in HTTP error response with @opentelemetry/instrumentation-express

### ISSUE THREAD

**Issue by vincent-herlemont** [open-telemetry/opentelemetry-js-contrib#1472]
I am currently using the `@opentelemetry/instrumentation-express` (via `@opentelemetry/auto-instrumentations-node`) library in my Express.js application to enable distributed tracing with OpenTelemetry. While this has been helpful, I have noticed that the HTTP response error response now includes fields like `trace_id`, `span_id`, and `trace_flags`.

For example:

```json
{
  "error": {
    "detail": "...",
    "span_id": "a1b2c3d4e5f6a7b8",
    "status": 409,
    "title": "Conflict",
    "trace_flags": "00",
    "trace_id": "b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6"
  }
}
```

I understand that these fields are included for better debugging and understanding the flow of requests within a distributed system. However, I'd like to know if there is a way to disable the inclusion of these fields (`trace_id`, `span_id`, and `trace_flags`) in the error messages generated by my application.

Can anyone provide guidance on how to achieve this?

- [ ] This only affects the JavaScript OpenTelemetry library
- [ ] This may affect other libraries, but I would like to get opinions here first

**Comment by Flarna** [comment]
Are you sure this comes from express instrumentation? If you use `@opentelemetry/auto-instrumentations-node` it includes also instrumentations for logging frameworks like `@opentelemetry/instrumentation-pino` (and others).

Maybe switch from `@opentelemetry/auto-instrumentations-node` to a selective list of instrumentations you really want?

**Comment by vincent-herlemont** [comment]
@Flarna Thanks you for your answer. I made a mistake on the issue description; I wanted to talk about HTTP request error messages, so I updated the issue title and description.

However, thank you for your remark; here is my list of instruments.
```json
    "@opentelemetry/instrumentation-http": "0.38.0",
    "@opentelemetry/instrumentation-express": "0.32.1",
    "@opentelemetry/instrumentation-mongodb": "0.34.1",
    "@opentelemetry/instrumentation-mongoose": "0.32.1",
    "@opentelemetry/instrumentation-ioredis": "0.34.0",
    "@opentelemetry/instrumentation-amqplib": "0.32.2",
    "@opentelemetry/instrumentation-socket.io": "0.33.1"

```

**Comment by vincent-herlemont** [comment]
After testing, I don't know where this update of HTTP response comes from, but selecting specific instrumentation fixes the issue.

https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1472#issuecomment-1517459033
