### ISSUE TITLE
Winston & express instrumentation not applied correctly when using ESM modules

### ISSUE THREAD

**Issue by jeppenejsum** [open-telemetry/opentelemetry-js-contrib#1479]
### What version of OpenTelemetry are you using?
 "@opentelemetry/auto-instrumentations-node": "^0.36.5",

### What version of Node are you using?
Welcome to Node.js v16.19.0.

### What did you do?
Have a TypeScript app that use express & winston with OpenTelemetry.

When changing module loader from commonjs to ESM, the instrumentation is not applied correctly.

### What did you expect to see?
❯ node app.js
@opentelemetry/api: Registered a global for diag v1.4.1.
@opentelemetry/api: Registered a global for trace v1.4.1.
@opentelemetry/api: Registered a global for context v1.4.1.
@opentelemetry/api: Registered a global for propagation v1.4.1.
@opentelemetry/instrumentation-http Applying patch for http@16.19.0
Applying patch for express@4.18.2

### What did you see instead?
❯ node app.js
@opentelemetry/api: Registered a global for diag v1.4.1.
@opentelemetry/instrumentation-winston Module winston has been loaded before @opentelemetry/instrumentation-winston so it might not work, please initialize it before requiring winston
@opentelemetry/instrumentation-winston Module winston has been loaded before @opentelemetry/instrumentation-winston so it might not work, please initialize it before requiring winston
@opentelemetry/api: Registered a global for trace v1.4.1.
@opentelemetry/api: Registered a global for context v1.4.1.
@opentelemetry/api: Registered a global for propagation v1.4.1.
@opentelemetry/instrumentation-express Module express has been loaded before @opentelemetry/instrumentation-express so it might not work, please initialize it before requiring express

### Additional context
The only change made was in package.json from
`"type": "commonjs",`
to
`"type": "module",`

**Comment by Flarna** [comment]
see https://github.com/open-telemetry/opentelemetry-js/pull/3698

**Comment by jeppenejsum** [comment]
Ahh thanks. While I did search for duplicate issues, I only did in this repo 👻

**Comment by dyladan** [comment]
@jeppenejsum ok to close this as a duplicate?

**Comment by jeppenejsum** [comment]
Yes 👍
