### ISSUE TITLE
Unmaintained component `instrumentation-express`

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-js-contrib#1499]
The component `instrumentation-express` appears to be unmaintained. If no component owner steps forward in the next 2 weeks, the following header will be added to the components README:

| Maturity                         | [Component Owner](#component_owners.yml) | Compatibility         |
| -------------------------------- | ---------------------------------------- | --------------------- |
| [Unmaintained](#CONTRIBUTING.md) | N/A                                      | API 1.0+<br/>SDK 1.0+ |

**Comment by JamieDanielson** [comment]
@pkanal and I will be component owners of this instrumentation.
