### ISSUE TITLE
Unmaintained component `instrumentation-fastify`

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-js-contrib#1500]
The component `instrumentation-fastify` appears to be unmaintained. If no component owner steps forward in the next 2 weeks, the following header will be added to the components README:

| Maturity                         | [Component Owner](#component_owners.yml) | Compatibility         |
| -------------------------------- | ---------------------------------------- | --------------------- |
| [Unmaintained](#CONTRIBUTING.md) | N/A                                      | API 1.0+<br/>SDK 1.0+ |

**Comment by pichlermarc** [comment]
I'm not too familiar with it but I think it's important to keep this one around, so I can take this one :slightly_smiling_face:
