### ISSUE TITLE
Alternative to `auto-instrumentations-node/register` when needing to configure specific instrumentations

### ISSUE THREAD

**Issue by eyalch** [open-telemetry/opentelemetry-js-contrib#1531]
- [x] This only affects the JavaScript OpenTelemetry library
- [ ] This may affect other libraries, but I would like to get opinions here first

I'm currently using the `auto-instrumentations-node/register` module as it's quite convenient:

```sh
node -r @opentelemetry/auto-instrumentations-node/register dist/index
```

Now I'm in a situation where I need to customize the config for one of the instrumentations (in this case it's `@opentelemetry/instrumentation-fs`).

What's the best way to achieve this?

One solution that comes to mind is to take the [source code of `auto-instrumentations-node/register`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/4e18a46396eb2f06e86790dbbd68075c4c2dc83b/metapackages/auto-instrumentations-node/src/register.ts) and customize the `getNodeAutoInstrumentations` call to my liking, like so:

```ts
import { DiagConsoleLogger, diag } from "@opentelemetry/api"
import { getNodeAutoInstrumentations } from "@opentelemetry/auto-instrumentations-node"
import { getResourceDetectorsFromEnv } from "@opentelemetry/auto-instrumentations-node/build/src/utils"
import * as opentelemetry from "@opentelemetry/sdk-node"

diag.setLogger(
  new DiagConsoleLogger(),
  opentelemetry.core.getEnv().OTEL_LOG_LEVEL
)

const sdk = new opentelemetry.NodeSDK({
  instrumentations: getNodeAutoInstrumentations({
    "@opentelemetry/instrumentation-fs": { enabled: false },
  }),
  resourceDetectors: getResourceDetectorsFromEnv(),
})

try {
  sdk.start()
  diag.info("OpenTelemetry automatic instrumentation started successfully")
} catch (error) {
  diag.error(
    "Error initializing OpenTelemetry SDK. Your application is not instrumented and will not produce telemetry",
    error
  )
}

process.on("SIGTERM", () => {
  sdk
    .shutdown()
    .then(() => diag.debug("OpenTelemetry SDK terminated"))
    .catch((error) => diag.error("Error terminating OpenTelemetry SDK", error))
})
```

Here's the significant diff:

```diff
<   instrumentations: getNodeAutoInstrumentations(),
---
>   instrumentations: getNodeAutoInstrumentations({
>     "@opentelemetry/instrumentation-fs": { enabled: false },
>   }),
```

Unfortunately, this code is using the `getResourceDetectorsFromEnv` function, which is internal and not exported. I get the following error when running the code above:

```sh
$ node -r ./dist/tracing dist/index

node:internal/modules/cjs/loader:535
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './build/src/utils' is not defined by "exports" in /Users/user/project/dist/node_modules/@opentelemetry/auto-instrumentations-node/package.json
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:358:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:668:3)
    at resolveExports (node:internal/modules/cjs/loader:529:36)
    at Module._findPath (node:internal/modules/cjs/loader:569:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/user/project/dist/tracing.js:28:17) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v18.12.1
```

After having a glance at the implementation of `getResourceDetectorsFromEnv`, it seems quite useful, so I wouldn't want to skip it.

Does it make sense to export `getResourceDetectorsFromEnv`? If yes, I can probably submit a PR with this change.

**Comment by eyalch** [comment]
Do we really need this part?

```ts
diag.setLogger(
  new DiagConsoleLogger(),
  opentelemetry.core.getEnv().OTEL_LOG_LEVEL
)
```

It seems to be the [default behavior](https://github.com/open-telemetry/opentelemetry-js/blob/228e67b941ea012781df75b2dc53c8731f97e8dc/experimental/packages/opentelemetry-sdk-node/src/sdk.ts#L102C1-L106).

**Comment by JamieDanielson** [comment]
I'm not sure that you need `resourceDetectors` here. In the docs [README](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/metapackages/auto-instrumentations-node#usage-auto-instrumentation) it states "By default, all SDK resource detectors are used"... but that you can also set them via environment variable like `export OTEL_NODE_RESOURCE_DETECTORS="env,host"`. Does that cover what you are trying to do?

**Comment by JamieDanielson** [comment]
Oh! I just realized you noted you are copying the code from the source here - maybe you would actually be interested in docs on using the SDK itself? Here is a [link to sdk-node](https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages/opentelemetry-sdk-node).

Set your environment variables and then you should just need this:

```ts
import { NodeSDK } from '@opentelemetry/sdk-node';
import { getNodeAutoInstrumentations } from '@opentelemetry/auto-instrumentations-node';

const sdk: NodeSDK = new NodeSDK({
  instrumentations: [    
    getNodeAutoInstrumentations({
      '@opentelemetry/instrumentation-fs': {
        enabled: false,
      },
    }),
  ],
});

sdk.start();
```

**Comment by eyalch** [comment]
@JamieDanielson The only occurrence of `getResourceDetectorsFromEnv` seems to be in `metapackages/auto-instrumentations-node/src/register.ts`. From my understanding, if I want to have the functionality of `getResourceDetectorsFromEnv` I have 2 options:

* use `@opentelemetry/auto-instrumentations-node/register`
* copy its source-code

Am I missing something?

**Comment by anuraaga** [comment]
I am also running into this issue, I am using the snippet from https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1531#issuecomment-1622681932 to be able to configure instrumentations (literally to disable `fs` instrumentation like the example :D), but would like to have ENV support for resource detectors, meaning for now I'm copying the function in. It would be great if `getResourceDetectorsFromEnv` were exported, it seems to have similar utility to the already exported `getNodeAutoInstrumentations`.

**Comment by hamin** [comment]
> @JamieDanielson The only occurrence of `getResourceDetectorsFromEnv` seems to be in `metapackages/auto-instrumentations-node/src/register.ts`. From my understanding, if I want to have the functionality of `getResourceDetectorsFromEnv` I have 2 options:
> 
> * use `@opentelemetry/auto-instrumentations-node/register`
> * copy its source-code
> 
> Am I missing something?

@opentelemetry/auto-instrumentations-node

I'm opening this issue again. I think I see what @eyalch @anuraaga are talking about.

The issue, as far as I understand, is that when you use the very convenient register module, there's no way to configure which instrumentations are enabled, or supply the configurations for the instrumentations being picked up by the register module.

I am running into this myself at the moment. 

It would be really nice to be able to at least disable certain instrumentations via environment variables similar to how `getResourceDetectorsFromEnv` picks up which resource detectors to pick up.


So there a few possible solutions that I can think of

1. Have an environment variable to pick up which which instrumentations are enabled by the auto instrumentation register module
2. Have a way to simply supply the configuration json to the current auto instrumentation registration module. This potentially can be very simple to implement. `getNodeAutoInstrumentations` already takes an optional input config https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/metapackages/auto-instrumentations-node/src/utils.ts#L136 . So the call in the registration module could simply pick it up from environment variables if available over here https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/metapackages/auto-instrumentations-node/src/register.ts#L29C21-L29C48 .
3. Don't change anything and create your own `tracer.js` file and call auto `getNodeAutoInstrumentations` yourself and configure it with/without any of the instrumentations you need. This would bypass the use of the register module altogether

Of course option `3` works today without any changes to the library. However I'm finding the registration module really useful as it's requiring little changes to services that have more complicated setup with the added ability of being able to call auto instrumentation via `NODE_OPTIONS`. I really find this very useful.

I think it would be great to select which instrumentations the register module picks up via environment variables too. And added bonus would be to be able to supply further config options via the json that one can pass currently when they call `getNodeAutoInstrumentations` in code as mentioned in option `2` (and potentially very easy to implement with little library code change). But having at least option `1` would be great!

**Comment by anuraaga** [comment]
FWIW, while I started with the non-register approach to disable fs, to eventually have clean traces I needed to do a lot more programatic configuration including a custom span processor to move attributes like http.route, I don't know if just env configuration of instrumentation will cover it for my case. More env knobs is always nice either way though

**Comment by Flarna** [comment]
> a custom span processor to move attributes like http.route

A bit of topic here but is this an indication that the `http.route` handling done between express/hapi/fastify/... and the http instrumentation is not working as intended?

I doubt also that a pure env based variant will be enough to configure everything. Besides that I think that env configs like this should start at spec to have a consistent naming across techs/instrumentations/exporters/processors/propagators/....

a json/yaml file is likely more flexible (well, an env variable could point to this file). But if hook functions are needed event this might be limited.

**Comment by anuraaga** [comment]
Yes, I believe currently the nodejs instrumentation isn't very usable out of the box as server spans are purely generated by http instrumentation - while maybe I'm the only one that has trouble with a sea of spans named `GET` and `POST`, I somehow doubt it ;)

Java (/cc @mateuszrzeszutek @trask) has a similar issue where servlet instrumentation, e.g. tomcat, handles HTTP and routing instrumentation, e.g. spring, handles routes. It took a lot of effort but with the instrumentation API it's currently handled in a reasonably well-structured manner. There might be some tips to take from that, but looking through http and nestjs instrumentation here I got the impression it's pretty ad-hoc so unifying patterns for e.g. updating a server span looks like it could be a huge effort.

Back on topic, I wonder if this issue title misses the point, or perhaps I should file a new one. As in the original issue, the main problem with `/register` is inability to configure environment resource. There doesn't seem to be a way to tie environment resource to the register hook given that environment resource is defined in the spec of the SDK itself. I think this is similar to Java having done similar in https://github.com/open-telemetry/opentelemetry-java/pull/5554, so maybe we could get that exposed here to solve the current main issue with `/register` as I read this issue.

**Comment by eyalch** [comment]
@Zirak @blumamir Thank you guys for resolving this!
