### ISSUE TITLE
@opentelemtry/instrumentation-graphql not working as expected

### ISSUE THREAD

**Issue by Tanveeshs** [open-telemetry/opentelemetry-js-contrib#1533]
### What version of OpenTelemetry are you using?
@opentelemtry/sdk-node:0.40.0
@opentelemtry/instrumentation-graphql:0.34.2

### What version of Node are you using?
Using Node v14

### What did you do?
Importing new GraphQLInstrumentation() in registerInstrumentation()

### What did you expect to see?
I wanted to see GraphQL resolver Logs

### What did you see instead?
I am able to access Mongoose, HTTP, KafkaJS Spans but unable to access GraphQL spans

### Additional context
I am using a nest-js application.

**Comment by dyladan** [comment]
Can you provide the setup code used? Many people are using this successfully so it's hard to say what the problem would be without knowing more about your setup.

**Comment by dyladan** [comment]
Closing in favor of #1648
