### ISSUE TITLE
Update dependency lerna to `v7`

### ISSUE THREAD

**Issue by pichlermarc** [open-telemetry/opentelemetry-js-contrib#1542]
`The "bootstrap" command was removed by default in v7, and is no longer maintained.`, which means we'd have to change the way we link packages, possibly by using npm workspaces. 

Further information:

- [ ] #1541, we will have to also update the pinned version here to v7

See also:

Same issue in the otel-js core repo https://github.com/open-telemetry/opentelemetry-js/issues/3894

**Comment by chigia001** [comment]
@pichlermarc should we switch to use `npm workspaces` in once PR?
I'm play arround with it a little bit in the current repo and foun the biggest issue is `npm install` in workspace don't guarantee the install order for each workspace => some workspace might depend on another's prepare script to excute first.
https://github.com/npm/cli/issues/4139

We can solve this by remove `prepare` script in each workspace use lerna to trigger each workspace's `compile` script in correct order.

**Comment by pichlermarc** [comment]
> @pichlermarc should we switch to use `npm workspaces` in once PR? 

Yes, I think doing it in one go would be preferable, or at least in a way that allows us to still release after merging the PR. I think creating that PR will be quite painful due to the amount of possible conflicts. Another option would also be switching to [`rush`](https://rushjs.io/) as the folks over at https://github.com/open-telemetry/opentelemetry-sandbox-web-js/ use that. Really, the biggest goal is to future-proof our setup - with `bootstrap` on it's way out we need to find another solution so that we're not stuck with old tooling in the long run. 

> I'm play arround with it a little bit in the current repo and foun the biggest issue is `npm install` in workspace don't guarantee the install order for each workspace => some workspace might depend on another's prepare script to excute first. [npm/cli#4139](https://github.com/npm/cli/issues/4139)
>
> We can solve this by remove `prepare` script in each workspace use lerna to trigger each workspace's `compile` script in correct order.

I think this makes sense, I wonder why we even have that prepare script here in contrib - I think we never had that setup in the core repo https://github.com/open-telemetry/opentelemetry-js and we require running `compile` first to do that AFAIK :thinking: 

> EDIT: also found some issue with hoisting, right now some workspace like `instrumentation-user-interaction` have a tsconfig file that reference a file from `zone.js` in `node_modules`. By default zone.js will be hoist to root dir and when compile instrumentation-user-interaction tsc will unable to find this file (they expect zone.js appear in instrumentation-user-interactio/node_modules). Lerna suggest that we use `yarn` if we require complicate hoisting rule.

Hmm, I see. I'm not opposed to switching to `yarn`, though I'd also like to hear the other @open-telemetry/javascript-maintainers opinion on that before moving forward with it.

Thank you for taking care of this, it may also be worth to sync with @clesleycode, they're working on the same thing over at the core repo https://github.com/open-telemetry/opentelemetry-js/issues/3927. Would you like for me to assign this issue to you? :slightly_smiling_face:

**Comment by chigia001** [comment]
> Would you like for me to assign this issue to you? 🙂
Yes, I already have a PR #1561. 
Right now it working with some twist but not sure hoisting is feature we need in long term.

There still some issue with the PR need to fix.

**Comment by chigia001** [comment]
I just learn more about the use of test-all-versions in the codebase and right now tav only support npm right now. So if we want to switch to other package manager that is something we also need to consider.
