### ISSUE TITLE
Context propagation issue with Amazon SQS and JS auto telemetry

### ISSUE THREAD

**Issue by teammakdi** [open-telemetry/opentelemetry-js-contrib#1551]
## Steps to Reproduce

With reference to https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8789#issuecomment-1604160772

I'm not sure if receiver has to do any additional configuration to start receiving traces from the SQS.

## Expected Result
Get end to end traces

## Actual Result
Separate trace

**Comment by pichlermarc** [comment]
Hi, thanks for reporting this - I transferred it to this repo as it seems like this is related `@opentelemetry/instrumentation-aws-sdk`.

@teammakdi would you mind providing a minimal reproducer? Before we start working on an issue we need to know exactly what's causing the behavior. Issues usually get fixed way quicker if a reproducer repository is at hand. :slightly_smiling_face: 

cc @carolabadeer (component-owner)
