### ISSUE TITLE
Request to add kafkajs instrumentation (opentelemetry-instrumentation-kafkajs) module to OpenTelemetry Meta Packages for Node (https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/metapackages/auto-instrumentations-node/README.md#supported-instrumentations).

### ISSUE THREAD

**Issue by bnanda-appd** [open-telemetry/opentelemetry-js-contrib#1554]
This is not a new instrumentation request. The instrumentation already exists. The request is to add kafkajs instrumentation (opentelemetry-instrumentation-kafkajs) module to OpenTelemetry Meta Packages for Node (https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/metapackages/auto-instrumentations-node/README.md#supported-instrumentations).

### Is your instrumentation request related to a problem? Please describe
A lot of users use kafkajs with node.js application in K8s and do not want to modify their source code or their application image with a tracing.js while instrumenting it with OpenTelemetry. The OpenTelemetry operator provides a way to achieve that. However it can instrument only the supported node.js packages mentioned at https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/metapackages/auto-instrumentations-node/README.md#supported-instrumentations.

As kafkajs is not included in the above list, there is no way to instrument kafka calls made by node.js using kafkajs framework. The only way to instrument such kafka call is to add a tracing.js into the application image and not use Opentelemetry operator to inject instrumentation. However, most of the times, it is a bit cumbersome.

### Is it applicable for Node or Browser or both?
Only Node.

### Do you expect this instrumentation to be commonly used?
Weekly Downloads:

### What version of instrumentation are you interested in using?
Versions:

**Comment by Flarna** [comment]
I don't think we should just copy the instrumentation. It's up to the owner to decide if they want to move it to this repo and maintain/release it here.

I think @blumamir move some instrumentations form aspecto to this repo in the past. Maybe they can give some hints if there are plans to move more.

**Comment by edenkoveshi** [comment]
Is there any progress with this? I would love to have this instrumentation too
