### ISSUE TITLE
Add Winston format/transport for OpenTelemetry

### ISSUE THREAD

**Issue by martinkuba** [open-telemetry/opentelemetry-js-contrib#1558]
### Is your feature request related to a problem? Please describe
The JS SDK now has full Logs API/SDK support. The [Logs API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md) is intended for creating log appenders for individual logging libraries.

This is a feature request to add support for Winston.

### Describe the solution you'd like to see
Users can configure Winston to export logs using to OTLP backends.

**Comment by gsaukov** [comment]
👍
