### ISSUE TITLE
Undeclared Dependency: mysql2 → sql-common

### ISSUE THREAD

**Issue by zaq42** [open-telemetry/opentelemetry-js-contrib#1586]
### What version of OpenTelemetry are you using?

```
    "@opentelemetry/api": "^1.4.1",
    "@opentelemetry/instrumentation": "^0.41.0",
    "@opentelemetry/instrumentation-mysql2": "^0.34.0",
```

### What version of Node are you using?

node:18-bullseye-slim  (18.16.1)

### What did you do?

Updated to    
 "@opentelemetry/instrumentation-mysql2": "^0.34.0"
from 0.33.4

### What did you expect to see?

App startup as normal 

### What did you see instead?

Error during startup:

```
@opentelemetry/instrumentation-mysql2 tried to access @opentelemetry/sql-common, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
Required package: @opentelemetry/sql-common
Required by: @opentelemetry/instrumentation-mysql2@virtual:75deb627e23e1c457a881d4183420467621628860af1bbe80272dda7b5a90b71b393ebf4013b1f4a513e72bedfb00fd59d03c13e311458d0945150f0849ebaec#npm:0.34.0 
```

### Additional context

Using Yarn 3.6.1 (pnp)

This issue appears to relate to [this commit](https://github.com/open-telemetry/opentelemetry-js-contrib/commit/f81f8a76a8f0af2101c62dbc73cde442f875d833#diff-177ba81cee88a5a6744999b2d1f843ec1d5d4d99af5a58a938a32a6d6edb6854)

Workaround is this addition in .yarnrc.yml:

```
packageExtensions:
  "@opentelemetry/instrumentation-mysql2@^0.34.0":
    dependencies:
      "@opentelemetry/sql-common": ^0.40.0
```

**Comment by dyladan** [comment]
This is also likely a problem for the mysql instrumentation https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-mysql/package.json

**Comment by dyladan** [comment]
Actually it looks like this isn't a problem with the code. The repo package.json has the dependency. I'll download the tarball and inspect its package.json to make sure it was properly published. Hopefully we're not seeing a publishing bug.

**Comment by dyladan** [comment]
Looks like `sql-common` is listed as a devDependency but is actually used in `instrumentation.ts`

**Comment by dyladan** [comment]
`instrumentation-pg` has the dependency correctly listed. `mysql` doesn't use the package.

**Comment by lizthegrey** [comment]
Likewise seeing with yarn 4.0.0-rc.48

`Error: @opentelemetry/instrumentation-mysql2 tried to access @opentelemetry/sql-common, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.`

**Comment by lizthegrey** [comment]
This is fixed now I believe.

**Comment by david-luna** [comment]
Yes it was fixed in this PR https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1584
