### ISSUE TITLE
aws-sdk 3.363.0 breaks v3 instrumentation

### ISSUE THREAD

**Issue by Fortiz2305** [open-telemetry/opentelemetry-js-contrib#1596]
### What version of OpenTelemetry are you using?
@opentelemetry/instrumentation-aws-sdk 0.35.0

### What version of Node are you using?
v16.16.0

### What did you do?
I upgraded some [aws-sdk](https://github.com/aws/aws-sdk-js-v3) packages to the 3.363.0 version.

### What did you expect to see?
I expected the instrumentation to work as usual, creating spans from the internal HTTP requests. For example, when making a request to S3, I used to see an `S3.GetObject` span, created by the aws-sdk instrumentation package.

### What did you see instead?

I only see spans for the original HTTP requests. Now, when doing a request to S3, I only see an HTTP GET span from the http-instrumentation package, but the aws-sdk instrumentation package is not catching anything. 

### Additional context

It looks like AWS has renamed the smithy-client packages from `@aws-sdk/smithy-client` to `@smithy/smithy-client` in https://github.com/aws/aws-sdk-js-v3/pull/4873. Checking [the current code](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-aws-sdk/src/aws-sdk.ts#L116), it seems the `smithy/smithy-client` is not taken into account. 

I already saw the same issue in some instrumentation providers like [NewRelic](https://github.com/newrelic/node-newrelic-aws-sdk/issues/194) or [Elastic](https://github.com/elastic/apm-agent-nodejs/pull/3455)

**Comment by carolabadeer** [comment]
Looks like both issues are reporting the same problem, thanks @Fortiz2305 for the additional context on the smithy-client packages. We can keep just one of those issues open for tracking a fix
