### ISSUE TITLE
[Plugin]: Add dns plugin

### ISSUE THREAD

**Issue by OlivierAlbertini** [open-telemetry/opentelemetry-js-contrib#16]
**Is your plugin request related to a problem? Please describe.**
Add traces in order to get useful dns operations information

**Is it applicable for Node or Browser or both**
`Node`

**Do you expect this plugin to be commonly used**
Weekly Downloads: `unknown`

**What version of plugin are you interested in using**
Node Versions: `>=10` but we can be compatible with `8` as well

**Additional context**
This can be assigned to me if you are agree.

Tricky part (I think) is to have dns spans that have the good indentation with http spans. I would need help at a certain moment since I believe I will struggle with the current scope.

We can create multiple PRs in order to facilitate the review:

- [X] lookup
- [X] example/docs
- [ ] lookupService
- [ ] resolveX
- [ ] reverse

Let me know, thanks.

**Comment by vmarchaud** [comment]
Just adding a quick comment for everyone who looking into the dns plugin, we have a problem with its current state. There are no system in place to stop new trace creation for dns request made by exporters so it can create loop:
> span creation -> exported to a specific exporter -> the exporter make a dns request to export -> that create a new span -> you have a loop

A spec is on-going to fix that problem [there](https://github.com/open-telemetry/opentelemetry-specification/issues/530), we are waiting for that to implementing it

**Comment by vmarchaud** [comment]
The spec has been implemented so the plugin is safe to use now !
