### ISSUE TITLE
Not able to log traces for Mongoose in NestJS

### ISSUE THREAD

**Issue by bradleybeighton** [open-telemetry/opentelemetry-js-contrib#1625]
### What version of OpenTelemetry are you using?
    "@opentelemetry/auto-instrumentations-node": "^0.36.4",
    "@opentelemetry/exporter-jaeger": "^1.10.0",
    "@opentelemetry/exporter-metrics-otlp-proto": "^0.41.1",
    "@opentelemetry/exporter-trace-otlp-http": "^0.37.0",
    "@opentelemetry/instrumentation-express": "^0.32.1",
    "@opentelemetry/instrumentation-graphql": "^0.35.0",
    "@opentelemetry/instrumentation-grpc": "^0.36.0",
    "@opentelemetry/instrumentation-http": "^0.36.0",
    "@opentelemetry/instrumentation-ioredis": "^0.35.0",
    "@opentelemetry/instrumentation-mongodb": "^0.36.0",
    "@opentelemetry/instrumentation-mongoose": "^0.33.0",
    "@opentelemetry/instrumentation-nestjs-core": "^0.33.0",
    "@opentelemetry/resources": "^1.10.0",
    "@opentelemetry/sdk-node": "^0.36.0",
    "@opentelemetry/sdk-trace-base": "^1.10.0",
    "@opentelemetry/semantic-conventions": "^1.10.0",

### What version of Node are you using?
v18.17.0

### What did you do?

I am attempting to capture logs for MongoDB interaction using Mongoose in NestJS, I've attempted both Auto instrumentation and named and neither capture any mongo interaction. 

main.ts
```ts
import { otelSDK } from './tracing';
otelSDK.start();

import { NestFactory } from '@nestjs/core';
import { MicroserviceOptions, Transport } from '@nestjs/microservices';
import { join } from 'path';
import { AppModule } from './app/app.module';

async function bootstrap() {
  const app = await NestFactory.createMicroservice<MicroserviceOptions>(
    AppModule,
    {
      transport: Transport.GRPC,
      options: {
        package: 'employee',
        protoPath: {path-to-proto},
        url: '0.0.0.0:{port}'
      },
    },
  );
  await app.listen();
}
bootstrap();
```

tracing.ts (auto instrumentation)
```ts
import {
  BatchSpanProcessor,
} from '@opentelemetry/sdk-trace-base';
import { NodeSDK } from '@opentelemetry/sdk-node';
import * as process from 'process';
import { getNodeAutoInstrumentations } from '@opentelemetry/auto-instrumentations-node';
import { Resource } from '@opentelemetry/resources';
import { SemanticResourceAttributes } from '@opentelemetry/semantic-conventions';

import { OTLPTraceExporter } from '@opentelemetry/exporter-trace-otlp-proto';

const jaegerExporter = new OTLPTraceExporter({
  url: 'http://localhost:4318/v1/traces',
});

export const otelSDK = new NodeSDK({
  spanProcessor: new BatchSpanProcessor(jaegerExporter),
  resource: new Resource({
    [SemanticResourceAttributes.SERVICE_NAME]: {service-name},
    [SemanticResourceAttributes.SERVICE_NAMESPACE]:
      process.env.GOOGLE_CLOUD_PROJECT_NAME,
    [SemanticResourceAttributes.SERVICE_INSTANCE_ID]:  {service-name},
  }),
  instrumentations: [
    getNodeAutoInstrumentations({
      '@opentelemetry/instrumentation-mongoose': {
        enabled: true,
        requireParentSpan: false,
        suppressInternalInstrumentation: false
      },
      '@opentelemetry/instrumentation-http': {
        enabled: false,
      },
      '@opentelemetry/instrumentation-fs': {
        enabled: false
      },
      '@opentelemetry/instrumentation-nestjs-core': {
        enabled: false,

      },
      '@opentelemetry/instrumentation-ioredis': {
        enabled: true,
        requireParentSpan: false
      },
      '@opentelemetry/instrumentation-net': {
        enabled: false,
      },
      '@opentelemetry/instrumentation-grpc': {
        enabled: true,
      },
      "@opentelemetry/instrumentation-graphql": {
        enabled: true,
      },
      "@opentelemetry/instrumentation-mongodb": {
        enabled: true,
        enhancedDatabaseReporting: true,
      },
      '@opentelemetry/instrumentation-dns': {
        enabled: false
      }
    }),
  ],
});
```
mongo.module.ts
```ts
import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { MongooseModule } from '@nestjs/mongoose';

@Module({
  imports: [
    MongooseModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: async (configService: ConfigService) => ({
        uri: configService.get<string>('DATABASE_CONN'),
        useNewUrlParser: true,
        useUnifiedTopology: true,
      }),
      inject: [ConfigService],
    }),
  ],
})
export class MongoModule {}
```
app.module.ts
```ts
import { MongoModule } from './mongo.module.ts';
import { forwardRef, Module } from '@nestjs/common';

import { GraphQLModule } from '@nestjs/graphql';
import {
  ApolloFederationDriver,
  ApolloFederationDriverConfig,
} from '@nestjs/apollo';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { CommonModule } from './common.module.ts';
import { ConfigService } from '@nestjs/config';

@Module({
  imports: [
    forwardRef(() => CommonModule),
    MongoModule,
    GraphQLModule.forRootAsync<ApolloFederationDriverConfig>({
      driver: ApolloFederationDriver,
      imports: [CommonModule],
      inject: [ConfigService],
      useFactory: async (configService: ConfigService) => ({
        typePaths: [
          './**/*.graphql'
        ],
      }),
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

example db call
```ts
getAll(): Promise<Customer[]> {
    return this.usersModel
      .find({ deleted: false })
      .sort({ name: 1 })
      .exec();
}
```

### What did you expect to see?

I would expect to see spans logged providing timings for DB calls

### What did you see instead?

No MongoDB communication is logged. 

### Additional context

    "@nestjs/mongoose": "^9.0.3",
    "mongoose": "^6.2.4",
    "@nestjs/core": "9.0.9",

**Comment by blumamir** [comment]
This blog post has a lot of useful tips on how to diagnose common issues: https://www.aspecto.io/blog/checklist-for-troubleshooting-opentelemetry-nodejs-tracing-issues/

Please try it out and update here about your findings:

- Do you see the mongoose instrumentation patching message in otel diag logs?
- Do you see any spans at all? if you create a manual span, are you able to see it in jaeger?

**Comment by blumamir** [comment]
seems like the same issue as #1469

**Comment by bradleybeighton** [comment]
Hi @blumamir. Thanks for the response. Had a look at the diagnose article and found the following:

Do you see the mongoose instrumentation patching message in otel diag logs - Yes see below:

```
@opentelemetry/instrumentation-nestjs-core Module @nestjs/core has been loaded before @opentelemetry/instrumentation-nestjs-core so it might not work, please initialize it before requiring @nestjs/core
@opentelemetry/instrumentation-grpc Module @grpc/grpc-js has been loaded before @opentelemetry/instrumentation-grpc so it might not work, please initialize it before requiring @grpc/grpc-js
@opentelemetry/instrumentation-graphql Module graphql has been loaded before @opentelemetry/instrumentation-graphql so it might not work, please initialize it before requiring graphql
@opentelemetry/instrumentation-mongoose Module mongoose has been loaded before @opentelemetry/instrumentation-mongoose so it might not work, please initialize it before requiring mongoose
```

Interestingly I am seeing a few errors such as graphql loaded before instrumentation-graphql however the interesting one is that instrumentation-mongoose is complaining about the instrumentation loading before instrumentation.

Do you see any spans at all? if you create a manual span, are you able to see it in jaeger? - Yes I see a lot of logs, almost for everything except Mongoose.

**Comment by bradleybeighton** [comment]
@blumamir interestingly if I move my trace init process out of a separate file and put it inline above the bootstrap process I do start to capture Mongoose instrumentation, however no matter how I attempt call and init tracing in another file it doesn't capture. Is there a recommended approach to structuring the trace init when in another file?

**Comment by blumamir** [comment]
Thanks for trying it and updating your findings here. 

I do not remember the exact details, but nestjs import a lot of things before the app actually runs, so hooking up opentelemetry into nest requires modifying the nest command itself, something like this: `nest start -e 'node -r ./tracing.js'`
When I tested the integration with aspecto otel distribution a long time ago, I got it to work and documented instructions here: https://docs.aspecto.io/v1/send-tracing-data-to-aspecto/aspecto-sdk/nodejs/nestjs

The docs are for a specific (aspecto) distribution, but you can modify it quite easily to your SDK setup.

**Comment by Skindidino** [comment]
but the same thing i am doing 
`import { getNodeAutoInstrumentations } from '@opentelemetry/auto-instrumentations-node';
import { OTLPLogExporter } from '@opentelemetry/exporter-logs-otlp-http';
import { OTLPMetricExporter } from '@opentelemetry/exporter-metrics-otlp-http';
import { OTLPTraceExporter } from '@opentelemetry/exporter-trace-otlp-http';
import { HttpInstrumentation } from '@opentelemetry/instrumentation-http';
import { IORedisInstrumentation } from '@opentelemetry/instrumentation-ioredis';
import { KnexInstrumentation } from '@opentelemetry/instrumentation-knex';
import { resourceFromAttributes } from '@opentelemetry/resources';
import { SimpleLogRecordProcessor } from '@opentelemetry/sdk-logs';
import { PeriodicExportingMetricReader } from '@opentelemetry/sdk-metrics';
import { NodeSDK } from '@opentelemetry/sdk-node';
import { ATTR_SERVICE_NAME, ATTR_SERVICE_VERSION } from '@opentelemetry/semantic-conventions';
import { env } from 'hono/adapter';

const { OTEL_ENDPOINT } = env();

export const otelSDK = new NodeSDK({
	resource: resourceFromAttributes({
		[ATTR_SERVICE_NAME]: 'platform',
		[ATTR_SERVICE_VERSION]: '1.0.0'
	}),
	traceExporter: new OTLPTraceExporter({ url: `http://localhost:4318/v1/traces` }),
	metricReader: new PeriodicExportingMetricReader({
		exporter: new OTLPMetricExporter({ url: `http://localhost:4318/v1/metrics` }),
		exportIntervalMillis: 10000
	}),
	logRecordProcessor: new SimpleLogRecordProcessor(new OTLPLogExporter({ url: `http://localhost:4318/v1/logs` })),
	instrumentations: [
		new HttpInstrumentation(),
		new KnexInstrumentation(),
		new IORedisInstrumentation({
			enabled: true
		})
	]
});
`

this my otel SDK

`import { otelSDK } from './otel/otel.js';
import { env } from 'hono/adapter';

console.log('Starting OTEL SDK...');
await otelSDK.start();
const { OTEL_ENDPOINT } = env();
console.log(OTEL_ENDPOINT);
console.log('OTEL SDK started, now loading server...');
await import('./index.ts');
console.log('Server module loaded');
`

i am running like this but still i am not able to get redis traces 

how to fix it pls help me if anyone can
