### ISSUE TITLE
Document how to use OpenTelemetry with Nest

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-js-contrib#1648]
We have received multiple bug reports from NestJS users that OpenTelemetry is not working for them and it frequently turns out that it is a misconfiguration. Clearly document that OTel needs to be loaded _before_ nest in order for it to work.

**Comment by aya986** [comment]
> We have received multiple bug reports from NestJS users that OpenTelemetry is not working for them and it frequently turns out that it is a misconfiguration. Clearly document that OTel needs to be loaded _before_ nest in order for it to work.

Could you give an example  or documentation to implement it in NestJs?

**Comment by aya986** [comment]
I implement a mini project [here](https://github.com/aya986/nestjs-opentelemetry/)
