### ISSUE TITLE
Support new tedious version 16

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-js-contrib#1656]
Tedious current latest major is 16.
Since tedious 16 dropped support for node 14, it makes our CI fail currently.

I attempted to fix that in #1638 in few ways, but they all were dead ends. I am unable to run tests locally as mssql has no docker image version for my Mac Apple chip which means I cannot run tests locally. After a few failed attempts to fix the test via the CI, I decided it was too much for me currently so I documented the task in this issue instead.

**Comment by david-luna** [comment]
@blumamir @mderriey 

I can take this one after https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2144 gets merged :)

**Comment by kirrg001** [comment]
@david-luna That would be nice. If you need any help, let me know.

**Comment by kirrg001** [comment]
@david-luna Could you please let me know if you want to add the support for v18 after the [merge](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2178)? Otherwise I will do it.

**Comment by kirrg001** [comment]
@david-luna 

> @david-luna Could you please let me know if you want to add the support for v18 after the https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2178? Otherwise I will do it.

**Comment by kirrg001** [comment]
https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2266
I will try to add support for v18.
