### ISSUE TITLE
support mongodb v6

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-js-contrib#1666]
mongodb [released version 6](https://www.npmjs.com/package/mongodb/v/6.0.0)

Renovate opened a PR for that in #1661 but we need to also update the supported version (in code and docs), `test-all-versions` config, and dependencies, along with verifying that all the tests are fine and no breaking changes that affect the instrumentation patching.

This PR is to track this task

**Comment by therynamo** [comment]
Hey @blumamir ! 

I saw your comment on #1661 and was wondering what code changes were needed? 

I'd be happy to look into this - as I'm currently leveraging `@fastify/mongodb` which uses `mondodb: 6` under the hood. 

https://github.com/fastify/fastify-mongodb/blob/master/package.json#L43

Without this - I'm unable to see `mongodb` auto-instrumentation in trace attributes. 

Just let me know what you'd like to see - and we'll see if we can get something put together!

**Comment by david-luna** [comment]
Hi @blumamir 

You can assign this oner to me. I'd be happy to help :)
