### ISSUE TITLE
Transaction is not used in Mongoose create operation after OpenTelemetry auto-instrumentation is added

### ISSUE THREAD

**Issue by juliana-tse** [open-telemetry/opentelemetry-js-contrib#1678]
### What version of OpenTelemetry are you using?
    "@opentelemetry/api": "^1.5.0",
    "@opentelemetry/auto-instrumentations-node": "^0.39.2",

### What version of Node are you using?
v16.15.1

### What did you do?
When running some database operation inside the transaction
```
const User = db.model('User', new Schema({ name: String }));
const session = await User.startSession();
await session.startTransaction();
const [newStaff] = await User.create([ {name: 'staffA'} ], {session});
await session.abortTransaction();
await session.endSession();

```

### What did you expect to see?
It is expected the transaction will be aborted, and user with name "staffA" will not be created in the database.

### What did you see instead?
The transaction was not rolled back, and the record was created in the database.

### Additional Info
I am using "mongoose": "^6.2.1"
The transaction works with `findOneAndUpdate`, for example the user name is not changed to `staffB` in the following case
```
const User = db.model('User', new Schema({ name: String }));
const [newStaff] = await User.create([ {name: 'staffA'} ]);
const session = await User.startSession();
await session.startTransaction();
await User.findOneAndUpdate({name: 'staffA'}, {name: 'staffB'}).session(session);
await session.abortTransaction();
await session.endSession();
```
However, when session is used in the `create` operation, the `lastUse` in `serverSession` is not updated across the whole function, which means the session is not used at all.

**Comment by juliana-tse** [comment]
Hi, is there any updates on this issue? This is blocking me from using auto-instrumentation.

**Comment by benthayer** [comment]
I am experiencing this issue also. It breaks critical portions of our code, so we're unable to use it

**Comment by benthayer** [comment]
In mongoose.ts,

```
const contextCaptureFunctions = [
  'remove',
  'deleteOne',
  'deleteMany',
  'find',
  'findOne',
  'estimatedDocumentCount',
  'countDocuments',
  'count',
  'distinct',
  'where',
  '$where',
  'findOneAndUpdate',
  'findOneAndDelete',
  'findOneAndReplace',
  'findOneAndRemove',
];
```

Maybe a partial solution is to add the create function here also?

**Comment by ferrelucas** [comment]
Hi, I believe I figured what's causing the issue. 

The mongoose instrumentation would unintentionally change the behaviour of some Model methods like `save()` and `remove()` by not passing the original function arguments - `options` (that contains the session to handle transactions) and `callback` - to the final call after instrumentation.

I have just opened a PR addressing this here: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2009
