### ISSUE TITLE
bug: host-metrics reporting wrong system and process CPU utilization

### ISSUE THREAD

**Issue by david-luna** [open-telemetry/opentelemetry-js-contrib#1718]
### What version of OpenTelemetry are you using?
"dependencies": {
    "@opentelemetry/api": "^1.4.1",
    "@opentelemetry/auto-instrumentations-node": "^0.39.2",
    "@opentelemetry/host-metrics": "^0.33.1",
    "@opentelemetry/sdk-metrics": "^1.15.2",
    "@opentelemetry/sdk-node": "^0.41.2"
  }

### What version of Node are you using?
v18.16.0

### What did you do?

Instrument an application with console metrics exporter and watch the CPU utilisation values. There is a repo with the app

https://github.com/david-luna/otel-metrics-cpu-utilization

### What did you expect to see?
According to [semantic conventions](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/system/system-metrics.md#metric-systemcpuutilization) I expect to see CPU utilization values between 0 and 1.

### What did you see instead?
Values are way above 1 like the sample provided in the repo I get some metric readings like this one.

```js
{
  descriptor: {
    name: 'system.cpu.utilization',
    type: 'OBSERVABLE_GAUGE',
    description: 'Cpu usage time 0-1',
    unit: '',
    valueType: 1
  },
  dataPointType: 2,
  dataPoints: [
    {
      attributes: [Object],
      startTime: [Array],
      endTime: [Array],
      value: 157.82086149302881
    },
    {
      attributes: [Object],
      startTime: [Array],
      endTime: [Array],
      value: 143.03498303049165
    },
    {
      attributes: [Object],
      startTime: [Array],
      endTime: [Array],
      value: 1083.5302883959548
    },
    {
      attributes: [Object],
      startTime: [Array],
      endTime: [Array],
      value: 1362.709911550165
    },
    {
      attributes: [Object],
      startTime: [Array],
      endTime: [Array],
      value: 0
    }
    // ...
  ]
}
```

### Additional context

N/A

**Comment by david-luna** [comment]
@legendecas since you're the module owner could you please have a look? Thanks :)

**Comment by legendecas** [comment]
Right, and the semantic convention the package used is outdated as well. We should update the semantic convention all together.

**Comment by david-luna** [comment]
@legendecas thanks for the confirmation :)

I'm planning on crate a PR which:
- will refer to the updated semantic convention
- will change the calculation to make diffs from the latest measurement as semantic convention specifies

One question. Semantic conventions defines `system.cpu.utilization` as
```
Difference in system.cpu.time since the last measurement, divided by the elapsed time and number of logical CPUs
```

Since we are using the `state` attribute does it makes sense to divide by the number of CPUs?
