### ISSUE TITLE
Issue on using auto instrumentation

### ISSUE THREAD

**Issue by mingshun** [open-telemetry/opentelemetry-js-contrib#1743]
### What version of OpenTelemetry are you using?
- @opentelemetry/api: 1.6.0
- @opentelemetry/auto-instrumentations-node: 0.39.4

### What version of Node are you using?
v18.17.1

### What did you do?

```
npm install --save @opentelemetry/api
npm install --save @opentelemetry/auto-instrumentations-node

export OTEL_TRACES_EXPORTER="otlp"
export OTEL_METRICS_EXPORTER="otlp"
export OTEL_LOGS_EXPORTER="none"
export OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:4317"
export OTEL_NODE_RESOURCE_DETECTORS="env,host,os"
export OTEL_SERVICE_NAME="my-service"
export NODE_OPTIONS="--require @opentelemetry/auto-instrumentations-node/register"

node --es-module-specifier-resolution=node --no-warnings dist/index.js
```

### What did you expect to see?

App starts with opentelemetry instrumented.

### What did you see instead?

```
Unable to initialize instrumentation for lambda. Cannot identify lambda handler or task root. { taskRoot: undefined, handlerDef: undefined }
@opentelemetry/instrumentation-grpc Module @grpc/grpc-js has been loaded before @opentelemetry/instrumentation-grpc so it might not work, please initialize it before requiring @grpc/grpc-js
OpenTelemetry automatic instrumentation started successfully
{"stack":"Error: Parse Error: Expected HTTP/\n    at Socket.socketOnData (node:_http_client:541:22)\n    at Socket.emit (node:events:514:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)\n    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)","message":"Parse Error: Expected HTTP/","code":"HPE_INVALID_CONSTANT","reason":"Expected HTTP/","rawPacket":"\u0000\u0000\u0006\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0005\u0000\u0000@\u0000","name":"Error"}
```

**Comment by pichlermarc** [comment]
This looks like a duplicate of https://github.com/open-telemetry/opentelemetry-js/issues/4166. The [default protocol is OTLP/http ](https://opentelemetry.io/docs/specs/otel/protocol/exporter/#configuration-options) but the endpoint in `OTEL_EXPORTER_OTLP_ENDPOINT` has the default port for OTLP/gRPC, so there's a parse error on the response

You can try setting `OTEL_EXPORTER_OTLP_PROTOCOL=grpc` or OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:4318" if you have an http receiver running at this port.

**Comment by pichlermarc** [comment]
removing the bug label as this is intended behavior.

**Comment by mingshun** [comment]
I find out myself just now. But I think the docs should be describe this more clearly. It is very confusing for someone who is new to this. And the first and second lines are also confusing.
