### ISSUE TITLE
`@opentelemetry/instrumentation-document-load` plugin does not work, if `@opentelemetry/instrumentation` esnext used

### ISSUE THREAD

**Issue by maximelkin** [open-telemetry/opentelemetry-js-contrib#1756]
### What version of OpenTelemetry are you using?
```
"@opentelemetry/instrumentation-document-load": "0.33.2"
"@opentelemetry/instrumentation": "0.43.0"
```

### What version of Node are you using?
v18.12.1

### What did you do?
1) override `@openetelemetry/instrumentation` to use esnext folder (we do it via webpack, it's annoying to list all packages, but it's working). `@opentelemetry/instrumentation-document-load` not have esnext folder, do nothing (use esm folder). 
2) 
```
import { DocumentLoadInstrumentation } from '@opentelemetry/instrumentation-document-load';

new DocumentLoadInstrumentation()
```

### What did you expect to see?
no error

### What did you see instead?
`DocumentLoadInstrumentation` constructor fails at 
https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/web/opentelemetry-instrumentation-document-load/src/instrumentation.ts#L62
Because `DocumentLoadInstrumentation` is transpiled, super constructor call transpiled to function call, but it does fail, because `InstrumentationBase` class not transpiled, so it only can be called via new

**Comment by dyladan** [comment]
@pkanal and @martinkuba are the code owners here. Can you please take a look and see what is going on here?

@maximelkin do you have an idea how this can be resolved?

**Comment by maximelkin** [comment]
For me, adding `build/esnext/`, as for packages in https://github.com/open-telemetry/opentelemetry-js will work.
