### ISSUE TITLE
FastifyDeprecation warning for accessing `request.routerPath` when accessing a non-existing page

### ISSUE THREAD

**Issue by omBratteng** [open-telemetry/opentelemetry-js-contrib#1757]
Separating the issue reported here https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1275#issuecomment-1777456234

### What version of OpenTelemetry are you using?

`@opentelemetry/instrumentation-fastify@032.3`

### What version of Node are you using?

`v18`

### What did you do?

Instrumented node with fastify instrumentation, did a request to a non-existing page.

Can be reproduced by starting the [fastify example](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/examples/fastify) and doing a request to any non-existent page

```
curl http://localhost:8080/i_do_not_exist
```

### What did you expect to see?

No deprecation notices

### What did you see instead?

```
(node:9) [FSTDEP017] FastifyDeprecation: You are accessing the deprecated "request.routerPath" property. Use "request.routeOptions.url" instead. Property "req.routerPath" will be removed in `fastify@5`.
```

### Additional context

We are using the latest version of the intrumentation

https://github.com/dailydotdev/daily-api/blob/dc3bbecd7c04984a60a224b19ae9752102caf09e/package.json#L48

and version 4.24.2 of fastify

https://github.com/dailydotdev/daily-api/blob/dc3bbecd7c04984a60a224b19ae9752102caf09e/package.json#L71

So digging a bit further into it, I think it might when the requests are to not found pages. but then both `request.routeOptions.url` and `request.routerPath` are undefined.

**Comment by Wazbat** [comment]
I'm also getting this when accessing existing pages, is that perhaps an unrelated issue?

**Comment by omBratteng** [comment]
That might be related to #1275 which should have been fixed in #1679

**Comment by dyladan** [comment]
I'll cut a release that includes #1679 and we can see if this is fixed. Seems to me that it shoudl be.

**Comment by 10xLaCroixDrinker** [comment]
@dyladan That says it was released 3 weeks ago. Was it not?

**Comment by dyladan** [comment]
Sorry I didn't confirm before typing that. @Wazbat @10xLaCroixDrinker  can you confirm your issue is fixed?

Seems we didn't catch all uses of deprecated properties then

**Comment by trentm** [comment]
@dyladan I can take this. I was just looking at it.

**Comment by omBratteng** [comment]
I think the issue is that on 404 pages, neither `request.routeOptions.url` or the deprecated `request.routerPath` is available. Could maybe check if `request.is404` is `false` and then set the path?

**Comment by Wazbat** [comment]
> Sorry I didn't confirm before typing that. @Wazbat can you confirm your issue is fixed?

I'm using the following packages and versions:
```json
{
    "@autotelic/fastify-opentelemetry": "^0.17.1",
    "@opentelemetry/instrumentation": "^0.44.0",
    "@opentelemetry/instrumentation-fastify": "^0.32.3",
    "@opentelemetry/instrumentation-http": "^0.44.0",
    "@opentelemetry/resources": "^1.17.1",
    "@opentelemetry/sdk-trace-node": "^1.17.0",
    "fastify": "^4.24.3",
}
```

And simplified app is as follows
```ts
import openTelemertryPlugin from '@autotelic/fastify-opentelemetry';
const fastify = Fastify();
await fastify.register(openTelemertryPlugin, {
    wrapRoutes: ['/my/route']
});
fastify.post('/my/route', async (req, res) =>{
    const { activeSpan } = req.openTelemetry();
    activeSpan?.setAttributes({ key: 'value' });
    res.send('whatever');
});
```

When running my application with this, I'm seeing these logs
```
(node:1) [FSTDEP017] FastifyDeprecation: You are accessing the deprecated "request.routerPath" property. Use "request.routeOptions.url" instead. Property "req.routerPath" will be removed in `fastify@5`.
```

**Comment by omBratteng** [comment]
@Wazbat it's the `@autotelic/fastify-opentelemetry` plugin that is using the `routerPath`
https://github.com/autotelic/fastify-opentelemetry/blob/41dfdb788acbb83733052cf0cfe5060e8ad677ae/index.js#L14-L15

**Comment by trentm** [comment]
> Could maybe check if `request.is404` is `false` and then set the path?

I'd prefer not to have different logic to try to sniff if the new attributes are the appropriate ones to use. I saw some reference about undefined values for a Fastify error as well. My suspicion is that cases other than a 404 might have an empty `request.routeOptions.url`.

`request.routeOptions` was added in https://github.com/fastify/fastify/pull/4397 and it included `.url` from its inception. So I'm planning to switch on if the `request.routeOptions` property exists.

---

Currently I'm adding a 404 test case and there is a separate weirdness. The `fastify.name` property is added to the span, but it is *assuming* all handlers are user-provided handlers, and not built-in ones:

```ts
      const handlerName = handler?.name.substr(6);
```

There it is assuming a handler is of the form `bound whateverUserHandlerFunctionName`. However, for a 404 the handler.name is `basic404`: https://github.com/fastify/fastify/blob/396b8b95bf0f1313b9deeb387d68fdc7ffa97abe/lib/fourOhFour.js#L48

**Comment by Wazbat** [comment]
> @Wazbat it's the `@autotelic/fastify-opentelemetry` plugin that is using the `routerPath` https://github.com/autotelic/fastify-opentelemetry/blob/41dfdb788acbb83733052cf0cfe5060e8ad677ae/index.js#L14-L15

Ah thanks for clarifying!

**Comment by 10xLaCroixDrinker** [comment]
@Wazbat I'll open a PR to autotelic/fastify-opentelemetry

**Comment by Wazbat** [comment]
> @Wazbat I'll open a PR to autotelic/fastify-opentelemetry

Thank you! That'd be awesome. My workaround for now is as follows, should anyone find this through google:
```ts
await fastify.register(openTelemertryPlugin, {
    wrapRoutes: ['/v3/search/merchant'],
    formatSpanName: (req) => (req.routeOptions?.url ? `${req.method} ${req.routeOptions.url}` : req.method)
});
```

Looks like this GH issue is unrelated, please disregard my comments about it occuring on existing routes

**Comment by Fernandomr88** [comment]
Not sure if this contributes to this issue, but that log appears on more cases than just accessing non-existing pages.

I have been using AppSignal (which depends on @opentelemetry/instrumentation-fastify) and my console is flooded of these logs. Not sure which events triggers this. 

Btw, using NestJS.

`[FSTDEP017] FastifyDeprecation: You are accessing the deprecated "request.routerPath" property. Use "request.routeOptions.url" instead. Property "req.routerPath" will be removed in `fastify@5`.`

<img width="1091" alt="image" src="https://github.com/appsignal/appsignal-nodejs/assets/14304128/b4c2c5bc-1964-4898-bea9-471f3d8436e4">

**Comment by Fernandomr88** [comment]
@trentm does that fix apply only to non-existing routes/pages?

**Comment by trentm** [comment]
> does that fix apply only to non-existing routes/pages?

@Fernandomr88 With that commit, the instrumentation-fastify will no longer access `request.routerPath` in versions of fastify that have `request.routeOptions.*` (that is fastify >=4.10.0).  So, this should prevent the `[FSTDEP017] FastifyDeprecation: You are accessing the deprecated "request.routerPath" property.` warning in any cases -- including in certain error response cases other than a 404 that I mentioned at https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1757#issuecomment-1789754415   Note that I haven't added a test case for cases other than a 404.

**Comment by omBratteng** [comment]
Updated and deployed, verified that we don't get this deprecation warning anymore
![image](https://github.com/open-telemetry/opentelemetry-js-contrib/assets/1681525/09f69fd0-476a-4a91-9db3-c088f8719c7a)
