### ISSUE TITLE
Module @grpc/grpc-js has been loaded before @opentelemetry/instrumentation-grpc 

### ISSUE THREAD

**Issue by edosrecki** [open-telemetry/opentelemetry-js-contrib#1773]
### What version of OpenTelemetry are you using?
* `@opentelemetry/api`: 1.6.0
 * `@opentelemetry/auto-instrumentations-node`: 0.39.4

### What version of Node are you using?
v20.9.0

### What did you do?
```sh
npm i @opentelemetry/api @opentelemetry/auto-instrumentations-node

# index.js is empty file
node -r @opentelemetry/auto-instrumentations-node/register index.js
```

### What did you expect to see?
No warnings.

### What did you see instead?
Following warning on process startup:

> @opentelemetry/instrumentation-grpc Module @grpc/grpc-js has been loaded before @opentelemetry/instrumentation-grpc so it might not work, please initialize it before requiring @grpc/grpc-js

### Additional context

I noticed following package chain:

```
@opentelemetry/auto-instrumentations-node
  -> @opentelemetry/sdk-node
  -> @opentelemetry/exporter-trace-otlp-grpc
  -> @grpc/grpc-js
```

**Comment by pichlermarc** [comment]
Thanks for reaching out! There's actually a bug in the exporters that I'm working on fixing that loads grpc too early and causes this error message to be logged. (https://github.com/open-telemetry/opentelemetry-js/issues/4151). It also interferes with the grpc instrumentation and causes telemetry to not be generated. I'll close this as a dupliacte in favor of the issue in the core repo for now.

Please let me know if you think this is a mistake, then I'll re-open this issue. 🙂
