### ISSUE TITLE
Add path to span name of `graphq.resolve` spans created by graphql instrumentation

### ISSUE THREAD

**Issue by satazor** [open-telemetry/opentelemetry-js-contrib#1791]
### Is your feature request related to a problem? Please describe

Currently, the `graphql` instrumentation packages adds spans for all resolvers where span name equals to [`graphql.resolve`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/2698bb1a5a4de5a5c6272643d6e50180db874d64/plugins/node/opentelemetry-instrumentation-graphql/src/utils.ts#L132). Here's how it looks in datadog for example:

<img width="543" alt="Screenshot 2023-11-10 at 13 29 46" src="https://github.com/open-telemetry/opentelemetry-js-contrib/assets/1017236/9eed0858-7653-4d65-ae05-713085792590">

However, to have improved DX, the span name could contain the actual path.

### Describe the solution you'd like to see

 Something like `graphl.resolve - <path>` as the span name would make this much better:

- Should this be the default behavior?
- Should this be under an option?
- Should the instrumentation offer a hook for every span added, so we could change it, including changing span name or adding attributes?

### Describe alternatives you've considered

The most obvious workound is to add a processor that changes the span name:

```js
if (span.name === 'graphql.resolve' && span.attributes['graphql.field.path']) {
  span.updateName(`${span.name} ${span.attributes['graphql.field.path']}`);
}
```

**Comment by diogotorres97** [comment]
I did a PR to update the span name to have more information. If you can check, if this #1796 resolves the issue 😄
