### ISSUE TITLE
mongoose tracer plugin

### ISSUE THREAD

**Issue by shaz1v** [open-telemetry/opentelemetry-js-contrib#18]
**Is your plugin request related to a problem? Please describe.**
After the 0.3.2 release and addition of the new mongodb plugin, I've started to use the library to trace our projects, while ones that are based are using the mongodb lib directly worked fine, I saw no traces when using mongoose (although it is based on mongodb).
After digging a bit into mongoose code I'm not entirely sure I'm correct but it seems like it is only using the mongodb lib for the connection part, then handles queries on its own. 

**Is it applicable for Node or Browser or both**
Node

**Do you expect this plugin to be commonly used**
Weekly Downloads:
mongoose has about 500k weekly downloads atm

**What version of the plugin are you interested in using**
Versions:
^5.0.0

**Is there a reference you could point for the well-defined lifecycle methods**
not sure I'm correct and I wish I was able to help more, seems like all mongoose operations end up getting to the Query object which handles the communication with the mongodb server, by inheriting and using the mquery library.
https://github.com/Automattic/mongoose/blob/master/lib/query.js
https://github.com/aheckmann/mquery

thanks!

**Comment by vmarchaud** [comment]
I'm gonna close this, @wdalmut feel free to move the plugin here if you want to

**Comment by wdalmut** [comment]
hi @vmarchaud no problem to move the plugin here. I will open a PR as soon as possible
