### ISSUE TITLE
JaegerHttpTracePropagator not able to inject context to carrier 

### ISSUE THREAD

**Issue by Madvinking** [open-telemetry/opentelemetry-js-contrib#181]
Hi,
i don't know exactly where to ask this,
but I'm trying to create a basic tracer with the JaegerHttpTracePropagator
after i create a new span i try to inject it to the carrier (the headers)
but something is not working because the carrier not containing the requested header (uber-trace-id in this case)

this is my code: 
```
  const provider = new tracing.BasicTracerProvider();
  const propagator = new jaegerHttpTracePropagator.JaegerHttpTracePropagator();

  provider.register({ propagator });
  // i also tried : api.propagation.setGlobalPropagator(propagator);
  cosnt tracer = api.trace.getTracer('node-js')

  function startSpan({ operation, tags = {}, carrier } = {}) {
    const currentContext = api.propagation.extract(carrier, api.defaultGetter);
    const span = tracer.startSpan(operation, { attributes: tags }, currentContext);
    const activeContext = core.setActiveSpan(currentContext, span);
    api.propagation.inject(carrier, api.defaultSetter, activeContext);
    return span;
  }
```
when i call startSpan({operation: '/route'  carrier: req.headers  }) everything working great.
but after the line 'api.propagation.inject(carrier, api.defaultSetter, activeContext);' 
the carrier still missing the uber-trace-id header

after debugging it a bit i got to the function 'core_1.getParentSpanContext(context)'
inside the file: @opentelemetry/propagator-jaeger/build/src/JaegerHttpTracePropagator.js
the context contain one element ( probobly my current span because i called setActiveSpan)
 but the 'getActiveSpan(context)' inside `getParentSpanContext` always return null

am i doing something wrong in the code? :(

**Comment by dyladan** [comment]
Hello, sorry to hear you're having trouble. I don't see anything obviously wrong with the code, but I can try to help you figure it out. What version of otel are you using?

**Comment by Madvinking** [comment]
Hi Daniel, appreciate the help.

```
 "@opentelemetry/api": "^0.10.2",
  "@opentelemetry/core": "^0.10.2",
  "@opentelemetry/exporter-jaeger": "^0.10.2",
  "@opentelemetry/propagator-jaeger": "0.9.0",
  "@opentelemetry/tracing": "^0.10.2"
```

**Comment by renatomjr** [comment]
Could this be related to https://github.com/open-telemetry/opentelemetry-js/issues/1557#issuecomment-789223392 ?
