### ISSUE TITLE
[opentelemetry/auto-instrumentations-web 0.34.0] Update zone.js peer dependency

### ISSUE THREAD

**Issue by ebussieres** [open-telemetry/opentelemetry-js-contrib#1820]
I'm wondering why zone.js peer dependency is hardcoded to version 0.11.4. Why caret was not used ? Change was introduced in https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1768.

I have an angular 17 app and i'm using zone.js 0.14.x version. This is preventing a lot of app to use the latest @opentelemetry/auto-instrumentations-web version.

**Comment by dyladan** [comment]
Added the `enhancement` label and modified the PR title. This seems to be a request to support other versions of zone.js. There is a similar issue for the zone context manager in the core repo.

**Comment by starushykart** [comment]
Hi, guys!
Many thanks for your work!
Is there an understanding of when the issue will be resolved?

**Comment by pichlermarc** [comment]
@starushykart no ETA at the moment as no one is actively working on it. PRs from volunteers are welcome :slightly_smiling_face:
