### ISSUE TITLE
`Can not execute the operation on ended Span` on express-instrumentation

### ISSUE THREAD

**Issue by ReDemoNBR** [open-telemetry/opentelemetry-js-contrib#1887]
### What version of OpenTelemetry are you using?
- `@opentelemetry/api`: `^1.7.0`
- `@opentelemetry/instrumentation-express`: `^0.34.0`
- `@opentelemetry/instrumentation-http`: `^0.46.0`
- `@opentelemetry/resources`: `^1.19.0`
- `@opentelemetry/sdk-node`: `^0.46.0`

### What version of Node are you using?
`v21.5.0` and `v20.10.0` on ArchLinux

### What did you do?
My tests called an endpoint in specific conditions which would make the request handler call the 4-argument error handler, and I saw the error logs.  

For this reason, I debugged the code and found some interesting stuff :smile: ... I made a small reproduction code with express and a basic OTel SDK config

### What did you expect to see?
I expected the instrumentation to avoid try to mutate an ended span.

### What did you see instead?
Warning messages on console:
```console
$ node index.js 
@opentelemetry/api: Registered a global for diag v1.7.0.
@opentelemetry/instrumentation-http Applying patch for http@21.5.0
Applying patch for express@4.18.2
@opentelemetry/api: Registered a global for trace v1.7.0.
@opentelemetry/api: Registered a global for context v1.7.0.
@opentelemetry/api: Registered a global for propagation v1.7.0.
Server open on port 54321
@opentelemetry/instrumentation-http http instrumentation incomingRequest
Can not execute the operation on ended Span {traceId: 1f0e3a3f84a3760ed1e5ba947f8f8455, spanId: 1faf39edb8c05d5b}
Can not execute the operation on ended Span {traceId: 1f0e3a3f84a3760ed1e5ba947f8f8455, spanId: 1faf39edb8c05d5b}
Can not execute the operation on ended Span {traceId: 1f0e3a3f84a3760ed1e5ba947f8f8455, spanId: e3dcb9c80abf6aa3}
Can not execute the operation on ended Span {traceId: 1f0e3a3f84a3760ed1e5ba947f8f8455, spanId: e3dcb9c80abf6aa3}
```

### Additional context
The ExpressInstrumentation does [not yet support](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/2d11b6983d259937ae0b9d0887af20a4034fc97a/plugins/node/opentelemetry-instrumentation-express/src/instrumentation.ts#L190C5-L190C5) the [4-argument error handler callback](https://expressjs.com/en/guide/error-handling.html) , so when a middleware passes to it ends up [in this conditional](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/2d11b6983d259937ae0b9d0887af20a4034fc97a/plugins/node/opentelemetry-instrumentation-express/src/instrumentation.ts#L283).
Stack tracing this condition, it calls `span.setStatus()`, and `span.recordException()` which itself triggers `span.addEvent()`. Both, `setStatus` and `addEvent` functions are responsible for calling [`_isSpanEnded()`](https://github.com/open-telemetry/opentelemetry-js/blob/ae0a3c522d0b802de264e4d8b9566d3677a36ee6/packages/opentelemetry-sdk-trace-base/src/Span.ts#L339C13-L339C13) which end up raising the message.

### Reproduction code
<details><summary>app.js</summary>

```javascript
// app.js
const Express = require("express");
const app = Express();
const router = Express.Router();
router.get("/foo/bar", (req, res, next)=>{
    // when send query ?error=true, the warning is printed on console
    if (req.query.error) return next(new Error("blow up")); 
    return res.send("OK");
});
app.use("/", router);
app.use((error, _req, res, _next)=>res.status(418).send(error.message));
module.exports = app;
```
</details>

<details><summary>otel.js</summary>

```javascript
// otel.js
const {diag, DiagConsoleLogger, DiagLogLevel} = require("@opentelemetry/api");
const {ExpressInstrumentation} = require("@opentelemetry/instrumentation-express");
const {HttpInstrumentation} = require("@opentelemetry/instrumentation-http");
const {Resource} = require("@opentelemetry/resources");
const {NodeSDK} = require("@opentelemetry/sdk-node");
const {ConsoleSpanExporter} = require("@opentelemetry/sdk-trace-node");

diag.setLogger(new DiagConsoleLogger(), DiagLogLevel.DEBUG)

module.exports = new NodeSDK({
    autoDetectResources: false,
    serviceName: "Foo service",
    traceExporter: new ConsoleSpanExporter(),
    resource: Resource.default(),
    instrumentations: [
        new HttpInstrumentation(),
        new ExpressInstrumentation()
    ]
});
```
</details>

<details><summary>index.js</summary>

```javascript
// index.js
const OTelSDK = require("./otel");
const app = require("./app");

OTelSDK.start();

function startServer() {
    return app.listen(54321, function logPort() {
        const server = this;
        console.log("Server open on port", server.address().port);
        process.on("SIGTERM", ()=>server.close());
        process.on("SIGINT", ()=>server.close());
    });
}

startServer();
```
</details>

<details><summary>package.json</summary>

```json
{
  "name": "fix-otel-express-inst",
  "version": "1.0.0",
  "type": "commonjs",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node ./index.js"
  },
  "author": "San 'rdn' Mônico",
  "license": "MIT",
  "dependencies": {
    "@opentelemetry/api": "^1.7.0",
    "@opentelemetry/instrumentation-express": "^0.34.0",
    "@opentelemetry/instrumentation-http": "^0.46.0",
    "@opentelemetry/resources": "^1.19.0",
    "@opentelemetry/sdk-node": "^0.46.0",
    "@opentelemetry/sdk-trace-node": "^1.19.0",
    "express": "^4.18.2"
  }
}
```
</details>

- Start the server: `node ./index.js` 
- Use your favorite API platform (ex: Postman, Insomnia etc), browser or CLI tool to make a request to /foo/bar?error=true
  - Ex with curl: `curl http://localhost:54321/foo/bar?error=true` will trigger the error
  - Ex that will not trigger the error: `curl http://localhost:54321/foo/bar` (without the `?error=true` querystring)

**Comment by ReDemoNBR** [comment]
I was able to stop these span error messages locally by patching this line: https://github.com/open-telemetry/opentelemetry-js-contrib/blob/2d11b6983d259937ae0b9d0887af20a4034fc97a/plugins/node/opentelemetry-instrumentation-express/src/instrumentation.ts#L283

This should check if the span has already ended.

```diff
-            if (isError) {
+            if (spanHasEnded && isError) {
```

If you guys want, I may have some time to open a PR for it with this change. But for long term, the 4-argument express error handler must be supported.

**Comment by ReDemoNBR** [comment]
I had some time and could debug this a little bit more. I could find that the span was closed [here](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/2d11b6983d259937ae0b9d0887af20a4034fc97a/plugins/node/opentelemetry-instrumentation-express/src/instrumentation.ts#L292:L296)

I will open a PR with the changes above in a few minutes

**Comment by JamieDanielson** [comment]
Appreciate the thorough investigation on this! Seems like we need to create a feature request ticket for the error handlers as you pointed out.

> The ExpressInstrumentation does [not yet support](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/2d11b6983d259937ae0b9d0887af20a4034fc97a/plugins/node/opentelemetry-instrumentation-express/src/instrumentation.ts#L190C5-L190C5) the [4-argument error handler callback](https://expressjs.com/en/guide/error-handling.html) , so when a middleware passes to it ends up [in this conditional](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/2d11b6983d259937ae0b9d0887af20a4034fc97a/plugins/node/opentelemetry-instrumentation-express/src/instrumentation.ts#L283).
