### ISSUE TITLE
Metrics not exported when multiple exporters are present

### ISSUE THREAD

**Issue by chippment** [open-telemetry/opentelemetry-js-contrib#1900]
### What version of OpenTelemetry are you using?
```
    "@opentelemetry/api": "1.7.0",
    "@opentelemetry/auto-instrumentations-node": "0.40.2",
    "@opentelemetry/exporter-metrics-otlp-grpc": "0.46.0",
    "@opentelemetry/exporter-metrics-otlp-proto": "0.46.0",
    "@opentelemetry/exporter-prometheus": "0.47.0",
    "@opentelemetry/host-metrics": "0.34.1",
    "@opentelemetry/sdk-node": "0.46.0",
```
### What version of Node are you using?
v21.5.0

### What did you do?
My use case is that the instrumentation shall use two separate exporters to export to two different endpoints. However, the data only gets exported via the first configured exporter. The second exporter receives an empty list of scope metrics in the export function.

Here is a sample application that reproduces the issue:

`monitoring.js`:
```monitoring.js
const { HostMetrics } = require('@opentelemetry/host-metrics');
const { PrometheusExporter } = require('@opentelemetry/exporter-prometheus');
const { NodeSDK } = require("@opentelemetry/sdk-node")
const { PeriodicExportingMetricReader, ConsoleMetricExporter } = require("@opentelemetry/sdk-metrics");
const { metrics } = require('@opentelemetry/api');

const exporter = new PrometheusExporter(
  {
    startServer: true
  }, () => {
    console.log('prometheus scrape endpoint: http://localhost:9464/metrics')
  }
);

const sdk = new NodeSDK({
    metricReader: exporter
});

sdk.start();

const hostMetrics = new HostMetrics({ name: 'example-host-metrics' });
hostMetrics.start();

const periodicReader = new PeriodicExportingMetricReader({
    exportIntervalMillis: 5000,
    exporter: new ConsoleMetricExporter() // this will never print any of the host metrics
});

metrics.getMeterProvider().addMetricReader(periodicReader) // expecting this to be the one global meter provider
```

`app.js`:
```app.js
const express = require('express')
const app = express()

app.get('/', function (req, res) {
  res.send('Hello World')
})

app.listen(3000)
```

start via: `node -r ./monitoring.js app.js`

### What did you expect to see?
Metrics being exported to two different endpoints via two different exporters.

### What did you see instead?
Only the first exporter receiving a list of scope metrics while the second one receives an empty list. Thus, nothing gets exported via the second exporter.

**Comment by pichlermarc** [comment]
This was actually never intended to be used in that way and it's a problem with how we designed the Metrics SDK (see https://github.com/open-telemetry/opentelemetry-js/issues/4112#issuecomment-1705416081) as it actually looks like this could work. To work around this, we could add a feature the `@opentelemetry/sdk-node` so that multiple readers can be added on SDK creation. 

Also note that this is actually getting the API type of the `MeterProvider` which does not advertise having such a method.

**Comment by chippment** [comment]
Is there any workaround available for the time being?

**Comment by pichlermarc** [comment]
A workaround may be to call `addMetricReader()` before creating any instruments (in the example above, do something like this):
```js
const { HostMetrics } = require('@opentelemetry/host-metrics');
const { PrometheusExporter } = require('@opentelemetry/exporter-prometheus');
const { NodeSDK } = require("@opentelemetry/sdk-node")
const { PeriodicExportingMetricReader, ConsoleMetricExporter } = require("@opentelemetry/sdk-metrics");
const { metrics } = require('@opentelemetry/api');

const exporter = new PrometheusExporter(
  {
    startServer: true
  }, () => {
    console.log('prometheus scrape endpoint: http://localhost:9464/metrics')
  }
);

const sdk = new NodeSDK({
    metricReader: exporter
});

sdk.start();

// Add metric reader before using host metrics
const periodicReader = new PeriodicExportingMetricReader({
    exportIntervalMillis: 5000,
    exporter: new ConsoleMetricExporter() // this will never print any of the host metrics
});

metrics.getMeterProvider().addMetricReader(periodicReader) // expecting this to be the one global meter provider

// Start up host metrics after registering the MetricReader
const hostMetrics = new HostMetrics({ name: 'example-host-metrics' });
hostMetrics.start();


```

this would cause the instruments in HostMetrics to be created AFTER registering the MetricReader.
