### ISSUE TITLE
Support @opentelemetry/instrumentation v0.47.0

### ISSUE THREAD

**Issue by pebo** [open-telemetry/opentelemetry-js-contrib#1911]
Installing the latest (`0.34.1`) contrib package `@opentelemetry/instrumentation-express` and then installing the latest experimental `@opentelemetry/instrumentation` (`0.47.0`) gives two versions of `@opentelemetry/instrumentation`: `0.46.0` and `0.47.0`

To reproduce:
```sh
yarn add @opentelemetry/instrumentation
yarn add @opentelemetry/instrumentation-express
yarn why @opentelemetry/instrumentation
├─ @opentelemetry/instrumentation-express@npm:0.34.1
│  └─ @opentelemetry/instrumentation@npm:0.46.0 (via npm:^0.46.0)
│
├─ @opentelemetry/instrumentation-express@npm:0.34.1 [f27bd]
│  └─ @opentelemetry/instrumentation@npm:0.46.0 [d2aea] (via npm:^0.46.0 [d2aea])
│
└─ otel@workspace:.
   └─ @opentelemetry/instrumentation@npm:0.47.0 [f27bd] (via npm:^0.47.0 [f27bd])
```

As I understand it the caret (`^`) in  the express-instrumentation package dependency below only allows patch updates (e.g. to version 0.46.**1** , 0.46.**2** etc as the version starts with `0.`:

```json
"@opentelemetry/instrumentation": "^0.46.0"
```
Are there specific dependencies on `"@opentelemetry/instrumentation": "^0.46.0"` from `@opentelemetry/instrumentation-express` or can the constraint be relaxed or extended to `"^0.46.0 || "^0.47.0"` to avoid getting duplicated packages due to incompatible version constraints?

**Comment by pichlermarc** [comment]
We've discovered a problem with `0.47.0` downstream dependencies that in certain cases causes the end-user's application to crash. (see #1905, https://github.com/open-telemetry/opentelemetry-js/pull/4441) 

Therefore, we will not support `0.47.0` and jump directly to `0.48.0` once it's released (https://github.com/open-telemetry/opentelemetry-js/pull/4442)

**Comment by pebo** [comment]
Thanks for a quick and detailed response! Will upgrade our otel lib versions when `@opentelemetry/instrumentation-express` picks the new `0.48.0` version.
