### ISSUE TITLE
Conflict with peer deps: zone.js@0.11.4

### ISSUE THREAD

**Issue by lugogregory** [open-telemetry/opentelemetry-js-contrib#1964]
### What version of OpenTelemetry are you using?
    "@opentelemetry/auto-instrumentations-web": "^0.36.0",
    "@opentelemetry/context-zone": "^1.21.0",
    "@opentelemetry/exporter-trace-otlp-http": "^0.48.0",
    "@opentelemetry/instrumentation": "^0.48.0",
    "@opentelemetry/sdk-trace-web": "^1.21.0",

### What version of Node are you using?
v-18.6.0

### What did you do?
I am trying to install: @opentelemetry/auto-instrumentations-web package to my project, with npm install.

### What did you expect to see?
I expect I don´t receive any errors

### What did you see instead?
I received a conflict with peer deps: zone.js@0.11.4

### Additional context
When you try to install the metapackage: auto-instrumentation-web in an application that has a version of the zone.js library different from the one specified in the project's peer-deps, it generates a dependency conflict, even though the one you have in your project is higher than that of the metapackage. 

You should consider changing the package.json (line 35) that currently has: "zone.js": "0.11.4" to "zone.js": "^0.11.4", so that it can use that version or one higher and does not generate conflicts when executing npm install

**Comment by dyladan** [comment]
Duplicate
