### ISSUE TITLE
Remove non-inclusive language

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry-js-contrib#197]
**Is your feature request related to a problem? Please describe.**

This repository contains non-inclusive language:

```
$ > git grep -Ei '(master|slave)' | grep -Evi '(tree|blob)/master' | grep plugins | grep -v githubusercontent
plugins/node/opentelemetry-plugin-mongodb/src/mongodb.ts:    } else if (command.ismaster !== undefined) {
plugins/node/opentelemetry-plugin-mongodb/src/mongodb.ts:      return MongodbCommandType.IS_MASTER;
plugins/node/opentelemetry-plugin-mongodb/src/types.ts:  ismaster: boolean;
plugins/node/opentelemetry-plugin-mongodb/src/types.ts:  IS_MASTER = 'isMaster',
```

Note: this does not address the use of `master` branch.

**Describe the solution you'd like**
Push Mongo to change non-inclusive language and then remove non-inclusive language from this repository.

**Describe alternatives you've considered**

**Additional context**

**Comment by dyladan** [comment]
Have you also created an issue on the mongo side?

**Comment by vmarchaud** [comment]
I think we can close this since the PR has been closed (it need modification on the mongodb nodejs driver)
