### ISSUE TITLE
instrumentation-pg: Invalid trace output if port=null

### ISSUE THREAD

**Issue by carlpett** [open-telemetry/opentelemetry-js-contrib#1980]
### What version of OpenTelemetry are you using?
API 1.8.0 / Stable 1.22.0 / Experimental 0.49.0
instrumentation-pg 0.38.0

### What version of Node are you using?
v18.19

### What did you do?
Due to a configuration issue, our app was passing a port of `null` to pg-pool. This is handled "correctly" (defaulting to 5432) by pg.

### What did you expect to see?
Valid traces

### What did you see instead?
`net.peer.port` is set to `NaN`, which is invalid, breaking the entire trace.

**Comment by pichlermarc** [comment]
Thanks for reporting this. Was able to find where in `pg` code this happens: https://github.com/brianc/node-postgres/blob/2a8efbee09a284be12748ed3962bc9b816965e36/packages/pg/lib/connection-parameters.js#L66

Couldn't find where it defaults to `5432` though, so my PR #1982 proposes falling back to `undefined` which will mean that the attribute won't be set on the exported trace.

**Comment by carlpett** [comment]
Nice! :clap:

Not setting the attribute sounds like a fine approach.
