### ISSUE TITLE
[instrumentation-mongodb] test failing for `mongodb@6.4.0` 

### ISSUE THREAD

**Issue by pichlermarc** [open-telemetry/opentelemetry-js-contrib#1983]
**Description:**
`mongodb@6.4.0` released with a refactor that changed how the internal `Connection.command()` works, so no spans are generated and test fail.

In the instrumentation, we heavily rely on `command`, see https://github.com/open-telemetry/opentelemetry-js-contrib/blob/2e9fce4d15bc15fd3cb0e98ad36af6f7d4cc3c38/plugins/node/opentelemetry-instrumentation-mongodb/src/instrumentation.ts#L495-L506

Since the signature changed we return `original.call()` instead of instrumenting. `resultHandler` is `undefined` and therefore not a function. also the other args have changed, see below. Right now I think this is not causing problems in end-user apps but if it is, we should temporarily disable `mongodb@6.4.0` instrumentation until a fix is ready.

**Resources:**
 - [`connection.ts` at `mongodb@6.3.0`](https://github.com/mongodb/node-mongodb-native/blob/v6.3.0/src/cmap/connection.ts#L493-L497) - works
 - [`connection.ts` at `mongodb@6.4.0`](https://github.com/mongodb/node-mongodb-native/blob/9ac2e38f59b673d831a2ac56e223ca8b1a49c713/src/cmap/connection.ts#L569-L579) - fails

**See failing test on `main`**
- https://github.com/open-telemetry/opentelemetry-js-contrib/actions/runs/8093744773/job/22167022286
 - I restarted the test for `18.18.2` on `main` after seeing failures in #1978

**Comment by trentm** [comment]
Yah, I was poking David as well ;)
I took a look, and in v6.4.0 the signature of `ConnectionPool.checkOut` changed:

```diff
-  checkOut(callback: Callback<Connection>): void {
+  async checkOut(): Promise<Connection> {
```

This breaks this patch in instr-mongodb/src/instrumentation.ts

```ts
  // This patch will become unnecessary once
  // https://jira.mongodb.org/browse/NODE-5639 is done.
  private _getV4ConnectionPoolCheckOut() {
    return (original: V4ConnectionPool['checkOut']) => {
      return function patchedCheckout(this: unknown, callback: any) {
        const patchedCallback = context.bind(context.active(), callback);
        return original.call(this, patchedCallback);
      };
    };
  }
```

**Comment by david-luna** [comment]
Hi @trentm @pichlermarc 

Thanks for the heads up :) I'm going to work on it today

**Comment by trentm** [comment]
Some issues here:

# `ConnectionPool.checkOut` signature change

In https://github.com/mongodb/node-mongodb-native/pull/3986 `ConnectionPool.checkOut` changed:

```diff
-  checkOut(callback: Callback<Connection>): void {
+  async checkOut(): Promise<Connection> {
```

which breaks our instrumentation:

```
  private _getV4ConnectionPoolCheckOut() {
    return (original: V4ConnectionPool['checkOut']) => {
      return function patchedCheckout(this: unknown, callback: any) {
        const patchedCallback = context.bind(context.active(), callback);
        return original.call(this, patchedCallback);
      };
    };
  }
```

My observation from this same issue with the Elastic Node.js APM agent is that
the async context loss for which this patch was added **is no longer an issue**.
So my *guess* is that we can just not do this patch for >=6.4.0 with something like:

```diff
--- a/plugins/node/opentelemetry-instrumentation-mongodb/src/instrumentation.ts
+++ b/plugins/node/opentelemetry-instrumentation-mongodb/src/instrumentation.ts
@@ -97,7 +97,7 @@ export class MongoDBInstrumentation extends InstrumentationBase {
       ),
       new InstrumentationNodeModuleDefinition<any>(
         'mongodb',
-        ['4.*', '5.*', '6.*'],
+        ['4.*', '5.*', '>=6.0.0 <6.4.0'],
         undefined,
         undefined,
         [
```

However, before that there is another breakage that results in spans not getting created.

# `Connection.command` signature change

In https://github.com/mongodb/node-mongodb-native/pull/3952 the `Connection.prototype.command` method in "src/cmap/connection.ts" was changed from:

```js
  command(
    ns: MongoDBNamespace,
    command: Document,
    options: CommandOptions | undefined,
    callback: Callback
  ): void {
```

to:

```js
  public async command(
    ns: MongoDBNamespace,
    command: Document,
    options: CommandOptions = {}
  ): Promise<Document> {
```

The current instrumentation patches that `callback`, which is now undefined. It will need to change to watch the returned Promise.

One thing I wasn't sure of is that the current instrumentation already has a guard to not `startSpan` if that callback is undefined, so I'm not sure what cases that is meant to handle.


I'm moving on for now. Happy if someone else wants to take this.
