### ISSUE TITLE
Instrumenting SPA navigations (eg. location history state)

### ISSUE THREAD

**Issue by AlonMiz** [open-telemetry/opentelemetry-js-contrib#1990]
As far as I understand the`@opentelemetry/instrumentation-document-load` instrumentation only cares about the initial page load.
it will not generate the subsequence page loads or navigations
this means that all of the user navigations will not be tracked. using `instrumentation-user-interaction` will only track the interactions (clicks, keypress etc)

example of unsupported navigations
* next.js router
* React router
* Any OPA router out there that uses history.pushState behind the scenes to simulate navigation without full page load

I do believe that the document load is pretty difference from subsequence navigations, but I think that's much more important than clicks for comparison.

Is there something that I'm missing? as I couldn't find an example for this kind of instrumentation.

**Comment by martinkuba** [comment]
The user-interaction instrumentation does patch `history.pushState()` and [updates the span name](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/web/opentelemetry-instrumentation-user-interaction/src/instrumentation.ts#L425) to indicate that it was a navigation event.

The Client/RUM SIG has also been working on semantic conventions for browser events. This is not available yet, but there is a proposal to add a [page_view event](https://github.com/open-telemetry/semantic-conventions/pull/30/files#diff-31cea6f5b1661b1a8bba88fd1a4594cb6455dcfd09c969c46db15dba3d718f0fR52-R57) that would capture both hard and soft navigations.

Aside from that, if you are interested in capturing routes from a specific framework, then I think it would be best to write an instrumentation that is specific to that framework. This would be more reliable/accurate than a generic history/navigation instrumentation.

**Comment by AlonMiz** [comment]
I see, thanks for the answer. 🙏 
it would be great to have this as part of the base RUM instrumentation.
