### ISSUE TITLE
[internal] format `.release-please.manifest.json`

### ISSUE THREAD

**Issue by pichlermarc** [open-telemetry/opentelemetry-js-contrib#1991]
`.release-please.manifest.json` is currently a one-line file, which makes it hard to track changes

`release-please` does not need it to be in one line. However, it does auto-update it, and when doing so it previously auto-formatted it back into one line (I'm not sure if that's still the case). 

**We should**
- [x] format the file and see if `release-please` still auto-formats it back into a single line file
- [ ] if it does format it, we should update the [release-please workflow](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/.github/workflows/release-please.yml) to add another commit to release-PRs that nicely formats that file again after `release-please` changed it back into one line.

**Comment by david-luna** [comment]
format is done in https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1951

**Comment by david-luna** [comment]
> see if `release-please` still auto-formats it back into a single line file

How can we check this @pichlermarc?
