### ISSUE TITLE
create a plugins-all package

### ISSUE THREAD

**Issue by andrewhsu** [open-telemetry/opentelemetry-js-contrib#20]
**NB:** Before opening a feature request against this repo, consider whether the feature should/could be implemented in the [other OpenTelemetry client libraries](https://github.com/open-telemetry/). If so, please [open an issue on opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/issues/new) first.

**Is your feature request related to a problem? Please describe.**
Would like an easy way to install plugins that would help to autoinstrument my app that would be sending opentelemetry traces.

**Describe the solution you'd like**
A plugins-all package that would instal the kitchen sink from opentelemetry-js-contrib.

**Describe alternatives you've considered**
Possible alternatives:
1. Manual instructions for the user to find the package and install themselves.
2. Utility tool to detect what npm package is already in the system and echo to the user a suggested npm command to run to install plugins that would help to auto-instrument.

**Additional context**
Talked about on 2020-04-22 [agenda](https://docs.google.com/document/d/1S_pN7sBU7wO6cBP2hDSAt3bjSWdWdm6jWeUikC9KrcY/edit#heading=h.lsz268gua808)

**Comment by dyladan** [comment]
Per sig, I will create it with name `@opentelemetry/plugins-all-node`

**Comment by vmarchaud** [comment]
This has been implemented since then (https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/metapackages/plugins-node-core-and-contrib) so i'm closing this
