### ISSUE TITLE
[winston-transport] Type 'OpenTelemetryTransportV3' is missing the following properties from type 'TransportStream'

### ISSUE THREAD

**Issue by netiperher** [open-telemetry/opentelemetry-js-contrib#2015]
### What version of OpenTelemetry are you using?
@opentelemetry/winston-transport@0.1.0
@opentelemetry/api-logs@0.49.1
winston-transport@4.5.0
typescript@5.3.3

### What version of Node are you using?
v18.18.2

### What did you do?
Tried to use the new `winston-transport` package with typescript, according instructions in README

```
import winston from 'winston';
import { OpenTelemetryTransportV3 } from '@opentelemetry/winston-transport';

const logger = winston.createLogger({
  transports: [new winston.transports.Console(), new OpenTelemetryTransportV3()],
});
```

### What did you expect to see?
Possible to run typescript compiler without build issues

### What did you see instead?
```
error TS2740: Type 'OpenTelemetryTransportV3' is missing the following properties from type 'TransportStream': writable, writableEnded, writableFinished, writableHighWaterMark, and 33 more.
```

### Additional context
This seems related to similar issue https://github.com/googleapis/nodejs-logging-winston/issues/342 that is related to using CommonJS. I also verified that applying the same fix to the winston-transport package solved the build issue for me:

```
diff --git a/packages/winston-transport/src/OpenTelemetryTransportV3.ts b/packages/winston-transport/src/OpenTelemetryTransportV3.ts
index 9ff40c49..c6f3450c 100644
--- a/packages/winston-transport/src/OpenTelemetryTransportV3.ts
+++ b/packages/winston-transport/src/OpenTelemetryTransportV3.ts
@@ -15,7 +15,7 @@
  */

 import { Logger, logs } from '@opentelemetry/api-logs';
-import * as Transport from 'winston-transport';
+import Transport = require('winston-transport');
 import { VERSION } from './version';
 import { emitLogRecord } from './utils';
```

**Comment by hectorhdzg** [comment]
@netiperher can you share your tsconfig?

**Comment by netiperher** [comment]
@hectorhdzg here is a minimal example of what I'm using
```
{
  "compilerOptions": {
    "target": "es2022",
    "module": "commonjs",
    "esModuleInterop": true,
    "strict": true,
    "skipLibCheck": true,
    "moduleResolution": "node",
    "outDir": "build"
  },
  "include": ["src"]
}
```

**Comment by lewinskimaciej** [comment]
We also encountered this issue with a commonjs project. I forcefully cast the transport like this: 
```new OpenTelemetryTransportV3() as unknown as winston.transport```
and it 'works' for now

**Comment by trentm** [comment]
For the record, that `import foo = require('bar');` syntax is defined here: https://www.typescriptlang.org/docs/handbook/modules/reference.html#export--and-import--require
