### ISSUE TITLE
 [ci] newly created packages are published before the release PR is merged

### ISSUE THREAD

**Issue by pichlermarc** [open-telemetry/opentelemetry-js-contrib#2020]
There seems to be a bug in our release pipeline where newly created packages are published before a release PR is merged. We should guard [in our workflow](https://github.com/open-telemetry/opentelemetry-js-contrib/blame/9df30ea0fd822a69203b818b8fbe34e1e1c8bced/.github/workflows/release-please.yml#L66-L72) so that it only releases on commits that are created by a release PR.

I've noticed this as the `@opentelemetry/winston-transport` package was published without an associated release PR.

**Resources:**
- Job that published the package: https://github.com/open-telemetry/opentelemetry-js-contrib/actions/runs/8286523704/job/22676722070
- Publish step which should only run after a release PR was merged: https://github.com/open-telemetry/opentelemetry-js-contrib/blame/9df30ea0fd822a69203b818b8fbe34e1e1c8bced/.github/workflows/release-please.yml#L66-L72

**Comment by JamieDanielson** [comment]
Hmm [these docs](https://github.com/google-github-actions/release-please-action?tab=readme-ov-file#automating-publication-to-npm) look promising. Think we just need to add `if: ${{ steps.release.outputs.release_created }}` to the workflow step. I'll open a PR for it

**Comment by pichlermarc** [comment]
re-opened as that unfortunately did not fix it :/

**Comment by pichlermarc** [comment]
I think it should've probably been `releases_created` instead of `release_created` (root-component vs non-root-component)

**Comment by JamieDanielson** [comment]
Ah darn! 😢

**Comment by pichlermarc** [comment]
@JamieDanielson do you want to give it another shot? :slightly_smiling_face: 
You originally found out how to do it - I think it'd work with `releases_created` :slightly_smiling_face: 

`releases_created` -> true if any release was created, false otherwise
`release_created` -> true if a root component release was created, false otherwise

**Comment by pichlermarc** [comment]
The solution from #2160 works :slightly_smiling_face: :tada:
