### ISSUE TITLE
re-enable dns as a default plugin

### ISSUE THREAD

**Issue by naseemkullah** [open-telemetry/opentelemetry-js-contrib#205]
- [x] This only affects the JavaScript OpenTelemetry library
- [ ] This may affect other libraries, but I would like to get opinions here first

As per gitter chat with @dyladan and @obecny :

The dns is currently disabled as we need to watch for:

> any case where creating a span may result in a DNS request, the DNS request may itself trigger a new trace, which may result in a new DNS request, and so on.

However, 

> with latest changes ver. 0.11 it should automatically surpress tracing for all exporters

> Yes that is an important point. The context property to suppress tracing is set in the span processor

> if that is happening for dns you might want to add surpressing manually then so the plugin will not cause creating a new span

> and at least for collector I have checked that and it was working fine

> I also heard from someone that it worked for zipkin that they weren't seeing recursive http calls

**Comment by vmarchaud** [comment]
We could totally enable it by default indeed.

**Comment by vmarchaud** [comment]
I think we can close this @naseemkullah ?
