### ISSUE TITLE
improve resource detector documentation

### ISSUE THREAD

**Issue by maryliag** [open-telemetry/opentelemetry-js-contrib#2055]
On the README of the [resource detectors](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/detectors/node), there are no details about which resource attributes are being set and what are their respective keys, making it hard to identify what we have available.

Improve documentation, adding a table with the info for all resource detectors.

- [x] Alibaba #2056 
- [x] AWS #2060 
- [x] Azure #2057 
- [x] Container #2061 
- [x] GCP #2062 
- [x] Github #2064 
- [x] Instana #2063

**Comment by trentm** [comment]
Done now, I believe.

**Comment by maryliag** [comment]
@trentm thank you for all the reviews and merges!
