### ISSUE TITLE
Rename all `@opentelemetry/plugin-*` packages to `@opentelemetry/plugin-contrib-*`

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-js-contrib#21]
In order to differentiate between "core" plugins like http and contrib plugins like mysql, we should rename all plugins so that it is obvious which "level" of plugin it is from the name and deprecate all released versions of the previous name.

**Comment by obecny** [comment]
My 3 cents. I would not complicate it. First one day certain plugin might be moved to core or opposite and then it will need to have its name changed - users will be confused. Secondly I would keep the same name for certain plugin forever to be able to upgrade to latest version without checking if name has changed or not. Based on only those issues I don't really see a big benefits in having different name as it might also change in future and will produce more confusions than benefits.
