### ISSUE TITLE
@opentelemetry/instrumentation-express Route and Span Name is incorrect

### ISSUE THREAD

**Issue by ray58750034** [open-telemetry/opentelemetry-js-contrib#2102]
### What version of OpenTelemetry are you using?
```
@opentelemetry/api 1.8.0
@opentelemetry/instrumentation-express  >0.33.1 & <=0.37.0
```

### What version of Node are you using?
v18.18.2

### What did you do?

I use following code to reproduce the issue
```
(async () => {
  const express = require('express');
  const router = express.Router();
  const http = require('http');
  const app = express();
  const port = 6666;
  const server = app.listen(port);

  router.all('/foo', (req, res, next) => {
    res.json({ hello: 'yes' });
    res.end();
    next();
  });

  app.use(router);
  app.use((req, res, next) => {
    console.log('-------- post handler');
    next();
  });

  http
    .request({
      method: 'POST',
      hostname: '127.0.0.1',
      port,
      path: '/foo'
    })
    .end();

  await TimeUtil.sleep(200);
})();
```

### What did you expect to see?
Span name: POST /foo

### What did you see instead?
Span name: POST /

### Additional context

I try to debug this issue and found that line 201 change in this [commit](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1620/files) removed  `type === ExpressLayerType.REQUEST_HANDLER` condition that would cause route to be overwrite in middleware after request handler.

**Comment by JamieDanielson** [comment]
I think this is what's described in #1993 . I haven't had a chance to get back to this but will try to get it taken care of this week.

**Comment by ray58750034** [comment]
I tested `@opentelemetry/instrumentation-express@0.44.0`, the span name is still `POST /`, expect to be `POST /foo`.

**Comment by ray58750034** [comment]
I tested with `@opentelemetry/instrumentation-express@0.44.0`, it seems to be fixed.
