### ISSUE TITLE
Request for new component: Baggage Span Processor

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-js-contrib#2104]
### Is your feature request related to a problem? Please describe
The Honeycomb distro currently provides a Span processor that takes items from the baggage and adds those items as attributes onto spans. 

### Describe the solution you'd like to see

We'd like to donate this code upstream if there's an interest from the community, the code is pretty minimal:
https://github.com/honeycombio/honeycomb-opentelemetry-node/blob/main/src/baggage-span-processor.ts

**Comment by trentm** [comment]
Sounds good to me.
