### ISSUE TITLE
Add Pino transport for OpenTelemetry

### ISSUE THREAD

**Issue by mhennoch** [open-telemetry/opentelemetry-js-contrib#2110]
### Is your feature request related to a problem? Please describe

We should add Logs API support to Pino also now that Bunyan/Winston have it.

### Describe the solution you'd like to see

Seems like Pino recommends doing this via [transports](https://github.com/pinojs/pino/blob/master/docs/transports.md). Ideally transports operate in a separate thread or a separate process which won't have access to globally set log provider. So we would need to duplicate and setup log provider inside the transport itself together with resource detection, processor/exporter configuration etc.  I don't see a sane way of passing in custom processor/exporter to the transporter tho. Also need to make sure this works well with Pino instrumentation and auto instrumentation.

Pino already links to one [OTEL transport](https://github.com/Vunovati/pino-opentelemetry-transport). Maybe @Vunovati is willing to move it to contrib.

Are there any other ways of doing this besides using a transport?

**Comment by Vunovati** [comment]
Hello @mhennoch, what problem would moving the transport to this repo solve for the end users? Is there a way to do it while preserving all the contributions of the contributors to the original repo?

**Comment by Vunovati** [comment]
Hello,

Pino Opentelemetry Transport is now moved to @pinojs org

https://github.com/pinojs/pino-opentelemetry-transport

I created an issue with the description and the motivation for doing so here:
https://github.com/pinojs/pino-opentelemetry-transport/issues/161

Thanks
