### ISSUE TITLE
Not instrumenting winston package automatically. Is it necessary to use "@opentelemetry/instrumentation-winston" ?

### ISSUE THREAD

**Issue by deep-iimjobs** [open-telemetry/opentelemetry-js-contrib#2119]
TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at exports.Logger.patchedLog [as log] (/home/ubuntu/www/recruiter/node_modules/@opentelemetry/instrumentation-winston/build/src/instrumentation.js:108:42)
    at cprint (/home/ubuntu/www/recruiter/utilities/logger.js:58:16)
    at fetchCalendars (/home/ubuntu/www/recruiter/routes/JobCalendar/fetchCalendars.js:17:3)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by trentm** [comment]
The instrumentation.js line above is this:

```js
// ...
    _getPatchedLog() {
        return (original) => {
            const instrumentation = this;
            return function patchedLog(...args) {
                const record = {};
                instrumentation._handleLogCorrelation(record);
                // Inject in metadata argument
                let isDataInjected = false;
                for (let i = args.length - 1; i >= 0; i--) {
                    if (typeof args[i] === 'object') {
                        args[i] = Object.assign(args[i], record);   // <--- HERE
                        isDataInjected = true;
                        break;
                    }
                }
// ...
```

The exception is, I'm guessing, this:

```js
> Object.assign(null, {foo:'bar'})
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
```

that `args[i]` is null or undefined.

So `Logger.prototype.log` (from 'winston/lib/winston/logger.js') is being called with a `null` or `undefined` last argument.

@deep-iimjobs Can you please show your JavaScript or TypeScript code that is calling this? That would be "/home/ubuntu/www/recruiter/utilities/logger.js:58" and possibly "/home/ubuntu/www/recruiter/routes/JobCalendar/fetchCalendars.js:17" would help as well.

/cc @hectorhdzg

**Comment by deep-iimjobs** [comment]
const levels = {
  0: "exception",
  1: "query",
  2: "info"
}
var logger = new (winston.Logger)({
  transports: [
    new (winston.transports.Console)({
      colorize: 'all',
      prettyPrint: true,
      timestamp: function () {
        return moment().format('YYYY-MM-DD HH:mm:ss');
      },
      formatter: function (options) {
        return (options.timestamp()) + ' ' + config.colorize(options.level, options.message ? options.message : '')
      },
      level: mode == 'debug' ? "info" : "error"
    })
  ],
  levels: {
    "exception": 0,
    "query": 1,
    "info": 2
  },
  colors: {
    "exception": "red",
    "query": "yellow",
    "info": "green"
  }
});
 
function cprint(text, level) {
  if (!levels[level])
    return
  return logger.log(levels[level], text);
}
 
cprint(1, "testing");

**Comment by trentm** [comment]
@deep-iimjobs Is there a reason you closed this issue?

I think there might be a real bug in the `@opentelemetry/instrumentation-winston` package here.
Possibly it is related to your using custom levels, but I'm not sure.

**Comment by lemanhmufc** [comment]
@trentm I'm start using opentelemetry and facing a same problem with winston on logging. Do you think that this should be check if agrs were null or undefine before converting inside instrumentation-winston. My current solution is checking and converting null/undefined agrs in to text "undefined" before winston loging. I think there should be a Definitive solution for this.

**Comment by lemanhmufc** [comment]
hello @trentm, are you there, please check my issue.
