### ISSUE TITLE
pg spans disconnected from parent

### ISSUE THREAD

**Issue by tmc** [open-telemetry/opentelemetry-js-contrib#213]
### What version of OpenTelemetry are you using?
0.11

### What version of Node are you using?
14.8.0

### What did you do?
Enabled express, pg plugins.

### What did you expect to see?
Connected parent and child spans.

### What did you see instead?
Each span produced by the pg plugin is unassociated with the parent span from the express plugin.

**Comment by akshah123** [comment]
I was about to create the same issue.  For me, this is happening with koa as well.  Here my details if it helps:


### What version of OpenTelemetry are you using?
0.11.0

### What version of Node are you using?
12.14.0

### What did you do?
Have default list of plugins enabled.  I am using lightstep's Otel project that wraps itself around this open-telemetry project.
```javascript
const sdk = lightstep.configureOpenTelemetry({
      logLevel: 'debug',
      serviceName: 'serviceability'
    })

    await sdk.start()
```

### What did you expect to see?
Connected parent and child spans.

### What did you see instead?
Each span produced by the pg plugin is unassociated with the parent span from the koa plugin.

**Comment by obecny** [comment]
@tmc Please provide you exact code example including the package.json

**Comment by akshah123** [comment]
@obecny I am still seeing this problem even after upgrading plugins to version 0.11.0.  Does this fix also require upgrade of Opentelemetry package to 0.12.0?

**Comment by dyladan** [comment]
@akshah123 can you please provide a minimum reproduction of your issue?

**Comment by obecny** [comment]
@akshah123 you are using lighstep launcher which hasn't been upgraded yet to latest version of pg plugin

**Comment by akshah123** [comment]
I am seeing this issue even after upgrading lightstep's launcher to the latest version.  

For an example, project please see this repo: https://github.com/akshah123/koa-test-app

**Comment by obecny** [comment]
@akshah123 I have responded here https://github.com/lightstep/otel-launcher-node/issues/20#issuecomment-729999974
