### ISSUE TITLE
sqsExtractContextPropagationFromPayload doesn't seem to work as expected

### ISSUE THREAD

**Issue by arun0009** [open-telemetry/opentelemetry-js-contrib#2135]
### What version of OpenTelemetry are you using?
```
    "@opentelemetry/api": "^1.8.0",
    "@opentelemetry/auto-instrumentations-node": "^0.44.0",
    "@opentelemetry/core": "^1.23.0",
    "@opentelemetry/exporter-trace-otlp-proto": "^0.50.0",
    "@opentelemetry/instrumentation-express": "^0.37.0",
    "@opentelemetry/sdk-metrics": "^1.23.0",
    "@opentelemetry/sdk-node": "^0.50.0",
    "@opentelemetry/sdk-trace-node": "^1.23.0",
```

### What version of Node are you using?
❯ node -v
v20.11.1

### What did you do?

I created a [repo](https://github.com/arun0009/otel) to reference this issue. 

In otel.ts I have `sqsExtractContextPropagationFromPayload: true` under AwsInstrumentation. I have 2 endpoints `/send` which sends a message to SQS and another endpoint `/receive` which pulls message from SQS and makes a http call before deleting the message from queue.

I assume since its extracting `traceParent` from MessageAttributes while receiving message it should set that as parent trace and add any spans to it (in `/receive`)? However, I see no updates to `/send` trace (had 3 spans after sending a message to sqs and it didn't update after calling `/receive`)? 

I see a link on `/receive` trace to `/send` trace but I see that regardless of `sqsExtractContextPropagationFromPayload` being true or false. (see image #3).

Jaeger Main Page:

<img width="1678" alt="image" src="https://github.com/open-telemetry/opentelemetry-js-contrib/assets/3824444/51b4123a-71e3-4f52-99f7-e12ce916e2bc">

/send Trace Details

<img width="1673" alt="image" src="https://github.com/open-telemetry/opentelemetry-js-contrib/assets/3824444/d1c638af-3ee8-4254-be4a-7719444d0640">
<br/>
<br/>
/receive Trace Details

<img width="1667" alt="image" src="https://github.com/open-telemetry/opentelemetry-js-contrib/assets/3824444/14d91286-0a42-4127-9121-0bbf8dea5c76">

### What did you expect to see?
Spans to be added to original trace i.e. `/send` but I don't see any spans being added to `send` trace after calling `receive`.

### What did you see instead?
see my details above.

**Comment by dyladan** [comment]
@carolabadeer can you please look into this?

**Comment by dyladan** [comment]
>I see a link on /receive trace to /send trace but I see that regardless of sqsExtractContextPropagationFromPayload being true or false.

In SQS the receive span is not a child of the send span. Because you can only get a batch it would be required to have multiple parents in order to make that work. The option you referenced only changes the mechanism used to get the context from the send to the receive span. This is required in some cases where MessageAttributes are not propagated by SQS/SNS. They are linked together using span links which is correct according to the current semantic convention. I believe this is working as intended.

**Comment by dyladan** [comment]
You can read more about the SNS/SQS integration here https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-aws-sdk/doc/sns.md#integration-with-sqs

**Comment by pichlermarc** [comment]
@arun0009 does this answer your question? :thinking:

**Comment by arun0009** [comment]
Yes, but I'm not sure if I can search for child traces that get spawned by this parent in Jaeger or New Relic? I posted this on [Jaeger](https://github.com/jaegertracing/jaeger-ui/issues/662#issuecomment-2094321500) org as well. Feel free to close this if its not relevant.
