### ISSUE TITLE
opentelemetry-instrumentation-pino not working with pino 9.0.0

### ISSUE THREAD

**Issue by gunjam** [open-telemetry/opentelemetry-js-contrib#2155]
### What version of OpenTelemetry are you using?
"@opentelemetry/auto-instrumentations-node": "0.44.0"
"@opentelemetry/resources": "1.24.0"
"@opentelemetry/sdk-node": "0.51.0"
"@opentelemetry/semantic-conventions": "1.24.0"

### What version of Node are you using?
20.12.0

### What did you do?

Updated from pino 8.21.0 to 9.0.0

### What did you expect to see?
otel properties in pino log output

### What did you see instead?
no otel properties in pino log output

### Additional context

I've been switching between the two versions and it logs correct in 8 but not 9, so it's only the version of pino that seems to be causing this.

Logging out the pino instance you can see that the otel mixin has not been added to log trace ids, etc:

pino 8.21.0
```javascript
[Symbol(pino.mixin)]: [Function: otelMixin],
```
pino 9.0.0
```javascript
[Symbol(pino.mixin)]: undefined,
```

**Comment by Flarna** [comment]
Not a bug.

Supported versions in doc state <9 see [here](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-pino#supported-versions).

Depending on the changes done on pino side it's maybe just needed to adapt range [here](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/7822461f53081937594ecf0ebcdecd79c2b08a2e/plugins/node/opentelemetry-instrumentation-pino/src/instrumentation.ts#L32).

**Comment by gunjam** [comment]
I thought that might be the case then forget to check 🤦. Thanks for the clarifiation

The only change in pino 9 is the project [dropping support for node < 18](https://github.com/pinojs/pino/pull/1947#issuecomment-2077203390).

**Comment by blumamir** [comment]
Opened #2163 to add support for new pino version
