### ISSUE TITLE
[Hapi Plugin] Hapi instrumentation plugins wrapping issue

### ISSUE THREAD

**Issue by jk1z** [open-telemetry/opentelemetry-js-contrib#218]
### What version of OpenTelemetry are you using?
"@opentelemetry/core": "^0.11.0",
"@opentelemetry/exporter-jaeger": "^0.11.0",
"@opentelemetry/hapi-instrumentation": "^0.10.0",
"@opentelemetry/node": "^0.11.0",
"@opentelemetry/plugin-http": "^0.11.0",
"@opentelemetry/plugin-https": "^0.11.0",
"@opentelemetry/plugin-mongodb": "^0.10.0",
"@opentelemetry/plugin-redis": "^0.10.0",
"@opentelemetry/tracing": "^0.11.0",

### What version of Node are you using?
v14.2.0

### What did you do?
In @hapi version 19.1.1, when I'm trying to use `server.register([{plugin: require("./plugin-a")}, require("./plugin-b")}])` while hapi-instrumentation is on. I'm getting `Cannot read property 'name' of undefined` from the `hapi-instrumentation` package.
![image](https://user-images.githubusercontent.com/18542127/95707787-377d6000-0ca6-11eb-89fe-b41e4d84e4ed.png)

This is because the `hapi-instrumentation` package only supports one of the plugin declaration format. The other declaration format are as follows:

```
plugin-a.js
exports.plugin = {
name: "test plugin",
....
}
```

### What did you expect to see?
The plugin should wrap the plugins normally

### What did you see instead?
It throws an error

### Additional context
Hapi allows two ways of making a plugin.
![image](https://user-images.githubusercontent.com/18542127/95726519-c39e8000-0cc4-11eb-9665-d627a60fe8a6.png)

**Comment by jk1z** [comment]
@carolinee21 To fix this issue, I had to add an extra line at the start of the `_wrapRegisterHandler` function in hapi-instrumentation package's hapi.js
`if (plugin.plugin) plugin = plugin.plugin;`
![image](https://user-images.githubusercontent.com/18542127/95708038-f76aad00-0ca6-11eb-80df-0a59f842d769.png)

The reason why is that when we do server.register([plugins, plugins]). _wrapRegisterHandler `plugin` input param will be plugin: { plugin: Object }
![image](https://user-images.githubusercontent.com/18542127/95708140-37ca2b00-0ca7-11eb-91cc-3afe0a1a01e3.png)

**Comment by carolinee21** [comment]
This seems like a good add to support this other declaration format - I support adding this fix
