### ISSUE TITLE
Mongodb integration doesn't work when used with promises

### ISSUE THREAD

**Issue by richardsimko** [open-telemetry/opentelemetry-js-contrib#2218]
### What version of OpenTelemetry are you using?
0.39.0

### What version of Node are you using?
20.12

### What did you do?

Running the OpenTelemetry Mongodb integration provided through Sentry v8.

### What did you expect to see?
Traces for Mongo DB requests when making queries using promises

### What did you see instead?
No traces

### Additional context

From my understanding the patch of the server command function only applies the span if there is a callback provided (https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-mongodb/src/instrumentation.ts#L443-L447). When using the mongo library with promises no callback is provided (https://github.com/mongodb/node-mongodb-native/blob/main/src/sdam/server.ts#L326) and as a result no spans are created.

I couldn't find anything in the docs saying that promises aren't supported, so perhaps there is something I'm missing?

**Comment by AbhiPrasad** [comment]
Does this apply for all versions of `mongodb`?

**Comment by mydea** [comment]
Could you share a concrete code snippet of something that is not instrumented today? (Just to clarify and make it easier to test this)

**Comment by richardsimko** [comment]
I think it was incorrect of me to assume this was the issue as it seems to have been resolved downstream in Sentry. See https://github.com/getsentry/sentry-javascript/issues/12181#issuecomment-2127955890
