### ISSUE TITLE
[Koa] koa plugin instrumentation doesnt generalize http routes

### ISSUE THREAD

**Issue by AndrewGrachov** [open-telemetry/opentelemetry-js-contrib#222]
- [x] This only affects the JavaScript OpenTelemetry library
- [ ] This may affect other libraries, but I would like to get opinions here first

having http and koa intrumentation enabled

**Expectation:**
I see  traces grouped by koa routes

**Reality:** 

I see every incoming http request as separate operation which is not really useable. Do I do something wrong, or this is an issue?

![download (5)](https://user-images.githubusercontent.com/2847615/95780372-788c6900-0cd4-11eb-8e86-799550b644a0.png)

**Comment by morigs** [comment]
Related to open-telemetry/opentelemetry-js#897
See [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#name)

**Comment by jmealo** [comment]
I just reviewed the tests for the koa instrumentation and it looks like this already works properly for traces (even using nested routers): https://github.com/open-telemetry/opentelemetry-js-contrib/blob/master/plugins/node/opentelemetry-koa-instrumentation/test/koa-router.test.ts#L155

It looks like this is a matter of setting the name on the request span from the koa instrumentation as it has become more generic in the http plugin.

**Comment by AndrewGrachov** [comment]
@madamas, pls confirm that you dont have this issue anymore, and we can close that :)

**Comment by Madamas** [comment]
yep, works like a charm in latest version, thanks for heads-up
