### ISSUE TITLE
Add hook to access response in instrumentation-undici

### ISSUE THREAD

**Issue by mydea** [open-telemetry/opentelemetry-js-contrib#2265]
It would be great to have a hook that allows us access to request & response in instrumentation-undici. 

Would you be open to add support for this? If so, I could work on a PR adding this. I am thinking about something like this which exists in instrumentation-http:

```ts
applyCustomAttributesOnSpan: (
  span,
  request,
  response,
) : void
```

Alternatively, if we could make certain things protected (e.g. `subscribeToChannel`) we could also extend the instrumentation class and add such things ourselves. If that's preferable I could also PR this?

**Comment by cpatti97100** [comment]
would this request be related to https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2179?
