### ISSUE TITLE
Reduce log level on detectors failing to detect

### ISSUE THREAD

**Issue by david-luna** [open-telemetry/opentelemetry-js-contrib#2268]
I've noticed that some detectors make use of `diag.info` or `diag.warn` when they fail to do the detection. So with the default log level they are displayed in stdout.

A couple of places where it happens

https://github.com/open-telemetry/opentelemetry-js-contrib/blob/6721bddc2d190befabab95f706ca467d06633674/detectors/node/opentelemetry-resource-detector-container/src/detectors/ContainerDetector.ts#L116

https://github.com/open-telemetry/opentelemetry-js-contrib/blob/6721bddc2d190befabab95f706ca467d06633674/detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsEksDetector.ts#L91

This is not a problem per se but these messages appear if the customer enables some detectors that for sure will fail. Some examples:
- app is started enabling container detector but not deployed in a container
- app is started enabling AWS detector but deployed in another cloud
- app is started with `OTEL_NODE_RESOURCE_DETECTORS=all` when using auto instrumentations

IMHO seeing messages about AWS when my app is running in another cloud could be a bit misleading. I'm attaching here a small repro

package.json
```json
{
  "name": "detectors-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@opentelemetry/api": "^1.9.0",
    "@opentelemetry/auto-instrumentations-node": "^0.47.0"
  }
}
```

index.js
```js
// Usage:
//  OTEL_NODE_RESOURCE_DETECTORS=all node --require '@opentelemetry/auto-instrumentations-node/register' index.js

const https = require('https');

const clientReq = https.request('https://opentelemetry.io/', function (cres) {
  console.log('client response: %s %s', cres.statusCode, cres.headers);
  const chunks = [];
  cres.on('data', function (chunk) {
      chunks.push(chunk);
  });
  cres.on('end', function () {
      const body = chunks.join('');
      console.log('client response body lenght: %j', body.length);
  });
});
clientReq.end();
```

And this is what you get
```sh
OTEL_NODE_RESOURCE_DETECTORS=all node --require '@opentelemetry/auto-instrumentations-node/register' index.js

OTEL_TRACES_EXPORTER is empty. Using default otlp exporter.
OpenTelemetry automatic instrumentation started successfully
Container Detector failed to read the Container ID:  ENOENT: no such file or directory, open '/proc/self/cgroup'
Process is not running on K8S [Error: ENOENT: no such file or directory, access '/var/run/secrets/kubernetes.io/serviceaccount/token'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/var/run/secrets/kubernetes.io/serviceaccount/token'
}
client response: 200 {
  ...
  connection: 'close'
}
client response body lenght: 20669
```

The K8s message is scary if you're not familiar with the topic. Detectors just resolved that they're nor running in a container neither in an AWS cluster. So my proposal would be:
- reduce the level to `debug`
- rephrase the messages

**Comment by johnli-developer** [comment]
I will work on this issue
