### ISSUE TITLE
[instrumentation-document-load] option to ignore resource spans

### ISSUE THREAD

**Issue by longility** [open-telemetry/opentelemetry-js-contrib#2284]
If this is acceptable, I can do a PR to expedite our needs and contribute for others to leverage as well.

### Is your feature request related to a problem? Please describe
I would like to minimize the number of spans created that may not be important to us, specifically resource spans.

<img width="733" alt="image" src="https://github.com/open-telemetry/opentelemetry-js-contrib/assets/720635/8e65cae3-8fe3-493c-8c68-7f69f83adbe7">

### Describe the solution you'd like to see
For this line,
https://github.com/open-telemetry/opentelemetry-js-contrib/blob/2dc2f72e5a86aa9e1220a26f78878070acde8424/plugins/web/opentelemetry-instrumentation-document-load/src/instrumentation.ts#L138

to be similar to this:
https://github.com/open-telemetry/opentelemetry-js-contrib/blob/2dc2f72e5a86aa9e1220a26f78878070acde8424/plugins/web/opentelemetry-instrumentation-document-load/src/instrumentation.ts#L160C7-L162C8

to where the end result may look something like this:
```typescript
      if (!this._getConfig().ignoreResourceSpans) {
        this._addResourcesSpans(rootSpan);
      }
```

### Describe alternatives you've considered
None.

### Additional context
None.

**Comment by scheler** [comment]
We are working on a new set of instrumentations using the new Events API, one of which is to emit ResourceTiming events for the resources loaded (https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2152), and another to emit PageView event (https://github.com/open-telemetry/opentelemetry-sandbox-web-js/issues/81). As part of this effort, I envision an instrumentation to emit a standalone documentFetch span. We have not created an issue yet to track this as this hasn't been discussed much in the Client SIG.

For your use-case does it work if you configure a custom sampler to drop these spans?

**Comment by longility** [comment]
> We are working on a new set of instrumentations using the new Events API, one of which is to emit ResourceTiming events for the resources loaded (#2152), and another to emit PageView event ([open-telemetry/opentelemetry-sandbox-web-js#81](https://github.com/open-telemetry/opentelemetry-sandbox-web-js/issues/81)). As part of this effort, I envision an instrumentation to emit a standalone documentFetch span. We have not created an issue yet to track this as this hasn't been discussed much in the Client SIG.
> 
> For your use-case does it work if you configure a custom sampler to drop these spans?

@scheler thanks for the status update and a workaround! I think that could be sufficient. Do you know of a sampler that could be a good starting point? I have not done one of those before.

**Comment by scheler** [comment]
@longility something like this - 

```js
const provider = new WebTracerProvider({
  resource,
  sampler: {
    shouldSample: (context, traceId, spanName, spanKind, attributes, links) => {
      return spanName == 'resourceFetch' ? SamplingDecision.NOT_RECORD : SamplingDecision.RECORD_AND_SAMPLED;
    }
  }
});
```

**Comment by scheler** [comment]
@longility  can you close this issue if the workaround works for you?

**Comment by JBlakd** [comment]
As of me posting this now, the return type of `shouldSample` has been slightly modified, so it should be done like so:
```
  const provider = new WebTracerProvider({
    sampler: {
      shouldSample: (
        _context,
        _traceId,
        spanName,
        _spanKind,
        _attributes,
        _links,
      ) => {
        return spanName == 'resourceFetch'
          ? { decision: SamplingDecision.NOT_RECORD }
          : { decision: SamplingDecision.RECORD_AND_SAMPLED };
      },
    },
  });
```
