### ISSUE TITLE
Pin package version to opentelemetry's version

### ISSUE THREAD

**Issue by sk-** [open-telemetry/opentelemetry-js-contrib#229]
**NB:** Before opening a feature request against this repo, consider whether the feature should/could be implemented in the [other OpenTelemetry client libraries](https://github.com/open-telemetry/). If so, please [open an issue on opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/issues/new) first.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I update OpenTelemetry dependencies, because the contrib pacakges use a different versioning scheme.

For example now, all packages are in version 0.10.0, but they use openetelemetry 0.11.0.

See below my dependencies:

```json
    "@opentelemetry/api": "^0.10.2",
    "@opentelemetry/core": "^0.10.2",
    "@opentelemetry/node": "^0.10.2",
    "@opentelemetry/plugin-express": "^0.9.0",
    "@opentelemetry/plugin-grpc-js": "^0.10.2",
    "@opentelemetry/plugin-https": "^0.10.2",
    "@opentelemetry/tracing": "^0.10.2",
```

Note how confusing it looks  "@opentelemetry/plugin-express": "^0.9.0". Whenever I update the dependencies I need to manually check they depend on a compatible version.

**Describe the solution you'd like**
The version of these packages should be pinned to the one used by OpenTelemetry. That is if the package has a dependency on "@opentelemetry/api": "^0.11.0", then the version of the plugin should be 0.11.0.

**Describe alternatives you've considered**

**Additional context**

**Comment by dyladan** [comment]
According to [node semver docs](https://github.com/npm/node-semver#caret-ranges-123-025-004), `^0.10.2` does not match `0.11.0`.

Specifically, caret ranges:

>Allows changes that do not modify the left-most non-zero element in the [major, minor, patch] tuple. In other words, this allows patch and minor updates for versions 1.0.0 and above, patch updates for versions 0.X >=0.1.0, and no updates for versions 0.0.X.

Pinning the versions would not allow the contrib packages to take care of compatible releases and bugfixes (`0.0.X` updates).

**Comment by sk-** [comment]
You could pin just the major and minor version for 0.x releases and just the major version for >= 1.x versions.

In that way you would know they are compatible without having to look a the sources.

**Comment by sk-** [comment]
Note how confusing it looks the dependency `"@opentelemetry/plugin-express": "^0.9.0",` compared to another plugin `    "@opentelemetry/plugin-https": "^0.10.2",`.

The problem stems from the fact that both packages uses the same namespace `@opentelemetry`. So one needs to dig deeper to understand why is that this single package requires a different version.

I guess it would be slightly less confusing if the package was in another namespace like `@opentelemetry-contrib`, but I think that ship has sailed.

**Comment by vmarchaud** [comment]
Now that instrumentation only depend on the API (and that we pin the version each is compatible with) it should be automatically handled by package managers
