### ISSUE TITLE
Timeline for next release or way for me to include master branch for redis plugin

### ISSUE THREAD

**Issue by akshah123** [open-telemetry/opentelemetry-js-contrib#230]
- [x] This only affects the JavaScript OpenTelemetry library
- [ ] This may affect other libraries, but I would like to get opinions here first

I would love to start making use of [this PR](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/215) that was merged few weeks ago.  

Is there a timeframe of when a 0.11.0 version of plugins may be released?  If not, is it possible for me to point directly to master branch somehow for this plugin?

**Comment by obecny** [comment]
@akshah123 the release should be this week

**Comment by dyladan** [comment]
Released
