### ISSUE TITLE
When using auto-instrumentations-node, some values of `OTEL_NODE_RESOURCE_DETECTORS` are treated as invalid

### ISSUE THREAD

**Issue by qbedard** [open-telemetry/opentelemetry-js-contrib#2311]
### What version of OpenTelemetry are you using?

@opentelemetry/api@1.9.0
@opentelemetry/auto-instrumentations-node@0.47.1
@opentelemetry/exporter-trace-otlp-http@0.52.1
@opentelemetry/instrumentation-express@0.40.1
@opentelemetry/instrumentation-http@0.52.1
@opentelemetry/instrumentation-undici@0.3.0
@opentelemetry/resource-detector-aws@1.5.1
@opentelemetry/sdk-node@0.52.1
@opentelemetry/sdk-trace-node@1.25.1

### What version of Node are you using?

18.12.1

### What did you do?

Use [auto-instrumentations-node](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/metapackages/auto-instrumentations-node) with `OTEL_NODE_RESOURCE_DETECTORS` set to `aws,env,host,os`.

### What did you expect to see?

AWS resource detector is enabled.

### What did you see instead?

> Invalid resource detector "aws" specified in the environment variable OTEL_NODE_RESOURCE_DETECTORS

### Additional context

[This conditional](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/0c46dfe406b22d4e83399812b421514b50a58573/metapackages/auto-instrumentations-node/src/utils.ts#L277) is evaluating to `false`-y and appears to do so for all resource detectors that are of type `Detector` or `Detector[]`. Those that have values of `DetectorSync` or `DetectorSync[]` _do_ work, so the issue is likely that a `Detector` instance is evaluating to `false`-y and the linked conditional or the detector map needs to be updated to evaluate those values properly.

**Comment by trentm** [comment]
@qbedard Thanks for the issue, and the PR.

I believe what is happening here is that those `Invalid resource detector "aws" specified ...` diag.error messages are actually coming from the underlying `@opentelemetry/sdk-node` package that `@opentelemetry/auto-instrumentations-node` is using.

For example:

```
% cat foo.js
console.log('hi')
[16:59:00 trentm@peach:~/tmp/asdf]
% OTEL_NODE_RESOURCE_DETECTORS=foo,gcp,alibaba,aws,env,host,os node -r @opentelemetry/auto-instrumentations-node/register foo.js
Invalid resource detector "foo" specified in the environment variable OTEL_NODE_RESOURCE_DETECTORS
Invalid resource detector "foo" specified in the environment variable OTEL_NODE_RESOURCE_DETECTORS
Invalid resource detector "gcp" specified in the environment variable OTEL_NODE_RESOURCE_DETECTORS
Invalid resource detector "alibaba" specified in the environment variable OTEL_NODE_RESOURCE_DETECTORS
Invalid resource detector "aws" specified in the environment variable OTEL_NODE_RESOURCE_DETECTORS
OTEL_TRACES_EXPORTER is empty. Using default otlp exporter.
OpenTelemetry automatic instrumentation started successfully
hi
Process is not running on K8S [Error: ENOENT: no such file or directory, access '/var/run/secrets/kubernetes.io/serviceaccount/token'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/var/run/secrets/kubernetes.io/serviceaccount/token'
}
```

Observe that there are *two* diag error messages about the invalid "foo" resource detector name.
What is happening in:

1. auto-instrumentations-node runs its `getResourceDetectorsFromEnv` (https://github.com/open-telemetry/opentelemetry-js-contrib/blob/9dc55da3b856e6bc147d59547582f0bf056384a1/metapackages/auto-instrumentations-node/src/register.ts#L30), which *successfully* loads the "gcp", "alibaba", and "aws" detectors.
2. Then it calls `new NodeSDK` (from `@opentelemetry/sdk-node`). NodeSDK's constructor calls *its* `getResourceDetectorsFromEnv`, even if `configuration.resourceDetectors` is passed in: https://github.com/open-telemetry/opentelemetry-js/blob/a037f84b679386daefd726133be6265c3c43de27/experimental/packages/opentelemetry-sdk-node/src/sdk.ts#L123-L132

I believe an appropriate fix for this would be to improve the NodeSDK constructor to not do the `defaultDetectors` processing if `configuration.resourceDetectors` is passed in. That would get rid of some unnecessary processing and would get rid of the diag.error messages.

---

Would you be interested in attempting a PR that does that?
