### ISSUE TITLE
[Koa] should the koa plugin shim ctx.throw() to recordExceptions?

### ISSUE THREAD

**Issue by jmealo** [open-telemetry/opentelemetry-js-contrib#234]
- [x] This only affects the JavaScript OpenTelemetry library
- [ ] This may affect other libraries, but I would like to get opinions here first

Hello all,

Does it make sense for the plugin to shim`ctx.throw()` and possibly `ctx.assert()` to call `recordException` on the span? I think this is useful and could be behind an option. I'm not proposing a mechanism or place of injection. We faced an issue where `ctx.throw()` didn't record the exception which was unexpected as an end-user.

Additionally: Should we expose the span on the `ctx` or provide helpers?

Thanks,
Jeff

**Comment by vmarchaud** [comment]
`recordException` only add the stacktrace / error message on the current span attributes, it make sense to record it inside the koa plugin automatically though.

> Additionally: Should we expose the span on the ctx or provide helpers?

I don't think so, end user should use the api to interact with the span or current context.

**Comment by jmealo** [comment]
I'm ready to do the work to make this happen and contribute it, but, I'm torn on where the work belongs.

I think that folks who use tracing probably have structured logging and I'll bet you they want to share some properties between their traces and their logging.

Developers should generally use the OTEL API directly, but from a UX standpoint I think koa developers should be able to call something on `ctx` to pass properties/baggage/tags to their structured logging and traces.

For example, I'm using pino the library has access to the `request` object, but not the Koa context. Similarly, the open telemetry HTTP plugin only has access to the underlying request/response, not the Koa `ctx`. I'm not sure if a `WeakMap` is required or I'm missing the OTEL-approved way of implementing this. Given that Koa already has a `ctx` it's unclear to me if it's an anti-pattern to implement things in a framework-specific way (not rely on context propagation where it's not needed)?

**Comment by vmarchaud** [comment]
> I think that folks who use tracing probably have structured logging and I'll bet you they want to share some properties between their traces and their logging.

@jmealo I'm sure they do and it would help a lot of people to have something like this available, however i believe it doesnt need to be currently on the otel repo (there is a specification on what we should store on both the core and contrib repo). 
What i would suggest is to write the helper for koa with the best UX and add it inside the registry: https://opentelemetry.io/registry/.

In a general way, instrumentations (http or koa) are only here to generate automatically metrics and traces so i would be against modifying them to help build a helper.

**Comment by dyladan** [comment]
I agree with @vmarchaud 

As a general rule, auto instrumentations should not make any changes that are observable by the user without using instrumentation-specific APIs. Adding methods on the ctx object is observable.

If you want to add these methods, I agree with @vmarchaud that you should make a koa plugin of some kind that adds these methods and add it to the registry.
