### ISSUE TITLE
Parent Context Should Be Null If It AWS XRay Trace Is Not Sampled

### ISSUE THREAD

**Issue by serkan-ozal** [open-telemetry/opentelemetry-js-contrib#2416]
### What version of OpenTelemetry are you using?
- `@opentelemetry/api`: `1.9.0`
- `@opentelemetry/core`: `1.25.1`
- `@opentelemetry/instrumentation-aws-lambda`: `0.43.0`

### What version of Node are you using?
Nodejs v22 (observed same issue with other Lambda Node.js versions too)

### What did you do?

I think there is a bug in the `opentelemetry-instrumentation-aws-lambda` package: https://github.com/open-telemetry/opentelemetry-js-contrib/blob/fa0139c048d21fabf94947f7313e44f6dbc1f79e/plugins/node/opentelemetry-instrumentation-aws-lambda/src/instrumentation.ts#L406

Regardless from `Active Tracing` is enabled or not, `_X_AMZN_TRACE_ID` is always there. But when `Active Tracing` is not enabled, its `Sampled` flag is `0`. So, when `Sampled` flag is `0`, parent context should be assumed as `null`.

However, the current implementation returns the extracted parent context from AWS XRay trace header if `Sampled` flag is `1` (this is OK), but doesn't return `null` if it is not sampled (since there is no return statement in else case, `_determineParent` call continues it execution and return parent extracted parent at the end of method even it is not sampled). I think, the correct code should be like this:
```js
      if (parent) {
        const spanContext = trace.getSpan(parent)?.spanContext();
        if (
          spanContext &&
          (spanContext.traceFlags & TraceFlags.SAMPLED) === TraceFlags.SAMPLED
        ) {
          // Trace header provided by Lambda only sampled if a sampled context was propagated from
          // an upstream cloud service such as S3, or the user is using X-Ray. In these cases, we
          // need to use it as the parent.
          return parent;
        } else {
          return null;
        }
      }
```

### What did you expect to see?
The parent id for the AWS Lambda handler span should be `null` when AWS XRay `Active Tracing` is NOT enabled.

### What did you see instead?
Parent id of the AWS Lambda handler span is set to id of the not sampled AWS XRay trace.

**Comment by pichlermarc** [comment]
@serkan-ozal yes this looks like a bug. Are you planning to work on this issue? We're also looking for new codeowners for this instrumentation as it was marked as unmaintained recently.

**Comment by serkan-ozal** [comment]
@pichlermarc sure, I can do that. Please assign to me

**Comment by serkan-ozal** [comment]
Hi @pichlermarc @dyladan, 

I have reinvestigated this issue and seems that there is no problem. Because when X-Ray trace header is not sampled, the current implementation extracts parent context and since it is not sampled, by default (default sampling strategy is `parentbased_always_on`) Lambda function span (and its child spans) is not sampled too (unless sampling strategy is `always_on`).

So, in summary, I think current behavior is correct.

**Comment by dyladan** [comment]
Can this issue be closed then?

**Comment by serkan-ozal** [comment]
I think so, but let me check with the FAAS folks too

**Comment by serkan-ozal** [comment]
Hi @dyladan, I think we are good to close this one
