### ISSUE TITLE
flaky test in ioredis

### ISSUE THREAD

**Issue by obecny** [open-telemetry/opentelemetry-js-contrib#242]
From time to time the unit tests in ioredis fails without reason
for example
```
1 failing

  1) ioredis
       #send_internal_message()
         Instrumenting query operations
           should create a child span for pubsub:

      AssertionError [ERR_ASSERTION]: 'subscribe' === 'info'
      + expected - actual

      -subscribe
      +info
```
https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-js-contrib/860/workflows/94bb90dc-514a-4931-a922-fd3403ace8b5/jobs/4072

**Comment by vmarchaud** [comment]
I believe this has been fixed by https://github.com/open-telemetry/opentelemetry-js-contrib/commit/366cbaecb776cbcfe23cab66340afe97166100d2 ?

**Comment by vmarchaud** [comment]
I'm pretty sure this was fixed by https://github.com/open-telemetry/opentelemetry-js-contrib/commit/366cbaecb776cbcfe23cab66340afe97166100d2 so i'll close this
