### ISSUE TITLE
Add support for Fastify v5

### ISSUE THREAD

**Issue by Xhale1** [open-telemetry/opentelemetry-js-contrib#2438]
Fastify v5 released recently, it'd be amazing to see support land in Open Telemetry!

- [Fastify v5 release on github](https://github.com/fastify/fastify/releases/tag/v5.0.0)
- [Documentation on breaking changes](https://fastify.dev/docs/latest/Guides/Migration-Guide-V5/)

**Comment by drewcorlin1** [comment]
The [diagnostic channel changes](https://fastify.dev/docs/latest/Guides/Migration-Guide-V5/#diagnostic-channel-support) are likely relevant for this instrumentation
