### ISSUE TITLE
Convert react-load plugin to instrumentation

### ISSUE THREAD

**Issue by obecny** [open-telemetry/opentelemetry-js-contrib#244]
- Change folder name from `opentelemetry-plugin-*` to `opentelemetry-instrumentation-*`
- Change package name from `@opentelemetry/plugin-*` to `@opentelemetry/instrumentation-*`
- Change implementation to use [InstrumentationBase](https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-instrumentation/src/platform/browser/instrumentation.ts#L23)

**Comment by obecny** [comment]
It looks like the plugin itself is not using old base plugin and it will not use the new instrumentation. The way it works there is no way to add the instrumentation class on top of that as it is a react class anyway. I'm leaving this as it is now.
@open-telemetry/javascript-approvers ^^

**Comment by Flarna** [comment]
at least the list of dependencies seems to be unneeded long:
```
  "dependencies": {
    "@opentelemetry/api": "^0.15.0",
    "@opentelemetry/context-zone": "^0.15.0",
    "@opentelemetry/core": "^0.15.0",
    "@opentelemetry/semantic-conventions": "^0.15.0",
    "@opentelemetry/tracing": "^0.15.0",
    "@opentelemetry/web": "^0.15.0",
    "shimmer": "^1.2.1"
  }
```
I think it would be good to get rid of context-zone, core, tracing and web if possible.
