### ISSUE TITLE
ci: unit tests failing due to error on mssql container startup

### ISSUE THREAD

**Issue by pichlermarc** [open-telemetry/opentelemetry-js-contrib#2445]
Currently our tests are failing as the mssql server 2017 container does not start up. 

Seems to be caused by: https://github.com/microsoft/mssql-docker/issues/899

**Comment by JamieDanielson** [comment]
I meant to share this last week, it's inconsistent. Linking as they are the same issue

- https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2436
