### ISSUE TITLE
@opentelemetry/auto-instrumentations-node 0.50.1 breaks when using Yarn PnP because of missing dependencies 

### ISSUE THREAD

**Issue by joekrill** [open-telemetry/opentelemetry-js-contrib#2472]
### What version of OpenTelemetry are you using?

0.50.1

### What version of Node are you using?

22.8.0

### What did you do?

Upgraded @opentelemetry/auto-instrumentations-node from 0.50.0 to 0.50.1

### What did you expect to see?

No errors.

### What did you see instead?

The following error:

> Error: @opentelemetry/instrumentation-pg tried to access @opentelemetry/core, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

I "fixed" that by adding the following to my `.yarnrc.yml`:

```yaml
packageExtensions:
  "@opentelemetry/instrumentation-pg@*":
    dependencies:
      "@opentelemetry/core": "*"
```

But that just caused this error: 

> Error: @opentelemetry/resource-detector-alibaba-cloud tried to access @opentelemetry/core, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

I didn't go further because I suspect fixing that would just cause similar errors from other related packages. Ultimately `@opentelemetry/instrumentation-pg`, `@opentelemetry/resource-detector-alibaba-cloud`, and (potentially) others _should_ include the dependency on ` @opentelemetry/core` in their `package.json`.

**Comment by pichlermarc** [comment]
Thanks for reporting this @joekrill 

> I didn't go further because I suspect fixing that would just cause similar errors from other related packages. Ultimately @opentelemetry/instrumentation-pg, @opentelemetry/resource-detector-alibaba-cloud, and (potentially) others should include the dependency on  @opentelemetry/core in their package.json.

Yes, you're right, these two were missing the dependencies as well - I did not find any other instances. I opened a PR #2473 to fix this.

**Comment by pichlermarc** [comment]
@joekrill a new release is out now, please let me know if that fixed the issue.
