### ISSUE TITLE
Convert pg plugin to instrumentation 

### ISSUE THREAD

**Issue by obecny** [open-telemetry/opentelemetry-js-contrib#248]
- Change folder name from `opentelemetry-plugin-*` to `opentelemetry-instrumentation-*`
- Change package name from `@opentelemetry/plugin-*` to `@opentelemetry/instrumentation-*`
- Change implementation to use [InstrumentationBase](https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts#L30)

**Comment by vmarchaud** [comment]
As linked in https://github.com/open-telemetry/opentelemetry-js-contrib/pull/321#pullrequestreview-577734674, wehn converting we could use `safeExecuteInTheMiddle` to be safer
