### ISSUE TITLE
[contrib-test-utils] stop using soon-to-be-removed `@opentelemetry/otlp-transformer` types

### ISSUE THREAD

**Issue by pichlermarc** [open-telemetry/opentelemetry-js-contrib#2565]
## Description

This issue is part of https://github.com/open-telemetry/opentelemetry-js/issues/4582

In https://github.com/open-telemetry/opentelemetry-js/issues/4583 we will remove large parts of the public API of the `@opentelemetry/otlp-transformer` package. Before this change is released we should also get rid of all usages of these soon to be removed APIs from our tests here in this repository to ensure a smooth update-process to the latest `@opentelemetry/*` packages.

**This issue is considered done when:**
- [ ] usages of all types/functions that will be removed in https://github.com/open-telemetry/opentelemetry-js/issues/4583 have been replaced in this repository
  - see PR https://github.com/open-telemetry/opentelemetry-js/pull/5200 for a proposal of what will be removed

**Comment by trentm** [comment]
Looks like the only usage is:

```
packages/opentelemetry-test-utils/src/test-fixtures.ts
27:import {
28:  IInstrumentationScope,
29:  IResource,
30:  ISpan,
31:} from '@opentelemetry/otlp-transformer';
```

This is code that I added. Hrm.

**Comment by trentm** [comment]
I'm happy to help adjust that code, but I'm not sure what the best way to do that would be.  Do you know if there are convenient exported types for the JSON serialization of the OTLP ExportTraceServiceResponse type (and eventually for the equivalent metrics and logs service response types)?

If not, I suppose the `test-fixtures.ts` test facility could re-define those types.  The object the `TestCollector` is making available is mostly just `JSON.parse(body)` where `body` is the content sent to the OTLP/json `POST /v1/traces` endpoint.

**Comment by pichlermarc** [comment]
@trentm Thanks for the offer, I assume the change would be quite mechanical so I'll look into it next week - I'll reach out if anything's unclear. 🙂 

> Do you know if there are convenient exported types for the JSON serialization of the OTLP ExportTraceServiceResponse type (and eventually for the equivalent metrics and logs service response types)?
> If not, I suppose the test-fixtures.ts test facility could re-define those types. The object the TestCollector is making available is mostly just JSON.parse(body) where body is the content sent to the OTLP/json POST /v1/traces endpoint.

hmm, there's no such thing AFAIK. I think we have to re-define them here - in any case I think we can get away with far fewer types exported from the contrib-test-utils package than what we had over at `@opentelemetry/otlp-transformer` 🙂
