### ISSUE TITLE
plugin-express: EventEmitter leak

### ISSUE THREAD

**Issue by johanneswuerbach** [open-telemetry/opentelemetry-js-contrib#258]
Please answer these questions before submitting a bug report.

### What version of OpenTelemetry are you using?

```
@opentelemetry/plugin-express: 0.11.0
```

### What version of Node are you using?

```
14.15.0
```

### What did you do?
If possible, provide a recipe for reproducing the error.

Upgrade`@opentelemetry/plugin-express` from `0.10.0` to `0.11.0` 

### What did you expect to see?

Nothing

### What did you see instead?

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [ServerResponse]. Use emitter.setMaxListeners() to increase limit
```

### Additional context

Downgrading the plugin resolved the issue for us, this was likely introduced in https://github.com/open-telemetry/opentelemetry-js-contrib/commit/ed0edf8f7fe29adb43f622600bff9c4e224e96cf

**Comment by vmarchaud** [comment]
Well it isn't a leak we need to attach to the end of the response to end the spans. I'm not sure how we could fix that warning without increasing to arbitrary value :/

**Comment by johanneswuerbach** [comment]
This https://github.com/open-telemetry/opentelemetry-js-contrib/pull/278 fixes the issue in our code base.
