### ISSUE TITLE
Express build failure

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-js-contrib#26]
Looks like the build fails on express with the latest typings https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-js-contrib/22/workflows/d59fb653-427e-453a-adf9-299a02966be7/jobs/134/steps

**Comment by dyladan** [comment]
@vmarchaud I see that you already assigned yourself. It looks like `@types/node` updated so that `assert` is a typescript assertion function now https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions

Earlier calls to assert are causing they types to be confused. Changing the calls from `assert(expr === expr2, "reason")` to `assert.strictEqual(expr, expr2, "reason")` fixes the issue.

**Comment by vmarchaud** [comment]
Ok, i'll make a PR tomorrow for that thanks for investigating !

**Comment by dyladan** [comment]
If you want I can make a PR for it now. It's causing other PRs to fail like #27
