### ISSUE TITLE
Graphql not traicing

### ISSUE THREAD

**Issue by carlitux** [open-telemetry/opentelemetry-js-contrib#260]
Please answer these questions before submitting a bug report.

### What version of OpenTelemetry are you using?
    "@opentelemetry/api": "^0.12.0",
    "@opentelemetry/base": "^0.7.0",
    "@opentelemetry/core": "^0.12.0",
    "@opentelemetry/instrumentation-graphql": "^0.11.0",
    "@opentelemetry/koa-instrumentation": "^0.11.0",
    "@opentelemetry/node": "^0.12.0",
    "@opentelemetry/plugin-dns": "^0.11.0",
    "@opentelemetry/plugin-grpc": "^0.12.0",
    "@opentelemetry/plugin-grpc-js": "^0.12.0",
    "@opentelemetry/plugin-http": "^0.12.0",
    "@opentelemetry/plugin-https": "^0.12.0",
    "@opentelemetry/plugin-pg": "^0.11.0",
    "@opentelemetry/plugin-pg-pool": "^0.11.0",
    "@opentelemetry/resources": "^0.12.0",
    "@opentelemetry/tracing": "^0.11.0",

### What version of Node are you using?
Node 12

### What did you do?
If possible, provide a recipe for reproducing the error.

index.js
```js
// @flow strict
import './tracer';

import Koa from 'koa'; // koa@2
import cors from '@koa/cors';
import jsonwebtoken from 'jsonwebtoken';
import sendgrid from '@sendgrid/mail';

import { ApolloServer } from 'apollo-server-koa';

import type { Context } from 'koa'; // koa@2

import typeDefs from './schema.gql';
import resolvers from './resolvers';
import AuthDirective from './directives/auth';

const server = new ApolloServer({
  typeDefs,
  resolvers,
  schemaDirectives: {
    auth: AuthDirective,
  },
  context: ({ ctx }) => {
    return {
      sendgrid,
      ctx,
    };
  },
});

const app = new Koa();

app.proxy = true;

app.use(cors({ credentials: true }));
server.applyMiddleware({ app, cors: false });

app.listen({ port: PORT });
```
tracer.js

```js
// @flow strict
import opentelemetry from '@opentelemetry/api';

import { GraphQLInstrumentation } from '@opentelemetry/instrumentation-graphql';
import { LogLevel } from '@opentelemetry/core';

import { NodeTracerProvider } from '@opentelemetry/node';
import { ConsoleSpanExporter, BatchSpanProcessor, SimpleSpanProcessor } from '@opentelemetry/tracing';
import { TraceExporter } from '@google-cloud/opentelemetry-cloud-trace-exporter';

import { GOOGLE_PROJECT_ID, IS_DEV, IS_TEST } from './config';

const provider = new NodeTracerProvider({
  logLevel: LogLevel.WARN,
  // plugins: {
  //   dns: { enabled: false, path: '@opentelemetry/plugin-dns' },
  //   http: { enabled: false, path: '@opentelemetry/plugin-http' },
  //   https: { enabled: false, path: '@opentelemetry/plugin-https' },
  //   pg: { enabled: false, path: '@opentelemetry/plugin-pg' },
  //   'pg-pool': { enabled: false, path: '@opentelemetry/plugin-pg-pool' },
  //   grpc: { enabled: false, path: '@opentelemetry/plugin-grpc' },
  //   'grpc-js': { enabled: false, path: '@opentelemetry/plugin-grpc-js' },
  //   koa: {
  //     enabled: false,
  //     // You may use a package name or absolute path to the file.
  //     path: '@opentelemetry/koa-instrumentation',
  //   },
  // },
});

if (!IS_TEST) {
  const exporter = new TraceExporter({
    projectId: GOOGLE_PROJECT_ID,
  });

  const graphQLInstrumentation = new GraphQLInstrumentation({
    // allowAttributes: true,
    // depth: 2,
    // mergeItems: true,
  });

  graphQLInstrumentation.setTracerProvider(provider);
  graphQLInstrumentation.enable();

  // provider.addSpanProcessor(new BatchSpanProcessor(exporter));
  provider.addSpanProcessor(new SimpleSpanProcessor(new ConsoleSpanExporter()));
}

// Initialize the OpenTelemetry APIs to use the NodeTracerProvider bindings
provider.register();

const tracer = opentelemetry.trace;

export default () => {
  return tracer;
};
```
### What did you expect to see?
Trace graphql requests

### What did you see instead?
Nothing is traced

### Additional context

@obecny here the issue hope this helps if need more context please let me know.

Thanks!

**Comment by obecny** [comment]
I won't be able to run your example, please either prepare some "complete minimum example" or push yr project to some github repo with everything, as it has more elements in it and I cannot guess what is missing and how it should look like.  There is a working example `examples/graphql`, to be able to help you somehow I would need similar thing.

**Comment by carlitux** [comment]
@obecny hi I found the issue

here the code https://github.com/carlitux/opentelemetry-koa-graphql

**master** branch does not work but **without-graphql-importer** works

I assume that these packages imports graphql before the instrumentation

"babel-plugin-graphql-tag": "^3.1.0"
"babel-plugin-import-graphql": "^2.7.0"

Thanks!

**Comment by dobesv** [comment]
@carlitux I think what's happening is that you are using babel/register and it is loading the `graphql` modules before you start the instrumentation stuff, so it isn't able to hook into the requires.  I'm not quite sure how best to get around that.

May have to start the instrumentation before loading `babel/register`.

**Comment by carlitux** [comment]
yes, these two plugins are the issues I already removed because do not have a good DX

"babel-plugin-graphql-tag": "^3.1.0"
"babel-plugin-import-graphql": "^2.7.0"

Now the tracing is working, thanks!
