### ISSUE TITLE
Alternative to deprecated `addSpanProcessor`

### ISSUE THREAD

**Issue by satazor** [open-telemetry/opentelemetry-js-contrib#2615]
### Is your feature request related to a problem? Please describe

I'm using the OpenTelemetry Node SDK to initialize OpenTelemetry because it does most of the work of setting it up. Besides the default span processor, I want to add some more span processors. I was using `addSpanProcessor` but it was deprecated here: https://github.com/open-telemetry/opentelemetry-js/pull/5134

At first, `spanProcessors` constructor option of `NodeSDK` seems designed for this use-case, but it has a shortcoming: you must specify the extra ones plus the default  `BatchSpanProcessor`. However, the `BatchSpanProcessor` requires an instance of exporter, that it's created automatically for us via environment variables. Currently, it's not feasible to create an exporter based on environment variables without duplicating code, since the code that does it is hidden via private functions, e.g.: `_buildExporterFromEnv` and `_getSpanExporter` within `BasicTracerProvider` class.

### Describe the solution you'd like to see
I would like an easy way to add span processors without having to duplicate the initialization of `BatchSpanProcessor` and the initialization of the exporter based on environment variables.

**Approach 1:**
Allow `spanProcessors` to be a function in order to append / prepend processors:

```js
new NodeSDK({
  spanProcessors: (spanProcessors) => [mySpanProcessor, ...spanProcessors],
});
```

The same logic could be applied to `logRecordProcessors `.

**Approach 2:**
Export the necessary functionality to create stuff from env, such as exposing `_buildExporterFromEnv`, `_buildPropagatorFromEnv`, etc.

### Describe alternatives you've considered

- Keep using the deprecated `addSpanProcessor` for now.
- Duplicate the code necessary to build an exporter from env to set up `BatchSpanProcessor`

**Comment by skhilliard** [comment]
@satazor I realize this is closed, but I wondered if you could offer a suggestion for this issue.  We are still using the applicationinsights package and recently updated it from version 3.7.0 to 3.9.0.  This broke the following configuration we were using:

```
import * as appinsights from 'applicationinsights';
import { trace, ProxyTracerProvider } from '@opentelemetry/api';
import { NodeTracerProvider } from '@opentelemetry/sdk-trace-node';
import { RedisSpanProcessor } from './utils/redisSpanProcessor';
if (!!process.env.APPLICATIONINSIGHTS_CONNECTION_STRING) {
    // Do this to override the cloud role instance values for application insights
    process.env.OTEL_RESOURCE_ATTRIBUTES = `service.instance.id=${process.env.HOSTNAME}`;
    appinsights.setup(process.env.APPLICATIONINSIGHTS_CONNECTION_STRING);
    // These commonProperties are displayed in customDimensions for all telemetry.
    appinsights.defaultClient.commonProperties = {
        serviceInstance: process.env.COMPUTERNAME || 'noname-instance'
    };
    appinsights.start();
    // Add custom OpenTelemetry SpanProcessor to filter out Redis PUBLISH commands for socketIO
    let provider = (trace.getTracerProvider() as ProxyTracerProvider).getDelegate() as NodeTracerProvider;
    let redisProcessor = new RedisSpanProcessor();
    provider.addSpanProcessor(redisProcessor);
}
```

Is there an alterative available for this approach?
