### ISSUE TITLE
Add instrumentation for knex.

### ISSUE THREAD

**Issue by obecny** [open-telemetry/opentelemetry-js-contrib#263]
https://www.npmjs.com/package/knex
weekly downloads 640k+

More context:
https://github.com/lightstep/otel-launcher-node/issues/2

**Comment by blumamir** [comment]
This instrumentation has been added by @Rauno56 
https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-knex
