### ISSUE TITLE
Jaeger propagator is missing the .fields() method, is incompatible with latest TextMapPropagator

### ISSUE THREAD

**Issue by jtmalinowski** [open-telemetry/opentelemetry-js-contrib#267]
As part of https://github.com/open-telemetry/opentelemetry-js/pull/1680 I need to import `JaegerHttpTracePropagator` into `@opentelemetry/node`, but then compilation fails, because `.fields()` is not implemented.

- [x] This only affects the JavaScript OpenTelemetry library
- [ ] This may affect other libraries, but I would like to get opinions here first

Also: `@opentelemetry/propagator-jaeger` will now become a dependency of `@opentelemetry/node`, so a release is needed.

**Comment by Flarna** [comment]
fixed via #268
