### ISSUE TITLE
Moving AWS X-Ray Components to JS-Contrib

### ISSUE THREAD

**Issue by KKelvinLo** [open-telemetry/opentelemetry-js-contrib#276]
**What is the Problem?**

Currently, the AWS X-Ray ID Generator and propagator components sit in the [aws-otel-js repo](https://github.com/aws-observability/aws-otel-js) instead of the [opentelemetry-js-contrib repo](https://github.com/open-telemetry/opentelemetry-js-contrib). The issue with this setup is that developers who plan on using OpenTelemetry with AWS X-Ray have to discover and locate the AWS X-Ray specific ID Generator and propagator since these components do not reside in the OpenTelemetry (CNCF) GitHub organization. 

Moreover, not having the AWS X-Ray ID generator and propagator inside the js-contrib repo is inconsistent with the structure that other language SDK repos follow for making contributed components available. The [Go](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/propagators/aws/xray), [Python](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/master/sdk-extension/opentelemetry-sdk-extension-aws/src/opentelemetry/sdk/extension/aws/trace) and [DotNet](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/master/src/OpenTelemetry.Contrib.Extensions.AWSXRay) implementations of these components all reside within their respective contrib repositories.

**Solution**

Reduce Developer Friction: I propose migrating the AWS X-Ray ID Generator and propagator components to be maintained in the [opentelemetry-js-contrib](https://github.com/open-telemetry/opentelemetry-js-contrib) repository. This will reduce developer friction greatly. As a possible solution, one could consider the existing OpenTelemetry [registry](https://opentelemetry.io/registry/). However using the existing registry does not reduce developer friction. 

Increase User Adoption: Adding vendor components such as the AWS ID-generator and propagator to js-contrib will also facilitate a better user experience for anyone using OpenTelemetry with AWS X-Ray.

@alolita, @wilguo

**Comment by vmarchaud** [comment]
Both have been upstreamed in the contrib repo, closing
