### ISSUE TITLE
PG Plugin - semantic conventions

### ISSUE THREAD

**Issue by obecny** [open-telemetry/opentelemetry-js-contrib#296]
Currently pg plugin is not using correct semantic conventions, some things are missing, some has different name etc. It should be aligned with
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/database.md

Both for database and general for example "net.peer.host" etc.

**Comment by cartermp** [comment]
I think this can be closed because https://github.com/open-telemetry/opentelemetry-js-contrib/pull/467 implements these. There's an outstanding issue around capturing the JDBC connection string but the rest appear correct specified as per the spec.
