### ISSUE TITLE
Version upgrade timeline (0.12.0 is incompatible with newer versions of opentelemetry-js and opentelemetry-collector-contrib)

### ISSUE THREAD

**Issue by ghirsch1** [open-telemetry/opentelemetry-js-contrib#305]
- [ ] This only affects the JavaScript OpenTelemetry library
- [x] This may affect other libraries, but I would like to get opinions here first

`opentelemetry-js-contrib` is up to version 0.12.0, while `opentelemetry-js` is up to 0.14.0 and `opentelemetry-collector-contrib` is up to 0.18.0.

These all seem to be incompatible with each other, which means that I need to downgrade everything to 0.12.0. Are there any plans to update `otel-js-contrib` (and `otel-js`) to be compatible with the newer versions of OpenTelemetry?

Specifically this is the error I'm seeing when I try to use later versions of the collector with 0.12.0 of `otel-js-contrib`
```
Error: 13 INTERNAL: grpc: error unmarshalling request: invalid length for SpanID
    at Object.exports.createStatusError (/Users/g/server/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/g/server/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/g/server/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/g/server/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/g/server/node_modules/grpc/src/client_interceptors.js:847:24)
    at callbackTrampoline (internal/async_hooks.js:126:14)
```

Specifically my use-case is that I am setting up tracing in a node app, and would like to use the express auto-instrumentation, hence the need to use `otel-js-contrib`, and of course `otel-js`. And I would like to use a collector to send to various destinations, hence the use of `otel-collector(-contrib)`

**Comment by dyladan** [comment]
Current version of the express plugin is compatible with `^0.14.0` of the OpenTelemetry SDK and API packages https://github.com/open-telemetry/opentelemetry-js-contrib/blob/master/plugins/node/opentelemetry-plugin-express/package.json#L47

**Comment by dyladan** [comment]
>opentelemetry-js-contrib is up to version 0.12.0, while opentelemetry-js is up to 0.14.0 and opentelemetry-collector-contrib is up to 0.18.0.

The JS contrib and core package versions may not match. This is expected. Please look at the dependencies of the plugin you are trying to use to determine SDK version compatibility for now.

The `opentelemetry-collector-contrib` version is entirely unrelated to our version.

**Comment by obecny** [comment]
the latest version of collector that was tested and is compatible is 0.16. If there was some change just in recent version you can't expect it will be working fine, use 0.16

**Comment by ghirsch1** [comment]
> Current version of the express plugin is compatible with `^0.14.0` of the OpenTelemetry SDK and API packages https://github.com/open-telemetry/opentelemetry-js-contrib/blob/master/plugins/node/opentelemetry-plugin-express/package.json#L47

Interesting, when I had everything else on 0.14.0 I was getting this type error `TypeError: Cannot read property 'replace' of undefined` but when I downgraded everything to 0.12.0 I no longer got that error. This was specifically when using the `CollectorTraceExporter` like so
```
import { SimpleSpanProcessor } from '@opentelemetry/tracing';
import { NodeTracerProvider } from '@opentelemetry/node';
import { CollectorTraceExporter } from '@opentelemetry/exporter-collector-grpc';

const provider = new NodeTracerProvider();
const exporter = new CollectorTraceExporter();
provider.addSpanProcessor(new SimpleSpanProcessor(exporter));
provider.register();
```

**Comment by dyladan** [comment]
Can you provide a minimum example which reproduces the issue?

Also, please provide the full stack trace of the error. The line you put doesn't have line numbers so it is hard to debug.

**Comment by ghirsch1** [comment]
A minimal example is [here](https://github.com/open-telemetry/opentelemetry-js/discussions/1819), but when I tried updating the various otel-js versions back to 0.14.0, I no longer get that type error. So perhaps it was an issue with a different dependency?

Additionally, it seems that 0.14.0 is compatible with the latest otel-collector-contrib version (0.18.0), at least for the purposes I'm using it for.

Apologies for the confusion!
