### ISSUE TITLE
getActiveSpan and setActiveSpan is still being used

### ISSUE THREAD

**Issue by obecny** [open-telemetry/opentelemetry-js-contrib#309]
Update to version 0.15 is missing replacing the `getActiveSpan` and `setActiveSpan`
Plugins affected:
- document load
- user interaction
- graphql
- react

**Comment by Flarna** [comment]
The change from `[gs]activeSpan` to `[gs]Span` will be part of the upcoming 0.15.0.

**Comment by Flarna** [comment]
@obecny Opened a PR for 0.15 which fixes this and other issues: #315
