### ISSUE TITLE
release followup: update examples

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-js-contrib#317]
Besides that the examples needs some more work to get them working because of the breaking changes between 0.14.0 and 0.15.0 (and maybe other oversights).

I assume you would like to release 0.13.0 plugins asap. Maybe keep them unmodified (0.12.1/0.14.0) but working for now and fix them as followup once 0.13.0 is availble at npm.

_Originally posted by @Flarna in https://github.com/open-telemetry/opentelemetry-js-contrib/pull/316#discussion_r562836815_

**Comment by Flarna** [comment]
Maybe we could include the samples somehow in the lerna project to avoid this release update ping-pong?

Clearly each of them would require some smoke test.

**Comment by dyladan** [comment]
They used to be included in the lerna project, but there were issues with the plugin system not properly patching modules due to lerna's linking.

**Comment by Rauno56** [comment]
> They used to be included in the lerna project, but there were issues with the plugin system not properly patching modules due to lerna's linking.

Just opened https://github.com/open-telemetry/opentelemetry-js-contrib/issues/422, but I guess you've already tried this, @dyladan, am I right? Do you have any details on the problems you had?
