### ISSUE TITLE
Report web vitals in Document Load instrumentation

### ISSUE THREAD

**Issue by bradfrosty** [open-telemetry/opentelemetry-js-contrib#320]
**Is your feature request related to a problem? Please describe.**
It's unrelated to a problem. This is an additional feature to add to the document load instrumentation.

**Describe the solution you'd like**
[Web Vitals](https://web.dev/vitals/) are a set of web performance metrics for analyzing user experience metrics rather than just navigation timing metrics. They are going to be used by [Google in the near future](https://developers.google.com/search/blog/2020/05/evaluating-page-experience) for evaluating SEO, meaning that many developers are optimizing for these metrics now. 

It would be useful to add these metrics into the document load plugin's existing span events.

**Describe alternatives you've considered**
It is possible for me to augment the plugin on the application side, but it feels beneficial for other OTel users to be in the library.

**Additional context**
[Here is the library](https://www.npmjs.com/package/web-vitals) for calculating these metrics on the client.

**Comment by JapuDCret** [comment]
I think this would be more appropriate as it's own plugin.

Mainly because some of the metrics make use of vendor(/chrome)-specific APIs, which require either polyfills or don't work at all.
Excerpt from the current [README.md](https://github.com/GoogleChrome/web-vitals):

> Browser support for each function is as follows:
> 
>     getCLS(): Chromium,
>     getFCP(): Chromium, Safari Technology Preview
>     getFID(): Chromium, Firefox, Safari, Internet Explorer (with the polyfill)
>     getLCP(): Chromium
>     getTTFB(): Chromium, Firefox, Safari, Internet Explorer

**Comment by obecny** [comment]
> I think this would be more appropriate as it's own plugin.
> 
> Mainly because some of the metrics make use of vendor(/chrome)-specific APIs, which require either polyfills or don't work at all.
> Excerpt from the current [README.md](https://github.com/GoogleChrome/web-vitals):
> 
> > Browser support for each function is as follows:
> > ```
> > getCLS(): Chromium,
> > getFCP(): Chromium, Safari Technology Preview
> > getFID(): Chromium, Firefox, Safari, Internet Explorer (with the polyfill)
> > getLCP(): Chromium
> > getTTFB(): Chromium, Firefox, Safari, Internet Explorer
> > ```

I cannot agree more, this is very good example, thx.

**Comment by bradfrosty** [comment]
Makes sense to me. I'll go ahead and close this issue. In the meantime, I will try to implement this in a local plugin definition, and if it proves useful I will look into proposing as an opentelemetry-js-contrib plugin. 

Thanks both!
