### ISSUE TITLE
Add AWS SDK Instrumentation

### ISSUE THREAD

**Issue by willarmiros** [open-telemetry/opentelemetry-js-contrib#323]
**Describe the solution you'd like**
I would like there to be an instrumentation package for the AWS SDK, so that requests made with AWS SDK V2 (and the recently GA'd V3) can be traced with relevant metadata recorded. 

**Describe alternatives you've considered**
I considered opening this as a plugin request, but I'm not sure what the formal definition of a plugin vs. an instrumentation library, especially with all the open issues to convert existing plugins to instrumentation packages. Regardless, I think this would be a widely-used and useful library.

**Additional context**
The [Java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/aws-sdk/aws-sdk-2.2/library/README.md) OTel repo has already implemented AWS SDK instrumentation for reference. Also somewhat relevant are some of the attributes that could be recorded laid out in this [spec PR](https://github.com/open-telemetry/opentelemetry-specification/pull/1095) (I know it's unattended but it should be picked back up and merged eventually).

**Comment by weyert** [comment]
What about Azure and GCP SDKs?

**Comment by willarmiros** [comment]
@weyert I think instrumentation for those could be tracked in separate issues. This is merely a feature request (that I may work on a PR for in the future), not meant to be an exhaustive list of cloud vendor SDKs to support.

**Comment by dyladan** [comment]
I believe azure is building opentelemetry support into their cloud sdk but I could be misremembering

**Comment by willarmiros** [comment]
It appears that Aspecto has already implemented this in their own repo: https://github.com/aspecto-io/opentelemetry-ext-js/tree/master/packages/plugin-aws-sdk

I will open an issue over there to see if they'd be interested in upstreaming their contribution.

**Comment by weyert** [comment]
Oh cool, all clear :)

**Comment by willarmiros** [comment]
https://github.com/aspecto-io/opentelemetry-ext-js/issues/169

**Comment by vmarchaud** [comment]
It has been upstreamed, closing
