### ISSUE TITLE
propagator-ot-trace published to NPM without build directory

### ISSUE THREAD

**Issue by neilfordyce** [open-telemetry/opentelemetry-js-contrib#340]
Please answer these questions before submitting a bug report.

### What version of OpenTelemetry are you using?
v0.13.0

### What version of Node are you using?
node v12.20.1
npm 6.14.10

### What did you do?
If possible, provide a recipe for reproducing the error.
```
npm install @opentelemetry/propagator-ot-trace@0.13.0
node -e "require('@opentelemetry/propagator-ot-trace');"
```

### What did you expect to see?
Nothing, exit status zero

### What did you see instead?
```
internal/modules/cjs/loader.js:303
      throw err;
      ^

Error: Cannot find module '/Users/node_modules/@opentelemetry/propagator-ot-trace/build/src/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:295:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:508:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:120:18)
    at Object.runInThisContext (vm.js:309:38)
    at Object.<anonymous> ([eval]-wrapper:10:26) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/node_modules/@opentelemetry/propagator-ot-trace/package.json',
  requestPath: '@opentelemetry/propagator-ot-trace'
```

### Additional context

You can see the error at https://runkit.com/embed/2cqmh29d8d6z

The installed package appears to be missing the build directory
```
ls node_modules/@opentelemetry/propagator-ot-trace/
LICENSE      README.md    package.json
```

**Comment by dyladan** [comment]
BAH! I'm beginning to feel our tests should be run against the final build artifact. I'm fixing this now.

**Comment by dyladan** [comment]
I'm not sure how this is possible. The package.json contains the correct entry and the build scripts should build the project before packaging just like any other package in the repository.

**Comment by neilfordyce** [comment]
Awesome.  Thanks for jumping on this so quickly 🙇‍♂️
