### ISSUE TITLE
koa: Should check _name for middleware

### ISSUE THREAD

**Issue by jonaskello** [open-telemetry/opentelemetry-js-contrib#349]
Please answer these questions before submitting a bug report.

### What version of OpenTelemetry are you using?

    "@opentelemetry/koa-instrumentation": "^0.12.1",

### What version of Node are you using?
v14.15.4

### What did you do?
If possible, provide a recipe for reproducing the error.

Create a middleware and then give it a name by setting `_name` on the created middleware (the function object) as [documented here](https://github.com/koajs/koa/blob/master/docs/guide.md#debugging-koa).

### What did you expect to see?

I expected the `_name` of the middleware to appear as the name of the middleware in the trace.

### What did you see instead?

The trace only says `middleware - ` where is usually says `middleware - {function_name}`.

**Comment by Rauno56** [comment]
Was still solved in https://github.com/open-telemetry/opentelemetry-js-contrib/pull/976 ?
