### ISSUE TITLE
Create a binary gRPC "CensusPropagator"

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-js-contrib#35]
>is there an argument for having a binary “CensusPropagator” (working off the grpc-trace-bin header) in the contrib  repo

That sounds like a great idea 👍

_Originally posted by @dyladan in https://github.com/open-telemetry/opentelemetry-js/issues/1071#issuecomment-630453807_

**Comment by nkelly75** [comment]
Please assign to me @dyladan

**Comment by dyladan** [comment]
Since this is also your first contribution, I'll also assign myself and help you through any part of the process if you need.

**Comment by nkelly75** [comment]
@dyladan I assume this can be closed now that the propagator has been merged and published.

FYI, I'm working on an example to show when/how the propagator can be used. Should we open a new issue to associate with the associated PR? (Planning to add the example under [examples](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/master/examples)

**Comment by dyladan** [comment]
no need to make an issue for it. you can if you want though
