### ISSUE TITLE
mssql Plugin request

### ISSUE THREAD

**Issue by mnadeem** [open-telemetry/opentelemetry-js-contrib#353]
**Is your plugin request related to a problem? Please describe.**

Instrumentation for mssql https://www.npmjs.com/package/mssql

**Is it applicable for Node or Browser or both**

Node

**Do you expect this plugin to be commonly used**
Yes, weekly download for mssql (https://www.npmjs.com/package/mssql) is 155,886

**What version of plugin are you interested in using**
Versions: 6.3.1

**Additional context**

- **Is there a reference you could point for the well-defined lifecycle methods**

**Comment by blumamir** [comment]
If you access mssqs with ORM library `typeorm` or `sequelize`, you can use [the following instrumentation libraries](https://github.com/aspecto-io/opentelemetry-ext-js) to get instrumentation on the ORM level.

**Comment by mnadeem** [comment]
Thanks for bringing this up @blumamir 

There are lot of applications which directly uses https://www.npmjs.com/package/mssql , including many applications in my Company, and this library has huge weekly download 155,886 , it would be difficult to rewrite all the applications.

**Comment by blumamir** [comment]
Hi @mnadeem ,
Yeah I understand. 
Just wanted to let you know in case it works for you.
Hope someone will write the mssql instrumentation

**Comment by mnadeem** [comment]
Perfect that would be great

**Comment by mnadeem** [comment]
**Created initial version** https://github.com/mnadeem/opentelemetry-instrumentation-mssql/tree/plugin This would be helpful to take it forward

**Comment by mnadeem** [comment]
I was able to make the instrumentation version work as well, can be found below

https://github.com/mnadeem/opentelemetry-instrumentation-mssql/tree/instrumentation

**Comment by vvydier** [comment]
is this complete or does it need work?

**Comment by dyladan** [comment]
You may want to add this to the registry on opentelemetry.io as well if you haven't already

**Comment by dyladan** [comment]
yeah of course it's documented here: https://github.com/open-telemetry/opentelemetry.io#adding-a-project-to-the-opentelemetry-registry

**Comment by mnadeem** [comment]
Created pull request https://github.com/open-telemetry/opentelemetry.io/pull/510
