### ISSUE TITLE
@opentelemetry/api is incompatible with 0.13.1 express plugin

### ISSUE THREAD

**Issue by previousdeveloper** [open-telemetry/opentelemetry-js-contrib#356]
Please answer these questions before submitting a bug report.

### What version of OpenTelemetry are you using?

0.17.0

### What version of Node are you using?
v14.5.0

### What did you do?
If possible, provide a recipe for reproducing the error.

PluginLoader#load: could not load plugin @opentelemetry/plugin-express of module express. Error: this._logger.debug is not a function

**Comment by Flarna** [comment]
That's known/expected, see [compatibility matrix](https://github.com/open-telemetry/opentelemetry-js#compatibility-matrix).

There is a WIP PR (https://github.com/open-telemetry/opentelemetry-js-contrib/pull/337) but it requires some work till it can land.
