### ISSUE TITLE
GraphQL: Support version 14.* in instrumentation-graphql

### ISSUE THREAD

**Issue by jorgelbg** [open-telemetry/opentelemetry-js-contrib#360]
While instrumenting an Apollo GraphQL server that is currently using v14 of the graphql library we found that `@opentelemetry/instrumentation-graphql` library didn't work. The issue is that the current version of the instrumentation library only supports graphql v15.

We ran a small test by changing the dependency in the graphql example in https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/examples/graphql to a local version of the `@opentelemetry/instrumentation-graphql` library after adding `14.*` to the supported versions:

```js
const supportedVersions = ['14.*', '15.*'];
```

and also downgraded the `graphql` dependency in the example to `^14`, which ended up installing version `14.7.0`. We got a trace from before and after the change:

before:
![image](https://user-images.githubusercontent.com/1291846/109187136-e4f29b00-7791-11eb-8198-4bbfbb7a6767.png)

after:
![image](https://user-images.githubusercontent.com/1291846/109187163-ecb23f80-7791-11eb-9ad4-809456b15a3f.png)

The same number of spans/traces were collected in both cases.

Changing the dependency itself of `@opentelemetry/instrumentation-graphql` to v14 could be a bit more complicated because `instrumentation-graphql` depends on `graphql/jsutils/Maybe`, which has changed paths since https://github.com/graphql/graphql-js/pull/2621 was merged.

In our limited testing, the extension points where the instrumentation-graphql library hooks itself into seem to be the same between version 14 and 15 of `graphql`.

- [x] This only affects the JavaScript OpenTelemetry library
- [ ] This may affect other libraries, but I would like to get opinions here first

**Comment by obecny** [comment]
@jorgelbg thx a lot for testing and findings, I will double check with `graphql/jsutils/Maybe` to see if that influence anything and if something needs to be changed because of that. Will do some testing and if all is fine we can change the supported versions.
