### ISSUE TITLE
Copy post-query custom attributes hook from pg plugin to pg instrumentation

### ISSUE THREAD

**Issue by obecny** [open-telemetry/opentelemetry-js-contrib#363]
this is original PR
https://github.com/open-telemetry/opentelemetry-js-contrib/pull/321
implement the same logic in PgInstrumentation

**Comment by Alon-Katz** [comment]
Hi @obecny, Is this still relevant and available for me to do?

**Comment by dyladan** [comment]
Yes

**Comment by obecny** [comment]
@Alon-Katz yeap
