### ISSUE TITLE
@opentelemetry/instrumentation-document-load is not published

### ISSUE THREAD

**Issue by Hongbo-Miao** [open-telemetry/opentelemetry-js-contrib#368]
Currently [@opentelemetry/instrumentation-document-load](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/web/opentelemetry-instrumentation-document-load) is not published to NPM.
It would be great to publish it. Thanks!

**Comment by obecny** [comment]
It was released with ver 0.14.
Please check
https://www.npmjs.com/package/@opentelemetry/instrumentation-document-load

**Comment by Hongbo-Miao** [comment]
Thanks @obecny . Works great!
