### ISSUE TITLE
@opentelemetry/plugin-express support for OpenTelemetry 0.16.0 and 0.17.0

### ISSUE THREAD

**Issue by mnadeem** [open-telemetry/opentelemetry-js-contrib#370]
Please answer these questions before submitting a bug report.

### What version of OpenTelemetry are you using?
0.16.0 and 0.17.0

### What version of Node are you using?
14.15.5

### What did you do?
If possible, provide a recipe for reproducing the error.

clone https://github.com/mnadeem/nodejs-opentelemetry-tempo/tree/v0.16.0

`docker-compose up --build`  ==> does not work

clone https://github.com/mnadeem/nodejs-opentelemetry-tempo/tree/v0.15.0

`docker-compose up --build`   ==> works like a charm

### What did you expect to see?

@opentelemetry/plugin-express supports 0.16.0 and 0.17.0

### What did you see instead?

@opentelemetry/plugin-express does not support  0.16.0 and 0.17.0

### Additional context

With  0.15.0

![image](https://user-images.githubusercontent.com/476145/109387099-48610200-7925-11eb-8228-7a9b0cf970e4.png)

0.16.0 and 0.17.0

![image](https://user-images.githubusercontent.com/476145/109387098-44cd7b00-7925-11eb-8e64-b18f58bd0720.png)

**Comment by Flarna** [comment]
Unfortunatelly you can't mix any version of plugins hosted in this repo with any version of core.
see [compatiblilty Matrix](https://github.com/open-telemetry/opentelemetry-js#compatibility-matrix) for details.

Update for modules here is in progress, see #362
