### ISSUE TITLE
Express example doesn't work as expected

### ISSUE THREAD

**Issue by bokjo** [open-telemetry/opentelemetry-js-contrib#376]
### What version of OpenTelemetry are you using?
v0.18.0

### What version of Node are you using?
v14.15.4 (npm v6.14.10)

### What did you do?
If possible, provide a recipe for reproducing the error.
1. Try to run the express example from => https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/examples/express

Running the zipkin:client npm script thrown an error! 

```sh
npm run zipkin:client

> express-example@0.13.1 zipkin:client /Users/bojanche/private/opentelemetry-js-contrib/examples/express
> cross-env EXPORTER=zipkin node ./client.js
(node:35519) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ERROR' of undefined
    at /Users/bojanche/private/opentelemetry-js-contrib/examples/express/client.js:19:45
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:35519) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35519) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Easy fix tho `StatusCode` should be `SpanStatusCode`
https://github.com/open-telemetry/opentelemetry-js-contrib/blob/e3c1359649afaeda35fda35f460c5cc91326b9e4/examples/express/client.js#L19 

However, after fixing the issue above I'm still not getting the desired outcome with trace and propper express spans...

### What did you expect to see?
Something like the example expected images for Express
https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/examples/express/images/zipkin.jpg

### What did you see instead?
Only one `client.makeRequest` span
![image](https://user-images.githubusercontent.com/3706379/109942277-540d4980-7cd4-11eb-88a2-5790402b9351.png)

### Additional context

Willing to help and create PR during the weekend for the `SpanStatusCode` issue and the example partially not working... however will need some guidance for the Express plugin and why it is not working properly (maybe some changes introduced with 0.17.0 or 0.18.0?)

**Comment by Flarna** [comment]
Unfortunately examples on current master here are in an inconsistent state.

The instrumentations/plugins here have been updated to use 0.18.0 just recently (see #371) but there was no release made yet therefore samples have not yet been updated.

OTel API is close to go GA and therefore quite a lot is moving. I assume the modules hosted here are published soon and then examples can be updated.

**Comment by kudlatyamroth** [comment]
@Flarna i see that there is recent release 0.13.1 of plugins
but plugins like pluign-pg plugin-pg-pool doesnt have new release as they have 0.13.1 since 23 days (as of today 05.03.21)

**Comment by Flarna** [comment]
#371 to move to 0.18.0 landed 3 days ago. I assume a release will be made soon.

As usual some helping hands could speed things up ;o)

**Comment by bokjo** [comment]
> #371 to move to 0.18.0 landed 3 days ago. I assume a release will be made soon.
> 
> As usual some helping hands could speed things up ;o)

Hello @Flarna,

Happy Monday!

As fairly new to OTel can you point me to some places where a helping hand is needed?

I'm willing to help with code and non-code-related stuff, aligning the examples with 0.18.x maybe?

I've read the `Contributing Guide`,  is there a rule for the Issues marked with `up-for-grabs` and `good first issue` to what to pick first, older-newer or it is up to you?

Kind Regards,
Bojanche S.

**Comment by Flarna** [comment]
I would say it's completely up to you.

Maybe @open-telemetry/javascript-maintainers  can chime in here as well as they have a better overview.
