### ISSUE TITLE
fix(instrumentation): use `path.normalize` for internal file patch to support windows

### ISSUE THREAD

**Issue by vmarchaud** [open-telemetry/opentelemetry-js-contrib#382]
Instrumentation to fix:
- mongodb
- graphql

**Comment by obecny** [comment]
@vmarchaud I think it would be better to fix this inside instrumentation in core package, so we will fix it for any other instrumentations (core, contrib, 3rd party etc.)

**Comment by vmarchaud** [comment]
Yeah i agree but @Flarna [mentionned](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/354#discussion_r586234015) that we could make the fix right now to avoid waiting for another core release so i opened an issue to do that. WDYT ?

**Comment by obecny** [comment]
both will work, I will prepare fix in core, and meanwhile the fix can be done here too

**Comment by Flarna** [comment]
The corresponding issue for core is https://github.com/open-telemetry/opentelemetry-js/issues/1990
If it is planned to release e.g. 0.18.1 core with this fixed soon then I see no need for doing this also here.
