### ISSUE TITLE
Publish net instrumentation

### ISSUE THREAD

**Issue by seemk** [open-telemetry/opentelemetry-js-contrib#400]
[net](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-net) module is now part of master, but it is not yet published to npm. How are the contrib packages published usually? Is there a release/publish cycle for them?

Thanks :slightly_smiling_face:

**Comment by dyladan** [comment]
Actually #366 was merged 6 days ago which makes this process much smoother. I'll try to cut a release today.

**Comment by seemk** [comment]
> Actually #366 was merged 6 days ago which makes this process much smoother. I'll try to cut a release today.

Thanks!

**Comment by seemk** [comment]
Reopening as a reminder

**Comment by seemk** [comment]
Thanks for publishing it! :+1:
