### ISSUE TITLE
Opentelemetry logging Js 

### ISSUE THREAD

**Issue by scumpah** [open-telemetry/opentelemetry-js-contrib#404]
Very simple use case. I wanna send logs from node-app to collector and export those logs to loki. I managed to integrate collector with loki exporter using this -> https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/lokiexporter/example

So now I am trying to read logs from oltp as receiver through http endpoint instead of fluent forward/fluentd and export them to loki. After going through docs I found out that otel format is required, couldn't find any references on how to send logs from node-app so thought I might ask here.

There are npm packages for tracing and metrics, can the same be used for sending logs to otlp and will they work the same to export logs to loki? 

I checked  https://opentelemetry.io/docs/js/  and there's no mention/references on sending logs. Thoughts on what to do here?

![image](https://user-images.githubusercontent.com/8604722/113272442-d3a72c00-9305-11eb-9b49-d8391e72f232.png)

**Comment by davispuh** [comment]
I'm also looking for JavaScript logging implementation for OpenTelemetry. Has there been any work done, any PRs, repository? I'm willing to contribute with implementation.

**Comment by dyladan** [comment]
There are a couple log appenders in the contrib repo. At least pino, bunyan, and winston.

[opentelemetry-instrumentation-bunyan](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-bunyan)
[opentelemetry-instrumentation-pino](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-pino)
[opentelemetry-instrumentation-winston](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-winston)

There has not yet been any work started on a log exporter but the latest protos in the otlp-transformation package contains the stable log protocol

**Comment by davispuh** [comment]
All of those look like for tracing not logging. I'm talking about logger with `.info(), .warn()` which would send to OpenTelemetry Collector `/v1/logs`

**Comment by vmarchaud** [comment]
>  I'm talking about logger with .info(), .warn() which would send to OpenTelemetry Collector /v1/logs

As daniel said, no work was started for logs in JS. If you want to move forwad this, you'll need to create an issue to state what need to be done in order to have an logs api package and sdk package (like what have been done with https://github.com/open-telemetry/opentelemetry-js/issues/2574) and start implementing them in the core repo (https://github.com/open-telemetry/opentelemetry-js)
