### ISSUE TITLE
Opentelemetry logging js

### ISSUE THREAD

**Issue by scumpah** [open-telemetry/opentelemetry-js-contrib#405]
Very simple use case. I wanna send logs from node-app to collector and export those logs to loki. I managed to integrate collector with loki exporter using this -> https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/lokiexporter/example

So now I am trying to read logs from oltp as receiver through http endpoint instead of fluent forward/fluentd and export them to loki. After going through docs I found out that otel log format is required, couldn't find any references on how to send logs from node-app in the official documentation

There are npm packages for tracing and metrics, can the same be used for sending logs to otlp and will they work the same to export logs to loki? Thoughts on what to do here?

P.S I checked https://opentelemetry.io/docs/js/ and there's no mention/references on sending logs. 

![image](https://user-images.githubusercontent.com/8604722/113275617-27ffdb00-9309-11eb-82af-4cb272e100ee.png)

**Comment by vmarchaud** [comment]
Hey, we don't have anything implemented for logs yet so you won't be able to do that
