### ISSUE TITLE
Support for fastify

### ISSUE THREAD

**Issue by PatrickHeneise** [open-telemetry/opentelemetry-js-contrib#41]
**Is your plugin request related to a problem? Please describe.**

We'd like to use the gcloud trace agent in our software which is runs on [fastify](https://www.npmjs.com/package/fastify). Fastify uses a similar API to express, I was hoping this would work out of the box, but unfortunately that's not the case.

**Is it applicable for Node or Browser or both**

- Node

**Additional context**

Original issue: https://github.com/googleapis/cloud-trace-nodejs/issues/1167#event-3388034298

**Comment by mayurkale22** [comment]
Thanks for opening this. I marked it as **up-for-grabs** for now. If you are feeling motivated, maybe you can attempt to write solution and open a PR.

**Comment by carolinee21** [comment]
@PatrickHeneise Hi - I was wondering if there have been any updates on this. Thanks!

**Comment by PatrickHeneise** [comment]
Haven't had a chance yet. @mayurkale22 how would I start on this? And, if I add fastify, how does it make it's way into Google Trace?

**Comment by dyladan** [comment]
@PatrickHeneise I would take a look at some of the node plugins in this repo to get an idea how they work, but generally we use `shimmer` to wrap functions exported by the module we want to instrument. The plugin uses the SDK to generate spans and other instrumentation data, and the SDK handles exporting it to a backend using the configured tracing exporter. Google cloud trace has a tracing exporter that you would use for that.

**Comment by vmarchaud** [comment]
For the plugin, you could refer to the implementation done by datadog here: https://github.com/DataDog/dd-trace-js/tree/master/packages/datadog-plugin-fastify/src
Note that the Tracer API is way different but at least you know which functions to patch :)

**Comment by adamegyed** [comment]
It looks like someone has already written a library connecting fastify to OpenTelemetry here: https://github.com/mkinoshi/fastify-opentelemetry
However, this does not conform to the spec of an OpenTelemetry plugin, rather, it is a fastify plugin that interacts with OpenTelemetry. There might still be value in adapting this to the form of an OT plugin.

**Comment by dyladan** [comment]
Both approaches likely have value, but it may be better to spend time elsewhere if there is already a good way to get spans from fastify.

**Comment by HW13** [comment]
We recently published a fastify plugin that utilizes `@opentelemetry/api` to trace requests. It's lightweight, but provides the tools to add more granular/custom tracing implementations if desired. Cheers 😄  -> https://github.com/autotelic/fastify-opentelemetry

**Comment by dyladan** [comment]
@HW13 You may want to think about listing it on the [registry](https://opentelemetry.io/registry/)

**Comment by HW13** [comment]
Thanks for the suggestion @dyladan 😎  - just opened a PR -> https://github.com/open-telemetry/opentelemetry.io/pull/241

**Comment by vmarchaud** [comment]
@dyladan Do we want to keep this issue open since there are multiple solutions available ?

**Comment by Rauno56** [comment]
Support for `fastify` is in the contrib now in addition to the one mentioned above: https://github.com/autotelic/fastify-opentelemetry
