### ISSUE TITLE
Capturing instrumented module version

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-js-contrib#411]
- [x] This only affects the JavaScript OpenTelemetry library
- [ ] This may affect other libraries, but I would like to get opinions here first

Hello
I want to open a small discussion regarding capturing instrumented library version, so in case of issues, the data is available for debugging and investigation.
Our current convention for this in [opentelemetry-ext-js](https://github.com/aspecto-io/opentelemetry-ext-js) is to add `moduleVersionAttributeName` option to instrumentation config, and if this option is set, a span attribute is automatically added by the plugin for each span. The key of this span attribute is the string supplied via the `moduleVersionAttributeName` config option, and the value is the instrumented module version.

Usage example:
```js
export const amqplibInstrumentationConfig: AmqplibInstrumentationConfig = {
    moduleVersionAttributeName: 'instrumentedmodule.version',
};
// will add to each span an attribute {'instrumentedmodule.version': '1.2.3'} (for example)
```

Since we are also using the `ioredis` instrumentation from this repo, we would like to create PR and add this feature to it as well. Before I invest time in a PR, I thought to discuss about how to implement it.

Another option would be to pass the version as a function parameter to an external instrumentation hook, and let the user add the attribute as he like, but that would require another hook to be added to `ioredis` instrumentation (and possibly other instrumentations in the future).
Something like this:
```js
const ioredisInstrumentationConfig: IORedisInstrumentationConfig = {
    requestHook: (span: Span, instrumentedModuleVersion: string) => {
        span.setAttribute('instrumentedmodule.version', instrumentedModuleVersion);
    }
}
```

**Comment by dyladan** [comment]
Is the instrumented module version part of the specification for semantic conventions?

**Comment by Flarna** [comment]
Another option would be to put loaded modules incl. version into resource or similar. As loading happens dynamically after startup this would require a second set of mutable/extendable resource.
As far as I know there is some ongoing discussion somewhere in spec to allow this.

**Comment by blumamir** [comment]
> Another option would be to put loaded modules incl. version into resource or similar

That would be amazing. But since resource is global, and there are usually more than one instrumentation libraries installed, then it might need to go somewhere else.
Also, it is possible for instrumentation library to patch multiple npm packages, each with its own version, so doing it automatically isn't always possible, but in most cases, it will work I believe.

**Comment by blumamir** [comment]
> Is the instrumented module version part of the specification for semantic conventions?

As far as I can tell, it currently isn't
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#instrumentation-libraries

**Comment by blumamir** [comment]
@dyladan @Flarna Since the specification does not support it yet, do you have any objection to adding the `moduleVersionAttributeName` config option to ioredis instrumentation?

**Comment by vmarchaud** [comment]
The module version is already known by the loader, i added it into the `onPatch` and `onUnpatch` hooks (https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts#L93). I think a common way for all node instrumentation to have this information would be handy but we need to think about handling instrumentation patching multiple modules (grpc, http for ex).

**Comment by blumamir** [comment]
> The module version is already known by the loader, I added it into the onPatch and onUnpatch hooks

Yes, this is what we use internally in the instrumentations to set the attribute value to the version.

**Comment by Flarna** [comment]
I'm fine with `moduleVersionAttributeName`. But the question which version of which module to use for multi module patchinb instrumentations remains.

**Comment by blumamir** [comment]
> I'm fine with `moduleVersionAttributeName`. But the question which version of which module to use for multi module patching instrumentations remains.

I haven't yet seen a real-world example where it's an issue. But theoretically it can happen, and then we would need to use common sense I suppose to choose the most appropriate one from the possible options.

**Comment by Flarna** [comment]
For example the postgres instrumentation patches module pg (version 7.x and 8.x) and pg-pool (versions 2.x and 3.x).
Which version should be set on a span created by this instrumentation?

**Comment by blumamir** [comment]
> For example the postgres instrumentation patches module pg (version 7.x and 8.x) and pg-pool (versions 2.x and 3.x).
> Which version should be set on a span created by this instrumentation?

I would use the version of `pg`, as it's the package that is used directly by the user (if I understand correctly, `pg-pool` is internal). But I agree it might be confusing and not well-defined in these cases.

**Comment by blumamir** [comment]
> As far as I know there is some ongoing discussion somewhere in spec to allow this.

@Flarna , do you remember maybe how to find this?

**Comment by Flarna** [comment]
I think it was https://github.com/open-telemetry/opentelemetry-specification/issues/1298

**Comment by obecny** [comment]
I think we could implement something like this on instrumentation package that will be collecting the information about all patched packages automatically and then exposing this either via method or adding such information to span directly ?

**Comment by blumamir** [comment]
> I think we could implement something like this on instrumentation package that will be collecting the information about all patched packages automatically and then exposing this either via method or adding such information to span directly ?

this is the preferred option by us, but I think it might take time to be available.

**Comment by dyladan** [comment]
Definitely that is the preferred technical solution, but I think this is something all SIGs will eventually run into. Has anyone engaged with the spec on this? The most recent comment from the linked spec issue is from February. I know I sound like a broken record and I am really not trying to be a constant obstruction, but features like this should have spec behind them.
