### ISSUE TITLE
"host-metrics" should collect system (os) cpu metrics to comply with spec

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-js-contrib#420]
## Edit:
This issue is for modifying the ["@opentelemetry/host-metrics" instrumentation](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/packages/opentelemetry-host-metrics) to use os metrics instead of process metrics, according to the specification for [Semantic Conventions for System Metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/system-metrics.md#semantic-conventions-for-system-metrics).

### What version of OpenTelemetry are you using?
v0.18.2

### What version of Node are you using?
v12.18.3

### What did you do?
I was playing with the `host-metrics` package and the metrics it produces.
I may be missing something, but it looks like cpu metrics are for the current process (`process.cpuUsage()` - "returns the user and system CPU time usage of the current process"), while the memory metrics are total os values (`os.totalmem()` - "Returns the total amount of system memory in bytes as an integer.").

Is it intentional? from [the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/1afab39e5658f807315abf2f3256809293bfd421/specification/metrics/semantic_conventions/system-metrics.md#systemcpu---processor-metrics) it looks like they should both be system metrics.

**Comment by obecny** [comment]
Nice spotted. When I implemented this for first time it wasn't yet spec'd, it had then few iterations and from what I see it should be probably using the `os.cpu()` instead of `process.cpuUsage()`.

**Comment by blumamir** [comment]
> Nice spotted. When I implemented this for first time it wasn't yet spec'd, it had then few iterations and from what I see it should be probably using the `os.cpu()` instead of `process.cpuUsage()`.

@obecny thanks for looking into it, edited the issue. 

Maybe we can add "up-for-grabs" and "good-first-issue" labels?

**Comment by svrnm** [comment]
I provided a PR for this, please let me know if this looks good or needs some changes.
