### ISSUE TITLE
customized naming for user interaction spans

### ISSUE THREAD

**Issue by ribrdb** [open-telemetry/opentelemetry-js-contrib#430]
### Is your feature request related to a problem? Please describe
The user interaction instrumentation attaches the element xpath to the span. When the element doesn't have an id, this results in something like "//html/body/div/div/div/div/div/div/div/div/button". 
This can be hard to understand.

### Describe the solution you'd like to see
Allow some other attribute than id to be used in the span. For example, opencensus-web supported 
`<button data-ocweb-id="myid">`

### Describe alternatives you've considered
You can attach an id to an element, but this is not always practical. Or the id may already be used in a way that is not helpful for humans reading the traces. (Say, randomly generated to ensure uniqueness).

**Comment by obecny** [comment]
maybe having the interceptor (hook) in config and then allowing simply add whatever you need by passing a span and element should fulfil all different cases and user needs. Similar we have for many other instrumentations. I would rather avoid adding some predefined attributes as this will always be not enough for certain user.

**Comment by ribrdb** [comment]
That sounds like a good solution.
