### ISSUE TITLE
Get current span within express handler

### ISSUE THREAD

**Issue by Pondidum** [open-telemetry/opentelemetry-js-contrib#435]
- [x] This only affects the JavaScript OpenTelemetry library
- [ ] This may affect other libraries, but I would like to get opinions here first

I've followed the instructions for setting up an express app with instrumentation from the repo: https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-express

I have a handler like this, and want to add some extra attributes to the handler span, but I can't for the life of me figure out how to get at the current span.  I expected this to work, but the `span` is always `undefined`:

```ts
router.post("/", async (req, res) => {
  const span = getSpan(context.active());
  span?.setAttribute("some_prop", "something I care about");
})
```

Is this possible?
I can't find any documentation on how at least, and don't mind adding some once it's figured out.

Thanks

**Comment by dyladan** [comment]
Please post all versions of your opentelemetry dependencies as well as setup code

**Comment by Pondidum** [comment]
This is the basic example:
```ts
import {
  SimpleSpanProcessor,
  ConsoleSpanExporter,
} from "@opentelemetry/tracing";
import { ExpressInstrumentation } from "@opentelemetry/instrumentation-express";
import { HttpInstrumentation } from "@opentelemetry/instrumentation-http";
import { NodeTracerProvider } from "@opentelemetry/node";
import { registerInstrumentations } from "@opentelemetry/instrumentation";
import { trace, context, getSpan } from "@opentelemetry/api";

const provider = new NodeTracerProvider();

registerInstrumentations({
  tracerProvider: provider,
  instrumentations: [new HttpInstrumentation(), new ExpressInstrumentation()],
});

provider.addSpanProcessor(new SimpleSpanProcessor(new ConsoleSpanExporter()));
provider.register();
trace.setGlobalTracerProvider(provider);

import express from "express";
const app = express();
app.post("/", async (req, res) => {
  const span = getSpan(context.active());
  span?.setAttribute("some_prop", "something I care about");
});
```
and dependencies:
```json
"dependencies": {
    "@opentelemetry/api": "^1.0.0-rc.0",
    "@opentelemetry/exporter-zipkin": "^0.18.2",
    "@opentelemetry/instrumentation": "^0.18.2",
    "@opentelemetry/instrumentation-express": "^0.15.0",
    "@opentelemetry/instrumentation-http": "^0.18.2",
    "@opentelemetry/node": "^0.18.2",
    "express": "^4.17.1"
}
```

**Comment by Flarna** [comment]
Could you please try with API 0.18.1 and express 0.14.0 as these would match better according to https://github.com/open-telemetry/opentelemetry-js#compatibility-matrix

**Comment by Pondidum** [comment]
Yes, that worked - thanks so much!

**Comment by lbrackenAternity** [comment]
FYI, with API v1.x and Core/Contrib v0.24.x, this has changed from...

```
const span = getSpan(context.active());
```
to 
```
const span = trace.getSpan(context.active());
```

per https://github.com/open-telemetry/opentelemetry-js-api/pull/47/files
