### ISSUE TITLE
use route as root span name in hapi instrumentation 

### ISSUE THREAD

**Issue by klaemo** [open-telemetry/opentelemetry-js-contrib#453]
### Is your feature request related to a problem? Please describe

Currently the root span name is set by the http instrumentation to a generic name like `HTTP GET`. Additionally, `http.route` of the root span is set to the actual http pathname and not the route. So, something like `http.route: /events/123` instead of `http.route: /events/{eventId}`.

This makes traces hard to identify (in Honeycomb in this case):
<img width="470" alt="Bildschirmfoto 2021-04-26 um 14 44 19" src="https://user-images.githubusercontent.com/778624/116084597-40f87380-a69e-11eb-8470-143007bd0c45.png">

The actual hapi route is buried somewhat deep in the trace:
<img width="284" alt="Bildschirmfoto 2021-04-26 um 14 43 02" src="https://user-images.githubusercontent.com/778624/116084692-553c7080-a69e-11eb-8765-fd7326c75ce4.png">

### Describe the solution you'd like to see

Similarly to the way it's done for Koa (#327) and Express (#176, #273) the root span name should be renamed once the route has been determined and `http.route` should be set to the actual `route` at that point.

### Describe alternatives you've considered

None

Thank you for your work on OpenTelemetry and all these instrumentations :)

**Comment by CptSchnitz** [comment]
hi,
I would like to work on this.

**Comment by obecny** [comment]
> hi,
> I would like to work on this.

assigned, thx
