### ISSUE TITLE
Express instrumentation depends on our SDK

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-js-contrib#464]
The express instrumentation has a type `ExpressInstrumentationSpan` which extends `Span` with `name: string`, which is not exposed by the API type. This means it can only be used with SDKs that provide a public accessor for name.

At the very least it should be documented. I would prefer to remove the type.

**Comment by vmarchaud** [comment]
Almost all http framework have the same logic to be able to retrieve the name of the parent (e.g: [restify](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-restify/src/types.ts#L53))

**Comment by dyladan** [comment]
then they all have the same bug. Forgive me for not knowing but what do they need the parent span name for? This might be something worth adding to the spec.

**Comment by vmarchaud** [comment]
They generally want to have a better span name for the http request (e.g: `HTTP GET /user/:id` instead of `HTTP GET`), i think this would deserve more thinking because the use case is quite tricky. We could remove it though but i think this is worth to keep to end users

**Comment by dyladan** [comment]
at least we should make the `name` property optional like `name?: string` or even `name: unknown` so if it is used with a different sdk that doesn't provide name then we aren't going to break.

**Comment by Flarna** [comment]
I think it's not nice that one instrumentation tinkers with spans of another.
If someone is doing a custom span between HTTP instrumenation and express this breaks.

Such functionality is better done in backend by combining information of spans in a trace.

**Comment by dyladan** [comment]
Lots of users use open source tools like jaeger and zipkin with no such backend processing available unfortunately

**Comment by dyladan** [comment]
each express span has the name for the particular middleware, not the whole request, that are children of the http server span. The http server span doesn't have enough information to know the route name so express calls `updateName` on the parent span to fix it.

@vmarchaud why does the instrumentation have to read the span name to update it though? Is the "bad" name generated by the `http` instrumentation used in some way to generate the "good" name?

**Comment by vmarchaud** [comment]
> why does the instrumentation have to read the span name to update it though? Is the "bad" name generated by the http instrumentation used in some way to generate the "good" name?

Because we can't be sure the parent span is the http one (depend on the instrumentations used), so we generally check that it contains `HTTP` which the default prefix for http spans.

> Such functionality is better done in backend by combining information of spans in a trace.

The spec actually talk about "good" span name ([here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#span)), this might come down to the DX we want to provide. I do agree with you that from a technical standpoint that this is a bad system though

**Comment by Flarna** [comment]
Somehow it looks like the name detection part of express/hapi/... instrumenation is sort of an plugin/extension of the http instrumenation.

I have no good idea how to link them together in an easy understandable way.
What could work is that http instrumenation adds it's span via a well documented context key on context. express could access this http span even some other span is inbetween. There would be no need anymore to check the current name for http detection.

**Comment by Rauno56** [comment]
HTTP spans are currently treated specially and if we'd like to make HTTP span names "good", there's no way around it - among the web framework instrumentations, most(express, hapi, koa) currently require a parent span to work at all, expecting(but unable to check as @Flarna pointed out) it to be one spanning the whole request.

**Comment by vmarchaud** [comment]
> What could work is that http instrumenation adds it's span via a well documented context key on context. express could access this http span even some other span is inbetween

i agree that is the most sane way to do it

**Comment by dyladan** [comment]
>Because we can't be sure the parent span is the http one (depend on the instrumentations used), so we generally check that it contains HTTP which the default prefix for http spans.

This seems quite error prone. Name is something that could easily change in the future and I wasn't aware of this contract between the http instrumentation and other instrumentations.

**Comment by vmarchaud** [comment]
Discussed at the SIG, here are the next steps:
- Create a new context key to set HTTP span inside instrumentation pkg so it can be re-used by all http framework instrumentation
- Open a spec issue to discuss if this need to be specified since other SDKs might have the need for this too

**Comment by blumamir** [comment]
there is also [this](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-instrumentation-http/src/utils.ts#L479) mechanism in http instrumentation which is an undocumented contract between HTTP and express instrumentation.
Might be worth addressing it as well.

```js
export const getIncomingRequestAttributesOnResponse = (
  request: IncomingMessage & { __ot_middlewares?: string[] },
  response: ServerResponse & { socket: Socket }
): SpanAttributes => {
  // take socket from the request,
  // since it may be detached from the response object in keep-alive mode
  const { socket } = request;
  const { statusCode, statusMessage } = response;
  const { localAddress, localPort, remoteAddress, remotePort } = socket;
  const { __ot_middlewares } = (request as unknown) as {
    [key: string]: unknown;
  };
  const route = Array.isArray(__ot_middlewares)
    ? __ot_middlewares
        .filter(path => path !== '/')
        .map(path => {
          return path[0] === '/' ? path : '/' + path;
        })
        .join('')
    : undefined;

  const attributes: SpanAttributes = {
    [SemanticAttributes.NET_HOST_IP]: localAddress,
    [SemanticAttributes.NET_HOST_PORT]: localPort,
    [SemanticAttributes.NET_PEER_IP]: remoteAddress,
    [SemanticAttributes.NET_PEER_PORT]: remotePort,
    [SemanticAttributes.HTTP_STATUS_CODE]: statusCode,
    [AttributeNames.HTTP_STATUS_TEXT]: (statusMessage || '').toUpperCase(),
  };

  if (route !== undefined) {
    attributes[SemanticAttributes.HTTP_ROUTE] = route;
  }
  return attributes;
};
```
