### ISSUE TITLE
PostgreSQL instrumentation uses wrong attributes

### ISSUE THREAD

**Issue by pauldraper** [open-telemetry/opentelemetry-js-contrib#465]
https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-pg/src/enums.ts

Instead of `net.peer.host` (the semantic convention) the instrumentation uses `peer.host`. Etc.

**Comment by svrnm** [comment]
I can take this.

**Comment by pauldraper** [comment]
While you're at it, probably makes sense to use SemanticAttributes in @opentelemetry/semantic-conventions

**Comment by svrnm** [comment]
@pauldraper the PR #467 should cover that, please double check if I missed anything!:-)

**Comment by obecny** [comment]
@svrnm can I assign this to you then ?
