### ISSUE TITLE
Why is PostgreSQL peer.address a JDBC string?

### ISSUE THREAD

**Issue by pauldraper** [open-telemetry/opentelemetry-js-contrib#473]
```
jdbc:postgresql://host:5432/database
```

Why? Do tools normally use JDBC URLs as an address?

All tools I know of, including psql, use the postgresql (or postgres) scheme.

```
psql postgresql://host:5432/database
```

**Comment by vmarchaud** [comment]
I believe the spec require to use a common (eg: jdbc) format: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#connection-level-attributes-for-specific-technologies

**Comment by pauldraper** [comment]
In my reading, I don't see anything about peer.address (or net.peer.address).

**Comment by pauldraper** [comment]
Still have this question.

I don't see anything about peer.address in the standard.

**Comment by dyladan** [comment]
It appears it is just drastically outdated. The spec at the time of writing the postgres instrumentation was this: https://github.com/open-telemetry/opentelemetry-specification/blob/c8109895a989480028b282fa796ed87ad1421b8a/specification/data-database.md which specified the JDBC substring.

The recent spec is quite different and requires:

- `db.system` - `postgresql `
- One of `net.peer.name` OR `net.peer.ip` - hostname or ip respectively
- `net.peer.port` only if using nonstandard port
- `net.transport` recommended in general, required only if using in-process - tcp or inproc

`db.connection_string` is not required but seems to be the replacement for the jdbc string.

This most likely also affects the mysql and mysql2 instrumentations

**Comment by dyladan** [comment]
Created #781 to address this
