### ISSUE TITLE
Improve GraphQL instrumentation readme adding more information about package

### ISSUE THREAD

**Issue by eternalmatt** [open-telemetry/opentelemetry-js-contrib#485]
### What version of OpenTelemetry are you using?
0.18.0

### What version of Node are you using?
12

### What did you do?

Visit https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-graphql

### What did you expect to see?
Explanation into the optional parameters.  When to use them, what is their purpose?
What is this plugin instrumenting exactly?  Will it place spans at the request/response level, or does it go into my resolvers?
Is this compatible with Apollo?  @nestjs/graphql? As there are my GraphQL implementations (GraphQL itself is a spec), which one does this instrument?

### What did you see instead?
Brief comment on "optional params"

### Additional context

I arrived at this page after visiting https://www.npmjs.com/package/@opentelemetry/instrumentation-graphql

**Comment by obecny** [comment]
graphql plugin instruments `graphql` directly not the apollo or any other package. It has been tested with apollo and express - 2 popular packages. So it should work with any package that wraps the graphql, yes it instruments resolvers too. You can check examples here https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/examples/graphql
