### ISSUE TITLE
Merge browser extension into this repository?

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry-js-contrib#490]
- [x] This only affects the JavaScript OpenTelemetry library
- [ ] This may affect other libraries, but I would like to get opinions here first

To understand the existing capabilities of [opentelemetry-web](https://www.npmjs.com/package/@opentelemetry/web) and it's plugins better, and to identify potential gaps or additional features I created a chrome extension that can instrument arbitrary websites:

https://github.com/svrnm/opentelemetry-browser-extension/

I tried to use as many rules (linter, tsconfig, ...) from this repo as possible, with the idea in mind to give it back. So the question I have is, if having this browser extension merged as contribution into opentelemetry-js-contrib something people find valuable?

**Comment by dyladan** [comment]
I don't see a reason it couldn't be included here. It's actually quite an interesting idea.

**Comment by svrnm** [comment]
superseded by #498
