### ISSUE TITLE
auto-instrumentations-node docs

### ISSUE THREAD

**Issue by naseemkullah** [open-telemetry/opentelemetry-js-contrib#497]
While the package name + sample code are quite descriptive in themselves, adding a brief description of what it does, how it works + use case(s) to the README would be that much better

https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/metapackages/auto-instrumentations-node/README.md

**Comment by CptSchnitz** [comment]
Hi,
I would like to work on this :)

**Comment by obecny** [comment]
@CptSchnitz thx, I have assigned this to you :)

**Comment by CptSchnitz** [comment]
this issue can be closed
