### ISSUE TITLE
instrumentation-pg loses its scope 

### ISSUE THREAD

**Issue by thestrayed** [open-telemetry/opentelemetry-js-contrib#507]
### What version of OpenTelemetry are you using?

```json
 "dependencies": {
    "@opentelemetry/api": "^1.0.0-rc.0",
    "@opentelemetry/exporter-zipkin": "^0.19.0",
    "@opentelemetry/instrumentation": "^0.19.0",
    "@opentelemetry/instrumentation-express": "^0.15.0",
    "@opentelemetry/instrumentation-http": "^0.19.0",
    "@opentelemetry/instrumentation-pg": "^0.16.0",
    "@opentelemetry/node": "^0.19.0",
    "@opentelemetry/tracing": "^0.19.0"
  },
```

### What version of Node are you using?

```txt
v12.22.1
```

### What did you do?

Calling request from 1st server to 2nd server then to query data from DB (postgres)

### What did you expect to see?

Expect to see a single span from 1st server to 2nd server then to PG

### What did you see instead?

PG trace is in different span altogether

<img width="828" alt="Screen Shot 2021-05-30 at 10 21 49 PM" src="https://user-images.githubusercontent.com/16605812/120109861-6f81d680-c195-11eb-8c9b-39ff15aab8d4.png">

### Additional context

I have example repository to reproduce [this](https://github.com/thestrayed/birdy)

**Comment by obecny** [comment]
instrumentation-express ver 0.15 is not compatible with 0.19 of core and 0.16 of contrib, please use ver. 016

**Comment by leandro-lugaresi** [comment]
I have the same problem, it's probably a problem with the async_hooks for the node version.
We got the tracing working updating the node version to 14

**Comment by thestrayed** [comment]
> instrumentation-express ver 0.15 is not compatible with 0.19 of core and 0.16 of contrib, please use ver. 016

Let me try this today and report back. I will also give it a try on node version.

**Comment by thestrayed** [comment]
Updating `instrumentation-express` to ver `0.15` does not resolve the issue, however updating node version from v12 ~ to `v14.17.0` does

![Screen Shot 2021-06-01 at 5 45 26 PM](https://user-images.githubusercontent.com/16605812/120310978-2b134980-c301-11eb-84e5-3cb4d3fd9091.png)
