### ISSUE TITLE
why user-interaction just support click eventType

### ISSUE THREAD

**Issue by jinphic** [open-telemetry/opentelemetry-js-contrib#509]
I glance over  the source code and find out this tracer just support eventType 'click' . On the mobile h5, we use 'tap' or 'touch' sometimes. What can we do if we want to use this project to collection other eventType.

```ts
  protected _allowEventType(eventType: string): boolean {
    return eventType === 'click';
  }
```

**Comment by kkruk-sumo** [comment]
I believe the `click` event is not desktop-specific and also works on mobile. Supporting other events by default may lead to generating unnecessary single-span traces as primarily mousedown(up)/touchstart(end) are used for visual effects or custom drag and drop implementations.
Of course this option could be configurable.
Do you have any examples or real use-case scenarios when instrumenting other events is helpful?

**Comment by jinphic** [comment]
> I believe the `click` event is not desktop-specific and also works on mobile. Supporting other events by default may lead to generating unnecessary single-span traces as primarily mousedown(up)/touchstart(end) are used for visual effects or custom drag and drop implementations.
> Of course this option could be configurable.
> Do you have any examples or real use-case scenarios when instrumenting other events is helpful?

If we have a old system and need to use this tracer to collect some production info, and the system developer has use `onTap` . We have to change thousand of codes to refactor the implements. We want a new argument for custom eventType, instead of  just writing `eventType === 'click'`. it's more friendly, thanks

**Comment by kkruk-sumo** [comment]
Where does the `onTap` come from? There is no "tap" event in DOM. Do you use some framework? In which version?
