### ISSUE TITLE
Add Resolver field name to graphql instrumentation span name

### ISSUE THREAD

**Issue by dragonfriend0013** [open-telemetry/opentelemetry-js-contrib#534]
### Is your feature request related to a problem? Please describe
No issue

### Describe the solution you'd like to see
When looking at the spans using instrumentation-graphql, it would be helpful to see the field name in the span name when viewing, instead of having to drill down into attributes.  Today it just shows `graphql.resolve`.  If we could add the field name to this, it would be much more helpful.  Ex:  `graphql.resolve (field1)`

### Describe alternatives you've considered
None

**Comment by spencerwilson** [comment]
Would the information conveyed by the current name ("this span encompasses a resolver executing") be preserved in any other span? Or do you imagine that if one wanted to, say, select all resolver spans, they would do so via something like "spans whose name starts with 'graphql.resolver'"?
