### ISSUE TITLE
AWS Lambda Instrumentation should use presence of context, not env var, to parent to Lambda

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-js-contrib#565]
Currently, AWS Lambda instrumentation checks whether a Lambda-provided parent is sampled or not to determine whether to instead extract from headers.

https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-aws-lambda/src/instrumentation.ts#L322

Actually Lambda always populates the environment variable, and it will be just a trace ID when env var propagation should be ignored. If we don't make sure to ignore this case, then it is never possible for the Lambda to start a sampled trace. This should be tweaked to not overwrite the `parent` variable

https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-aws-lambda/src/instrumentation.ts#L312

**Comment by NathanielRN** [comment]
I was wondering if this is still an issue? I can see that the current implementation only overwrites the `parent` value _if_ the `_X_AMZN_TRACE_ID` is `;Sampled=1`. This should only be set if we have "active tracing" enabled on the AWS Lambda configuration, and is `;Sampled=0` if this is turned off (based on my tests on a _Python_ Lambda).

https://github.com/open-telemetry/opentelemetry-js-contrib/blob/e5a65c67ec63e9235f7ddf82b2cd75a5a926f7c8/plugins/node/opentelemetry-instrumentation-aws-lambda/src/instrumentation.ts#L352-L355

There are also methods to `disableAwsContextPropagation` and provide a helper to extract a custom context from the Lambda event. So I would say the behavior is what we expect according to the [OTel specifications for Determining a parents in Lambda Instrumentation](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/instrumentation/aws-lambda.md#determining-the-parent-of-a-span)? Please let me know what you think!
