### ISSUE TITLE
route span is missing when route throws an error in hapi instrumentation

### ISSUE THREAD

**Issue by CptSchnitz** [open-telemetry/opentelemetry-js-contrib#572]
### What version of OpenTelemetry are you using?
api - 1.0.1
core - 0.23.0
contrib - 0.23.0

### What version of Node are you using?
v12.20.0

### What did you do?

I created a simple hapi server based on the example that only throws errors.
I made a few requests to it's endpoints, one throws a normal error, and the other using boom.
the server can be found here:
https://github.com/CptSchnitz/instrumented-hapi-with-errors

### What did you expect to see?
I expected to see the route span with its status set on error.

### What did you see instead?
the route span is missing.
![image](https://user-images.githubusercontent.com/12687466/125503822-30ca193e-c7bc-4fc1-8efd-0989e73f51ef.png)

### Additional context

I would happy to work on fixing this once you confirm its an actual bug.

**Comment by CptSchnitz** [comment]
@vmarchaud the pull request you linked wont solve this, it only handles the route name.
I can add error handling to the it, or open a new PR.

**Comment by vmarchaud** [comment]
@CptSchnitz Sorry i though i was on the other issue ahah, thanks for the heads up

**Comment by CptSchnitz** [comment]
I started working on the issue and I got a question about implementation.
Hapi uses errors thrown by [Boom](https://github.com/hapijs/boom) to set status codes.
Do I need to set the span status to error (according to the HTTP semantic convention) and record the exception, or if the error is created by boom I shouldn't record the exception?

**Comment by vmarchaud** [comment]
> Do I need to set the span status to error (according to the HTTP semantic convention) and record the exception, or if the error is created by boom I shouldn't record the exception?

I guess if you can thats better
