### ISSUE TITLE
feat(mongodb-instrumentation): support mongodb v4

### ISSUE THREAD

**Issue by vmarchaud** [open-telemetry/opentelemetry-js-contrib#577]
The new mongodb driver (that has been rewritten from scratch) has been released, you can see the PR of renovate which obviously fails here: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/575.
I expect people will start to request to support it in the near term so opening an issue for this

**Comment by CptSchnitz** [comment]
Is the plan to support both v4 and v3 or just upgrade? (v3 will get bug fixes for a year).

**Comment by vmarchaud** [comment]
I think we should support both of them since v3 is still massively used

**Comment by osherv** [comment]
Hey guys :)
I can do that!
pls assign this to me.
@vmarchaud @CptSchnitz
