### ISSUE TITLE
Instrumentation PG are not in the line

### ISSUE THREAD

**Issue by thanaratjaruenying** [open-telemetry/opentelemetry-js-contrib#579]
### What version of OpenTelemetry are you using?
```
"@opentelemetry/api": "1.0.1",
"@opentelemetry/core": "0.23.0",
"@opentelemetry/exporter-zipkin": "0.23.0",
"@opentelemetry/instrumentation": "0.23.0",
"@opentelemetry/instrumentation-express": "0.23.0",
"@opentelemetry/instrumentation-grpc": "0.23.0",
"@opentelemetry/instrumentation-http": "0.23.0",
"@opentelemetry/instrumentation-ioredis": "0.23.0",
"@opentelemetry/instrumentation-pg": "0.23.0",
"@opentelemetry/node": "0.23.0",
"@opentelemetry/resources": "0.23.0",
"@opentelemetry/semantic-conventions": "0.23.0",
"@opentelemetry/tracing": "0.23.0",

"objection": "2.2.4",
"pg": "7.7.1",
"knex": "0.21.10",
```

### What version of Node are you using?
12.22

### What did you do?
controller subscribe on specific to pic to get data from DB

### What did you expect to see?
I expect to see PG.query are in the scope of subscribe handler

### What did you see instead?
pg.query is not in the scope

### Additional context
I have tried to upgrade to node 14 and also update `knex` `pg` `objection` to the latest one but the issue still occurs

**Comment by thanaratjaruenying** [comment]
![Uploading Screen Shot 2564-07-19 at 18.18.57.png…]()

**Comment by Flarna** [comment]
I runnable sample would be helpful.
Can you reproduce the problem only with knex or also by using pg without knex?
