### ISSUE TITLE
Redis&IORedis instrumentations not following spec for net.peer.ip

### ISSUE THREAD

**Issue by aspectom** [open-telemetry/opentelemetry-js-contrib#581]
Hey,

I noticed that the current implementations of redis & ioredis instrumentations does not follow the spec completely for NET_PEER_IP.

The [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#connection-level-attributes) mentions NET_PEER_IP should be an IP address.
![image](https://user-images.githubusercontent.com/75930313/126293482-0bc128e1-5613-47bc-8479-fafe6a3fde7b.png)

However, the instrumentation code looks like this: 
ioredis
![image](https://user-images.githubusercontent.com/75930313/126293826-0bbe8499-ab31-4e86-8354-7a7b009ca986.png)

Redis
![image](https://user-images.githubusercontent.com/75930313/126293911-1c9a3026-7e04-4d12-9e3d-b9710dc797cb.png)

I think we should consider fixing it & move this value to db.connection_string. 
Would love to know your thoughts.

Thanks,
Tom
- [x] This only affects the JavaScript OpenTelemetry library

**Comment by aspectom** [comment]
I'd love to make a PR for this but also I have a few more concerns I'd like to hear more opinions on.

As mentioned, the spec says it should be an IP.
Often times, we have a hostname, not an IP - like localhost, x.google.com etc.
What should we do with NET_PEER_IP in this case? not add it at all ? add hostname in NET_PEER_IP even though that's not what the spec says?
Should we validate it's a valid IP address ?

Thanks,
Tom

**Comment by vmarchaud** [comment]
I believe you must only set `NET_PEER_IP` if we know the actual IPv4/v6 address, otherwise if we have a hostname we can use `net.peer.name` instead

**Comment by aspectom** [comment]
Sorry for disappearing, didn't have time to get to this. I'm unassigning myself for now, if I'll have a chance to do before someone else takes it i'll reassign.

**Comment by Just-Sieb** [comment]
Looks like this was already fixed in #913. This should be able to be closed now.
