### ISSUE TITLE
Publish test-utils as a package on NPM

### ISSUE THREAD

**Issue by jonchurch** [open-telemetry/opentelemetry-js-contrib#595]
Per discussion at the JS SIG meeting on 7/28/2021, it was decided to publish the [test-utils](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/packages/opentelemetry-test-utils) as a package to improve workflow of contributors.

Needs a readme, ~and to be moved out into it's own folder~ (should it be moved into the opentelemetry-js repo?)

@Rauno56 volunteered to work on this. 

Refs: https://github.com/open-telemetry/opentelemetry-js/discussions/2085

**Comment by Rauno56** [comment]
Thanks for doing the legwork of documenting it!

It's already in its own package [here](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/packages/opentelemetry-test-utils), but it just happens not to be published.

**Comment by Rauno56** [comment]
Pumped into this one again, @dyladan. Please publish `@opentelemetry/test-utils`.
