### ISSUE TITLE
ioredis: SetConfig not supported

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-js-contrib#624]
### What version of OpenTelemetry are you using?
v0.24.0

### What version of Node are you using?
12

### What did you do?
tried to call `setConfig` function from the `InstrumentationAbstract` api on an instance of the ioredis instrumentation to update the config.

### What did you expect to see?
instrumentation to use the new config on future operations

### What did you see instead?
previous config is in use

### Additional context
ioredis instrumentation is [using the `_config` object during patching](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-ioredis/src/instrumentation.ts#L88) as closure param instead of reading the current attribute from `this` everytime it should be used. Thus instrumentation will not be affected when `setConfig` is called.

**Comment by mustafain117** [comment]
I noticed that the `IORedisInstrumentation` does not override the base `setConfig` function. Using an instance of ioredis instrumentation, `setConfig` can only be called with parameters of the type `InstrumentationConfig` instead of type `IORedisInstrumentationConfig` to update the config. Does the scope of this issue include accepting `IORedisInstrumentationConfig` parameter type in setConfig?

**Comment by blumamir** [comment]
> I noticed that the `IORedisInstrumentation` does not override the base `setConfig` function. Using an instance of ioredis instrumentation, `setConfig` can only be called with parameters of the type `InstrumentationConfig` instead of type `IORedisInstrumentationConfig` to update the config. Does the scope of this issue include accepting `IORedisInstrumentationConfig` parameter type in setConfig?

I support fixing this too as part of this issue. That is: override the `setConfig` in the instrumentation with the correct type.
Would you like to create a PR for that?

**Comment by Flarna** [comment]
`IORedisInstrumentationConfig` extends `InstrumentationConfig` therefore it should fit into the base class `setConfig()`.

Actually it's `getConfig` which is more problematic as it returns only an `InstrumentationConfig` instead `IORedisInstrumentationConfig`.
But this is already tracked: https://github.com/open-telemetry/opentelemetry-js/issues/2258
Maybe also relevant/related: https://github.com/open-telemetry/opentelemetry-js/issues/2257
