### ISSUE TITLE
Filter pg query spans

### ISSUE THREAD

**Issue by yang** [open-telemetry/opentelemetry-js-contrib#645]
I would like to be able to filter pg queries only to slow queries. Is this already possible to do?

I saw a related issue here: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/499

Thanks!

**Comment by Flarna** [comment]
I think it would be needed to implement a SpanProcessor and/or SpanExporter which does this instead of using that ones from SDK.

**Comment by dyladan** [comment]
I agree I think a custom spanprocessor is likely the best place for this.

**Comment by obecny** [comment]
You could simply extend the standard batch processor and then add your logic into export function where you can check for those things and either export it or ignore it.

**Comment by yang** [comment]
Thanks - will dig into this and close for now!
