### ISSUE TITLE
aws-lambda instrumentation v0.25.0 depends on v0.24.0 OTEL core/trace packages

### ISSUE THREAD

**Issue by nozik** [open-telemetry/opentelemetry-js-contrib#672]
### What version of OpenTelemetry are you using?

aws-lambda instrumentation v0.25.0

### What version of Node are you using?

v15.12

### Please provide the code you used to setup the OpenTelemetry SDK

N/A

### What did you do?

I've imported the latest aws-lambda instrumentation into my code and noticed this inconsistency, see [here](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/1b7ae9c3c249cd1166b610e2a4c95c01fec93d1c/plugins/node/opentelemetry-instrumentation-aws-lambda/package.json#L49).

### What did you expect to see?

I expected the instrumentation to use the 0.25.0 OTEL packages, i.e. `sdk-trace-base` / `sdk-trace-node`.

### What did you see instead?

The old 0.24.0 versions of `core` and `node` packages.

### Additional context

The instrumentation [relies](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/1b7ae9c3c249cd1166b610e2a4c95c01fec93d1c/plugins/node/opentelemetry-instrumentation-aws-lambda/src/instrumentation.ts#L270) on `BasicTracerProvider` from the older packages, causing a mismatch.

**Comment by dyladan** [comment]
This is fixed
