### ISSUE TITLE
Can't find https://www.npmjs.com/package/@opentelemetry/exporter-otlp-grpc

### ISSUE THREAD

**Issue by emmansun** [open-telemetry/opentelemetry-js-contrib#673]
Can't install @opentelemetry/exporter-otlp-grpc  from https://www.npmjs.com/package/@opentelemetry/exporter-otlp-grpc

**Comment by vmarchaud** [comment]
We just renamed it and waiting to release it, you can use https://npmjs.com/package/@opentelemetry/exporter-collector-grpc in the mean time.
