### ISSUE TITLE
Express instrumentation request body

### ISSUE THREAD

**Issue by gregz07** [open-telemetry/opentelemetry-js-contrib#693]
Using @opentelemetry/instrumentation-express any reason I can't the request body in the logs ? Since I'm including the middleware for body parsing.

**Comment by gregz07** [comment]
Thanks for the quick feedback. Can you give me any pointers on how to achieve it then ? Examples on span creation maybe.

**Comment by Flarna** [comment]
@gregz07 Could you describe a bit more what you want to archive? Creating a span and putting the request body into an attribute doesn't sound right to me. spans should describe operations, not duplicate data. span attributes are usually limited in size but a request body can have several mega bytes.

Regarding span creation see e.g.
https://github.com/open-telemetry/opentelemetry-js-api/blob/main/docs/tracing.md
https://github.com/open-telemetry/opentelemetry-js-api/blob/main/docs/context.md
or the various samples like https://github.com/open-telemetry/opentelemetry-js/blob/main/examples/basic-tracer-node/

**Comment by gregz07** [comment]
Yes of course, my requirements are to log the request/response body of HttpRequests. I have done that with a simple piece of middleware inside Express. But I have to start using open telemetry, but I can't seem to find examples on how to include this information inside the given logs.

**Comment by gregz07** [comment]
But since it offers other important information as the status code of the requests, is it so out-of-context to ask for the body data ? Why is the line drawn there ? 

Again, thank you for your input.

**Comment by gregz07** [comment]
Hum ok I see where you are coming from now. Thanks for ur insight, I appreciate it.
