### ISSUE TITLE
Proposal: Separate release pipeline for core and contrib repositories.

### ISSUE THREAD

**Issue by mayurkale22** [open-telemetry/opentelemetry-js-contrib#7]
Benefits:
- Independent release pipeline: Possible to release contrib modules without waiting on core modules.
- Easy to manage versions: No need to worry about version sync
- Once API/SDK is stable will have less releases in core compared to contrib.

In order to avoid version confusions, we can include "**contrib**" name in all the packages under contrib repository like `@opentelemetry/contrib-plugin-mysql`. 

It might look something like this:
```
"dependencies": {
    "@opentelemetry/api,": "0.7.0",
    "@opentelemetry/core,": "0.7.0",
    "@opentelemetry/tracing,": "0.7.0",
    "@opentelemetry/metrics": "0.7.0",
    ....
    "@opentelemetry/contrib-plugin-mysql": "0.6.2",
    "@opentelemetry/contrib-plugin-redis": "0.6.2",
    "@opentelemetry/contrib-propagator-jaeger": "0.6.2",
  }
```

This is just a rough idea, please add your suggestions.

**Comment by dyladan** [comment]
I like this, but we need to be explicit somewhere about which SDK/API version is required for a specific plugin. Perhaps in the README. Adding contrib to package names is a good idea in my opinion.

**Comment by dyladan** [comment]
@open-telemetry/javascript-approvers

**Comment by vmarchaud** [comment]
Agree for both the naming and the split of versionning. @dyladan I think we would need to implement something in the code as no everyone read closely the readme and most likely just install the plugins. Could we add a error log if the API version doesn't match ?

**Comment by mayurkale22** [comment]
> we need to be explicit somewhere about which SDK/API version is required for a specific plugin. 

Hmmm.. Should we do this for the latest release version or keep a history of the plugin versions?

**Comment by dyladan** [comment]
We could try to completely decouple the plugins from the SDK, and have them only depend on the API. Then the API version code in the other PR would take care of this for us. Not sure how feasible this is.

**Comment by vmarchaud** [comment]
@dyladan I agree, however we could have problem if a plugin use non-api method (ex: `withAsync`) :/

**Comment by dyladan** [comment]
The plugin could always just do `if (tracer instanceof otel.Tracer)` to flag features which require our sdk.

**Comment by vmarchaud** [comment]
I'll close this since we've done that since few months
