### ISSUE TITLE
resource-detector-aws times out while acquiring token

### ISSUE THREAD

**Issue by nwalters512** [open-telemetry/opentelemetry-js-contrib#708]
### What version of OpenTelemetry are you using?

* `@opentelemetry/sdk-node@0.26.0`
* `@opentelemetry/resource-detector-aws@0.24.0`

### What version of Node are you using?

v14.15.4

### What did you do?

I'm using the Node SDK with automatic resource detection.

### What did you expect to see?

I expect to see my spans tagged with my AWS EC2 information (`cloud.*`, etc.).

### What did you see instead?

I do not see any resource attributes for my AWS EC2 information.

### Additional context

I added the following to my code to see additional debugging information:

```js
const { diag, DiagConsoleLogger, DiagLogLevel } = require('@opentelemetry/api');
diag.setLogger(new DiagConsoleLogger(), DiagLogLevel.DEBUG);
```

This results in logs like the following:

```
AwsEc2Detector failed: EC2 metadata api request timed out
```

I modified the code around [here](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/f5851e72512117dbce571a42930a90c560dbf63d/detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsEc2Detector.ts#L122) to include additional information:

```diff
  private async _fetchString(options: http.RequestOptions): Promise<string> {
    return new Promise((resolve, reject) => {
+     const start = Date.now();
      const timeoutId = setTimeout(() => {
        req.abort();
        reject(new Error('EC2 metadata api request timed out.'));
-     }, 1000);
+     }, 10000);

      const req = http.request(options, res => {
+       console.log(`connection took ${Date.now() - start}ms to initialize`);
        clearTimeout(timeoutId);
        const { statusCode } = res;
        res.setEncoding('utf8');
        let rawData = '';
        res.on('data', chunk => (rawData += chunk));
        res.on('end', () => {
          if (statusCode && statusCode >= 200 && statusCode < 300) {
            try {
              resolve(rawData);
            } catch (e) {
              reject(e);
            }
          } else {
            reject(
              new Error('Failed to load page, status code: ' + statusCode)
            );
          }
        });
      });
      req.on('error', err => {
        clearTimeout(timeoutId);
        reject(err);
      });
      req.end();
    });
  }
```

With this, I now see logs like the following:

```
connection took 1924ms to initialize
connection took 9ms to initialize
connection took 2ms to initialize
```

So, it takes an oddly long amount of time to initialize the first connection to the metadata service to acquire a token, which exceeds the 1000ms timeout that's hardcoded for requests. This renders the detector unable to get any information, which means none of my spans have the correct attributes set.

I'm not sure what the right solution is here. Either we can increase the default timeout to something like 5000ms, or else make the timeout configurable. I'd prefer the former, as that would allow me to avoid adding additional config to the SDK, but it also feels like that might end up with a game of whack-a-mole if other folks encounter requests that take even longer.

**Comment by willarmiros** [comment]
@vmarchaud I assume the resource detectors operate asynchronously right? If so, I'm fine with increasing the timeout to 5000ms, but obviously would be more hesitant if it's blocking.

**Comment by vmarchaud** [comment]
@willarmiros By the spec they need to be async (some sync exists but are from community), increasing the timeout will fix the specific issue however i'm not sure why the first request is slower than subsequent one ?

**Comment by dyladan** [comment]
There is actually no spec saying they should be sync or async. We have implemented our async and honestly I regret it a little bit, but its too late now.

**Comment by willarmiros** [comment]
Hmm that is interesting. I would say then increasing the timeout would make sense if it's async and there are no plans to change that.

@vmarchaud The first request is to get a token from the EC2 instance metadata service, and subsequent requests use that token to actually retrieve the metadata. I don't know too much about how that works under the hood, but it does make sense for there to be a discrepancy between the first and subsequent requests.

**Comment by dyladan** [comment]
There are no plans to change the async nature. Now that the trace SDK is at 1.0 I think it would be difficult to change the resource detector interface. I might consider adding a `SyncResourceDetector` interface or something though in order to simplify startup (many use-cases don't make use of async resources and it complicates startup).
