### ISSUE TITLE
React Example project is not working

### ISSUE THREAD

**Issue by chethan-devopsnow** [open-telemetry/opentelemetry-js-contrib#717]
### What version of OpenTelemetry are you using?
"@opentelemetry/context-zone": "^0.25.0",
"@opentelemetry/core": "^0.25.0",
"@opentelemetry/exporter-collector": "^0.25.0",
"@opentelemetry/plugin-react-load": "^0.23.0",
"@opentelemetry/sdk-trace-base": "^0.25.0",
"@opentelemetry/sdk-trace-web": "^0.25.0",
"react": "^16.13.1",
"react-dom": "^16.13.1",
"react-router-dom": "^5.2.0",
"react-scripts": "^3.4.1",
"reactstrap": "^8.5.1"

### What version of Node are you using?
v16.10.0

### What did you do?

I tried to clone the repo (https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/examples/react-load/react)  and followed the instructions in the README and got the website running however I do not see any auto-instrumentation happening. 

### What did you expect to see?
I am a beginner and new to this concept. All that I am trying to check is to get the open-telemetry auto-instrumentation working on my NextJs project, finding it very hard.. Requesting a help !

Also tried to install the following package on my nextjs project, even that breaks. (https://www.npmjs.com/package/@opentelemetry/plugin-react-load)

![image](https://user-images.githubusercontent.com/91748832/139302672-ffe17356-34a4-45fa-a9bf-a4e90230b95f.png)

Thanks in advance.

**Comment by chethan-devopsnow** [comment]
anybody any luck ?

**Comment by weyert** [comment]
I only have been using Opentelemtry tracing on the server-side only with Next.js

**Comment by smhmayboudi** [comment]
I have the same issue. just follow this sample with `nextjs`

https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/examples/react-load/react/
