### ISSUE TITLE
Express instrumentation in Lambda

### ISSUE THREAD

**Issue by knvpk** [open-telemetry/opentelemetry-js-contrib#729]
### Is your feature request related to a problem? Please describe

My setup includes deploying the express js in lambda and using this package https://github.com/dougmoscrop/serverless-http/, it is working fine,,, but some how the express instrumentation is not patching the express app if it is not using the "app.listen" method because it uses the package i mentioned. Is there a way to patch express while using the serverless-http.

### Describe the solution you'd like to see

I didn't find any solution yet.

### Describe alternatives you've considered

There are no alternatives as well.

### Additional context

I did checked by keeping opentelemetry DiagLogLevel to ALL, i didn't find the log that indicates patched for express.

**Comment by knvpk** [comment]
ping @dyladan

**Comment by dyladan** [comment]
I'm not familiar enough with serverless-http to say if this is simple or not. Most likely you would have to create an instrumentation for that package, which may be simple or may be a lot of work.
