### ISSUE TITLE
Define more concise operation names for http operations

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-js-contrib#730]
Instrumentation (for Node specifically) is generating spans for http operations with names that are too generic, such as `HTTP GET` or `HTTP DELETE`.

Based [on the Specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#span), more specific names should be used, such as `get_account`.

Sounds like a relatively small change, overall (once the proper span name is defined).

**Comment by carlosalberto** [comment]
Maybe this is something that @obecny can do once we come to an agreement?

**Comment by dyladan** [comment]
This is not really possible to do with just the HTTP instrumentation. If you are using a supported framework like express or fastify, the instrumentation changes the name of the HTTP span to something more meaningful already.
