### ISSUE TITLE
Nestjs core instruction instrumentation with Jaeger exporter

### ISSUE THREAD

**Issue by SunilManthenaG01** [open-telemetry/opentelemetry-js-contrib#742]
Hi, I am trying to integrate the Nestjs application with jaeger using open telemetry and nest instrumentation by using the below configuration.

const provider = new NodeTracerProvider({
  resource: new Resource({
    [SemanticResourceAttributes.SERVICE_NAME]: 'bff-trace-test',
  }),
});
const jaegarConfig: ExporterConfig = {
  host: 'localhost',
  port: 6832,
};
const exporter = new JaegerExporter(jaegarConfig);
provider.addSpanProcessor(new SimpleSpanProcessor(exporter));
provider.register();

registerInstrumentations({
  instrumentations: [new NestInstrumentation()],
});

But i don't see any traces in a jaeger. Is there anything I am missing here?

As per my understanding, if we are using instrumentation, I don't have to create and end span's in order to see the trace correct?

Below are the versions I am using.

    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "@opentelemetry/api": "^1.0.3",
    "@opentelemetry/exporter-jaeger": "^1.0.1",
    "@opentelemetry/instrumentation": "^0.26.0",
    "@opentelemetry/instrumentation-nestjs-core": "^0.26.0",
    "@opentelemetry/resources": "^1.0.1",
    "@opentelemetry/sdk-trace-base": "^1.0.1",
    "@opentelemetry/sdk-trace-node": "^1.0.1",
    "@opentelemetry/semantic-conventions": "^1.0.1",

**Comment by SunilManthenaG01** [comment]
@dyladan  can you help me on this one?

**Comment by mentos1386** [comment]
@SunilManthenaG01 You can try using
```ts
import { diag, DiagConsoleLogger, DiagLogLevel } from "@opentelemetry/api";
diag.setLogger(new DiagConsoleLogger(), DiagLogLevel.DEBUG);
```
To make sure that spans get created, so that issue isn't with Jaeger exporter.

Also, one thing to keep in mind, you should do `New NestInstrumentation()` before you import anything from `@nestjs/core`. For example:
```ts

import { NestInstrumentation } from '@opentelemetry/instrumentation-nestjs-core';

... opentelemetry stuff ...

import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

async function bootstrap(): Promise<void> {
  ... nestjs stuff ...
}

```

**Comment by SunilManthenaG01** [comment]
@mentos1386  thank you for your response.
After some debugging, I see the issue is because I am using spdy listening on h2 protocol. If I switch that to HTTP 1.1 I can see the traces in jaeger but if the server protocol is h2 I can not see the traces.

Do we need to change anything if we need to make the trace work for h2 protocol?
