### ISSUE TITLE
Run a daily `test-all-versions` run

### ISSUE THREAD

**Issue by Rauno56** [open-telemetry/opentelemetry-js-contrib#756]
### Is your feature request related to a problem? Please describe

Some of the contrib packages have a way to run the tests against multiple versions. That's super awesome and useful! We don't run those in our CI though, namely because 

### Describe the solution you'd like to see

We should schedule a regular run of the full test suite with TAV for packages that have it. + maybe for release PRs.

### Describe alternatives you've considered

Run it in every PR, but that could slow PR-work down too much.

**Comment by vmarchaud** [comment]
I'm not against running it in every PRs, it may takes time but avoid problems after the PR is merged. To avoid too much impact we could just run tests on package that have been modified by the PR (since contribs pkgs don't depend on each other, i don't tihnk that would be an issue)

**Comment by haddasbronfman** [comment]
I'll start looking at this issue if it's ok

**Comment by Rauno56** [comment]
That's configured in https://github.com/open-telemetry/opentelemetry-js-contrib/pull/823
