### ISSUE TITLE
http auto instrumentation not working - @opentelemetry/auto-instrumentations-node: "latest"

### ISSUE THREAD

**Issue by sanasz91mdev** [open-telemetry/opentelemetry-js-contrib#759]
### What version of OpenTelemetry are you using?
latest

### What version of Node are you using?
v14.18.1

### What did you do?

1. clone [repo](https://github.com/sanasz91mdev/monitor-nodejs-opentelemetry)
2.  run Jaeger / OTEL collector with any exporter e.g [otelcol-config.yaml](https://github.com/sanasz91mdev/monitor-nodejs-opentelemetry/blob/main/otelcol-config.yaml)

### What did you expect to see?
http attributes like 
http.flavor 
http.host 
http.method
http.response_content_length_uncompressed
http.status_code 
http.status_text 

</body>
</html>

### What did you see instead?

Absence of these attributes were observed

**Comment by jugglingthebits** [comment]
I'm observing this as well. No spans are created for outgoing https requests.

**Comment by vmarchaud** [comment]
You need to require `./tracing.js` before the `express` package otherwise it will not work

**Comment by jugglingthebits** [comment]
Turns out the issue was what is described in https://github.com/open-telemetry/opentelemetry-js/issues/1315
I've since switched away from node-fetch and http instrumentation is now working properly.
