### ISSUE TITLE
Compatibility between versions in the opentelemetry base repo

### ISSUE THREAD

**Issue by dpkirchner** [open-telemetry/opentelemetry-js-contrib#770]
* [x]  This only affects the JavaScript OpenTelemetry library
* [x]  This may affect other libraries, but I would like to get opinions here first

This question is partially inspired by issue https://github.com/open-telemetry/opentelemetry-js-contrib/issues/749 where there was a mismatch between versions.

Should we as users pin our packages to a specific common minor rev?

That is, should we use only `0.26.*` for every `@opentelemetry/*` (meta)package if that's the maximum common (minor) version amongst all the packages we're using? One practical example that led me to this confusing: I'm using `@opentelemetry/auto-instrumentations-node:0.26.2` and there is a `@opentelemetry/sdk-trace-node:1.0.1` and `@opentelemetry/sdk-trace-node:0.26.0`. Should I stick with the latter for now? The numbers for most of the packages are close enough to suggest that the answer is "yes", but some of them are substantially different -- `@opentelemetry/api` doesn't have a `0.26.*` for example.

I understand that all of the packages can't be updated together as it's a huge project, so that's not what this is about (put another way, this isn't a "complaint" about there being 1.0 here and 0.27 there, etc). Apologies if there's already a discussion about this on GH, I haven't found it.

**Comment by dpkirchner** [comment]
Obligatory anti-stalebot reply.

**Comment by legendecas** [comment]
The api package (`@opentelemetry/api`), sdk package (like `@opentelemetry/sdk-trace-base`) and instrumentation package (`@opentelemetry/instrumentation`) are released with different stability guarantees today. Both API and trace SDK are stable now, but not the instrumentation. 

Instrumentation packages like `@opentelemetry/auto-instrumentations-node` has their version compatibility documented on their README page, like:

```
Compatible with OpenTelemetry JS API and SDK 1.0+.
```
