### ISSUE TITLE
Add support for graphql@16

### ISSUE THREAD

**Issue by Rauno56** [open-telemetry/opentelemetry-js-contrib#784]
### Is your feature request related to a problem? Please describe

Tests currently fail on `graphql@16`. Haven't investigated further.

**Comment by vmarchaud** [comment]
@obecny Do you still plan to do this ?

**Comment by obecny** [comment]
> @obecny Do you still plan to do this ?

I don't recall I was planning to do this.

**Comment by hilladalins** [comment]
Can you please assign this issue to me?

**Comment by Rauno56** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-js-contrib/pull/998
