### ISSUE TITLE
opentelemetry-instrumentation-redis never end / emit span

### ISSUE THREAD

**Issue by gaellm** [open-telemetry/opentelemetry-js-contrib#785]
### What version of OpenTelemetry are you using?
@opentelemetry/instrumentation-redis version 0.27.0
@opentelemetry/instrumentation version 0.27.0
@opentelemetry/semantic-conventions version 1.0.0
@opentelemetry/api version 1.0.2
@types/redis version 2.8.31
@opentelemetry/auto-instrumentations-node version 0.27.0
@opentelemetry/sdk-node version 0.27.0

### What version of Node are you using?
node 14.18.2

### What did you do?
I try to use node auto-instrumentation to generate and send a span when I set a value in Redis.  

`await redisClient.SET('key', 'value');` 

### What did you expect to see?
A span emitted on my trace exporter.  

### What did you see instead?
No span on my trace exporter.  

### Additional context
The issue is that @opentelemetry/instrumentation-redis lib check a callback function existence here:
https://github.com/open-telemetry/opentelemetry-js-contrib/blob/c60e934838e0fb6f8dd7014e0d463054ed733a73/plugins/node/opentelemetry-instrumentation-redis/src/utils.ts#L128. 

Without callback on my redis set, the `endSpan()` function will never be called.  

To generate a span I have to add a callback function:  

`await redisClient.SET('key', 'value', ()=>{});`

**Comment by vmarchaud** [comment]
I may be wrong but this callback is set even for async/await usage (at least that the case for ioredis and they both are similar). Could you share the node redis version you are using and if possible a sample repo that reproduces the problem ?

**Comment by gaellm** [comment]
Sure, you'll find here a sample: https://github.com/gaellm/redis-opentelemetry-issue-785-sample.
a `docker-compose up ` highlights the issue.

**Comment by Flarna** [comment]
@gaellm Your package.json says redis 2.8.0 but you use the redis API with `await` which is only supported since 4.x. I wonder if this sample is really doing what you expect.

**Comment by gaellm** [comment]
Yes, I've started with redis 4 client, and then downgraded because tracing seems not compatible with 4.x. Is it limited to 3.x? https://github.com/open-telemetry/opentelemetry-js-contrib/blob/c60e934838e0fb6f8dd7014e0d463054ed733a73/plugins/node/opentelemetry-instrumentation-redis/src/instrumentation.ts#L53

**Comment by gaellm** [comment]
I've updated my sample repo here: https://github.com/gaellm/redis-opentelemetry-issue-785-sample to reproduce with version redis 3.x

**Comment by Flarna** [comment]
> Is it limited to 3.x?

Yes, it hasn't been updated yet to work with 4.x

Seems you are right, if no callback is given span is never ended as this happens in the wrapped callback [here](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/e3ce1029914b4bb4715a644629b9b86c76b9f007/plugins/node/opentelemetry-instrumentation-redis/src/utils.ts#L149).

Maybe instrumentation could inject a dummy in that case but not sure if this has side effects regarding error handling.

But in general I wonder why you use redis API without callback. For reading commands it would mean you never get the result, for writing commands you never know if it actually worked and there is no error handling.

**Comment by gaellm** [comment]
:) sure a callback is mandatory to write apps for production. I work on a tracing preload module to instrument futur apps (with some custom configuration needs, a little like the java agent customization), so my test app is a quick check of OpenTelemetry auto instrumentation on Nodejs, with express, amqp, mongoose and redis to develop this module. And I was surprised to not emit span regarding Redis using node auto instrumentation. Redis gives some samples without callbacks on the documentation [here](https://github.com/redis/node-redis/tree/v3.1#commands).

**Comment by rohanagarwal36** [comment]
Any plan on fixing this?

**Comment by Ugzuzg** [comment]
>Maybe instrumentation could inject a dummy in that case but not sure if this has side effects regarding error handling.

Indeed, it has a side effects. Adding a dummy callback would change the error emitting behaviour.

>`client` will emit `error` when encountering an error connecting to the Redis
server or when any other in Node Redis occurs. If you use a command without
callback and encounter a ReplyError it is going to be emitted to the error
listener.
>
>So please attach the error listener to Node Redis.
> -- https://github.com/redis/node-redis/tree/v3.1.2#error

https://github.com/redis/node-redis/blob/v3.1.2/lib/utils.js#L87-L93

**Comment by pedroaraujo1952** [comment]
Is there any plans to make it work with redis v4?
