### ISSUE TITLE
Express with ignoreUrls

### ISSUE THREAD

**Issue by nerumo** [open-telemetry/opentelemetry-js-contrib#80]
I have a health check that is called by kubernetes every 15 seconds. I don't want any traces to be created for the health check. I can ignore routes in the http/https plugins, but I can't do that in the express plugin. It would make sense to support a `ignoreUrls` which ignores all layers for certain urls.

**Comment by vmarchaud** [comment]
I've made https://github.com/open-telemetry/opentelemetry-js-contrib/pull/43 exactly for that use case, it would make the express plugin not create trace if the http plugin did not.

**Comment by nerumo** [comment]
@vmarchaud Great! In my scenario this would work. It's not exactly the same as my proposal (spans can be created in other ways than through http/https), but it's satisfying for me.
