### ISSUE TITLE
NestInstrumentation ignores @HttpCode decorator and returns the default value

### ISSUE THREAD

**Issue by royi-frontegg** [open-telemetry/opentelemetry-js-contrib#801]
### What version of OpenTelemetry are you using?
0.26.0
NestJS 7
### What version of Node are you using?
14

### What did you do?
An endpoint with a "non-default" http response code returns a different response code than expected. e.g
```
@Post('/')
@HttpCode(HttpStatus.OK) // should return 200, but returns 201 which is the default for Post in NestJS
public async operation(
	@Body() body: SomeDto,
): Promise<SomeResponseDto> {
	return this.service.operate(body);
}
```

### What did you expect to see?
200 OK

### What did you see instead?
201 CREATED

### Additional context
NestJS 7

**Comment by Flarna** [comment]
Maybe #796 fixes this?

**Comment by royi-frontegg** [comment]
@Flarna looks like it thnx. Can it be back ported to 0.26 ?

**Comment by Flarna** [comment]
Thanks for confirmation.

I doubt that bugfixes in experimental packages get backported. But I think it should be quite easy to do a new release once #796 is merged.
It's up to the @open-telemetry/javascript-maintainers to decide.

**Comment by dyladan** [comment]
@royi-frontegg is there some reason you would not be able to update?

**Comment by royi-frontegg** [comment]
@dyladan I'm using `opentelemetry-instrumentation-kafkajs` that still haven't upgraded

**Comment by royi-frontegg** [comment]
@dyladan They have upgraded to 0.27
