### ISSUE TITLE
Add missing insrumentations to the opentelemetry.io registry

### ISSUE THREAD

**Issue by Rauno56** [open-telemetry/opentelemetry-js-contrib#803]
At least some of our instrumentations are not listed in the [official OTel registry](https://opentelemetry.io/registry/).
Fastify is one of them. There's **a** Fastify instrumentation there, but it's a 3rd party one. See: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/41

Sample PR here: https://github.com/open-telemetry/opentelemetry.io/pull/1010

**Comment by jscherer92** [comment]
@Rauno56 I'd be happy to pick this one up! New to this repo but want to get involved in the OpenTelemetry JS repos!

**Comment by jscherer92** [comment]
@Rauno56  https://github.com/open-telemetry/opentelemetry.io/pull/1158

**Comment by Rauno56** [comment]
Closed for now, follow-up here: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/971
