### ISSUE TITLE
integration example for apollo-server-express

### ISSUE THREAD

**Issue by jitenderchand** [open-telemetry/opentelemetry-js-contrib#81]
- [x] This only affects the JavaScript OpenTelemetry library
- [x] This may affect other libraries, but I would like to get opinions here first

**Comment by dyladan** [comment]
@jitenderchand there is no real context here to describe what you want. Are you looking for an example to manually trace apollo server express, or are you looking for an autoinstrumentation plugin? Are you currently working on this, or hoping someone else will do it?

**Comment by jitenderchand** [comment]
@dyladan I was trying to set up tracing for my project. we are using the `apollo-server-express`. I followed the getting started guide to setup. It works with example and it automatically traced whenever I hit the backed API. However, when I tried to set up this with my project the setup was successful but whenever I was hitting graphql API it was not working, which means it was not sending any traced data to `zipkin`. I have tried to set up it with the following code.

```
"use strict";

const { LogLevel } = require("@opentelemetry/core");
const { NodeTracerProvider } = require("@opentelemetry/node");
const { SimpleSpanProcessor } = require("@opentelemetry/tracing");
const { ZipkinExporter } = require("@opentelemetry/exporter-zipkin");

const provider = new NodeTracerProvider({ logLevel: LogLevel.ERROR });

provider.addSpanProcessor(
  new SimpleSpanProcessor(
    new ZipkinExporter({
      serviceName: "getting-started"
      // If you are running your tracing backend on another host,
      // you can point to it using the `url` parameter of the
      // exporter config.
    })
  )
);

provider.register();
console.log("tracing initialized");

```

I also tried to follow the `http` example to send the trace manually. unfortunately, that didn't work as well. 

My repository code which make API call.

```
async retrieveList(limit?: number, page?: number): Promise<any> {
        const url = new URL(`${this._baseURL}/v1/request/list`);
        const span = tracer.startSpan('makeRequest');
        return tracer.withSpan(span, async () => {
            const response = await this.get(url.toString());
            span.end();
           
            return {
                items: response.list
            };
        })
    } 
```

my tracer.js
```

'use strict';

import opentelemetry from "@opentelemetry/api";
import { NodeTracerProvider } from "@opentelemetry/node";
import { SimpleSpanProcessor } from "@opentelemetry/tracing";
import { ZipkinExporter } from "@opentelemetry/exporter-zipkin";

export default (serviceName: any) => {
    const provider = new NodeTracerProvider({
        plugins:{
            express: {
                enabled: true,
                path: '@opentelemetry/plugin-express'
            }
        }
    });
    const exporter = new ZipkinExporter({
        serviceName,
    });

    provider.addSpanProcessor(new SimpleSpanProcessor(exporter));

    // Initialize the OpenTelemetry APIs to use the NodeTracerProvider bindings
    provider.register();

    return opentelemetry.trace.getTracer('http-example');
};

```
So I know I am missing something, I have tried to search for example code where it can work with `apollo-server-express` but could not fine one

**Comment by jitenderchand** [comment]
@dyladan I am still struggling to setup it with apollo graphql. Could you please point me to some document if we have any.

**Comment by dyladan** [comment]
I'm sorry we don't have any examples specific for apollo

**Comment by vmarchaud** [comment]
I'm gonna close this in favor of the issue for the plugin [here](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/14)
