### ISSUE TITLE
Word the readmes better

### ISSUE THREAD

**Issue by Rauno56** [open-telemetry/opentelemetry-js-contrib#819]
Many of the packages have a section like that:

> This module provides automatic instrumentation for package name.
> For automatic instrumentation see the @opentelemetry/sdk-trace-node package.

Which reads very weird to me - both are kind of true, but in a different way.

https://github.com/open-telemetry/opentelemetry-js-contrib/pull/797#issuecomment-1001695501 suggested a better wording:

> This module provides automatic instrumentation for the ___ module, which may be loaded using the [@opentelemetry/sdk-trace-node](...url...) package and is included in the [@opentelemetry/auto-instrumentations-node](...url...) bundle.
>
> If total installation size is not constrained, it is recommended to use the [@opentelemetry/auto-instrumentations-node](...url...) bundle with [@opentelemetry/sdk-node](...url...) for the most seamless instrumentation experience.

Go over the readmes and fix the above occurrences.
Alternatively, we could figure out a better format for the README to avoid such tweaks in the future.

**Comment by pizzaz93** [comment]
@dyladan would this be a PR implementing that pattern for all the **relevant** folder's readmes in https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node, and then a variation of that content in the `web` folder?

**Comment by dyladan** [comment]
Yes. Are you considering taking on this work?

**Comment by pizzaz93** [comment]
Yes, I think the only missing detail would be some of the context for the web folder, but I think we can first focus on the node folder and address web in a later PR.

**Comment by pizzaz93** [comment]
https://github.com/open-telemetry/opentelemetry-js-contrib/pull/960 @dyladan confirming I have the right pattern/links before propogating further.
