### ISSUE TITLE
Set `files` field in all of our `package.json` files

### ISSUE THREAD

**Issue by rauno56** [open-telemetry/opentelemetry-js-contrib#820]
`files` field defines which files ought to be included in the final published package.

- [ ] set `files` for all the `package.json` files. Don't include [files always included](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#files), remove non-existing `doc`, TS source files. Basically only `.js`, `.js.map` and `.d.ts` files in the build folder need to be included,
- [ ] remove `.npmignore` files since it doubles `files` as an blacklist.

#### Motivation:

- Users may experience issues with `tsconfig.json` being included: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/733
- Package sizes could be a lot smaller - excluding `build/tsconfig.tsbuildinfo` would halve the package size for `@opentelemetry/auto-instrumentations-node`

**Comment by dyladan** [comment]
Existence of this field seems like something that could easily be checked in CI

**Comment by Rauno56** [comment]
> Existence of this field seems like something that could easily be checked in CI

Yes, that's a good idea! Plus points for adding that for whoever will take this.

**Comment by macno** [comment]
ready to pick this one #contribfest
