### ISSUE TITLE
hapi: support direct plugins with prefixed paths

### ISSUE THREAD

**Issue by seemk** [open-telemetry/opentelemetry-js-contrib#822]
### What version of OpenTelemetry are you using?

`@opentelemetry/instrumentation-hapi 0.27.0`

### What version of Node are you using?

`16.10.0`

### What did you do?

Passed plugin directly to `server.register` along with options:

```javascript
const Hapi = require('@hapi/hapi');

const init = async () => {
  const server = Hapi.server({port: 3000, host: 'localhost'});
  const plugin = {
    name: 'myPlugin',
    version: '1.0.0',
    register: async function (server, options) {
      server.route({
        method: 'GET',
        path: '/test',
        handler: function (request, h) {
          return 'hello, world';
        }
      });
    },
  };
  await server.register(myPlugin, {
    routes: {
      prefix: '/foo',
    }
  });
  await server.start();
};

init();
```

Did a request to `http://localhost:3000/foo/test`, got the following error:

```
TypeError: Cannot read properties of undefined (reading 'name')
    at Object.getPluginName (node_modules/@opentelemetry/instrumentation-hapi/build/src/utils.js:23:16)
    at HapiInstrumentation._wrapRegisterHandler (node_modules/@opentelemetry/instrumentation-hapi/build/src/instrumentation.js:184:36)
    at internals.Server.register (node_modules/@opentelemetry/instrumentation-hapi/build/src/instrumentation.js:103:33)
    at init (index.js:27:18)
```

### What did you expect to see?

Application starting up and a span named `myplugin: route - /foo/test`

### What did you see instead?

Application not booting due to an error in the instrumentation.

**Comment by dyladan** [comment]
@seemk if closing this as stale is not correct lmk and i'll reopen it

**Comment by jonathansamines** [comment]
Hello @dyladan I just tried to load the `@opentelemetry/instrumentation-hapi` in a project of ours and this exact signature to register hapi plugins is still unsupported (throws an error)

**Comment by dyladan** [comment]
hapi plugin does not have a component owner currently. I'll mark this as up for grabs
