### ISSUE TITLE
Difference between module Readmes and examples

### ISSUE THREAD

**Issue by kriptontr** [open-telemetry/opentelemetry-js-contrib#831]
Usage of `registerInstrumentations` is like 
```
registerInstrumentations({
  instrumentations: [
    // Express instrumentation expects HTTP layer to be instrumented
    new HttpInstrumentation(),
    new ExpressInstrumentation(),
  ],
});
```
at https://www.npmjs.com/package/@opentelemetry/instrumentation-express
but its used like 
```
  registerInstrumentations({
    tracerProvider: provider,
    instrumentations: [
      // Express instrumentation expects HTTP layer to be instrumented
      HttpInstrumentation,
      ExpressInstrumentation,
    ],
  });
```
without getting instances of classes here. 
https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/examples/express/tracer.js

- [+] This only affects the JavaScript OpenTelemetry library
- [+] This may affect other libraries, but I would like to get opinions here first

**Comment by Flarna** [comment]
Both works. 
The implementation of instrumentation checks if a function/constructor is passed and calls `new` in that case, otherwise it uses the given instance. see [here](https://github.com/open-telemetry/opentelemetry-js/blob/d315b0a75eb9517537b96a4ace083371cbdba552/experimental/packages/opentelemetry-instrumentation/src/autoLoaderUtils.ts#L37-L40)

**Comment by dyladan** [comment]
> Both works. The implementation of instrumentation checks if a function/constructor is passed and calls `new` in that case, otherwise it uses the given instance. see [here](https://github.com/open-telemetry/opentelemetry-js/blob/d315b0a75eb9517537b96a4ace083371cbdba552/experimental/packages/opentelemetry-instrumentation/src/autoLoaderUtils.ts#L37-L40)
> 
> Personally I would prefer to avoid such magic but I doubt that this will be removed as it would most likely break some user code.

I would also prefer not to have it. It would break user code, but technically it isn't 1.0 yet so it's not too late _officially_. With tracing being 1.0 we might be stuck with it anyway though.
