### ISSUE TITLE
Provide auto-instrumentation for `fs` module

### ISSUE THREAD

**Issue by Rauno56** [open-telemetry/opentelemetry-js-contrib#832]
### Describe the solution you'd like to see

I think this really doesn't need an explanation. `fs` module is quite a large one and has functionality across all paradigms:

- callback-based,
- promise-based,
- synchronous and
- streaming.

I'm sure there are differences across node versions, etc.

**Comment by blumamir** [comment]
+1
I use this module in one of my personal projects, and would really be happy to have instrumentation for it.

**Comment by Rauno56** [comment]
Initial version added here: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/872
