### ISSUE TITLE
AWS SDK Instrumentation trace is broken

### ISSUE THREAD

**Issue by shaicantor** [open-telemetry/opentelemetry-js-contrib#833]
### What version of OpenTelemetry are you using?
@opentelemetry/api@1.0.4
@opentelemetry/core@1.0.1
@opentelemetry/instrumentation-aws-sdk@0.4.0
@opentelemetry/auto-instrumentations-node@0.27.1

### What version of Node are you using?
16.11.1

### What did you do?
I'm using pm2
I configured a module to require using node.js --require option

tracing.js
```
const { getNodeAutoInstrumentations } = require("@opentelemetry/auto-instrumentations-node");
const { JaegerExporter } = require("@opentelemetry/exporter-jaeger");
const { SemanticResourceAttributes } = require('@opentelemetry/semantic-conventions');
const { Resource } = require('@opentelemetry/resources');
const { NodeTracerProvider } = require('@opentelemetry/sdk-trace-node');
const { BatchSpanProcessor, SimpleSpanProcessor } = require('@opentelemetry/sdk-trace-base');
const { registerInstrumentations } = require('@opentelemetry/instrumentation');
const {AwsInstrumentation} = require("@opentelemetry/instrumentation-aws-sdk");
const { CollectorTraceExporter } = require('@opentelemetry/exporter-collector');

const jaegerExporter = new JaegerExporter();
const tracerProvider = new NodeTracerProvider({
    resource: new Resource({
        [SemanticResourceAttributes.SERVICE_NAME]: JSON.parse(process.env.pm2_env)["SERVICE"]
    })
});

tracerProvider.addSpanProcessor(new SimpleSpanProcessor(jaegerExporter));
tracerProvider.register();
registerInstrumentations({
    tracerProvider: tracerProvider,
    instrumentations: [new AwsInstrumentation({}), getNodeAutoInstrumentations()],
});
```
We have a flow that uses http mixed with SQS and SNS.

### What did you expect to see?
I expected to see one trace with all spans from all services containing the send and the receive spans.

### What did you see instead?
spans for incoming and outgoing http were OK.
receive spans were linked to a new trace instead of the send span on a different service.

Trace containing the send span
![image](https://user-images.githubusercontent.com/2952388/149511683-80a7af90-26c8-4ed5-88e0-dbce82cccc72.png)
![image](https://user-images.githubusercontent.com/2952388/149511732-b8e48f79-a8e9-4d01-8db0-33e3a8ff2df7.png)

A new trace containing the receive span
![image](https://user-images.githubusercontent.com/2952388/149511576-9ab9bfc1-8611-4df0-963e-1f21b108a69e.png)
![image](https://user-images.githubusercontent.com/2952388/149511850-1653123d-03f8-433d-96e2-723c5fbaad7c.png)

### Additional context
I this related to the responseHook method in the sqs.js and more specifically https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-aws-sdk/src/services/sqs.ts#L133

But I'm not sure.
Please advise
Thank you

**Comment by blumamir** [comment]
Hi @shaicantor ,
This implementation follows the [Semantic Conventions for Messaging Systems Batch Receive](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#batch-receiving).

There is ongoing work to stabilize the conventions. Currently it looks like it will also use this structure of creating new trace for receive.
If you think the trace should look different, please point to the relevant part in the spec.

**Comment by shaicantor** [comment]
Thanks for the response @blumamir.
I stumbled upon this today after submitting the issue.
I have a follow up question.
What if you received only one message?
Shouldn't this follow single receiving and set the parent as expected?

> Hi @shaicantor , This implementation follows the [Semantic Conventions for Messaging Systems Batch Receive](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#batch-receiving).
> 
> There is ongoing work to stabilize the conventions. Currently it looks like it will also use this structure of creating new trace for receive. If you think the trace should look different, please point to the relevant part in the spec.

Thanks for the response @blumamir.
I stumbled upon this link today after submitting the issue.
I have a follow up question.
What if you received only one message?
Shouldn't this follow "single receiving" and set the parent as expected?

**Comment by dyladan** [comment]
Removing bug label as this is currently working as designed.

I'm looking at the link and don't see anything that says "single receiving" am I just missing something obvious?

**Comment by shaicantor** [comment]
> Removing bug label as this is currently working as designed.
> 
> I'm looking at the link and don't see anything that says "single receiving" am I just missing something obvious?

Hey @dyladan,
Sorry for the misunderstanding. I'll rephrase my question.

From what I'm seeing in the SQS implementation in the aws-sdk instrumentation, it is always assumed that we're batch receiving, but we can also have a scenario where 1 producer sends 1 message and there's 1 or more consumers, like in the https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#topic-with-multiple-consumers
In this case I would expect that the span receive will have the parent of the producer.

If you look in Datadog's implementation, you'll see that they check the max number of messages requested, and only if it's 1 they extract the context from the first message. Datadog doesn't implement batch receiving but they so implement 1 producer multiple consumers.

Shouldn't the implementation have both scenarios?

**Comment by blumamir** [comment]
> > Removing bug label as this is currently working as designed.
> > I'm looking at the link and don't see anything that says "single receiving" am I just missing something obvious?
> 
> Hey @dyladan, Sorry for the misunderstanding. I'll rephrase my question.
> 
> From what I'm seeing in the SQS implementation in the aws-sdk instrumentation, it is always assumed that we're batch receiving, but we can also have a scenario where 1 producer sends 1 message and there's 1 or more consumers, like in the https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#topic-with-multiple-consumers In this case I would expect that the span receive will have the parent of the producer.
>

This issue keeps coming up again and again. It is also widely discussed in the SIG for messaging systems semantic conventions. 
Although 1 message receive is possible, connecting receiver to producer span creates the following issues:
- We start the receive span upon user call to `client.receive(params)`. At this point, we don't know how many messages we'll get back, and are not aware of the remote span context, so we cannot create a span with the remote producer context as a parent. Delayed spans can overcome this, but create other issues such as downstream operation context loss and complex sampling. For example, the http span for the RPC to SQS will not be the child of the receive, but a new trace.
- Receive span may have ambient context, which will be lost if the span is attached to the producer and not the active span at the moment user invokes `client.receive()`. This implementation will have pros and cons, most notable is that user will not be able to track how the actual code execution was invoked in the application. You'll be left again with 2 traces that are not trivially linked and can be confusing in other contexts.
- 1 message receive is not very common, and different instrumentation behavior for the different cases can also cause confusion IMO. All the uses I've seen so far in production code always fetch the maximum of 10 messages which is the common case.
- Connecting producer trace to consumer may potentially create very long traces, with many many spans and long duration, which can sometimes obscure the ability to get valuable insights from the timeline. Current direction is leaning to recommend **always** creating new traces for remote async operations, which potentially can delay consumption in hours and days (when using the `DelaySeconds` feature in SQS, and similar in other brokers and queues). Traces that span days, but only have a few hundred of relevant ms at the bigging and end are hard to work with.
- SQS is just one of many services in the `aws-sdk` package, and there is a value that they all behave in similar RPC semantics which resonates well with how the code is actually executing. Consistency is also a valuable metric for instrumentation.
- OpenTelemetry uses the `links` concept to represent the kind of span relationships that solves the above issues. `process` spans are linked to the producer context and enable users to track the sender for the consumer spans. Links currently have different levels of support in vendor's backends and opensource tools, but they are for sure here to stay, and specification and implementations should use links where it makes sense and solves the messages fan-in problem.

Having said that, if you are up to it, you can also open a PR to extended behavior for the instrumentation to work in the way you described above. The default behavior will follow the spec, but you could opt-in via configuration to use different parent-child schemas. This is common in Ruby instrumentations that expose an option `propagation_style` which user can set to `child` or `link`. If it's not very urgent, I would recommend waiting for the specification to settle into a stable draft, as this entire SQS instrumentation will probably be refactored once the new spec is out.

Feel free to communicate your thought and plans. I can help with advising and reviewing any work, as the author of the `aws-sdk` instrumentation and an active participant in the messaging SIG.

I also encourage you to participate in the SIG meetings yourself, share your feedback and needs, and discuss the potential approaches to this problem. This is the best time, as we are actively discussing these exact issues at the moment. A stable draft for the new specification is expected at the end of Q1.

> If you look in Datadog's implementation, you'll see that they check the max number of messages requested, and only if it's 1 they extract the context from the first message. Datadog doesn't implement batch receiving but they do implement 1 producer multiple consumers.

@ericmustin , I think you wrote the DataDog implementation, right? and carried an in-depth research on this topic.  Maybe you have some more input to share?

**Comment by shaicantor** [comment]
@blumamir, thank you very much for a very thorough and clear explanation.
All issues are clear.

I really like the idea to opt-in to change different parent-child schemas via configuration, as I believe that the user knows how his/hers system work and what would represent accurately the system behavior and what would give him/her the most value.
In my system, we actually have multiple schemas (1 sent message - 1 received message + multiple messages - 10 batch receive) just in different services.

Regarding participating in the SIG meetings and SIG channels, can you please share the info?
Is the channel in slack under the CNCF workspace in #otel-messaging?

Thanks

**Comment by shaicantor** [comment]
I validated the above spec to see the **links** for the "Batch Receiving" scenario and didn't see the links I was expecting.
```
Process P: | Span Prod1 | Span Prod2 |
--
Process C:                      | Span Recv1 |
                                        | Span Proc1 |
                                               | Span Proc2 |
```

Span Proc1 and Span Proc2 didn't have a link to the Span Prod1 and Span Prod2 trace and span.
They had a link to "Span Recv1".
Just to validate that I wasn't wrong, I'm exporting data to Jaeger and the traces response json contains "references" of type "CHILD_OF".
Is that how Jaeger represents links or is there another way?

Thanks

**Comment by blumamir** [comment]
> Regarding participating in the SIG meetings and SIG channels, can you please share the info?
> Is the channel in slack under the CNCF workspace in #otel-messaging?

You can find all the details [here](https://github.com/open-telemetry/community). The meetings take place "Every Thursday at 8:00 PT". You have the link to the zoom in the public calendar which you can access from this repo. There is also the otel-messaging slack channel which is not very active

**Comment by blumamir** [comment]
> I validated the above spec to see the **links** for the "Batch Receiving" scenario and didn't see the links I was expecting.
> 
> ```
> Process P: | Span Prod1 | Span Prod2 |
> --
> Process C:                      | Span Recv1 |
>                                         | Span Proc1 |
>                                                | Span Proc2 |
> ```
> 
> Span Proc1 and Span Proc2 didn't have a link to the Span Prod1 and Span Prod2 trace and span. They had a link to "Span Recv1". Just to validate that I wasn't wrong, I'm exporting data to Jaeger and the traces response json contains "references" of type "CHILD_OF". Is that how Jaeger represents links or is there another way?
> 
> Thanks

Regarding the links in Jeager, I never tried but "CHILD_OF" means that the `process` span is the child of receive which is correct. [Looks like jaeger exporter does not transform links](https://github.com/open-telemetry/opentelemetry-js/blob/d315b0a75eb9517537b96a4ace083371cbdba552/packages/opentelemetry-exporter-jaeger/src/transform.ts#L121), so it's expected that they are missing.
I don't know what is the level of support for links in Jaeger itself. Also not sure if it's valid not to export them or if it's just an unimplemented behavior that needs to be done.
Anyhow, this is not related to SQS and the instrumentation itself, which should populate links correctly as far as I am aware.

**Comment by blumamir** [comment]
Thanks for bringing it up @shaicantor and for opening the issue for jaeger exporter in core repo

**Comment by blumamir** [comment]
closing as this behavior follows the spec and the Jaeger export problem is already documented in its own issue

**Comment by lukiano** [comment]
Just stumbled upon this. I've always thought that the consumer span would share the same `traceId` than the producer span. Because I use a Zipkin collector the links relationship is lost.
Do you know which collectors visualise links references? LightStep?

**Comment by ericmustin** [comment]
@lukiano I believe they're supported in the UI in Jaeger (Apache 2) and Grafana(AGPL), as "Span References"

-  https://github.com/grafana/grafana/blob/c98d835f81af1dd8deb0f7e59376c802a7a00525/packages/jaeger-ui-components/src/types/trace.ts#L41-L48
- https://github.com/jaegertracing/jaeger-ui

**Comment by mentos1386** [comment]
@lukiano LightStep doesn't support it ATM. I have asked support and they say "maybe in Q4 this year".
