### ISSUE TITLE
redis instrumentation - support v4

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-js-contrib#834]
Looks like the `redis` package released [v4](https://www.npmjs.com/package/redis/v/4.0.0)

Out instrumentation currently [only supports v2 and v3](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/9326c99f3cdf3e0166f74093a8093066be78bd0a/plugins/node/opentelemetry-instrumentation-redis/src/instrumentation.ts#L53)

This issue is to add support to this instrumentation for the new v4.
This will also resolve [this PR](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/758)

**Comment by maxbol** [comment]
any progress on this?

**Comment by vmarchaud** [comment]
@maxbol Its up for grab so i believe no one started to work on this

**Comment by blumamir** [comment]
I am working on adding support for v4.
Will be ready soon
