### ISSUE TITLE
graphql: support new v16

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-js-contrib#836]
grpahql has a new major version: 16 [npm](https://www.npmjs.com/package/graphql)
Our tests seems to fail for this version, as can be seen in [this renovate PR](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/719)

The instrumentation reports [supporting version >=14](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/b231412514addf0ec73f97b21edb7ad08badf5b7/plugins/node/opentelemetry-instrumentation-graphql/src/instrumentation.ts#L63). But tests for v16 fail.
This issue is to investigate why tests are failing and create a PR with fixes and support for v16

**Comment by vmarchaud** [comment]
Rauno already opened an issue for this here: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/836 so i'm closing this one

**Comment by vmarchaud** [comment]
Sorry it was this one: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/784
