### ISSUE TITLE
React/Redux plugin

### ISSUE THREAD

**Issue by thgao** [open-telemetry/opentelemetry-js-contrib#84]
**Is your plugin request related to a problem? Please describe.**
Currently, React routing doesn't trigger tracing from other plugins like document load, but it'd be nice to be able to see this for React pages as well.

State storage in Redux would also be interesting to see traces of.

**Is it applicable for Node or Browser or both**
Browser

**Comment by dyladan** [comment]
Assigned the issue to you as discussed in SIG. If you'd like any help or guidance feel free to reach out to me on gitter or ask in the https://gitter.im/open-telemetry/opentelemetry-node channel.

**Comment by bbigras** [comment]
Any progress for functional components (like with react hooks)?

**Comment by vmarchaud** [comment]
@bbigras Sorry for the late response but i don't think someone is working on this

**Comment by vmarchaud** [comment]
I'm gonna close this one since initial plugin has been merged, functional component support will be tracked here: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/178
