### ISSUE TITLE
Plugin for angular or rxjs or both 

### ISSUE THREAD

**Issue by obecny** [open-telemetry/opentelemetry-js-contrib#86]
The angular is using rxjs and thus the context propagation is not kept between user_interaction and for example XMLHttpRequest when using rxjs observable. To achieve that I believe it would be a rxjs which needs to be patched. It might be not all but I think Observable could be a start and then to see if context (zone) is being propagated correctly

**Comment by jufab** [comment]
FWY, I made an angular library https://www.npmjs.com/package/@jufab/opentelemetry-angular-interceptor

**Comment by dyladan** [comment]
@jufab awesome! Maybe you should list it on the registry so people can find it?

**Comment by jufab** [comment]
@dyladan PR sent for the registry ;)
