### ISSUE TITLE
npm run lint doesn't work

### ISSUE THREAD

**Issue by obecny** [open-telemetry/opentelemetry-js-contrib#87]

**Comment by rezakrimi** [comment]
I see that the the project is using tslint and it's been deprecated. Is it ok to setup eslint similar to the core repo?

**Comment by dyladan** [comment]
@rezakrimi yes that would be great! Would you like to be assigned?

**Comment by rezakrimi** [comment]
Sure

**Comment by vmarchaud** [comment]
I believe we can close this since we moved to eslint and the lint run fine on the CI: https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/.github/workflows/lint.yml
