### ISSUE TITLE
Switched parameters of log hook in README

### ISSUE THREAD

**Issue by EddieGarcia** [open-telemetry/opentelemetry-js-contrib#870]
Hi all, i have noticed error in documentation. In README usage section there is example how to use loghook:
```
logHook: (record, span) => {
    record['resource.service.name'] = provider.resource.attributes['service.name'];
},
```
in fact parameters should be switched as the first one is span and record comes second.
https://github.com/open-telemetry/opentelemetry-js-contrib/blob/7bde622802a88dbca685ae2400bdcf665f1443d1/plugins/node/opentelemetry-instrumentation-winston/src/instrumentation.ts#L121
```
 private _callHook(span: Span, record: Record<string, string>) {
    const hook = this.getConfig().logHook;

    if (!hook) {
      return;
    }

    safeExecuteInTheMiddle(
      () => hook(span, record),
      err => {
        if (err) {
          diag.error('winston instrumentation: error calling logHook', err);
        }
      },
      true
    );
  }
```

**Comment by jscherer92** [comment]
I'll grab this! Thank you for bringing it up,!
