### ISSUE TITLE
@opentelemetry/instrumentation-fastify has not been published since November

### ISSUE THREAD

**Issue by jhasselgren** [open-telemetry/opentelemetry-js-contrib#871]
It looks like @opentelemetry/instrumentation-fastify have not be published to NPM since November. It has been work done on the code after that, but they are not published.

The effect of this is that the current @opentelemetry/instrumentation-fastify on npm (v0.25.0) is not compatible with @opentelemetry/instrumentation v0.27.0. 

Gets the error:
`Type 'Meter' is missing the following properties from type 'Meter': createValueRecorder, createValueObserver, createSumObserver, createUpDownSumObserver, createBatchObserver`

Looking at the commit I see that it is fixed in #769

**Comment by Flarna** [comment]
seems there is no owner for this instrumentation mentioned in https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/.github/component_owners.yml

@obecny you created this one initially in #611. Do you still feel responsible for it?

**Comment by Flarna** [comment]
seems the fastify instrumentation is missing in release config. I created https://github.com/open-telemetry/opentelemetry-js-contrib/pull/873 to add it.

**Comment by jhasselgren** [comment]
looks to be 0.26.0 that is published to npm now 
https://www.npmjs.com/package/@opentelemetry/instrumentation-fastify

closing
