### ISSUE TITLE
Express instrumentation yielding no spans?

### ISSUE THREAD

**Issue by dchambers** [open-telemetry/opentelemetry-js-contrib#875]
### What version of OpenTelemetry are you using?

```
"@opentelemetry/api": "~1.0.4",
"@opentelemetry/core": "~1.0.1",
"@opentelemetry/exporter-trace-otlp-http": "^0.27.0",
"@opentelemetry/instrumentation-express": "^0.27.1",
"@opentelemetry/instrumentation-graphql": "^0.27.2",
"@opentelemetry/instrumentation-http": "^0.27.0",
"@opentelemetry/sdk-trace-base": "~1.0.1",
```

### What version of Node are you using?

v14.18.1

### What did you do?

I tried to register three instrumentations:

```
registerInstrumentations({
    tracerProvider,
    instrumentations: [
        new HttpInstrumentation(),
        new ExpressInstrumentation(),
        new GraphQLInstrumentation(),
    ],
})
```

### What did you expect to see?

I expect to see the `express` library be instrumtented *and* produce spans for requests I make to the server.

### What did you see instead?

I see `express` being instrumented prior to me importing it (using diag logs),  but I don't see any `express` spans at all.  Instead, I only see `http` and `graphql` spans relating to my request.

### Additional context

```
@opentelemetry/api: Registered a global for diag v1.0.4.
@opentelemetry/api: Registered a global for trace v1.0.4.
@opentelemetry/api: Registered a global for propagation v1.0.4.
📡 Transmitting OpenTelemetry traces to http://localhost:8080/v1/traces
@opentelemetry/instrumentation-http Applying patch for http@14.18.1
@opentelemetry/instrumentation-http Applying patch for https@14.18.1
Applying patch for express@4.17.2
>>> prior to loading Apollo
[34mdebug[39m:    Starting server
```

None of my spans have a `trace.parent_id` set, such that everything's flat in the UI, and this is presumably because `@opentelemetry/instrumentation-express` was going to be the thing creating the root span (based either on context received via tracing headers, or by creating a new root span)?

I'm an OpenTelemetry noob, so I'm presumably doing something stupid, but lots of digging through the docs and I'm none the wiser, so any pointers would be greatly appreciated!

**Comment by Flarna** [comment]
Could you provide some more details how you initialize the SDK?
It looks like you use `sdk-trace-base` which doesn't install a context manager so it's up to the user to do so otherwise implicit passing of spans can't work.

An alternative is to use `sdk-trace-node` which does this specific for Node.js (or `sdk-trace-web` for web).

**Comment by dchambers** [comment]
Thanks @Flarna, I hadn't realised that subtlety. I just thought `NodeTracerProvider` automatically registered built-in Node.js instrumentation. I was initially using it but I gave up on it because I didn't get spans for either `http` or `express` when I was originally using it, and moving to `BasicTracerProvider` is what caused `http` spans to start working for me.

However, by switching back to `NodeTracerProvider` now I can see that everything is now finally working, and I'm getting trees of spans rather stand-alone spans. I've changed a fair bit in my config since switching in an attempt to get things working, so presumably one of those changes was what was needed.

Thank you so much for getting me on my way. 🙇

**Comment by Flarna** [comment]
Yes, that's a bit confusing as there are quite some building blocks where one depends on the other.

I think you meant `@opentelemetry/sdk-node` instead `@opentelemetry/sdk-trace-node`.
sdk-node is the full blown (but still experimental) thing which combines trace, metrics, resource detection. Not sure about autoinstrumentation of "everything" as this might be somewhere else, not sure here.

**Comment by dchambers** [comment]
For posterity, I found the issue that was originally breaking things for me:

```
import https from 'https'

const localHttpsServer = (app) => https.createServer({ key, cert }, app)

// ...

if (process.env.HTTPS_DEV === 'true') {
    localHttpsServer(app).listen(6443) // Failure 💣 
    logger.info('GraphQL server running on port 6443')
} else {
    app.listen(PORT) // Success 🎉 
    logger.info(`GraphQL server running on port ${PORT}`)
}
```

Googling "express https" seems to indicate that this approach is still the recommended way of enabling `https:` support, so it might be w

**Comment by dyladan** [comment]
> Yes, that's a bit confusing as there are quite some building blocks where one depends on the other.
> 
> I think you meant `@opentelemetry/sdk-node` instead `@opentelemetry/sdk-trace-node`. sdk-node is the full blown (but still experimental) thing which combines trace, metrics, resource detection. Not sure about autoinstrumentation of "everything" as this might be somewhere else, not sure here.

autoinstrumentation is included in that afaik.

the sdk-node package is honestly not a great experience at the moment and I would like to refactor it so that it is sync. Currently it assumes async resource detection, but I think that is an unusual case for most people.
