### ISSUE TITLE
AWS Lambda Instrumentation Trace ID is same for all calls

### ISSUE THREAD

**Issue by lewis-green** [open-telemetry/opentelemetry-js-contrib#876]
### What version of OpenTelemetry are you using?
1.0.1

### What version of Node are you using?
14.17.3

### What did you do?
Call Lambda via API Gateway multiple times from different end users.

### What did you expect to see?
Unique trace ID per execution request coming in to the lambda

### What did you see instead?
Trace ID same for all executions within a lambda instance.

**Comment by jscherer92** [comment]
I think this is similar to #849. Once I'm finished up there I will try to take a look but most likely the way the instrumentation is working it is not tying to the context correctly.

**Comment by dyladan** [comment]
@willarmiros this seems like it might be a configuration issue?
