### ISSUE TITLE
Release automation doesn't include fastify instrumentation

### ISSUE THREAD

**Issue by Flarna** [open-telemetry/opentelemetry-js-contrib#886]
Even fastify instrumentation was added in #873 and some change was committed in #879 release please doesn't include it into the release main PR #874.

**Comment by dyladan** [comment]
The tag `chore:` was used for that change which is ignored by the release automation

**Comment by vmarchaud** [comment]
Closing since its fixed via https://github.com/open-telemetry/opentelemetry-js-contrib/pull/887
