### ISSUE TITLE
express plugin: doesnt work with express-async-errors module

### ISSUE THREAD

**Issue by vmarchaud** [open-telemetry/opentelemetry-js-contrib#9]
`express-async-errors` is a module that wrap express layers so they can be async, however to do so it change the handle fn location (https://github.com/davidbanham/express-async-errors/blob/master/index.js#L36)

**Comment by sk-** [comment]
@vmarchaud any progress on this? The blocking PR was already merged.

**Comment by vmarchaud** [comment]
I stopped using `express-async-errors` and i don't have the time to fix this, feel free to make a PR though

**Comment by david-luna** [comment]
Hi @vmarchaud 

Latest version includes #2137 which also fixes this issue by exposing the `handler` properties in the patched function. I've done a sanity check with the sample given in the package's readme file. This is the code

`pacakge.json`
```json
{
  "name": "xpress-async-errors",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node --require @opentelemetry/auto-instrumentations-node/register index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@opentelemetry/auto-instrumentations-node": "^0.47.1",
    "express": "^4.19.2",
    "express-async-errors": "^3.1.1"
  }
}
```

`index.js`
```js
const express = require('express');
require('express-async-errors');
const app = express();
const port = 3000;

const User = {
  list: [
    { id: 1, name: 'John Doe', token: '12345' },
  ],
  findAll() {
    return Promise.resolve(this.list);
  },
  findByToken(t) {
    return Promise.resolve(this.list.find(u => u.token === t));
  },
};


app.use(async (req, res, next) => {
  const user = await User.findByToken(req.get('authorization') || 'no-auth');

  if (!user) throw Error("access denied");

  next();
});

app.get('/users', async (req, res) => {
  const users = await User.findAll();
  res.send(users);
});


app.use((err, req, res, next) => {
  if (err.message === 'access denied') {
    res.status(403);
    res.json({ error: err.message });
  }

  next(err);
});

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
});
```

and starting the application with auto-instrumentations
```sh
npm start
```

then on a separate shell I can request the API without issues, errors are handled correctly

```sh
curl -H "authorization: 125" http://localhost:3000/users
{"error":"access denied"}

curl -H "authorization: 12345" http://localhost:3000/users
[{"id":1,"name":"John Doe","token":"12345"}]
```

So I'm closing this issue. Feel free to create a new issue if you detect a case where is not working.

Cheers :)

**Comment by vmarchaud** [comment]
I think i actually fixed this one way or another back in my code when i was maintaining the instrumentation because i've been using both instrumentation and the package since 2021, but cool that this has been fixed for more people :)
