### ISSUE TITLE
Plugin for Hapi

### ISSUE THREAD

**Issue by carolinee21** [open-telemetry/opentelemetry-js-contrib#92]
**Is your plugin request related to a problem? Please describe.**
Requested plugin for [Hapi](https://hapi.dev/) framework

**Is it applicable for Node or Browser or both**
Node
**Do you expect this plugin to be commonly used**
Weekly Downloads:
[250k](https://www.npmjs.com/package/@hapi/hapi)

**Comment by mayurkale22** [comment]
In my opinion, this would be useful. @dyladan Any thoughts?

**Comment by dyladan** [comment]
💯

**Comment by mwear** [comment]
If this tweet can be trusted: https://twitter.com/hapijs/status/1275887984114413569, Hapi will be EOL'd. It's anyone's guess how this will actually play out as it does seem to have a loyal following.

**Comment by carolinee21** [comment]
Based on [this update from Hapi](https://github.com/hapijs/hapi/issues/4113), I believe Hapi will be sticking around! I would like to look more into this plugin - could someone please assign this to me?
