### ISSUE TITLE
Plugin for Koa

### ISSUE THREAD

**Issue by carolinee21** [open-telemetry/opentelemetry-js-contrib#93]
**Is your plugin request related to a problem? Please describe.**
Requesting a plugin for the [Koa](https://koajs.com/) framework

**Is it applicable for Node or Browser or both**
Node
**Do you expect this plugin to be commonly used**
Weekly Downloads:
[525k](https://www.npmjs.com/package/koa)

**Additional context**
Existing plugin for OpenTracing is shown [here](https://github.com/teambition/koa-opentracing)

**Comment by carolinee21** [comment]
@dyladan Could you please assign this to me? Thanks

**Comment by hairyhenderson** [comment]
@carolinee21 Has there been any progress on this? I was just looking for a koa otel plugin 😉

**Comment by carolinee21** [comment]
@hairyhenderson Yes - I have been working on it on [this fork](https://github.com/carolinee21/opentelemetry-js-contrib) and expect to have a PR out in the next week or so. I would appreciate any feedback you have!

**Comment by hairyhenderson** [comment]
Awesome! I'll wait for the PR and will have a look when it's up 🙂

**Comment by hairyhenderson** [comment]
@carolinee21 should this issue have been closed? It looks like carolinee21/opentelemetry-js-contrib#1 only merged it into your fork's `master` branch 🤔

**Comment by dyladan** [comment]
Nope :)

**Comment by carolinee21** [comment]
My apologies - did not realize that the issue would close based on a fork's PR. The formal PR into this repo is now open at #144

**Comment by hairyhenderson** [comment]
awesome, thanks @carolinee21 🙂
