### ISSUE TITLE
instrumentation-aws-sdk error handling incorrect for aws.error leading to Invalid attribute value set for key

### ISSUE THREAD

**Issue by jreichhold** [open-telemetry/opentelemetry-js-contrib#937]
### What version of OpenTelemetry are you using?
"aws-sdk": "^2.675.0",
"@opentelemetry/instrumentation-aws-sdk": "^0.5.0",

### What version of Node are you using?
Node 12.22.9

### What did you do?
When I turned on tracing in my production env I started seeing lots of
```Invalid attribute value set for key: aws.error```

### What did you expect to see?
No error for errors in response and instead to record the error

### What did you see instead?
Lots of errors

### Additional context
https://github.com/open-telemetry/opentelemetry-js-contrib/blame/09b8555007c3c05ad046dd67925f3640a7b35fbe/plugins/node/opentelemetry-instrumentation-aws-sdk/src/aws-sdk.ts#L321

has 
```span.setAttribute(AttributeNames.AWS_ERROR, response.error);```

Which calls https://github.com/open-telemetry/opentelemetry-js/blob/315abae2fb197259515d0b5139af5cc8ced25594/packages/opentelemetry-sdk-trace-base/src/Span.ts

Which has the following check:
```
if (!isAttributeValue(value)) { api.diag.warn(Invalid attribute value set for key: ${key}); return this; }
```

Which calls isAttributeValue in:
https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-core/src/common/attributes.ts

which has the following checks:
```
export function isAttributeValue(val: unknown): val is SpanAttributeValue {
  if (val == null) {
    return true;
  }

  if (Array.isArray(val)) {
    return isHomogeneousAttributeValueArray(val);
  }

  return isValidPrimitiveAttributeValue(val);
}
```

My suspicion is instead of calling Span.setAttribute on an Error one should do one of the following
- likely call Span.recordException
- Stringify the exception
- Use the error.message only

Seems this should fail for everyone as request.error is an object and not a string.

**Comment by jreichhold** [comment]
Digging into the AWS response object I see the following: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Response.html#error-property

```
error ⇒ Error (readonly)
Note: This attribute is only filled if a service or networking error occurs.
An structure containing information about a service or networking error.

Returns:

(Error) —
code [String] a unique short code representing the error that was emitted.
message [String] a longer human readable error message
retryable [Boolean] whether the error message is retryable.
statusCode [Numeric] in the case of a request that reached the service, this value contains the response status code.
time [Date] the date time object when the error occurred.
hostname [String] set when a networking error occurs to easily identify the endpoint of the request.
region [String] set when a networking error occurs to easily identify the region of the request.
```

**Comment by jreichhold** [comment]
Since I can't push to the repo I think the answer is as something simple as
```
diff --git a/plugins/node/opentelemetry-instrumentation-aws-sdk/src/aws-sdk.ts b/plugins/node/opentelemetry-instrumentation-aws-sdk/src/aws-sdk.ts
index 5d9eddaf..9c33dfcd 100644
--- a/plugins/node/opentelemetry-instrumentation-aws-sdk/src/aws-sdk.ts
+++ b/plugins/node/opentelemetry-instrumentation-aws-sdk/src/aws-sdk.ts
@@ -318,7 +318,10 @@ export class AwsInstrumentation extends InstrumentationBase<typeof AWS> {

         self._callUserResponseHook(span, normalizedResponse);
         if (response.error) {
-          span.setAttribute(AttributeNames.AWS_ERROR, response.error);
+          span.setAttribute(
+            AttributeNames.AWS_ERROR,
+            '[${response.error.code}] ${aws.error.message}'
+          );
         } else {
           this.servicesExtensions.responseHook(
             normalizedResponse,
```
You could also `JSON.stringify(response.error)` but that might get a bit long and truncated in spans

**Comment by Rauno56** [comment]
I'm seeing this aswell. Assigning component owners @NathanielRN, @willarmiros, @blumamir

**Comment by blumamir** [comment]
@jreichhold  Sorry for the late response. I think this is indeed incorrect and support changing to `recordException`. Would you like to contribute PR with a fix?

**Comment by jreichhold** [comment]
Tried to create but not figuring out how to get npm or yarn build on the package is limiting. Looked around for instructions but curious how this project is built today?

**Comment by andreroggeri** [comment]
Still happening
