### ISSUE TITLE
Migrate examples for koa instrumentation

### ISSUE THREAD

**Issue by andyfleming** [open-telemetry/opentelemetry-js-contrib#950]
We're moving instrumentation examples from the top-level examples folder to the individual instrumentation packages to help keep them up to date. [See the original PR here](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/939).

This issue is specifically for the [@opentelemetry/instrumentation-koa](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/examples/koa) examples.

Step-by-step instructions for migrating these examples can be found in [examples/README.md](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/examples/README.md#instructions-for-migrating-an-example).

**Comment by andyfleming** [comment]
@dyladan @Flarna @Rauno56 — Here's an example issue for migrating a given instrumentation package. Let me know if you think anything else needs included in the issue description. Also would be great to tag these with "Good First Issue". Thanks!

**Comment by Rauno56** [comment]
I think this is perfect! The example PR can be really good guidance for what is expected!

**Comment by haddasbronfman** [comment]
Hi, can you assign it to me please?

**Comment by andyfleming** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1118
