### ISSUE TITLE
Error handling middleware with connect fails after instrumenting

### ISSUE THREAD

**Issue by davidmr** [open-telemetry/opentelemetry-js-contrib#975]
### What version of OpenTelemetry are you using?
* OpenTelemetry API 1.0.4
* OpenTelemetry/connect 0.27.0

### What version of Node are you using?
14.19.0

### What did you do?

I created an application that uses one custom middleware and one error handling middleware. Here's an example: https://github.com/davidmr/connect-opentelemetry-instrumentation

### What did you expect to see?
No behavior changes in the application

### What did you see instead?
Error handling middleware is not working as expected. It reports a `TypeError: res.end is not a function` for the example above.

### Additional context

I did some debugging and noticed two things:
_Hopefully my analysis is appropriated_

* The `call` method in _connect_ checks for the number of arguments in the function: https://github.com/senchalabs/connect/blob/master/index.js#L225-L249. However, when patching the middleware at https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-connect/src/instrumentation.ts#L117, the signature of the function seems to be changed (it no longer has 3 or 4 parameters). It seems that this is making it difficult for _connect_ to properly decide how to invoke the middleware handler.
* In the tests that I did, when passing an error to `next`, I got `undefined` in the original function. This also makes _connect_ fail since it checks for the error before deciding how to invoke the handler. Using `next(err)` instead `next.apply(this, err)` seemed to work but I don't know what other effects it can have.

**Comment by Rauno56** [comment]
Connect and Express are known to base their behavior on the function "length"(number or stated arguments), and we do make it hard for those packages to know what's going on. So I think your analysis might be on point.

We battle that in some [other instrumentations](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/fb681828f7e039957afee4a15cd063fc2246b617/plugins/node/instrumentation-tedious/src/instrumentation.ts#L218-L221) by resetting the length and, in some cases, the name of the patched functions to what it used to be.

Do you think you would be able to give it a try to fix this?

**Comment by davidmr** [comment]
Yes, I think I can try. Thanks for taking a look at this.
