### ISSUE TITLE
Use @opentelemetry/semantic-conventions

### ISSUE THREAD

**Issue by mayurkale22** [open-telemetry/opentelemetry-js-contrib#98]
`@opentelemetry/semantic-conventions` has been published in `0.9.0`. Update all the relevant plugins to use this commonly defined enums.

Same as https://github.com/open-telemetry/opentelemetry-js/pull/1160

/cc @markwolff

**Comment by MarkSeufert** [comment]
Hi, could I take this one?

**Comment by vmarchaud** [comment]
I'll close this since all instrumentation use semantic conventions now
