### ISSUE TITLE
nestjs depends on types from devDependency, failing compilation

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-js-contrib#985]
### What version of OpenTelemetry are you using?
`1.0.1`

### What version of Node are you using?
`v16.14.0`

### What did you do?
`yarn add @opentelemetry/instrumentation-nestjs-core` -> `"@opentelemetry/instrumentation-nestjs-core": "0.28.3"` and then:

```js
import { NestInstrumentation } from '@opentelemetry/instrumentation-nestjs-core';
new NestInstrumentation();
```

This package does not depend on nestjs directly.

When `yarn build`ing the package, following error printed to console:
```
../../node_modules/@opentelemetry/instrumentation-nestjs-core/build/src/instrumentation.d.ts:2:30 - error TS2307: Cannot find module '@nestjs/core' or its corresponding type declarations.

2 import type * as NestJS from '@nestjs/core';
                               ~~~~~~~~~~~~~~


Found 1 error.
```

This message is valid, as the nestjs instrumentation indeed [does this](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/cb915cfe018678060b014e1385fcefd0dc73c776/plugins/node/opentelemetry-instrumentation-nestjs-core/src/instrumentation.ts#L25):
```js
import type * as NestJS from '@nestjs/core';
export class Instrumentation extends InstrumentationBase<typeof NestJS> {
```

which transpile into the `instrumentation.d.ts` file in `build` as:
```js
import type * as NestJS from '@nestjs/core';
export declare class Instrumentation extends InstrumentationBase<typeof NestJS> {
```

So in order for this package to work correctly in typescript, we will need to include these types in the regular "dependencies" which also means dragging a dependency on the entire `@nestjs/core` for all users just for the type.

Another alternative would be to remove the type from InstrumentationBase, replacing it with `any` and thus having no type import in the public interface. It seems to not be used for anything anyhow.
```js
export class Instrumentation extends InstrumentationBase<typeof NestJS> {

// Change to 
export class Instrumentation extends InstrumentationBase<any> {
```

[The other type imports from `@nestjs/*`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/cb915cfe018678060b014e1385fcefd0dc73c776/plugins/node/opentelemetry-instrumentation-nestjs-core/src/instrumentation.ts#L26) are not exported to the public interface so I think they are safe to use in `instrumentation.ts`:
```js
import type { NestFactory } from '@nestjs/core/nest-factory.js';
import type { RouterExecutionContext } from '@nestjs/core/router/router-execution-context.js';
import type { Controller } from '@nestjs/common/interfaces';
```

If there is support for this change, I can work on a PR to add it.

@Rauno56

**Comment by Flarna** [comment]
We had several issues like this in the past resulting in moving types into dependencies resulting in complains by consumers that the version specified by the instrumentation differs from that one used by the end user.
This is in special a problem for packages which have built in types as instrumentation has to depend on the package itself.

see for example (there are more)
https://github.com/open-telemetry/opentelemetry-js-contrib/issues/878
https://github.com/open-telemetry/opentelemetry-js-contrib/issues/802

**Comment by blumamir** [comment]
> We had several issues like this in the past resulting in moving types into dependencies resulting in complains by consumers that the version specified by the instrumentation differs from that one used by the end user. This is in special a problem for packages which have built in types as instrumentation has to depend on the package itself.
> 
> see for example (there are more) #878 #802
> 
> I think we have to get rid of type definitions of the instrumented module in the instrumentation API.

Me too. Would like to start with `nestjs` as it blocks my current task, and also discuss guidelines or changes to the `InstrumentationBase` api to address this wider issue.

@Rauno56 - You wrote the instrumentation, right? Does it make sense to you to remove the type above?

**Comment by Flarna** [comment]
Some more references:
https://github.com/open-telemetry/opentelemetry-js/pull/2256
https://github.com/open-telemetry/opentelemetry-js/pull/2388

it's not an easy topic and most likely resulting in some breakage. Also the hook concept quite some instrumentation have will be harder to use as we can't use a well known type there without leaking the type dependency.

**Comment by blumamir** [comment]
> Some more references: [open-telemetry/opentelemetry-js#2256](https://github.com/open-telemetry/opentelemetry-js/pull/2256) [open-telemetry/opentelemetry-js#2388](https://github.com/open-telemetry/opentelemetry-js/pull/2388)
> 
> it's not an easy topic and most likely resulting in some breakage. Also the hook concept quite some instrumentation have will be harder to use as we can't use a well known type there without leaking the type dependency.

Thanks for the references, I need to free up some time to dive deep into the details

**Comment by Rauno56** [comment]
> @Rauno56 - You wrote the instrumentation, right? Does it make sense to you to remove the type above?

I don't see another solution. For packages that rely on `@types/*` it's not such a big issue, but others' importing the module itself just isn't a good solution.

[This autoinstrumentation PR](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/981) reveals more:

```
node_modules/@opentelemetry/instrumentation-aws-sdk/build/src/aws-sdk.d.ts:1:27 - error TS2307: Cannot find module 'aws-sdk' or its corresponding type declarations.

1 import type * as AWS from 'aws-sdk';
                            ~~~~~~~~~

node_modules/@opentelemetry/instrumentation-aws-sdk/build/src/types.d.ts:3:27 - error TS2307: Cannot find module 'aws-sdk' or its corresponding type declarations.

3 import type * as AWS from 'aws-sdk';
                            ~~~~~~~~~

node_modules/@opentelemetry/instrumentation-cassandra-driver/build/src/instrumentation.d.ts:4:39 - error TS2307: Cannot find module 'cassandra-driver' or its corresponding type declarations.

4 import type * as CassandraDriver from 'cassandra-driver';
                                        ~~~~~~~~~~~~~~~~~~

node_modules/@opentelemetry/instrumentation-knex/build/src/instrumentation.d.ts:3:28 - error TS2307: Cannot find module 'knex' or its corresponding type declarations.

3 import type * as knex from 'knex';
                             ~~~~~~

node_modules/@opentelemetry/instrumentation-mysql2/build/src/instrumentation.d.ts:2:34 - error TS2307: Cannot find module 'mysql2' or its corresponding type declarations.

2 import type * as mysqlTypes from 'mysql2';
                                   ~~~~~~~~

node_modules/@opentelemetry/instrumentation-nestjs-core/build/src/instrumentation.d.ts:2:30 - error TS2307: Cannot find module '@nestjs/core' or its corresponding type declarations.

2 import type * as NestJS from '@nestjs/core';
```

**Comment by ledniy** [comment]
> ```
> node_modules/@opentelemetry/instrumentation-aws-sdk/build/src/aws-sdk.d.ts:1:27 - error TS2307: Cannot find module 'aws-sdk' or its corresponding type declarations.
> 1 import type * as AWS from 'aws-sdk';
>                             ~~~~~~~~~
> 
> node_modules/@opentelemetry/instrumentation-aws-sdk/build/src/types.d.ts:3:27 - error TS2307: Cannot find module 'aws-sdk' or its corresponding type declarations.
> 3 import type * as AWS from 'aws-sdk';
>                             ~~~~~~~~~
> 
> node_modules/@opentelemetry/instrumentation-cassandra-driver/build/src/instrumentation.d.ts:4:39 - error TS2307: Cannot find module 'cassandra-driver' or its corresponding type declarations.
> 4 import type * as CassandraDriver from 'cassandra-driver';
>                                         ~~~~~~~~~~~~~~~~~~
> 
> node_modules/@opentelemetry/instrumentation-knex/build/src/instrumentation.d.ts:3:28 - error TS2307: Cannot find module 'knex' or its corresponding type declarations.
> 3 import type * as knex from 'knex';
>                              ~~~~~~
> 
> node_modules/@opentelemetry/instrumentation-mysql2/build/src/instrumentation.d.ts:2:34 - error TS2307: Cannot find module 'mysql2' or its corresponding type declarations.
> 2 import type * as mysqlTypes from 'mysql2';
>                                    ~~~~~~~~
> ```

I'm getting exactly these errors, is there any workaround? I see that there's an upcoming fix https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1017 but with the current release cycle idk when to expect it

**Comment by aikoven** [comment]
A workaround is to add `"skipLibCheck": true` to `compilerOptions` in `tsconfig.json`.
