### ISSUE TITLE
instrumentation-pg used with pg-query-stream causes user application crash

### ISSUE THREAD

**Issue by gabrielemontano** [open-telemetry/opentelemetry-js-contrib#991]
### What version of OpenTelemetry are you using?
I use this versions:
"pg": "^8.7.3",
"pg-cursor": "^2.7.3",
"pg-query-stream": "^4.2.3"
"@opentelemetry/api": "^1.0.4",
"@opentelemetry/exporter-jaeger": "^1.0.1",
"@opentelemetry/instrumentation": "^0.28.0",
"@opentelemetry/instrumentation-amqplib": "^0.28.0",
"@opentelemetry/instrumentation-hapi": "^0.27.1",
"@opentelemetry/instrumentation-http": "^0.27.0",
"@opentelemetry/instrumentation-pg": "^0.28.0",

### What version of Node are you using?
16.10

### What did you do?
i have configured opentelemetry with instrumentation-pg. It seems to work perfectly but not on streamed queries.

### What did you expect to see?
No errors on console, i exect results of streamed query

### What did you see instead?
When i perform a streamed query, i've got a 500 in my hapi handler.

The console output something like this:
`{
  traceId: '74b485fc07b9463d77990009eaa33d35',
  parentId: 'e7798cf16dc3587e',
  name: 'pg.query:unknown',
  id: 'd7a5c8567e99de95',
  kind: 2,
  timestamp: 1651240871135298,
  duration: 5962,
  attributes: {
    'db.name': 'measurements',
    'db.system': 'postgresql',
    'db.connection_string': 'jdbc:postgresql://persistence:5432/measurements',
    'net.peer.name': 'persistence',
    'net.peer.port': 5432,
    'db.user': 'postgres'
  },
  status: {
    code: 2,
    message: 'A query must have either text or a name. Supplying neither is unsupported.'
  },
  events: []
}`

and this stack trace

`Debug: internal, implementation, error
TypeError: Cannot read properties of undefined (reading 'on')
at Database.queryStream (/main/node_modules/@a2asc/common-persistence/src/database.js:115:12)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Repository.findInDatesRangeByDevicesStream (/main/app/measurements/persistence/repository.js:110:12)
at async handler (/main/app/measurements/web/controller.js:178:36)
at async exports.Manager.execute (/main/node_modules/@hapi/hapi/lib/toolkit.js:60:28)
at async Object.internals.handler (/main/node_modules/@hapi/hapi/lib/handler.js:46:20)
at async exports.execute (/main/node_modules/@hapi/hapi/lib/handler.js:31:20)
at async Request._lifecycle (/main/node_modules/@hapi/hapi/lib/request.js:371:32)
at async Request._execute (/main/node_modules/@hapi/hapi/lib/request.js:281:9)`

If i disable instrumentation-pg it works perfectly

**Comment by yaverin** [comment]
I have the same error.

I create QueryStream with "pg-query-stream": "4.2.3"
`               qs = new QueryStream(`SELECT * ${qryFrom} ${orderByCondition}`);
                 qs.callback = () => {}; // necessary if pg options has query_timeout
`

And in pg-promise/lib/stream.js file on this line:
`    const stream = ctx.db.client.query(qs);

      stream.on(`data`, onData);
`
"stream" is "undefined" after "ctx.db.client.query(qs)" call.

And this error appears:

> TypeError: Cannot read properties of undefined (reading 'on')\n    at Database.$stream (/list_builder/node_modules/pg-promise/lib/stream.js:54:12)

If I disable "instrumentation-pg", "ctx.db.client.query(qs)" returns correct "stream", not "undefined".

**Comment by yaverin** [comment]
@gabrielemontano,

please remove "stale" label from this issue.

**Comment by dyladan** [comment]
This is not stale and the title does not accurately describe the severity of the bug. The instrumentation is not broken by pg-query-stream, but the opposite. User applications using pg-query-stream are vulnerable to a crashing bug when the instrumentation-pg module is used.

**Comment by yaverin** [comment]
> This is not stale and the title does not accurately describe the severity of the bug. The instrumentation is not broken by pg-query-stream, but the opposite. User applications using pg-query-stream are vulnerable to a crashing bug when the instrumentation-pg module is used.

@dyladan, fully agreed, thank you.

**Comment by dyladan** [comment]
@Rauno56 you're marked as the component owner. Do you have time to look at this? If not i'll take it

**Comment by yaverin** [comment]
@dyladan, please clarify, do you have some ETA for this fix? Thanks in advance!

**Comment by francisdb** [comment]
Same issue with 

`pg 8.7.1`
`knex 0.14.2`
`@opentelemetry/instrumentation-pg 0.31.1`

a rollback to `0.30.0` fixes the issue

```
TypeError: Cannot read properties of undefined (reading 'on')
    at Client.<anonymous> (test/node_modules/knex/lib/dialects/postgres/index.js:171:20)
    at Client.patchedClientConnectCallback [as _connectionCallback] (test/node_modules/@opentelemetry/instrumentation-pg/build/src/utils.js:176:12)
    at Client._handleReadyForQuery (test/node_modules/pg/lib/client.js:279:14)
```

**Comment by Rauno56** [comment]
Knex acquires the connection like this:
```
  acquireRawConnection: function acquireRawConnection() {
    var client = this;
    return new _bluebird2.default(function (resolver, rejecter) {
      var connection = new client.driver.Client(client.connectionSettings);
      connection.connect(function (err, connection) {
        if (err) {
          return rejecter(err);
        }
        connection.on('error', function (err) {
          connection.__knex__disposed = err;
        });
        connection.on('end', function (err) {
          connection.__knex__disposed = err || 'Connection ended unexpectedly';
        });
        if (!client.version) {
          return client.checkVersion(connection).then(function (version) {
            client.version = version;
            resolver(connection);
          });
        }
        resolver(connection);
      });
    }).tap(function setSearchPath(connection) {
      return client.setSchemaSearchPath(connection);
    });
  },
```

The current signature for the callback for connect method, however, is `(err) => void`, which our patching is based upon. Either it used to return the client as well(likely, mentioned knex version is 4+ years old), or are those versions(knex and pg) incompatible.

But(and that's a big one) that doesn't explain why it works without the instrumentation.

A failing code example would be helpful. I'm failing to repro for now.

**Comment by Rauno56** [comment]
Working on a fix.

cc: @dyladan

**Comment by max-mathieu** [comment]
👋  thanks for the work on these modules!

Just FYI I faced the same issue as @francisdb here (even on 0.30.0), but I manually applied the fix from https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1224 locally and it worked perfectly
(knex version: 0.95.11, ~1 year old)

**Comment by phil-nelson-bt** [comment]
We are having this same error with `pg-copy-stream`. in this snippet, pgjs is the imported pg-copy-stream instance

`.         const stream = client.query(
              pgcs.from(`
            CREATE TEMP TABLE tmp_${tableName}
            ON COMMIT DROP AS
            SELECT * FROM ${query.schema || 'energy'}.${tableName} LIMIT 0;
            COPY tmp_${tableName} FROM STDIN;`),
            );
`
We are using version "0.32.0" of the pg instrumentation. We are going to have to drop pg instrumentation from our solution if we can't get this solved which is unfortunate because it is really valuable to us. If we can help test, let me know.
