### ISSUE TITLE
Allow instrumentations to use propagated traceparent during SPA first hit to create single trace

### ISSUE THREAD

**Issue by nvolker** [open-telemetry/opentelemetry-js-contrib#995]
### Scenario

I have a React Single Page Application (SPA) with an Express, Node backend server. When I make a direct request (first-hit) to, for example, `localhost:3000/app/analysis` I hit my Node BE server which then calls `res.render` to render the SPA application in the browser. I'm sending my traces to a local collector, which then exports them to a variety of vendors (I will show Honeycomb.io screenshots) as well as console logging for debugging purposes.

<details>
  <summary>Node Configuration</summary>
  
  ```javascript
const { NodeTracerProvider } = require('@opentelemetry/sdk-trace-node')
const { ConsoleSpanExporter, SimpleSpanProcessor } = require('@opentelemetry/sdk-trace-base')
const { HttpInstrumentation } = require('@opentelemetry/instrumentation-http')
const { Resource } = require('@opentelemetry/resources')
const { SemanticResourceAttributes } = require('@opentelemetry/semantic-conventions')
const { OTLPTraceExporter } = require('@opentelemetry/exporter-trace-otlp-http')
const { registerInstrumentations } = require('@opentelemetry/instrumentation')

const exporter = new OTLPTraceExporter({ url: 'http://localhost:4318/v1/traces' })
const provider = new NodeTracerProvider({
    resource: new Resource({
        [SemanticResourceAttributes.SERVICE_NAME]: 'node',
    })
})

provider.addSpanProcessor(new SimpleSpanProcessor(exporter))
provider.addSpanProcessor(new SimpleSpanProcessor(new ConsoleSpanExporter()))
provider.register()

registerInstrumentations({
    instrumentations: [
        new HttpInstrumentation()
    ]
})
  ```
</details>

<details>
  <summary>React Configuration</summary>
  
  ```javascript
import { ZoneContextManager } from '@opentelemetry/context-zone'
import { CompositePropagator, W3CTraceContextPropagator } from '@opentelemetry/core'
import { OTLPTraceExporter } from '@opentelemetry/exporter-trace-otlp-http'
import { registerInstrumentations } from '@opentelemetry/instrumentation'
import { DocumentLoadInstrumentation } from '@opentelemetry/instrumentation-document-load'
import { FetchInstrumentation } from '@opentelemetry/instrumentation-fetch'
import { UserInteractionInstrumentation } from '@opentelemetry/instrumentation-user-interaction'
import { XMLHttpRequestInstrumentation } from '@opentelemetry/instrumentation-xml-http-request'
import { B3Propagator } from '@opentelemetry/propagator-b3'
import { Resource } from '@opentelemetry/resources'
import { BatchSpanProcessor, ConsoleSpanExporter, SimpleSpanProcessor } from '@opentelemetry/sdk-trace-base'
import { WebTracerProvider } from '@opentelemetry/sdk-trace-web'
import { SemanticResourceAttributes } from '@opentelemetry/semantic-conventions'

// add provider
const provider = new WebTracerProvider({
    resource: new Resource({
        [SemanticResourceAttributes.SERVICE_NAMESPACE]: 'react'
    })
})

provider.register({
    contextManager: new ZoneContextManager(),
    propagator: new CompositePropagator({
        propagators: [
            new B3Propagator(),
            new W3CTraceContextPropagator()
        ]
    })
})

// add exporter
const exporter = new OTLPTraceExporter({ url: 'http://localhost:4318/v1/traces' })
provider.addSpanProcessor(new BatchSpanProcessor(exporter))

// add console debugger
provider.addSpanProcessor(new SimpleSpanProcessor(new ConsoleSpanExporter()))

// instrument everything
registerInstrumentations({
    instrumentations: [
        new DocumentLoadInstrumentation(),
        new FetchInstrumentation({
            propagateTraceHeaderCorsUrls: [
                /.+/g
            ]
        }),
        new XMLHttpRequestInstrumentation({
            ignoreUrls: [/socket.io/],
            propagateTraceHeaderCorsUrls: [
                /.+/g
            ]
        }),
        new UserInteractionInstrumentation()
    ]
})
  ```
</details>

### Problem

During a first hit, i.e. opening up a new tab and loading a link such as `localhost:3005/app/analysis` I expect all instrumented spans to form a single, concise trace to allow me to stitch together all the requests made during the initial load of our SPA. However, the context propagation done from the Node server to the React SPA is cut off before the fetch requests are being made, by the browser, to other backend servers in our ecosystem. 

I am connecting the node Http instrumentation to the react DocumentLoad instrumentation using the optional `traceparent` ([docs here](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/web/opentelemetry-instrumentation-document-load#optional-send-a-trace-parent-from-your-server)).

```js
<meta name="traceparent" content='{{{ traceparent }}}'/>
```

This works as expected, however, the DocumentLoad instrumentation is not setting the context, rather clearing it, preventing any Fetch/XMLHttpRequest spans created by the react app from using the context to link the spans together into a single trace. 

Here you can see this play out, where the `applicationNode` span is my own custom, server-side span used to then create the `traceparent` meta tag in the HTML which gets picked up by the DocumentLoad instrumentation:

![Screenshot 2022-04-28 at 15 04 18](https://user-images.githubusercontent.com/45795784/166411723-42edca1a-6cc0-424f-a41e-ae7f452eb3f2.png)

However, nothing else gets attached to this trace and I'm **left with a handful** (depending on the page being loaded on first hit) **of orphaned fetch traces** like this:

![Screenshot 2022-04-28 at 15 04 57](https://user-images.githubusercontent.com/45795784/166411942-7cccfae1-be87-463b-b925-2f6e79488992.png)

## Describe the solution you'd like to see

If not by default, I'd love to have an option to enable which will make the DocumentLoad instrumentation set the `traceparent` (either the propagated `traceparent` or the context of the `documentLoad` span itself) as the _globalContext_ (not sure if I'm referencing this correctly). This would then make all fetch/XML requests, that occur during the first hit, child spans of the original trace. Perhaps something like:

```js
new DocumentLoadInstrumentation({
  propagateContext: true
})
```

What I've also noticed is that the UserInteraction instrumentation is a perfect example of how the `Navigation: <URL>` trace groups together all spans created from subsequent Fetch/XMLHttpRequest requests. Similarly to this, I'd love to see the same grouping (and single trace view) during the first load traced from Node to Browser.

## Describe alternatives you've considered

While asking for suggestions on the community Slack (I'm a huge fan that we've moved the community to Slack ❤️) it was suggested that [I open up an issue](https://cloud-native.slack.com/archives/C01NL1GRPQR/p1651500908963049?thread_ts=1651150806.660619&cid=C01NL1GRPQR).

However, with some advice, I'd think to look into perhaps trying to somehow set the `traceparent` as the global context myself in a similar place to where I have created the `meta` tag. I'm not sure how much success I'd have with this though, so any advice here would be appreciated.

I have experience with patching gems in ruby, but not so much for javascript libraries so I can't really put to words a suggestion on how I'd patch the DocumentLoad instrumentation. However, I wouldn't be particularly keen on this approach as I feel it could be to the benefit of the community to have something like this as a part of the library, rather than our own custom code. Also, maintenance budget.

## Additional context

If I have fumbled anything here please ask me to correct things or correct me! I am, first and foremost, a backend engineer and am still getting comfortable with all things front-end 🙂

**Comment by nvolker** [comment]
If my title is a bit off, I'd be happy to change it! It's a bit presumptuous on what the outcome might be from discussions had here.

**Comment by vmarchaud** [comment]
I think the hardest part is that we don't have a global context (there is a default which is different), so you wouldn't be able to set it for every call. Might i ask how the frontend fetch calls are made ? If you have a central place where all calls are made you could manually set the span context from the trace-parent.

It might be something the rum sig might be interested to know about (see https://docs.google.com/document/d/16Vsdh-DM72AfMg_FIt9yT9ExEWF4A_vRbQ3jRNBe09w/edit#heading=h.yplevr950565)

**Comment by martinkuba** [comment]
@vmarchaud Is there a technical reason why there is no global context? If we wanted the parenting to be automatic, then we would need to set the document-load span as active in the global context, and then unset it when it ends.

The other issue, aside from the context, is that the document-load span is created and ended at the same time. So, with manual instrumentation, you could use a custom span as a parent, but not the one from the document-load instrumentation (as it is currently implemented).

**Comment by vmarchaud** [comment]
>  Is there a technical reason why there is no global context? If we wanted the parenting to be automatic, then we would need to set the document-load span as active in the global context, and then unset it when it ends.

I mean there is one: the default one which is immutable anyway (as required by the spec). The problem is how context is shared, it can only go downstream to its called callback.

**Comment by xoscar** [comment]
Is there something that can be done to update the context during initialization to allow us to inject the traceparent in the context so it is used for the entire user session?
